### ISSUE TITLE
Explore alternative methods for contribution tracking

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#100]
Discussion: https://blog.andrewray.me/a-better-git-blame/

Competitor tool: https://www.syntevo.com/deepgit/

**Comment by harryggg** [comment]
Isn't the first article just describing the rationale of Git Blame, he's just doing it manually via Git Log. The author also did not find a good example proving his way is better, his example can be done using Git Blame -w, which automatically ignore indentation and whitespaces...

**Comment by fzdy1914** [comment]
Close as the issue now have a relatively good solution.
