### ISSUE TITLE
Code segments and toggle buttons overlap on top of resizable tab

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1001]
Observe that some code segments and toggle icons overlap on top of the resizable tab when scrolled across:

![Kapture 2020-01-17 at 1 17 44](https://user-images.githubusercontent.com/32864116/72547264-4a096b00-38c7-11ea-8649-3a762de7f740.gif)

Probably just need to set the z-index for the resizable tab.

**Comment by anubh-v** [comment]
Thanks @jamessspanggg. I've replicated this bug on Google Chrome. Will investigate it.

**Comment by anubh-v** [comment]
When testing on Google Chrome (v 79), using the current RepoSense on master branch, I found some related strange behaviour..

*For some authors*, there is a large empty space in the code panel.

Example:
![largeEmpty](https://user-images.githubusercontent.com/35621759/72674529-d461f280-3ab2-11ea-8c51-580f85040194.gif)

For other authors, the empty spacing is much smaller (but still present).
![smallEmpty](https://user-images.githubusercontent.com/35621759/72674540-f6f40b80-3ab2-11ea-9488-416a4c6b6cfe.gif)

Some authors do not have any empty spacing.

Is this bug already recorded / being tackled?
