### ISSUE TITLE
LogsManager: `setConsoleHandlerLevel` and `setFileConsoleHandlerLevel` methods are not used anywhere

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1002]
Relevant code snippet: 

https://github.com/reposense/RepoSense/blob/74ac22a3848f1009bab31d3ecb865c00f227e71e/src/main/java/reposense/system/LogsManager.java#L136-L142

These methods were added in this [pull request](https://github.com/reposense/RepoSense/pull/123).

To me, it seems these can be safely removed. Does anyone have more information?

**Comment by fzdy1914** [comment]
I think it is not so necessary to be removed right now.
