### ISSUE TITLE
Code Panel: Large empty space when author has edited a file with a long filepath

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1005]
When an author has contributed to a file with a long filepath, a large empty space is seen in the Code Panel, in order to accomodate the length of the filepath.

![largeEmpty](https://user-images.githubusercontent.com/35621759/72674715-e47ad180-3ab4-11ea-8cca-f310096f63f4.gif)

Suggestion: Show filepaths in a separate scrollable div

**Comment by jamessspanggg** [comment]
Instead of making the file paths scrollable, how bout just break the path text into next line when it overflows?

**Comment by anubh-v** [comment]
> Instead of making the file paths scrollable, how bout just break the path text into next line when it overflows?

That will work as well.
Another option is to shorten the displayed file path by omitting the intermediate directories in the filepath.

Instead of showing:
```
src/test/resources/RepoConfigParserTest/require_trailing_whitespaces/repoconfig_redundantLines_test.csv
```
we could show

`src/test/.../require_trailing_whitespaces/repoconfig_redundantLines_test.csv`
