### ISSUE TITLE
User Guide: Errors in "Tool Bar" section

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1006]
(1) The UG mentions that the `Sort Groups by` and `Sort within groups by` features have an option to sort by `Repo / Branch`, which is not true.

(2) The instructions for the `Sort within groups by` feature use the term "sub-group", which is a little unclear. Instead, we can use the phrase "the entities within the group will be sorted by..."

![image](https://user-images.githubusercontent.com/35621759/72674839-c44c1200-3ab6-11ea-880e-1fb39b9b2024.png)

**Comment by jamessspanggg** [comment]
(1)
> If the `Repo/Branch` is selected for the `group by` option, then `group title` for `sort groups by` option refers to `Repo/Branch`. If the `Author` is selected for the `group by` option, then `group title` for `sort within groups by` option refers to `Repo/Branch`.

You can refer here for more on our last discussion: https://github.com/reposense/RepoSense/pull/668

**Comment by Tejas2805** [comment]
Solved in #907
