### ISSUE TITLE
Refactor JS code used for the adjustable center divider

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1007]
This is a suggestion; need some input from those who've worked more on frontend if this is a good idea.

Currently, it seems that the logic used for the center divider is quite independent from the other code in `main.js`. Perhaps we can separate it into its own file?

Relevant code snippet:
https://github.com/reposense/RepoSense/blob/f1e78063acc0178e9bd22ba8e6a78c9de46beb0d/frontend/src/static/js/main.js#L39-L86

**Comment by anubh-v** [comment]
@fzdy1914, may I get your thoughts?

**Comment by fzdy1914** [comment]
If we are not abstracting out tab wrapper from the index, I don't think there is a need to separate it in an own file.
