### ISSUE TITLE
Code Panel: long lines of code takes up large horizontal space

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1010]
Currently, every line of code takes up a single line of space, no matter how long it is.

Lines of code that are long will then take up large horizontal space:
![Kapture 2020-01-19 at 16 59 14](https://user-images.githubusercontent.com/32864116/72678031-21f35500-3add-11ea-87c5-d6877a05340b.gif)

**Comment by jamessspanggg** [comment]
GitHub currently breaks every line into the next when it overflows:

<img width="691" alt="Screen Shot 2020-01-19 at 5 01 12 PM" src="https://user-images.githubusercontent.com/32864116/72678069-6bdc3b00-3add-11ea-84ac-c16a8673bd3c.png">


Prof @damithc, should we follow GitHub's way of displaying every line of code?

**Comment by damithc** [comment]
> Prof @damithc, should we follow GitHub's way of displaying every line of code?

Yes, that seem like a good idea.

**Comment by jamessspanggg** [comment]
Fixed in #1008
