### ISSUE TITLE
`Sort groups by` and `Sort within groups by`: Repo/Branch

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1012]
Based on Issue #1006 we have realized that there is no option to `sort groups by` and `sort within groups by` by Repo/Branch. Let's implement it.

**Comment by jamessspanggg** [comment]
If the `Repo/Branch` is selected for the `group by` option, then `group title` for `sort groups by` option is `Repo/Branch`. If the `Author` is selected for the `group by` option, then `group title` for `sort within groups by` option is `Repo/Branch`.

**Comment by Tejas2805** [comment]
Alright, it makes sense. Closing this issue down.
