### ISSUE TITLE
RepoConfiguration: Several methods are unused

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1014]
The following methods in `RepoConfiguration` class are unused:

- `getIgnoredAuthorsList`
- `isIgnoredAuthorsListOverriding`
- `addAuthor`
- `setAuthorConfiguration`
- `containsAuthor`
- `setGroups`
- `getOrganization`

I'm still trying to determine whether these should be removed. 
Will update this issue when I have a better idea.
If anyone has more information about why these methods have been kept, please let me know.

**Comment by Tejas2805** [comment]
Maybe you can look into the PR which added them and understand why were they added? And we can discuss from there?

**Comment by anubh-v** [comment]
@fzdy1914 would it be suitable if we remove these unused methods?
We can always re-introduce them if they are needed in future?

**Comment by fzdy1914** [comment]
We can remove them, but I believe leaving most of them in the codebase won't make it more difficult to understand the codebase and will not complicate the codebase much. For each class attribute, it is fine to have one set method and get methods.

**Comment by yash-chowdhary** [comment]
> leaving most of them in the codebase won't make it more difficult to understand the codebase and will not complicate the codebase much

In that case, I will leave these methods in the codebase and not include them in #1177.

**Comment by anubh-v** [comment]
Thanks for the responses. I'll close this issue then
