### ISSUE TITLE
Add link to author's profile for `group by` Author 

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1016]
Since we are aiming for consistency among the different views, we can think of implementing a link to the author's profile when `merge Group` and `group by Author` options are selected. As working on #873, will add octocat icon for merge Group for `group by Repo/Branch`

**Comment by Tejas2805** [comment]
@damithc @fzdy1914 @jamessspanggg require your feedback.

**Comment by fzdy1914** [comment]
I think it is a good idea.

**Comment by damithc** [comment]
No objections from me. :+1:
