### ISSUE TITLE
Make base URL a variable

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1021]
As discussed in PR #1017 , `https://gtihub.com` is used at several points in our js files.
Let's keep the base URL as a variable.

**Comment by yash-chowdhary** [comment]
I'd like to take up this issue. 
There are a few instances where functions return strings (like in `frontend/src/static /js/main.js`) -

```js
getRepoSenseVersionLink() {
      const version = window.app.repoSenseVersion;
      if (!version) {
        return 'https://github.com/reposense/RepoSense';
      }
      if (version.startsWith('v')) {
        return `https://github.com/reposense/RepoSense/releases/tag/${version}`;
      }
      return `https://github.com/reposense/RepoSense/commits/${version}`;
    },
```

There is also an instance where `http://reposense.org` is returned.
Would it be favourable to create a new `constants.js` file to avoid the use of magic variables?

**Comment by Tejas2805** [comment]
Hey sorry for the late reply. If possible could you first give a small list of magic variables actually used? In case, they turn out to be a lot, we can then think of creating a new `constant.js` file?

**Comment by yash-chowdhary** [comment]
I suppose there aren't a lot of them to create a `constants.js` file. 

For the current issue, the 2 files that could use the `baseUrl` variable are `frontend/src/static/js/v_summary.js` and `frontend/src/static/js/main.js`. Should I go ahead with this?

**Comment by Tejas2805** [comment]
> For the current issue, the 2 files that could use the `baseUrl` variable are `frontend/src/static/js/v_summary.js` and `frontend/src/static/js/main.js`. Should I go ahead with this?

Yes, can go ahead.
