### ISSUE TITLE
FileInfoAnalyzer: Deprecate the "//@reused" tag

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1022]
Currently, `FileInfoAnalyzer` will not analyse a file if the first line of the file has the `//@reused` string.
The file will not be included in the final Code Panel view.

May I check what is the meaning of this `//@reused` mechanism?
Is it meant as a way to omit files?

Relevant code snippets:
https://github.com/reposense/RepoSense/blob/6fe782466dc827ab5c37c095000dfaba6e2ee3db/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L27-L33

https://github.com/reposense/RepoSense/blob/6fe782466dc827ab5c37c095000dfaba6e2ee3db/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L49-L53

https://github.com/reposense/RepoSense/blob/6fe782466dc827ab5c37c095000dfaba6e2ee3db/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L129-L143

**Some investigation**
After some searching, I found that this mechanism was introduced in [this commit](https://github.com/reposense/RepoSense/commit/55787167ef17fc4c0979e2e27c41c416d9299093).
Back then, the file analysis logic was in `FileAnalyzer`.
`FileAnalyzer` was deleted and `FileInfoAnalyzer` took its place in [this commit](https://github.com/reposense/RepoSense/commit/87571e26e9792c62b602b2760906db234b68b3c7).

Please correct me if I'm wrong about the history here.

**Comment by anubh-v** [comment]
@fzdy1914, may I check with you about this? Thanks for your time.

**Comment by eugenepeh** [comment]
@anubh-v the `@@reused` is a syntax used in CS2103 by [Collate](https://github.com/se-edu/collate) for students to self-declare that the specific chuck of code was taken from peers or other developers, and do not wish to include them into their contribution (in case of any issues arise due to plagiarism).

**Comment by eugenepeh** [comment]
If i am not mistaken, the correct syntax should begin with `@@` like author.
For some reason, we have forgotten to include it in the user guide.
@anubh-v could you help us to put up or rename this issue to highlight a fix?
Thanks!

**Comment by anubh-v** [comment]
Thanks for the response @eugenepeh.
I have a few clarifications:

> If i am not mistaken, the correct syntax should begin with @@ like author.

I think the syntax being used is `//@reused`, as seen in the code snippet below:
https://github.com/reposense/RepoSense/blob/6fe782466dc827ab5c37c095000dfaba6e2ee3db/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L27-L33

> the @@reused is a syntax used in CS2103 by Collate for students to self-declare that the specific chuck of code was taken from peers or other developers

In the current code, this mechanism is being used to omit *files*, rather than *code blocks*.
I can add this to the user guide - just wanted to confirm that the current implementation is as expected.

**Comment by eugenepeh** [comment]
>I think the syntax being used is //@reused, as seen in the code snippet below:

Yes, I think its a typo.

>To further clarify, a similar method of "disowning code" is mentioned by Prof in #823.
Do we plan to use both `@@author` and `//@reused` for this purpose?

@damithc , for your input.

**Comment by damithc** [comment]
The way we used in the collate tool (a predecessor to RepoSenes) `@@reused` has no special meaning. It it treated as just another author. By giving the code to a fictitious author named `reused` the user can indicate which code was reused from elsewhere.

**Comment by damithc** [comment]
> The way we used in the collate tool (a predecessor to RepoSenes) `@@reused` has no special meaning. It it treated as just another author. By giving the code to a fictitious author named `reused` the user can indicate which code was reused from elsewhere.

Sorry, I meant `@@author reused`, not `@@reused`. This `//@reused` thing seems to be some internal detail that I was unaware of.

**Comment by anubh-v** [comment]
Thanks @eugenepeh, and @damithc for the response.

From the code, my understanding is that RepoSense does not analyze files which have `//@reused` on their first line.

I verified this, by testing on [this repository](https://github.com/anubh-v/reposenseTest-alpha).
The repository contains the following file:
```
//@reused

- apple
- tomato
- grapes
- watermelon
- pineapple
- orange
```
To generate a report for this repo, 
run RepoSense with this command:
`--repo https://github.com/anubh-v/reposenseTest-alpha.git --view --since d1`

In the Code Panel, the file is not attributed to the author:

![image](https://user-images.githubusercontent.com/35621759/73122561-68572100-3fc1-11ea-9434-109cbbae5f79.png)

**In contrast**, if we remove the `//@reused` tag, then the file will be attributed to the author.
![image](https://user-images.githubusercontent.com/35621759/73122579-9f2d3700-3fc1-11ea-9dfa-6c70556c0b6b.png)

Is this the intended usage for the `//@reused` tag?
If yes, we could add it to our user guide.

**Comment by damithc** [comment]
> From the code, my understanding is that RepoSense does not analyze files which have `//@reused` on their first line.

I don't remember such a feature but it is possible the feature was implemented without my knowledge (or I simply forgot about it). Feels like half-baked, given that `//` might not even be considered a comment in some languages.

**Comment by eugenepeh** [comment]
>In the Code Panel, the file is not attributed to the author:

@anubh-v good finding, could you help me to verify something?
If the tag was replaced by an `@@author reused`, would the report spawn a ramp chart for an author named `reused`?

>I don't remember such a feature but it is possible the feature was implemented without my knowledge (or I simply forgot about it). Feels like half-baked, given that // might not even be considered a comment in some languages.

I think moving forward, we can probably either remove it (since it was added unknowingly by the original author), or we can modify it and make it another feature. E.g. `@@exclude` to exclude code from showing up on the reposense report.

@damithc what do you think?

**Comment by damithc** [comment]
> I think moving forward, we can probably either remove it (since it was added unknowingly by the original author), or we can modify it and make it another feature. E.g. `@@exclude` to exclude code from showing up on the reposense report.

Agreed. I prefer removing as if in doubt we should go with the simpler solution.

**Comment by anubh-v** [comment]
> good finding, could you help me to verify something?

@eugenepeh, sorry for the late reply. There is an existing bug in the behaviour of the `@@author` tag (documented in #823), hence I needed a bit more time to respond. I will confirm the behaviour and respond by tonight.

**Comment by anubh-v** [comment]
@eugenepeh I tested running RepoSense on a file with a `@@author reused tag`.
There will be no separate ramp chart created for the author named `reused`.

![image](https://user-images.githubusercontent.com/35621759/73461759-a3889400-43b5-11ea-8536-9a3b9a9020ad.png)

The above chart was generated by running RepoSense on [this repo](https://github.com/anubh-v/reposenseTest-alpha).

**Comment by eugenepeh** [comment]
Thanks @anubh-v , looks like that is also something needed to be fixed

**Comment by anubh-v** [comment]
> looks like that is also something needed to be fixed

To clarify: if the user marks code with 
`@@author random-user`, where `random-user` is **not** a git author name present in the standalone config, author-config csv or the list of authors that have contributed to the repo in the specified time period,

do we want a ramp chart for the `random-user` author?

Also, should I go ahead and remove the `//@reused` tag functionality?

**Comment by damithc** [comment]
> To clarify: if the user marks code with
> `@@author random-user`, where `random-user` is **not** a git author name present in the standalone config, author-config csv or the list of authors that have contributed to the repo in the
> specified time period -- do we want a ramp chart for the `random-user` author?

I think the answer is no. If we want to track reused code, we can instruct students to use a specific author name to tag reused code e.g. `@@author reused` and also include `reused` as an author in config files.

**Comment by anubh-v** [comment]
@damithc, thanks for the response.

It was mentioned in #823 that `@@author random-user` is a means of disowning code.

So if we have the following file committed by a legitimate author with the the `anubh-v` git author name,
```
@@author random-user

apple
pear
grapes
oranges
```

then:
- we do not want the lines in this file to be attributed to `anubh-v` (as discussed in #823)

- we do not want a ramp chart for the `random-user` author

Effectively, the lines are just taken out of the authorship summary.
Is this right?

**Comment by damithc** [comment]
> then:
> 
> * we do not want the lines in this file to be attributed to `anubh-v` (as discussed in #823)
> * we do not want a ramp chart / code panel for the `random-user` author
> 
> Effectively, `anubh-v` disowns the code but we will not have a separate code panel that shows all the disowned code falling under `random-user`.
> 
> Is this the expected behaviour?

Yes, unless random-user is listed in our configs as a legit author or RepoSense is configured to show all authors (IIRC, we have such a setting).

**Comment by anubh-v** [comment]
Ok, understood.

What should be the resolution for the `//@reused` tag feature?
In my view, it serves the same purpose as the existing mechanism of ignoring files (by specifying in standalone and config csvs).

**Comment by damithc** [comment]
> What should be the resolution for the `//@reused` tag feature?
> In my view, it serves the same purpose as the existing mechanism of ignoring files (by specifying in standalone and config csvs).

I vote to remove it.

**Comment by eugenepeh** [comment]
Can be removed, we can bring it back in future if there's a need

Anyway back to the `@@author reused` in the earlier example, I would say without any config files, a ramp chart should be generated for `reused` by default so that users can troubleshoot it if there is any problem.

E.g. `Author A` labels all his code as `Author a`. The code didn't show up in the end because of the typo error (case-difference in this case as an example). However, this is unknown to the `Author A` because he assume that RepoSense would be accurate or he simply has too many code to keep track of.

This can be detected/avoided if we show the code of all authors (including those that did not contribute to the repo in the specified time period) by default.

**Comment by damithc** [comment]
> This can be detected/avoided if we show the code of all authors (including those that did not contribute to the repo in the specified time period) by default.

That's a fair point but in some cases we only want to track certain authors. For example, tracking external contribution of CS3281&2 students in which hundreds of other authors could be contributing to the repo in the same period. Perhaps we can include a list of omitted authors in the log file or in the report in some other non-obtrusive way?

**Comment by eugenepeh** [comment]
>That's a fair point but in some cases we only want to track certain authors. For example, tracking external contribution of CS3281&2 students in which hundreds of other authors could be contributing to the repo in the same period. Perhaps we can include a list of omitted authors in the log file or in the report in some other non-obtrusive way?

I just realized I word it wrongly. By `including those that did not contribute to the repo` ~in the specified time period~, I actually meant the "virtual" authors that were created by the `@@author` tag. 

What I suggested is that, if no author configuration exist, we should also create a ramp chart displaying these "virtual" authors' contribution if it exist in the code base assuming that the changes to those lines were made in the specified time period. Hence, there shouldn't be any major pitfall unless there are hundreds other authors spam the `@@author` tag.

If the user/repo owner do not want these "virtual" authors appear in the report, they can specific the `author-config.csv` to only include the main authors.

**Comment by damithc** [comment]
> What I suggested is that, if no author configuration exist, we should also create a ramp chart displaying these "virtual" authors' contribution if it exist in the code base assuming that the changes to those lines were made in the specified time period. Hence, there shouldn't be any major pitfall unless there are hundreds other authors spam the `@@author` tag.
> 
> If the user/repo owner do not want these "virtual" authors appear in the report, they can specific the `author-config.csv` to only include the main authors.

Yes, that is a good idea (if it can be done without much extra effort).

**Comment by anubh-v** [comment]
> we should also create a ramp chart displaying these "virtual" authors' contribution if it exist in the code base assuming that the changes to those lines were made in the specified time period.

@eugenepeh, @damithc, would this be a single ramp chart that collates all work done by all virtual authors, or a separate ramp chart for each virtual author?

I think a single ramp chart is sufficient? Users could open the Code Panel and see all the files that have code attributed to the virtual authors.

**Comment by damithc** [comment]
> @eugenepeh, @damithc, would this be a single ramp chart that collates all work done by all virtual authors, or a separate ramp chart for each virtual author?

Feels like they should be separate i.e., the code will likely to be simper that way as there is less 'special' handling to do.
