### ISSUE TITLE
Authorship Panel: expand all button always appear when first open the page

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1023]
Currently, the `expand all` button will always appear on the authorship panel when we first open the page or when refresh the page, until the loading is complete. The button to display is supposed to be `collapse all` as we are to display all the file details initially.

![Screenshot (14)](https://user-images.githubusercontent.com/39231750/73120597-5d919180-3fab-11ea-8d6e-40f3e9082f6e.png)

After the loading is completed, the button will change to `collapse all` all of a sudden. We could modify the js file to make the `collapse all` appears from the very beginning, even before the loading is completed.

**Comment by 0blivious** [comment]
@damithc @fzdy1914 your opinion?

**Comment by damithc** [comment]
From the user POV, this seems like a good thing to do. 👍

**Comment by fzdy1914** [comment]
Can, if only need to change the initial value.

**Comment by 0blivious** [comment]
> Can, if only need to change the initial value.

A easy fix is to change the data's initial value to be 1. After looking through the code I feel it is unnecessary to keep the number and we can change this to a boolean variable. How do you feel about this?
