### ISSUE TITLE
User Guide: broken formatting

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1024]
![image](https://user-images.githubusercontent.com/1673303/73343329-66d87200-42bb-11ea-8451-7d60ebffda07.png)

**Comment by anubh-v** [comment]
I think this is the same issue as #994 ?  Please let me know if this is not the case.
It is being tackled in PR #907

**Comment by Tejas2805** [comment]
Tackling in #907

**Comment by Tejas2805** [comment]
#907 Merged
