### ISSUE TITLE
Zoom view's ramp chart changes according to summary view's settings

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1026]
While trying to fix #830, the following behaviour was found:

When toggling between settings such as `granularity` and `sinceDate` and `untilDate`, the zoom view's ramp chart updates itself accordingly. Is this intended? Or should the zoom view's ramp chart not be affected by the changes in summary?

![Kapture 2020-01-30 at 0 47 38](https://user-images.githubusercontent.com/32864116/73377563-34019e80-42fa-11ea-8a3d-2b8b9844c597.gif)

**Comment by fzdy1914** [comment]
From my experiment, only granularity will result in this error?

**Comment by fzdy1914** [comment]
The inner reason is the `user` inside `info` property got updated when changing the granularity.
Sending a deep clone of the `info` when opens the tab should solve the problem.

**Comment by fzdy1914** [comment]
But I am not sure if it is better to correct it or not.

**Comment by fzdy1914** [comment]
@damithc @eugenepeh  Can I know your idea if we need to synchronize the summary and tab? 

For now, we allow the setting of summary and tab to be separated. For example, we may first open the authorship in the default view and then click the merged group. Then, the setting is different in two parts of our report. 

If we synchronize the settings, we ensure that those settings can be synchronized to the tab when the setting is changed in summary. Just like the issue described here.

These two different ways of synchronizing may change the inner logic a lot.

**Comment by eugenepeh** [comment]
I think we can leave it for now, its not _exactly_ a bug that we need to rush in to fix it.
Just to check, does merge ramp affects this behavior?

**Comment by fzdy1914** [comment]
> I think we can leave it for now, its not _exactly_ a bug that we need to rush in to fix it.
> Just to check, does merge ramp affects this behavior?

However, if we need to restore the zoom tab, we need to decide what exact page we want to reproduce. So maybe we can get the answer here and then modify it gradually to the target during the development.

**Comment by eugenepeh** [comment]
>However, if we need to restore the zoom tab, we need to decide what exact page we want to reproduce. So maybe we can get the answer here and then modify it gradually to the target during the development.

For now, I would think the having the correct date range and the last opened (the author) zoom tab would be sufficient. It is normal to have some non-important controls get reset back to default upon refresh etc, especially for a non-critical component like zoom tab

Can seek @damithc 's opinion too

**Comment by jamessspanggg** [comment]
> From my experiment, only granularity will result in this error?

Modifying `since date` and `until date` in summary will also result to this error. However, the error will only exist when the updated since/until date does not contain the commits in the zoom tab. I suspect it's because the `filteredUser` in zoom tab is updated such that it does not contain the previous commits anymore.

![Kapture 2020-01-30 at 21 32 55](https://user-images.githubusercontent.com/32864116/73453995-20ad0c80-43a8-11ea-9074-0f3143a67255.gif)

**Comment by damithc** [comment]
> For now, I would think that having the correct date range and the last opened (the author) zoom tab would be sufficient. It is normal to have some non-important controls get reset back to default upon refresh etc, especially for a non-critical component like zoom tab

Yes, let's go with that.

**Comment by jamessspanggg** [comment]
Closing this as this issue no longer occurs.
