### ISSUE TITLE
Weird arrangement with overlonged tag list in Zoom tab

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#1027]
![image](https://user-images.githubusercontent.com/35621726/73414336-7c947880-4349-11ea-86b4-eace429e0053.png)

**Comment by Tejas2805** [comment]
Is there a possibility of such a case?

**Comment by fzdy1914** [comment]
> Is there a possibility of such a case?

Yes, when viewing the zoom tab of merged groups.
