### ISSUE TITLE
Contribution bar UI error

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1029]
May be a regression due to PR #1003.

<img width="778" alt="Screen Shot 2020-01-30 at 9 24 33 PM" src="https://user-images.githubusercontent.com/32864116/73453411-e98a2b80-43a6-11ea-84d1-9317ee827a0f.png">

**Comment by damithc** [comment]
Need to fix quickly as I'm using the master branch for CS2113.

**Comment by jamessspanggg** [comment]
@damithc noted prof.

**Comment by Tejas2805** [comment]
Yup. I just checked. It's due to my PR #1003 Sorry about that.
