### ISSUE TITLE
Contribution output for each repository is randomized

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#103]
Running functional test consecutively produce output that are arranged in different order.
Using diff on 2 different generated folder gives the following output
`Files 2018-05-16-11-30-22/CS2103AUG2017-W09-B1_main/result.js and 2018-05-16-11-31-53/CS2103AUG2017-W09-B1_main/result.js differ`

This makes it hard for us to perform automated tests as the generated and expected would be different.

**Comment by harryggg** [comment]
But the result is the same right...? Just the order of element is different?

**Comment by eugenepeh** [comment]
> But the result is the same right...? Just the order of element is different?

Yup but for now I think we will just remove threading because it starves our PC of processing power as well.

**Comment by harryggg** [comment]
okok. 
Just want to mention here that you can just Collection.sort before converting to ensure the absolute consistency.

**Comment by eugenepeh** [comment]
Got it, will take note of that when we're ready to bring threading back.
