### ISSUE TITLE
Author: Copy constructor assigns `authorAliases` to `ignoreGlobList`

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1032]
In the `Author` class' copy constructor, we are assigning the copied instance's `authorAliases` to the original instance's `ignoreGlobList`.

See line 65 below:

https://github.com/reposense/RepoSense/blob/5b1fb323dc18c52e930158a4cdd184232dd8a826/src/main/java/reposense/model/Author.java#L60-L67

Is this intended? I think there might be a mistake here.

**Comment by anubh-v** [comment]
@jylee-git, @fzdy1914, may I check this with you?

**Comment by fzdy1914** [comment]
I think it should be a mistake.

**Comment by anubh-v** [comment]
@fzdy1914, in that case I'll submit a fix for this.
This isn't a very serious issue as this copy constructor is only used by 3 test cases, and even those are unaffected by this problem.
