### ISSUE TITLE
Duplicate code in v_summary.js

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1046]
There is duplicate code in v_summary.js. 

![Screen Shot 2020-02-03 at 4 42 08 AM](https://user-images.githubusercontent.com/35946746/73615036-bdd5a280-463f-11ea-8530-fdb36030eddd.png)

![Screen Shot 2020-02-03 at 4 41 53 AM](https://user-images.githubusercontent.com/35946746/73615033-b4e4d100-463f-11ea-96b0-fc23b9a37976.png)

**Comment by yash-chowdhary** [comment]
I can work on this if it's still up for grabs.

**Comment by Tejas2805** [comment]
Please go ahead.
