### ISSUE TITLE
Hard to understand code snippet in v_summary.js

### ISSUE THREAD

**Issue by openorclose** [reposense/RepoSense#1047]
https://github.com/reposense/RepoSense/blob/b98f31eaa04839fa7d3883b684f933bd51241a93/frontend/src/static/js/v_summary.js#L412-L415

This code checks to see if there exists at least one search term inside `user.searchPath`, which
can be easier to understand if changed to:

```js
 const toDisplay = this.filterSearch.toLowerCase() 
     .split(' ').filter((param) => param) 
     .some((param) => user.searchPath.includes(param));
```

**Comment by fzdy1914** [comment]
Yes, I think it is a good suggestion.
