### ISSUE TITLE
Inconsistent thickness of different contribution bars despite PR fix

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#1049]
Following issue #181 and PR #976 , the issue of different thickness still exists

![image](https://user-images.githubusercontent.com/35756209/73633498-cf4b9880-4699-11ea-9075-2a543c09fb00.png)

https://github.com/reposense/RepoSense/blob/b98f31eaa04839fa7d3883b684f933bd51241a93/frontend/src/static/css/v_summary.scss#L168-L174

The height is reverted to `rem` for some reason.

**Comment by fzdy1914** [comment]
It should be the same reason for #1003. It is my bad for not carefully check the merged content.

**Comment by Tejas2805** [comment]
Sorry about this. :'(

I will fix this in #1017 ? If okay with both of you?

**Comment by fzdy1914** [comment]
Yes, since it is a small change, just sneak it in #1017.

**Comment by Tejas2805** [comment]
Fixed in #1017
