### ISSUE TITLE
Add Issue Selector and Templates

### ISSUE THREAD

**Issue by yash-chowdhary** [reposense/RepoSense#1052]
An issue selector looks something like [this](https://github.com/facebook/react/issues/new/choose). The purpose of this is to direct the user to different templates that they can follow to file the issues. Some users may forget to add information that _they_ might think is not relevant but _could_ potentially be relevant in the eyes of the developers. This would also help developers get a clearer understanding of the issue.

The suggested issue types could be `Bug Report`, `Feature Request`, and `Documentation`.

Here are a few templates for each that we could refer to -
1. Bug Report - [React](https://github.com/facebook/react/issues/new?labels=Status%3A+Unconfirmed&template=bug_report.md&title=Bug%3A+), [Gatsby](https://github.com/gatsbyjs/gatsby/issues/new?template=bug_report.md), [MarkBind](https://github.com/MarkBind/markbind/issues/new?labels=c.Bug+%3Abug%3A&template=bug-report.md)
1. Feature Request - [MarkBind](https://github.com/MarkBind/markbind/issues/new?labels=c.Feature+%3Arocket%3A&template=feature-request.md), [Gatsby](https://github.com/gatsbyjs/gatsby/issues/new?template=feature_request.md)
1. Documentation Update/Issue - [Gatsby](https://github.com/gatsbyjs/gatsby/issues/new?template=documentation.md) (excluding the `Steps to resolve this issue` part)

**Comment by Tejas2805** [comment]
I think this is a good idea. Let's wait for the senior devs to respond.
