### ISSUE TITLE
Provide a way to use GitHub actions to auto-generate the dashboard

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1058]
Current: users need to use Travis to auto-generate the dashboard periodically
Suggested: explore if GitHub actions can be given as an alternative

**Comment by niqiukun** [comment]
Working on this. Tried update GitHub pages on push using GitHub actions and it works.

![image](https://user-images.githubusercontent.com/5328196/74466613-88984280-4ed2-11ea-9d42-9bb1c42eec7d.png)

Will work on scheduled trigger and documentation soon.
