### ISSUE TITLE
Add time taken for analysis in report

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#1060]
I think we should add a hidden time taken value in the report for our own benchmark purposes.
This allows us to do a rough gauge on the RepoSense's performance from e.g. automated nightly build of dashboard demo or CS2113 dashboard etc.

**Comment by anubh-v** [comment]
I'll attempt this

**Comment by fzdy1914** [comment]
@eugenepeh How would you like the hidden time to be displayed? An attribute can be viewed in the Vue developer tool or a value hidden in the DOM?

**Comment by anubh-v** [comment]
Sorry, @eugenepeh, I might have mis-understood.
I understood this to be about adding a footnote indicating the time taken.

i.e. something like this:
![image](https://user-images.githubusercontent.com/35621759/74010219-ebb04380-49bf-11ea-8e97-7763d58cbb9a.png)

Is this what you meant?

**Comment by eugenepeh** [comment]
hidden in the dom will be preferred, so that it is not necessary to install the vue dev tool.

>Is this what you meant?
The time measured here is the time taken for cloning + analysis + generating json files, (excluding zipping the files).

Yes, something like that but this field should probably be hidden as the info is not particularly important to the readers.
