### ISSUE TITLE
Author: Add a `isIgnoringFile` method

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1076]
Currently, there are a few instances where we obtain the `ignoreGlobMatcher` from an `Author` instance and then manually check if this matches with a given file path.

We could simplify the design by allowing the `Author` instance to tell clients if it is ignoring a particular file (given a filepath) - instead of giving clients the `ignoreGlobMatcher` and letting clients figure out the answer on their own.

Here are the current usages of `getIgnoreGlobMatcher`:

**FileInfoAnalyzer**
https://github.com/reposense/RepoSense/blob/cc28942504f513fc7c277c6eda0ac01b353ae962/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L145-L152

**AnnotatorAnalyzer**
https://github.com/reposense/RepoSense/blob/cc28942504f513fc7c277c6eda0ac01b353ae962/src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java#L32-L36

**AuthorTest**
https://github.com/reposense/RepoSense/blob/cc28942504f513fc7c277c6eda0ac01b353ae962/src/test/java/reposense/model/AuthorTest.java#L84-L87

**AuthorTest**
https://github.com/reposense/RepoSense/blob/cc28942504f513fc7c277c6eda0ac01b353ae962/src/test/java/reposense/model/AuthorTest.java#L44-L48

**Comment by anubh-v** [comment]
@fzdy1914 @jylee-git what do you think?
Thanks for your time

**Comment by fzdy1914** [comment]
OK to me.

**Comment by jylee-git** [comment]
Yes; can go ahead to refactor
