### ISSUE TITLE
ChartPanel: Total LoC contribution does not match with the commits

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1077]
In the CS3281 dashboard, the following author is seen with 0 code contribution, however, there is a commit that has 180 lines of contribution. The code panel does not show any code changes as well.

Link to reproduce: [here](https://nus-cs3281.github.io/2020-dashboard/#search=nbrian&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByAuthors&breakdown=false&since=2019-12-01)
<img width="500" alt="Screen Shot 2020-02-13 at 12 42 37 PM" src="https://user-images.githubusercontent.com/32864116/74402184-767cbc80-4e5e-11ea-96c8-c72054b2a266.png">

**Comment by damithc** [comment]
That commit was reverted later. That's why there is no net contribution.

**Comment by jamessspanggg** [comment]
> That commit was reverted later. That's why there is no net contribution.

Ah I see. Then would the current behaviour be appropriate to reflect reverted commits?

**Comment by damithc** [comment]
> Ah I see. Then would the current behaviour be appropriate to reflect reverted commits?

Yes, if there is no net effect, there should not be any contribution (as per our current definition of contribution).

**Comment by jamessspanggg** [comment]
Ok. Will be closing this issue.
