### ISSUE TITLE
Authorship view: bug in `hide all file details` button

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1081]
As raised by @Tejas2805 in #1040, the file detail will be automatically displayed after untick->tick the file type, though it is supposed to be hidden.

Step to reproduce:
1) Click on `hide all file details`
2) Untick `frontend`
3) Tick `frontend`
4) Scroll all the way to the bottom

Expected result: Files should still be hidden due to Step 1
Actual result: Files affected by Step 3 are not hidden

![Screen Shot 2020-02-15 at 12 49 15 AM](https://user-images.githubusercontent.com/35946746/74560686-15073b80-4f8d-11ea-8a6c-107bc3c4b4ad.png)

_Originally posted by @Tejas2805 in https://github.com/reposense/RepoSense/pull/1040#issuecomment-586433653_

**Comment by Tejas2805** [comment]
Better name for issue might be - bug in `hide all file details`?

**Comment by 0blivious** [comment]
Can be solved by #1065
