### ISSUE TITLE
RepoConfiguration: remove `annotationOverwrite` flag

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1083]
The `RepoConfiguration` class has a `annotationOverwrite` attribute that controls whether the `@@author` tags are applied / ignored.

However, this attribute is always true.
Do we plan to have any cases where `@@author` tags are ignored?
If not, would it be preferable to remove `annotationOverwrite` attrbute to simplify the `RepoConfiguration` class?

Relevant code snippets:
https://github.com/reposense/RepoSense/blob/5cd4123966a51b1916858b08bc45d12014ad8157/src/main/java/reposense/model/RepoConfiguration.java#L32

The setter method below is not used anywhere.
https://github.com/reposense/RepoSense/blob/5cd4123966a51b1916858b08bc45d12014ad8157/src/main/java/reposense/model/RepoConfiguration.java#L331-L333

The `annotationOverwite` property is checked in `FileInfoAnalyzer`.
The check always passes since `annotationOverwrite` property is always true.

https://github.com/reposense/RepoSense/blob/5cd4123966a51b1916858b08bc45d12014ad8157/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L63-L65

**Comment by anubh-v** [comment]
@fzdy1914 @jylee-git may I check this with you? Thanks alot for your time.

**Comment by jylee-git** [comment]
If i recall correctly, I think it was used for test cases previously but not utilized in the main code at all.

I don't think it's used anywhere now. So we should remove the usage of `annotationOverwrite`
