### ISSUE TITLE
Authorship view: Sort by FileType

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1084]
When files are sorted by `fileType`, the following occurs where `java` test files are not in order...

<img width="776" alt="Screen Shot 2020-02-15 at 2 37 37 PM" src="https://user-images.githubusercontent.com/32864116/74583306-bda2b300-5000-11ea-8e2c-576f7b3893f1.png">

[Link to reproduce](https://deploy-preview-1074--reposense.netlify.com/#search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=AdityaA1998&tabRepo=reposense%2FRepoSense%5Bmaster%5D)

_Originally posted by @jamessspanggg in [1074](https://github.com/reposense/RepoSense/pull/1074#issuecomment-586560683_)

**Comment by 0blivious** [comment]
They are sorted in order, the reason here is that in the code we define fileType to be the custom group. So in the page you shown the actual file type used are `tests`, `frontend`, `backend`, etc. 

If we want to make this more explicit, maybe we should rename the sort option to `customised group` and add another option to sort by the real file type (the naming after the dot). However, in the Chart panel we also have the button `break down by file type`, which again correspond to the customised group (if any). 

@fzdy1914 Do you feel we need to rename the buttons?

**Comment by fzdy1914** [comment]
That's an interesting finding.  We should aim to find a `noun` to replace `file type` which can stand for both `file extension` and `customized group`?

**Comment by Tejas2805** [comment]
If we do rename the buttons, might as well do the changes in #1074 , since I am already touching this logic in it?

**Comment by Tejas2805** [comment]
@damithc Your opinion on this.

**Comment by damithc** [comment]
> That's an interesting finding. We should aim to find a `noun` to replace `file type` which can stand for both `file extension` and `customized group`?

I think `file type` means exactly that i.e., If groups have bee defined, `type` is used to mean the group. Else, it is used to mean type as implied by the file extension.

However, we can visually indicate the type of each file, to avoid this kind of confusion. For example, as a text label, or using colors.

**Comment by Tejas2805** [comment]
> I think file type means exactly that i.e., If groups have bee defined, type is used to mean the group. Else, it is used to mean type as implied by the file extension.

We can explain this in the UG for better understanding?

> However, we can visually indicate the type of each file, to avoid this kind of confusion. For example, as a text label, or using colors.

We can implement this for better understanding.

**Comment by Tejas2805** [comment]
@0blivious You want to take up this issue or is it okay if I do it in #1074

**Comment by 0blivious** [comment]
Actually I was thinking trying sth like a colored background (like #1025) for the file title since now we have too many icons appended at the back? Also I feel the name can be changed to sth like `file group` which sounds less misleading for me. I think you can change the UG in your PR first. I will try some UI adjustment and paste it here.

**Comment by Tejas2805** [comment]
Better to keep both in one PR. You should proceed with both.

**Comment by 0blivious** [comment]
I propose this new UI, how do you feel? @damithc @fzdy1914 @Tejas2805 
![image](https://user-images.githubusercontent.com/39231750/74752307-6ffca380-52a9-11ea-8d35-a889453d23f4.png)

**Comment by Tejas2805** [comment]
If the color of breakdown by file type matches with the colors for the files on the chart panel, I am okay with it. 

But, I feel the file headers will take a lot of space, and not sure if that is required.

Let's wait for the Prof's comment.

**Comment by damithc** [comment]
Generally OK but I don't want to dedicate two lines for each header is we can help it. Perhaps we can simply add the color tag to the end of the current header?
![image](https://user-images.githubusercontent.com/1673303/74793112-60597b00-52fa-11ea-83d8-0100768b4877.png)

**Comment by 0blivious** [comment]
> Generally OK but I don't want to dedicate two lines for each header is we can help it. Perhaps we can simply add the color tag to the end of the current header?

My justification is, usually the path can be very long and without the new color tag, it already occupy 2 lines.
![image](https://user-images.githubusercontent.com/39231750/74801916-2c3e8400-5313-11ea-8916-291ceb5ff54f.png)

So my suggestion is we display only the file name in the title. If you dont like 2 lines, we can hide the path in the code section.
![image](https://user-images.githubusercontent.com/39231750/74801983-660f8a80-5313-11ea-9cbd-c430a7cfd716.png)

![image](https://user-images.githubusercontent.com/39231750/74801881-0add9800-5313-11ea-9047-4de6f7aaf4f8.png)

How do you feel about this? Only display the full path we the user expand the code.

**Comment by damithc** [comment]
> My justification is, usually the path can be very long and without the new color tag, it already occupy 2 lines.

In rare cases, yes, but usually it doesn't. It's fine to spill over to a second line if the file name is long, but we shouldn't force it. Besides, a user can always widen the code panel to make room for longer file paths.

> How do you feel about this? Only display the full path we the user expand the code.

That doesn't save space, plus it is less informative than before.

**Comment by fzdy1914** [comment]
I agrees that a color is enough.
