### ISSUE TITLE
AuthorConfigCsvParser has some similar code as AuthorConfiguration

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1086]
Within the `processLine` method of `AuthorConfigCsvParser`, we call the methods `setEmails`, `setDisplayName`, `setAliases` and `setAuthorIgnoreGlobList`.

The `setEmails`, `setDisplayName` and `setAliases` method will update some internal data structures in the `AuthorConfiguration` class.

However, `AuthorConfiguration` also has an `addAuthor` method that accepts an `Author` and then updates these data structures by inspecting the `Author` instance.

From my understanding, it seems we could allow `AuthorConfiguration` to update its data structures on its own, without performing this task in `AuthorConfigurationCsvParser`. 

Is there a reason behind having `setEmails`, `setDisplayName`, `setAliases`, and `setAuthorIgnoreGlobList` in `AuthorConfigCsvParser`?

Thanks for your time.

Here are the relevant methods in `AuthorConfigurationCsvParser`:

https://github.com/reposense/RepoSense/blob/cdc42693ec91199e3638dff068fb07aae61a5e9b/src/main/java/reposense/parser/AuthorConfigCsvParser.java#L74-L78

https://github.com/reposense/RepoSense/blob/5cd4123966a51b1916858b08bc45d12014ad8157/src/main/java/reposense/parser/AuthorConfigCsvParser.java#L103-L144

Here are the relevant methods in `AuthorConfiguration`:
https://github.com/reposense/RepoSense/blob/5cd4123966a51b1916858b08bc45d12014ad8157/src/main/java/reposense/model/AuthorConfiguration.java#L126-L132

https://github.com/reposense/RepoSense/blob/5cd4123966a51b1916858b08bc45d12014ad8157/src/main/java/reposense/model/AuthorConfiguration.java#L105-L117

**Comment by anubh-v** [comment]
@fzdy1914, @jylee-git may I get your thoughts on this?
Thanks for your time

**Comment by fzdy1914** [comment]
One is setting the info for Author and another one is setting the info for configuration? It seems to be different from my view.

**Comment by jylee-git** [comment]
> Is there a reason behind having setEmails, setDisplayName, setAliases, and setAuthorIgnoreGlobList in AuthorConfigCsvParser?

I guess it's a form of abstraction? Especially in `setEmails`, `setDisplayName` and `setAliases` method of `AuthorConfigCsvParser`.

**Comment by anubh-v** [comment]
Thanks very much for the response.
I'm still a little unclear.

Let me know if I'm wrong here - but I think the program would be unaffected if it was written as follows ?
- Do not update the `AuthorConfiguration` instance in the `setEmails`, `setDisplayName` and `setAliases` methods. Only update the `Author` instance.
- Call `setEmails`, `setDisplayName`, `setAliases`, `setIgnoreGlobsList`  **before** calling the `addAuthor` method

**Comment by fzdy1914** [comment]
> Thanks very much for the response.
> I'm still a little unclear.
> 
> Let me know if I'm wrong here - but (I think) the program should be unaffected if it was written as follows ?
> 
> * Do not update the `AuthorConfiguration` instance in the `setEmails`, `setDisplayName` and `setAliases` methods. Only update the `Author` instance.
> * In `AuthorConfigCsvParser#processLine`, call `setEmails`, `setDisplayName`, `setAliases`, `setIgnoreGlobsList`  **before** calling the `addAuthor`
> 
> Essentially, I wish to clarify why the `AuthorConfigCsvParser` needs to modify the `AuthorConfiguration` instance since the `AuthorConfiguration` instance can perform this work when we call `addAuthor`.
> 
> > One is setting the info for Author and another one is setting the info for configuration?
> 
> But isn't the `AuthorConfiguration` instance being updated in both `AuthorConfigCsvParser` and `AuthorConfiguration` ? Let me know if I'm understanding this incorrectly.
> 
> Thanks for your time.

After reviewing your comment, I believe what you think is correct.  I thought we got a PR fixing this? It seems that I cannot find it anymore.

**Comment by anubh-v** [comment]
I have tried addressing this issue in [this PR](https://github.com/reposense/RepoSense/pull/1270)

**Comment by fzdy1914** [comment]
> I have tried addressing this issue in [this PR](https://github.com/reposense/RepoSense/pull/1270)

OK

**Comment by fzdy1914** [comment]
Closing this issue as we got another similar one.
