### ISSUE TITLE
README: update netlify badge

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#1087]
Starting April 14, 2020, sites without a custom domain are being moved from your-site.netlify.com to your-site.netlify.app. As the badge icon on our readme is a customed icon, it would not work after 14 April. See if netlify have its own badge icon now that we can implement or update the current badge on 14 April.

**Comment by jamessspanggg** [comment]
Do you mean netlify badges from this link? https://www.netlify.com/press/#badges

Our README currently uses one of these badges tho.

**Comment by eugenepeh** [comment]
>[![deploy on_netlify](https://img.shields.io/badge/deploy-on_netlify-blue.svg)](https://reposense.netlify.com/)

I mean this badge ^

**Comment by jamessspanggg** [comment]
The deploy status badge can be found in the netlify website. 

<img width="728" alt="Screen Shot 2020-03-14 at 8 34 04 PM" src="https://user-images.githubusercontent.com/32864116/76681995-28143680-6633-11ea-970d-0ae351c7e7c6.png">

**Comment by eugenepeh** [comment]
holding this issue for now as we owe netlify some overusage fee and they may soon cancel our subscription.

meanwhile I am getting them to waive off the charges.

**Comment by eugenepeh** [comment]
can proceed with changing to this badge

[![Netlify Status](https://api.netlify.com/api/v1/badges/260983b3-589e-4619-a2e8-0bfb7a2b4422/deploy-status)](https://app.netlify.com/sites/reposense/deploys)
