### ISSUE TITLE
Repo not analyzed

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1092]
Even though a student has commits for the given time period, the chart panel shows no contribution.

![Screen Shot 2020-02-18 at 12 06 43 PM](https://user-images.githubusercontent.com/35946746/74710284-3dba5a00-5247-11ea-92b9-b48f04834b3a.png)

![Screen Shot 2020-02-18 at 12 06 32 PM](https://user-images.githubusercontent.com/35946746/74710264-3004d480-5247-11ea-9228-e36e31a57270.png)

CS2103 AY1920 S2 Dashboard: [Link](https://nus-cs2103-ay1920s2.github.io/ip-dashboard/#sort=groupTitle&groupSelect=groupByAuthors&search=tohkerwei&sortWithin=title&timeframe=commit&mergegroup=false&breakdown=false&since=2020-01-17&tabOpen=true&tabType=zoom&tabAuthor=tohkerwei&tabRepo=tohkerwei%2Fduke%5Bmaster%5D)

Let's try and understand why.

**Comment by fzdy1914** [comment]
Please include a reproduce link if possible.

**Comment by 0blivious** [comment]
It works fine on my computer when I try to analyse the master repo. Can we get the argument file used?

![image](https://user-images.githubusercontent.com/39231750/74716472-98fd4400-5269-11ea-8ecb-8e3fc3319073.png)

**Comment by jylee-git** [comment]
Note that the author used a different Git ID to commit his work than the one that was provided in (I presume CS21X3, when students are required to provide their GitHub ID).

**Comment by Tejas2805** [comment]
Thanks for helping @jylee-git .
