### ISSUE TITLE
RepoLocation: `convertStringsToLocations` method is unused

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1097]
The method `convertStringsToLocations` is not used in the codebase.

It was introduced in [this PR](https://github.com/reposense/RepoSense/pull/425).

https://github.com/reposense/RepoSense/blob/cd9e636fec6c7919fc50ed040da195e699760fa3/src/main/java/reposense/model/RepoLocation.java#L109-L126

Let's decide if this method should be kept?

**Comment by anubh-v** [comment]
@fzdy1914 may I confirm that this is suitable to remove? 
We could collate all the issues involving unused code, if that is more organised?

**Comment by fzdy1914** [comment]
It seems not used. It is OK to remove them one by one. However, it is encouraged to remove more at one time.
