### ISSUE TITLE
File type does not match with the contribution

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1107]
The filetype `docs` is shown but there are no contribution to docs in the contribution bar, as well as the code panel:

<img width="1767" alt="Screen Shot 2020-03-01 at 10 34 45 PM" src="https://user-images.githubusercontent.com/32864116/75627651-04052e00-5c0d-11ea-8fb9-339b12030647.png">

[Link to reproduce](https://deploy-preview-1068--reposense.netlify.com/#search=delta&sort=totalCommits&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=true&tabOpen=true&since=2017-10-09&tabType=authorship&tabAuthor=codeeong&tabRepo=reposense%2Ftestrepo-Delta%5Bmaster%5D)

**Comment by jamessspanggg** [comment]
The reason due to this issue is that the user has already specified the group file types beforehand, that is why the filetype is shown in the summary panel. It might be useful to view the filetype, even though 0 contribution is made for that particular filetype.

<img width="1000" alt="Screen Shot 2020-03-03 at 10 46 27 AM" src="https://user-images.githubusercontent.com/32864116/75738084-4c6f3980-5d3c-11ea-855b-9f3c902872f5.png">

**Comment by jamessspanggg** [comment]
@ang-zeyu look at my comment above. I think your PR may not be necessary.

**Comment by ang-zeyu** [comment]
> @ang-zeyu look at my comment above. I think your PR may not be necessary. Thanks for trying to fix tho.

Thanks for the follow up as well! I'll close the PR then
