### ISSUE TITLE
Links to cross-origin destinations are unsafe

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1110]
Links to cross-origin destinations are unsafe. Let's move the links to open on the same webpage.

**Comment by Tejas2805** [comment]
@fzdy1914 What do you think? 

@damithc Since this might affect User Experience, what do you suggest?

**Comment by jamessspanggg** [comment]
I don't think this is necessary as we are only linking to GitHub...?

**Comment by Tejas2805** [comment]
Agree with you on that. But thought better to clarify and discuss it.

Closing this.
