### ISSUE TITLE
Webpage might go to quirks mode

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1111]
We currently don't have a `DOCTYPE` and neither a language mentioned. This causes the page to go to [quirk mode](https://stackoverflow.com/questions/1695787/what-is-quirks-mode) some times and as a result the page might not get rendered correctly.

Sggestion: Let's add a `DOCTYPE` and specify the language, to make sure the page goes to standard mode and renders correctly.

**Comment by Tejas2805** [comment]
@jylee-git @fzdy1914 Need your take on this. Thank you for your time.

**Comment by fzdy1914** [comment]
GO AHEAD

**Comment by Tejas2805** [comment]
Removing assignment and moving this to a `firstTimers` issue as we need more of them.
