### ISSUE TITLE
Investigate case of @@author tag not being honored

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1115]
Shouldn't this code block be skipped as it is attributed to a different author?
![image](https://user-images.githubusercontent.com/1673303/75888439-53926680-5e66-11ea-9ab3-428517da3975.png)

https://nus-cs2113-ay1920s2.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2020-03-01&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=jinfayap&tabRepo=AY1920S2-CS2113T-M16-2%2Ftp%5Bmaster%5D

configs https://github.com/nus-cs2113-AY1920S2/tp-dashboard

**Comment by jylee-git** [comment]
I think this issue is identical to #823

**Comment by damithc** [comment]
> I think this issue is identical to #823

I see. Yes, looks like it. We need to fix it soon as it affects the current usage in ongoing modules.

**Comment by anubh-v** [comment]
I have been working on this bugfix.
The progress was slightly delayed as I increased the scope of the PR in order to cater for the "ramps for virtual authors" (#1082) feature.

I'll postpone that work to another PR, since the bugfix is urgent.

**Comment by damithc** [comment]
Guys, this is urgent as this is central to how RepoSense is being used.

**Comment by anubh-v** [comment]
The bugfix is ready to merge
