### ISSUE TITLE
Use less restrictive regex for author name in @@author tags

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1118]
Currently, the regex used to validate names in `@@author some-randomeuser` tags is:
`[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]`

 This regex ensures the author name has at least 2 consecutive alphanumeric characters.

As discussed in this [comment](https://github.com/reposense/RepoSense/pull/1067#discussion_r382583692), we can consider using a less restrictive regex, so that tags such as `@@author --myname--` are accepted.

**Comment by anubh-v** [comment]
@jylee-git after some thought, I do not really see a reason we might need a regex validation at all for the author name given in `@@author` tags.

(if no author name is provided, the tag is consider an *end tag* )

Do you see any need for a regex validation?

**Comment by jylee-git** [comment]
I don't think there's a need for any validations required for the author names/IDs.

An author ID should be valid as long as it's not empty.

**Comment by anubh-v** [comment]
> I don't think there's a need for any validations required for the author names/IDs.

I agree with this.
Shall we remove the regex validation then?
@fzdy1914 would you agree?

**Comment by HCY123902** [comment]
Hello, I am wondering if this issue is still under discussion, or will it be acceptable for me to work on this issue?

**Comment by fzdy1914** [comment]
> > I don't think there's a need for any validations required for the author names/IDs.
> 
> I agree with this.
> Shall we remove the regex validation then?
> @fzdy1914 would you agree?

I am OK with it.

**Comment by damithc** [comment]
@fzdy1914 is this suitable for first-timers?

**Comment by fzdy1914** [comment]
Yes, it is quite simple to remove the validation.

**Comment by HCY123902** [comment]
Note for first timers who want to work on this issue:

The basic idea is to change or remove the validation for the author name tag located in `AnnotatorAnalyzer.java` by modifying the`REGEX_AUTHOR_NAME_FORMAT` argument.

https://github.com/reposense/RepoSense/blob/451f11b74cb895b079c14316a4fd323f2eccff1c/src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java#L17-L21

You may need to check that the unit and system testing still passes after making the change by running the command `gradlew systemtest` and `gradlew test`

Here are some explanation about the [usage of author tag](https://reposense.org/ug/usingAuthorTags.html).

**Comment by bingsen0806** [comment]
Hi @damithc can I confirm that no one is currently working on this? I would like to take on this issue as a first timer.

**Comment by RyanCheungJF** [comment]
Hi, could I try taking up this issue?

**Comment by dcshzj** [comment]
@RyanCheungJF Sure, I've assigned you the issue.

**Comment by sikai00** [comment]
Hi, given that the last PR was last modified a month ago, can I try taking this issue?

**Comment by HCY123902** [comment]
> Hi, given that the last PR was last modified a month ago, can I try taking this issue?

yeah sure. However, please considering discussing it with @RyanCheungJF about it first. You may need to continue the work from #1846 instead of starting again on your own

**Comment by sikai00** [comment]
>  However, please consider discussing it with @RyanCheungJF about it first. 
Understood, I will try to contact him regarding this!

**Comment by RyanCheungJF** [comment]
Hi! Sorry for being inactive, but Si Kai has contacted me and I'm ok with him taking over the issue 👍🏻. Since he has created a new PR, I'll close my PR in a day if there's nothing else. Thanks!
