### ISSUE TITLE
Author: class attribute 'NAME_FAILED_TO_CLONE_OR_CHECKOUT' is unused

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1119]
Relevant code snippet:
https://github.com/reposense/RepoSense/blob/4d38d298cc0b7e0e03f9a8b0d7e88e2f46a31ad5/src/main/java/reposense/model/Author.java#L11-L13

Let's remove this if it is un-intentional?

**Comment by jylee-git** [comment]
That should have been deprecated after the introduction of #743 . Let's remove that
