### ISSUE TITLE
Make Zoom Panel consistent with Authorship Panel

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1126]
In authorship we click on the file title to expand the file detail and use the fa-user icon to open the github page for the blame view.

However in authorship we click on the commit title to open the github page while use the fa button besides to  expand the commit message body.

Let's make them the same for consistency, clicking on the title on both panel will either expand the message body or open the github page. The icon vice versa.

**Comment by Tejas2805** [comment]
Discussed this with Prof today. He said better to keep it the way it is for rn. And once all current UI PR's are merged, then can take this up to make it consistent.

**Comment by damithc** [comment]
Closing for now as not a big issue. Will reopen later if needed.
