### ISSUE TITLE
GitTestTemplate: Remove code for setting file formats in BeforeClass method

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1128]
In both the `Before` and `BeforeClass` method, we are setting the file formats for the config.
See line 65 and line 72 in the snippet below:

https://github.com/reposense/RepoSense/blob/33e24b8d009acfe69932b8b8ceb4427778c5195c/src/test/java/reposense/template/GitTestTemplate.java#L61-L74

Is it necessary to set the file formats in both?

**Comment by anubh-v** [comment]
@jylee-git, may I check this with you?

**Comment by jylee-git** [comment]
No I don't think it's necessary. Can help to remove this when refactoring.
