### ISSUE TITLE
mbdf files not counted and displayed

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1132]
Though this [PR](https://github.com/MarkBind/markbind/pull/1063) was merged, the mbdf files are not displayed. 

I checked repo-config.csv mbdf is there. Any other reason?

![Screen Shot 2020-03-09 at 5 29 05 PM](https://user-images.githubusercontent.com/35946746/76200008-d54e0f80-622b-11ea-8b95-7f523f1447f9.png)

[Link to reproduce](https://nus-cs3281.github.io/2020-dashboard/#search=tejas&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=false&groupSelect=groupByAuthors&breakdown=false&since=2019-12-01&tabOpen=true&tabType=authorship&tabAuthor=Tejas2805&tabRepo=markbind%2Fmarkbind%5Bmaster%5D)

**Comment by jamessspanggg** [comment]
This is because the author for this commit is `marvinchin` on GitHub.

<img width="346" alt="Screen Shot 2020-03-09 at 10 36 19 PM" src="https://user-images.githubusercontent.com/32864116/76223558-676b0d80-6256-11ea-81c4-6b4312c0bdaa.png">

**Comment by jamessspanggg** [comment]
Closing this, as it is not an issue/bug that is related to RepoSense.

**Comment by Tejas2805** [comment]
Thanks for looking into it.
