### ISSUE TITLE
Build Failure when setting up project

### ISSUE THREAD

**Issue by shuiyao-sg** [reposense/RepoSense#1133]
Hi I'm planning to contribute to this project and was trying to set up the project locally following this [developer guide](https://github.com/reposense/RepoSense/blob/master/docs/DeveloperGuide.md#verifying-the-setup). I actually successfully imported the project into IntelliJ after following the instructions. The initial build was successful. But when I tried to verify my build as suggested in this [section](https://github.com/reposense/RepoSense/blob/master/docs/DeveloperGuide.md#verifying-the-setup), the "clean build" failed (as shown by the screenshot).
![image](https://user-images.githubusercontent.com/46176136/76245984-dd33a100-6277-11ea-8c0a-6a40353de495.png)

To replicate:
use IntelliJ's gradle run with command `gradlew clean build` (as shown below).
![image](https://user-images.githubusercontent.com/46176136/76246094-08b68b80-6278-11ea-970b-fd7bf2fd21c6.png)

The strange thing is that I tried again on WSL ubuntu with command `./gradlew clean build` and the build was successful.
![image](https://user-images.githubusercontent.com/46176136/76246207-37346680-6278-11ea-80c6-afbc28479375.png)

May I know why is this so? Is it the problem with my project set-up or is it just some problem with my IntelliJ/Windows path/configuration?

**Comment by shuiyao-sg** [comment]
Sorry...forgot to mention that here's the link to my forked repo https://github.com/shuiyao-sg/RepoSense

**Comment by 0blivious** [comment]
This is due to the fail in deletion of the certain file in `repos` folder. For your case, you can try to run the `RepoConfigurationTest` directly. If it passes, you may ignore the failure for now and continue your development.

**Comment by shuiyao-sg** [comment]
When I run `RepoConfigurationTest`, it shows me the same error but the rest all passed.
![image](https://user-images.githubusercontent.com/46176136/76294138-430e4000-62ed-11ea-815b-43f2247bfaf4.png)

Is this ok to proceed?

**Comment by 0blivious** [comment]
I meant to find the `RepoConfigurationTest.java` file, right click and run it (don't use gradle command). You may also try to run Reposense directly using the argument given in our Developer Guide. If the report is generated successfully, it is alright to proceed.

**Comment by shuiyao-sg** [comment]
I re-run the test and it passed. Thank you for your help!
