### ISSUE TITLE
Weird behaviour of RepoConfigurationTest

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1134]
As stated, this test cause `gradle clean build` to fail on windows. When run independently, it will fail for the first execution and pass for all the following tries. The fail is due to java io exception when trying to delete certain files in `repos`
![Screenshot (21)](https://user-images.githubusercontent.com/39231750/76280406-ba7fa780-62cc-11ea-8f19-320bb780d539.png)

**Comment by dcshzj** [comment]
I'm on Windows but I can't seem to reproduce this error. @0blivious do you have any reproducible steps for this bug?

**Comment by dcshzj** [comment]
Sure, thanks for your help @chan-j-d!
