### ISSUE TITLE
Invalid Location in example for config files in DG

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1135]
The example that we show for the location of config files in the Developer Guide is invalid. There are no config files in that location to run.

![Screen Shot 2020-03-11 at 3 32 23 AM](https://user-images.githubusercontent.com/35946746/76352497-19cfcd00-634a-11ea-9958-46e6d0506d74.png)

**Suggestion:** Since we display it as an example, let's either update the location or add config files in that location so that the location becomes valid.

**Comment by 0blivious** [comment]
Can update the since/until date also? I remembered that the date range actually display nothing when I tried.

**Comment by Tejas2805** [comment]
@fzdy1914 What do you think? Should I update the location to `--config ./` or add config files in the config folder?

**Comment by fzdy1914** [comment]
> @fzdy1914 What do you think? Should I update the location to `--config ./` or add config files in the config folder?

I personally prefer the latter. @eugenepeh Your inputs?
