### ISSUE TITLE
eslint in npm lint script malformed and uses the --fix option

### ISSUE THREAD

**Issue by ang-zeyu** [reposense/RepoSense#1138]
`eslint -- --fix frontend/src/**/*js frontend/cypress/**.js`

causes `--fix` to be treated as a file ( tested ) and auto-fixable errors to be unfixed.

The main `lint` script should not have `--fix` either so that the errors get reported in CI.

I've searched the eslint documentation as well, and could not find mention of an empty `--` option anywhere. Was this a typo in https://github.com/reposense/RepoSense/pull/803#discussion_r304482267?

**Comment by jamessspanggg** [comment]
> Preferably the javascript and css coding style can be combined together as they both use npm.
> The command can also be combined to npm run lint -- --fix frontend/src/**/*js && npm run stylelint so that developers dont have to do it separately.

@eugenepeh

**Comment by ang-zeyu** [comment]
`npm run lint -- --fix frontend/src/**/*js && npm run stylelint`
🤦‍♂ Apologies, looked at the command again, realised its `npm run lint -- --fix` and not `eslint -- --fix` ( what was merged ). ( arguments are provided to npm scripts via a `--` separator )

**Comment by eugenepeh** [comment]
is this issue still valid? if not please close it, thanks

**Comment by ang-zeyu** [comment]
> is this issue still valid? if not please close it, thanks

The problem still exists, only that it wasn't a typo here https://github.com/reposense/RepoSense/pull/803#discussion_r304482267 but a mistake made when translating the command given in it
