### ISSUE TITLE
Display message for empty commits panel

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1142]
For code panel that has zero contribution, a message is displayed `nothing to see here :(`

<img width="868" alt="Screen Shot 2020-03-13 at 4 54 26 PM" src="https://user-images.githubusercontent.com/32864116/76605413-620a0d80-654b-11ea-9194-2b49077a1784.png">

For empty commit panel, should we also find a way to tell the user that the commit panel is empty?  
<img width="868" alt="Screen Shot 2020-03-13 at 4 54 37 PM" src="https://user-images.githubusercontent.com/32864116/76605427-66362b00-654b-11ea-80c0-aa082de46ce1.png">

**Comment by Tejas2805** [comment]
Seeing the empty ramp chart on the summary panel, I think the user can figure out that the commits panel is empty in most probably. But, we can still display something.

**Comment by jamessspanggg** [comment]
@damithc may I get your opinion on this? 


- follow current way of displaying an empty ramp or
- display a message without the empty ramp and controls below it or
- display a message with the empty ramp and controls below it

**Comment by damithc** [comment]
Let's keep it as it is if the payoff for changing is not high.

**Comment by jamessspanggg** [comment]
Ok noted. Closing this issue.
