### ISSUE TITLE
Commit message title indicator is too light

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1143]
![Screen Shot 2020-03-13 at 8 12 54 PM](https://user-images.githubusercontent.com/35946746/76620027-3dbc2a00-6567-11ea-9d51-ca9dc4f8c319.png)

The line indicating 50 characters for commit message title is not seen too properly in the background. Let's make it a bit darker?

**Comment by Tejas2805** [comment]
@jamessspanggg What do you think?

**Comment by jamessspanggg** [comment]
It is actually intended to be subtle while bringing across the point. We don't want the border to take away too much attention from the title.

**Comment by Tejas2805** [comment]
Agree on that but I still feel it could be a tinge darker
