### ISSUE TITLE
Change example pictures in UG

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1144]
The example pictures in UG still have a grey background for the right panel. 

Let's update the pictures to  show the new white background.

**Comment by jamessspanggg** [comment]
Let's wait until  #1025 gets merged and create a PR that updates all diagrams in the UG. Reason being #1025 also updates the UI of the report, in this way we only need to update once.

**Comment by Tejas2805** [comment]
Agreed. Will keep the PR on hold till then.
