### ISSUE TITLE
Reactivity of zoom tab with changes in summary

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1145]
The zoom tab is currently reactive to changes in summary (such as granularity changes). However, when merge group is checked, the zoom tab is no longer reactive to the changes in summary.

To replicate, any PR preview will do.
![Kapture 2020-03-14 at 16 50 24](https://user-images.githubusercontent.com/32864116/76678571-1f603800-6614-11ea-8d2d-9f5550e42345.gif)

Should we make the zoom tab totally independent of the summary? As it will affect the implementations of PRs such as #779, #1101 and #967.

**Comment by jamessspanggg** [comment]
@fzdy1914 @0blivious your thoughts on this?

**Comment by 0blivious** [comment]
I am ok with it. What is the initial consideration for making this reactive though?

**Comment by jamessspanggg** [comment]
I am actually unsure of the reason as well.

**Comment by damithc** [comment]
Best not to go down paths that can cause unnecessary grief later on. If we can't make everything reactive, might as well not make anything reactive so that there is no confusion to the user. It is fine the right-side panel to not be reactive to the left-side panel, across the entire application.

**Comment by fzdy1914** [comment]
This may be related to what  #967 .
