### ISSUE TITLE
Not intuitive that authorship file detail is collapsible

### ISSUE THREAD

**Issue by ccyccyccy** [reposense/RepoSense#1146]
Currently it is not clear that the title is clickable to collapse the code view.

![image](https://user-images.githubusercontent.com/32454748/76683574-2a30c200-6640-11ea-805d-76bf419db679.png)

Let's add a small arrow such that it is clear that the panel is collapsible, similar to github's one

![image](https://user-images.githubusercontent.com/32454748/76683570-1e450000-6640-11ea-820f-0de046f8c8a4.png)

It should change when the panel is collapsed.

![image](https://user-images.githubusercontent.com/32454748/76683603-619f6e80-6640-11ea-882e-8f079902608d.png)

**Comment by jamessspanggg** [comment]
@damithc your opinion on this?

**Comment by damithc** [comment]
Yes, it is good to have.

**Comment by ccyccyccy** [comment]
@damithc Should we only allow clicking of the arrow to collapse the code panel, or clicking either the title or the arrow would collapse the panel?

**Comment by damithc** [comment]
> @damithc Should we only allow clicking of the arrow to collapse the code panel, or clicking either the title or the arrow would collapse the panel?

No harm allowing both I guess.
