### ISSUE TITLE
Consistency between Code panel and Chart panel for file type selection

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1150]
When a user clicks on the </> icon, we can auto-set the file types of the code panel to match the file type selection of the ramp chart.

_Originally posted by @damithc in https://github.com/reposense/RepoSense/pull/1025#issuecomment-599303582_

**Comment by Tejas2805** [comment]
Also, file type selection can be encoded in the URL so that a specific file selection can be shared through the URL.

@0blivious Is it okay if take this part? I don't have any other open PR right now. So I have some bandwidth. 

I am okay with taking the first one, if you want to do the second one.

**Comment by 0blivious** [comment]
> @0blivious Is it okay if take this part? I don't have any other open PR right now. So I have some bandwidth.
> 
> I am okay with taking the first one, if you want to do the second one.

I opened a new issue for you for better management.
