### ISSUE TITLE
Netlify preview not showing in PR checks tab

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1156]
As described in title.

The recent pushes to PRs does not have netlify preview in the PR checks tab.

PRs:
https://github.com/reposense/RepoSense/pull/1148
https://github.com/reposense/RepoSense/pull/830

**Comment by jamessspanggg** [comment]
@eugenepeh is this possibly due to the waiver?

**Comment by Tejas2805** [comment]
I think they won't allow us to use netlify till we agree to the plan.

**Comment by jamessspanggg** [comment]
Netlify preview showing up now, closing this.
