### ISSUE TITLE
Zero contribution despite large number of commits

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1160]
![Screen Shot 2020-03-18 at 5 11 27 PM](https://user-images.githubusercontent.com/35946746/76944219-990d6400-693b-11ea-9216-1e505a48c12e.png)

[Link to reproduce](https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=f10-2&sort=variance&sortWithin=totalCommits&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=foochifa&tabRepo=AY1920S2-CS2103T-F10-2%2Fmain%5Bmaster%5D)

**Comment by 0blivious** [comment]
I guess coz they revert everything in the master according to their new workflow.
![image](https://user-images.githubusercontent.com/39231750/76949782-1341e680-6944-11ea-9caf-7f50396a46ee.png)

**Comment by jamessspanggg** [comment]
hmmm yeah, they seem to revert everything from Internship Diary back to AB3

**Comment by Tejas2805** [comment]
I saw the revert commits too but I didn't think it was fully reverted. Thought it was just few  commits.

**Comment by Tejas2805** [comment]
Closing as solved.
