### ISSUE TITLE
GitLsTreeTest: improve testing in `unix_cloneInvalidWindowsFilePaths_success` test case

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1163]
I am referring to this test: 
https://github.com/reposense/RepoSense/blob/bf77c18fd41e53676458e80fd07922a215c7472c/src/test/java/reposense/git/GitLsTreeTest.java#L73-L79

Shouldn't the test call `validateFilePaths(config)` after setting the branch?

For comparison, here is the test for Windows OS
https://github.com/reposense/RepoSense/blob/bf77c18fd41e53676458e80fd07922a215c7472c/src/test/java/reposense/git/GitLsTreeTest.java#L63-L71

**Comment by anubh-v** [comment]
@fzdy1914  may I check this with you?

**Comment by fzdy1914** [comment]
Not clear about the logic here also, can you git blame to see who wrote that part of code?

**Comment by anubh-v** [comment]
The test was introduced in [this PR](https://github.com/reposense/RepoSense/pull/564)
@yong24s, may we get clarify this issue with you? Thanks for your time

**Comment by anubh-v** [comment]
@eugenepeh, may we clarify this issue with you? Thanks for your time

**Comment by yong24s** [comment]
On hindsight, it may be missed out.

`GitLsTreeTest#unix_cloneInvalidWindowsFilePaths_success` should call `GitLsTreeTest#validateFilePaths` regardless for a more complete testing.

**Comment by anubh-v** [comment]
Removing the FirstTimers issue as it may be better to fix the test case ASAP 
(in order to catch possible regressions)
