### ISSUE TITLE
Authorship / Zoom tab bug from regressions introduced by PR #967

### ISSUE THREAD

**Issue by ccyccyccy** [reposense/RepoSense#1167]
The PR #967 caused some regressions because it did not re-render the component, causing the previous state to be preserved.

This caused the following bugs
1. Duplicate values getting pushed into `fileTypes`, causing filter selections to not work properly. This occurs even when the same authorship icon is clicked multiple times.
![image](https://user-images.githubusercontent.com/32454748/77102496-e41a9a80-6a53-11ea-8e20-ad6b7c0b64c5.png)
2. `getFileTypeExistingLinesObj` is not invoked when the prop `info` is changed as `filesLinesObj` is not watched by Vue.  As such, `getFileTypeExistingLinesObj` keeps the value the first author selected, even after selecting another author. This caused the filetype linecount to be not presented correctly.
![image](https://user-images.githubusercontent.com/32454748/77102558-feed0f00-6a53-11ea-8d94-e140b19319aa.png)

There might be more bugs due to the old state being preserved. Will continue to investigate.

**Comment by jamessspanggg** [comment]
> 1. Duplicate values getting pushed into fileTypes, causing filter selections to not work properly.

Resetting the values of `fileTypes` and `selectedFileTypes` when calling `initiate()` will work. However, note that other values such as `toReverseSortFiles` will also persist after selecting new authors.

> 2. getFileTypeExistingLinesObj is not invoked when the prop info is changed as filesLinesObj is not watched by Vue

Seems like this issue is because `filesLinesObj` is not initialised within `data()`, so Vue is not watching it.

**Comment by jamessspanggg** [comment]
actually, we can just use `v-bind:key=...` to re-render the authorship component, right? Whenever the key changes, the entire authorship component will be re-rendered. The key can be the `repoName + authorName`. This will be much cleaner than the previous way of re-rendering the authorship component (setting `isTabActive` to false and true).

@fzdy1914 with the implementation introduced in #967, you would need to add some new logic to reset the `data()` values. Should we just follow the `v-bind:key` way?

**Comment by jamessspanggg** [comment]
This issue happens to zoom tab as well.

**Comment by jamessspanggg** [comment]
Some other weird behaviour: some code segments show codes that are not in correct order.

![Kapture 2020-03-20 at 16 39 49](https://user-images.githubusercontent.com/32864116/77147966-80cb4f80-6ac9-11ea-8f9c-d812d61fd8d4.gif)

To reproduce, click on the code view button of Jun An first, then click on code view button of Yong Hao.
[Link to reproduce](https://reposense.netlify.com/)

**Comment by fzdy1914** [comment]
From my experience, it is not so ideal to re-render the whole component. If some value is computed just by the `info` passed in, we should make it `computed` or at least `watched` instead of just re-render it. 

Correct me if what I thought is not applicable here.

**Comment by ccyccyccy** [comment]
Yes I agree that converting the fields to `computed` values is more appropriate. 

However, it is quite an intensive change to do so, and this is quite a breaking bug. So I feel that we can force the re-render for now, and then do the conversion in another PR?

**Comment by jamessspanggg** [comment]
There are also properties that are not tied to the `info` being passed in, such as `filterSearch`, `toReverseSortFiles`, `filesSortType` and more in authorship tab. Same goes for zoom tab as well. Without re-rendering the whole component, these values need to be reset when a new author is toggled.

Re-rendering the component maybe much more simpler and cleaner, since the logic to reset the values is no longer needed. 

> From my experience, it is not so ideal to re-render the whole component. 

Your concern with this is because performance may be sacrificed?

**Comment by fzdy1914** [comment]
Maybe we can revert #967 first? Just keep the cloned user feature? 

@eugenepeh Need your input here.

**Comment by jamessspanggg** [comment]
> Maybe we can revert #967 first? Just keep the cloned user feature?

Agree with this.

**Comment by eugenepeh** [comment]
>Maybe we can revert #967 first? Just keep the cloned user feature?

Seems that there are more than 1 breaking point, perhaps revert will be a better choice for now while we investigate. 

Meanwhile do take note of the broken features, we need to add cypress tests for those area
