### ISSUE TITLE
Total line contribution not updated when filetypes are unchecked

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1170]
When filetypes are unchecked, the contribution bar length adjusts to the correct length, while the total line contribution of each group does not (shown in diagram below). 

Hence, when toggling sorting controls to decreasing order of contribution, groups with higher total contribution are seen to be in lower position than groups with lower contribution (as they are sorted based on total contribution among checked filetypes). This may cause confusion in users.

<img width="873" alt="Screen Shot 2020-03-20 at 2 30 02 PM" src="https://user-images.githubusercontent.com/32864116/77142013-c849df80-6ab9-11ea-84ad-07e7da565d9e.png">

**Comment by jamessspanggg** [comment]
@damithc should we update the total contribution to reflect the total contribution among those file types that are checked?

**Comment by damithc** [comment]
> @damithc should we update the total contribution to reflect the total contribution among those file types that are checked?

I think we should.
