### ISSUE TITLE
Compon-ify tab resizer

### ISSUE THREAD

**Issue by ang-zeyu** [reposense/RepoSense#1173]
1. The tab resize element logic currently resides within `main.js`.
   - We can make the resizer a component instead, passing the tab/summary wrapper as the `left/right` slots of this resizer component, allowing us to encapsulate resize logic within it

2. The resize component currently uses a tab-resize-guide. We could change the resizing to be instant for a more responsive feel.

Would like to try (1) out if there aren't any issues; Not so sure about the second though, do we want the resizing to be instant?

**Comment by fzdy1914** [comment]
We freeze the resize because of performance.

**Comment by ang-zeyu** [comment]
> We freeze the resize because of performance.

Noted, thanks!
I'll just go with the compon-ifying portion then 😁
