### ISSUE TITLE
Travis fails with macOS 10.13.6 JDK8

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1174]
Travis is failing with the following log: 
<img width="1007" alt="Screen Shot 2020-03-22 at 10 37 47 AM" src="https://user-images.githubusercontent.com/32864116/77241158-67411980-6c29-11ea-92ef-3aee2a84d0c4.png">

This occurs for several PRs:
#1165 #1153 #1168 #1104 #1053, #1171 and #1172

**Comment by jamessspanggg** [comment]
It seems like all PRs are having the same issue.

I've tried creating a PR to my forked repo, with travis setup and running the same `.travis.yml` file. The `macOS` build seems to work fine. [Link to the successful macOS build](https://travis-ci.com/github/jamessspanggg/RepoSense/jobs/300804860)

@eugenepeh would it happen to be some changes to the configurations/settings in the team's travis?

**Comment by jamessspanggg** [comment]
Update:

Don't think the problem is due to our side as there are several forum posts about the similar events:
[Link 1](https://travis-ci.community/t/macos-build-fails-with-an-error-occurred-while-generating-the-build-script/7695)
[Link 2](https://travis-ci.community/t/macos-build-an-error-occurred-while-generating-the-build-script/7684)

**Comment by Tejas2805** [comment]
Travis is under maintainance

**Comment by jamessspanggg** [comment]
@Tejas2805 do u mean this [maintenance](https://blog.travis-ci.com/Database-Maintenance-21st-of-March-2020)? They are already done with the maintenance. [link](https://twitter.com/travisci/status/1241411541150433281)

**Comment by Tejas2805** [comment]
Yup.

**Comment by fzdy1914** [comment]
But the issue is still not solved

**Comment by jamessspanggg** [comment]
> But the issue is still not solved

Yes. I don't think the problem is on our side, but Travis. There are several forum posts on Travis with the same problem.

**Comment by jamessspanggg** [comment]
Just confirmed that it's an issue on Travis' side. [Link to comment](https://travis-ci.community/t/macos-build-an-error-occurred-while-generating-the-build-script/7684/16) They will be fixing the issue.

**Comment by jamessspanggg** [comment]
I think they fixed the issue already. The Travis builds for macOS are running fine now!

**Comment by jamessspanggg** [comment]
They issued an [official statement](https://www.traviscistatus.com/incidents/7mbxh26jk3sl) saying that the issue is resolved. The builds are running fine as well. Closing this.
