### ISSUE TITLE
UI for viewing repo confusing

### ISSUE THREAD

**Issue by ccyccyccy** [reposense/RepoSense#1178]
Currently we have an octocat icon to redirect users to the respective repos, as well as the same ocotcat icon directing users to github profiles when grouped by `Authors` and `merge group` selected. 

This icon is duplicated multiple times in the default setting of grouping by `Repo/Branch`, with them all pointing to the same repo.

![image](https://user-images.githubusercontent.com/32454748/77330802-d10d1080-6d5a-11ea-9b7f-b27e5a01f76e.png)

This is confusing as one would think that the icon is related to the author, only to find out that they all point to the same repo.

Also, the other 2 icons changes the tab, while the octocat icon is the odd one out that redirects users to elsewhere, and is not consistent with its neighbours.

Hence, I would suggest that we make the author names and the repo names clickable to redirect users to the author profile and repo url respectively, replacing the need for the octocat icons. This would make the UI consistent no matter how we `group by` or if `merge group` is selected.

**Comment by Tejas2805** [comment]
I agree with you but I believe the icon keeps it neat and succinct. Allowing all the names to be a clickable link might make navigation bit of an issue. Users might end up clicking them while just trying to scroll. So, I think better to keep as is.

Let's see what senior devs think.

**Comment by ang-zeyu** [comment]
How about shifting the icon to the right? Personally, I was confused when coming across this the first time as an external link typically wouldn't be in the middle of the two internal icons.

> redirect users to the author profile and repo url respectively, replacing the needed for the octocat icons. 

I think this is a nice addition either way though

**Comment by Tejas2805** [comment]
> How about shifting the icon to the right?

This is a better idea, I feel.

**Comment by ccyccyccy** [comment]
> Allowing all the names to be a clickable link might make navigation bit of an issue. Users might end up clicking them while just trying to scroll. So, I think better to keep as is.

I don't think people would accidentally click on things while scrolling? Never had that experience before...  I feel like people are already quite used to having everything being clickable. Also, since we open a new tab when clicking on a link, it should be quite easy to just close the new tab.

> How about shifting the icon to the right?

Hmm that might help, I'm not sure if that would be enough. There's still the problem of the repo link being associated with the authors instead of the repo, and duplicated multiple times for no reason.

Also, when `merge group` is selected, it is not even possible to go to the repo, since the author columns are collapsed.

Meanwhile, the only way I know of to go to the author's profile page is to `group by` author and check `merge group`, which is very very obscure and specific.

It just feels like the UI of this linking to github is not consistent to me. Would feel more consistent if I can always click on the author / repo to link to them respectively.

@fzdy1914 @eugenepeh @damithc Your opinions?

**Comment by damithc** [comment]
I like that linking names eliminates the need for certain icons, which saves space and makes the UI cleaner. It's not without a cost though.
e.g., 
* bigger clickable areas could make it harder to use for touch interfaces users? (I'm not sure as I don't use a touch interface myself).
* When text is clickable, we typically use blue color to indicate that they are clickable, which upsets the UI balance i.e., those links start attracting more attention than they should.

But I'm all for eliminating the duplicated icon though. Perhaps we make it appear near the repo name instead?
Also, we can consider using different icons for profile link and repo link to reduce confusion.

**Comment by Tejas2805** [comment]
> But I'm all for eliminating the duplicated icon though. Perhaps we make it appear near the repo name instead?

Let's go ahead with:

1) Octocat icons beside repo name (same for merge group).
2) No octocat icon for profiles or repo within the group.
3) A new icon (we can decide which) for author repos.

Sounds good?

**Comment by ccyccyccy** [comment]
@damithc I don't think these are hard issues to solve though.

>  bigger clickable areas could make it harder to use for touch interfaces users? (I'm not sure as I don't use a touch interface myself).

Actually I think it's the opposite? Touch interface users generally need a bigger clickable surface.

> When text is clickable, we typically use blue color to indicate that they are clickable, which upsets the UI balance i.e., those links start attracting more attention than they should.

We can implement in CSS `:hover` selector to make the text become blue color **only** on hover to indicate that they are clickable, and making the cursor become a pointer. This way the UI balance is still preserved.

<br />

> 1. Octocat icons beside repo name (same for merge group).
> 
> 2. No octocat icon for profiles or repo within the group.
> 
> 3. A new icon (we can decide which) for author repos.

Otherwise this seem good if we are sticking with icons. Except that I would prefer to have the icon available for the author profiles and repos, no matter which one is in the group. So what I have in mind is something like this...

![image](https://user-images.githubusercontent.com/32454748/77440317-23196900-6e23-11ea-9b2d-8ac9c1d639da.png)

**Comment by damithc** [comment]
> We can implement in CSS `:hover` selector to make the text become blue color **only** on hover to indicate that they are clickable, and making the cursor become a pointer. This way the UI balance is still preserved.

True, that does work but I think it's best not to depend entirely on hover as we cannot expect users to hover their mouse  over the entire page to discover all clickable areas, and then remember those later? I guess we can use a different visual cue for linked text that does not depend on hover and does not upset the UI balance. Having said that, let's try the option of reorganizing icons to overcome the problems pointed out instead of going too deep into custom link visualizations.

**Comment by Tejas2805** [comment]
@ccyccyccy Are you taking this up or can I try?

**Comment by ccyccyccy** [comment]
I will be taking this up, since I kind of need some PRs going on.

> Having said that, let's try the option of reorganizing icons to overcome the problems pointed out instead of going too deep into custom link visualizations.

@damithc So something like this? Maybe change the icons a little.

![image](https://user-images.githubusercontent.com/32454748/77524255-ff593000-6ec1-11ea-851e-c6bee3a73879.png)

**Comment by damithc** [comment]
> @damithc So something like this? Maybe change the icons a little.
> 
> ![image](https://user-images.githubusercontent.com/32454748/77524255-ff593000-6ec1-11ea-851e-c6bee3a73879.png)

Not sure it's worth breaking up the icon group like that though. Visually, neater to keep the icons together?

**Comment by ccyccyccy** [comment]
> Not sure it's worth breaking up the icon group like that though. Visually, neater to keep the icons together?

Ok no problem. So we will have the following changes.

1. Reorder the icon corresponding to the repo or the author profile to be the leftmost icon.
2. Add icon beside the parent group ( the option selected by `group by`)
3. Change where the icons link to. Icon beside author will link to author github profile. Icon beside repo name will link to the repo.

@damithc Is that right?

**Comment by damithc** [comment]
> @damithc Is that right?

OK for me.
