### ISSUE TITLE
Filter ramps by file type

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1181]
Current: all ramps are shown even when some file types have been filtered out
![image](https://user-images.githubusercontent.com/1673303/77603798-f2811e80-6f4b-11ea-8658-67b0f920b7b4.png)

Suggestion: show ramps that are relevant to the selected file types only

**Comment by jamessspanggg** [comment]
Some ramps have contribution to multiple file types. Should we only remove them if all of the filetypes within the ramp are removed?

**Comment by 0blivious** [comment]
> Some ramps have contribution to multiple file types. Should we only remove them if all of the filetypes within the ramp are removed?

I feel this will cause confusion as the size of ramp is related to LoC. If you remove the ramp according to file types, this gives the user intuition that LoC of each file types matters and they will expect the other ramp size to change also.

**Comment by jamessspanggg** [comment]
> I feel this will cause confusion as the size of ramp is related to LoC. If you remove the ramp according to file types, this gives the user intuition that LoC of each file types matters and they will expect the other ramp size to change also.

Hmm so you are suggesting that the ramp should be adjusted (if part of the filetypes are unchecked) or removed (if all filetypes unchecked) accordingly?

@damithc may i get ur opinion here?

**Comment by jamessspanggg** [comment]
Btw, I have implemented the one where it will remove ramps if only all of their file types are unchecked. Can test the dashboard preview out in #1192. Will modify accordingly if it is unintuitive.

**Comment by damithc** [comment]
> Hmm so you are suggesting that the ramp should be adjusted (if part of the filetypes are unchecked) or removed (if all filetypes unchecked) accordingly?

Ideally, yes, but not sure if it worth it. Also, I believe the ramp size doesn't _really_ match the contribution size, for example, it could be the same lines that are being modified over and over, and even can be claimed by someone else later.

**Comment by damithc** [comment]
> Btw, I have implemented the one where it will remove ramps if only all of their file types are unchecked. Can test the dashboard preview out in #1192. Will modify accordingly if it is unintuitive.

Seems OK to me. 👍
