### ISSUE TITLE
StandaloneConfigTest: standaloneConfig_validJson_success test does not verify the author list?

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1182]
I am referring to this test:

https://github.com/reposense/RepoSense/blob/ac0909a177c043183807bb4cea027eab111ba931/src/test/java/reposense/model/StandaloneConfigTest.java#L48-L52

After calling `config.update(standaloneConfig)`, shouldn't the test verify that the author list in `config` is  as expected?

**Comment by anubh-v** [comment]
@jylee-git, @fzdy1914 may I check this with you?

**Comment by fzdy1914** [comment]
Not sure it is checking if we can parse a valid json file only or what. Can double-check with code owner.

**Comment by anubh-v** [comment]
The test seems to be have been introduced in [this PR](https://github.com/reposense/RepoSense/pull/283/files).

@eugenepeh, may we check this with you?

**Comment by eugenepeh** [comment]
Yes, the unit test was created to ensure that a proper json won't throw any error. Otherwise it may cost extra work to identify the failing point should the execution fails at `.update`. Checking of values are done in subsequent tests.
