### ISSUE TITLE
Consider adding the number of commits over a particular day, week and as a whole in the commits panel

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#1183]
![image](https://user-images.githubusercontent.com/35756209/77610471-c373a880-6f5d-11ea-8e9e-fc776a49c1f8.png)

**Comment by jamessspanggg** [comment]
@damithc where would be an appropriate location to place the number of commits?

Perhaps for total commits, it should be placed beside/after the date range? i.e. `34 commits from 2017-10-09 to 2020-03-23...`

For commits within a single granularity duration, we can add beside the date? i.e. `2019-12-24 [1 commit(s)]`

**Comment by damithc** [comment]
Shall we put this on hold for now? I can't remember a time I wanted to find how many commits in a period. As a high number of commits can mean either lot of good work or a lot of spam commits caused by sloppy work, I don't usually pay attention to that number.
