### ISSUE TITLE
AuthorConfiguration: all authors' information reset when ignored authors are removed

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1188]
In the snippet below, we see that the `resetAuthorInformation` method is called after ignored authors are removed.

`resetAuthorInformation` will re-populate the `AuthorConfiguration` with the information of all authors except the ignored authors.

I wish to clarify:
- Is there a reason we reset **all** authors' information, rather than only removing the ignored authors' information?
- It seems that `resetAuthorInformation` will run even when no authors are ignored. Is this intended?

To me, it seems simpler to selectively remove the ignored authors' information, rather than resetting all authors' information. Hence, I wanted to clarify if there's a reason for the current design

https://github.com/reposense/RepoSense/blob/e0e912a58a3b4391522b1107dcbd5c789e04af11/src/main/java/reposense/model/AuthorConfiguration.java#L142-L152

**Comment by Tejas2805** [comment]
> Is there a reason we reset all authors' information, rather than only removing the ignored authors' information?

On a closer look, I have come to realize that it is not easier to remove the ignored author's information. This is because we put the author as a `value` in the `authorEmailsAndAliasesMap` and not as a key. Therefore, to remove it we will have to write this logic and it might be a tedious to do so. This is why we clear everything and then just the new author's list again.

**Comment by Tejas2805** [comment]
I have created a PR #1189 which kind of modifies the logic to what we wanted. If all looks good, maybe we can merge this first and then the duplicate alias warning PR.

**Comment by Tejas2805** [comment]
> It seems that resetAuthorInformation will run even when no authors are ignored. Is this intended?

Doesn't seem to be the case. Cause based on the current implementation, running the function `resetAuthorInformation` without any authors to ignore is redundant.
