### ISSUE TITLE
RepoLocation: ftp protocol is accepted in repo url

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1190]
To observe this, run RepoSense with the command 
`./gradlew run -Dargs="--repo ftp://github.com/reposense/RepoSense.git"`

RepoSense does not treat this as an invalid location, but tries to clone the repository (and fails):
![image](https://user-images.githubusercontent.com/35621759/77724425-e53c6080-702d-11ea-99f2-4d635b82bd5d.png)

Is this intended? 
Currently, we only use repo URLs for repos hosted on GitHub, and I do not think GitHub allows cloning over ftp

**Comment by anubh-v** [comment]
From the git man pages (git version 2.17.1): 

`Git supports ssh, git, http, and https protocols (in addition, ftp, and ftps can be used for fetching, but this is inefficient and deprecated; do not use it).`

**Comment by damithc** [comment]
@reposense/21-22-active-developer What is the recommended solution here?

**Comment by gerhean** [comment]
I think it is fine either way, reposense fails gracefully when unable to clone the repo so not a big concern. Most normal users will not ever think of doing this anyway.


Prefer that ftp be recognised as invalid, in order to prevent any abuse of the system (in case using ftp can be some security or privacy risk but I doubt it.)

**Comment by HCY123902** [comment]
![image](https://user-images.githubusercontent.com/54735123/112643543-6f0c4d00-8e7f-11eb-9014-3287b4451818.png)

![image](https://user-images.githubusercontent.com/54735123/112643561-73d10100-8e7f-11eb-95bc-961fd13ceaec.png)

After trying it locally, it seems that this protocal has already been recognized as invalid location. However, there does not seem to be corresponding message shown on the generated report. Maybe the message can be shown on the report?

**Comment by dcshzj** [comment]
Yes, let's fail gracefully if the URL contains FTP with a warning message, but I don't think we need to mention explicitly in the documentation, since it is hardly used.

**Comment by damithc** [comment]
> However, there does not seem to be corresponding message shown on the generated report. Maybe the message can be shown on the report?

If we fail to clone a normal Git repo, we show it as an error message in the report, right? In that case this should produce a similar error.
