### ISSUE TITLE
Change preview link in our GitHub home page

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1196]
Our GitHub home page contains a link that navigates to the dashboard generated by [reposense/dashboard-demo](https://github.com/reposense/dashboard-demo). The link normally shows the dashboard that is out-of-date as we need to update the generated files in the dashboard-demo repo.

<img width="916" alt="Screen Shot 2020-03-29 at 8 07 08 PM" src="https://user-images.githubusercontent.com/32864116/77848664-f1c0e480-71f8-11ea-93a0-4be642edb58a.png">

How about we just provide the link that navigates to the Netlify preview of our master branch? In this way, we don't need to keep updating the dashboard-demo repository every time when there's a new change.

**Comment by anubh-v** [comment]
What was the original purpose for the dashboard-demo? I suppose it pre-dates the Netlify preview?

**Comment by jamessspanggg** [comment]
> Is the dashboard-demo meant to have a different purpose than the Netlify preview?

I guess it's to demonstrate to the people on how RepoSense works, while the netlify preview is sort of for the PR previews?

> I suppose it pre-dates the setup of the Netlify preview? I agree that we can replace the link to dashboard-demo with Netlify preview, if it doesn't have an additional purpose

Yes I think we can replace with the netlify preview of the master branch

**Comment by dcshzj** [comment]
We should make use of the publish-RepoSense repository to automatically pull and generate from the latest release branch.

**Comment by damithc** [comment]
I changed it to https://reposense.org/ as that's our main website which also contains a separate page showcasing various demo sites.

**Comment by dcshzj** [comment]
@damithc I think we can also delete the [reposense/dashboard-demo](https://github.com/reposense/dashboard-demo) repository, since it is no longer needed and outdated.

**Comment by damithc** [comment]
> @damithc I think we can also delete the [reposense/dashboard-demo](https://github.com/reposense/dashboard-demo) repository, since it is no longer needed and outdated.

Yup. No objections from me.
