### ISSUE TITLE
Use @mixin for fonts 

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1198]
We are duplicating fonts in a large number of places. 

![Screen Shot 2020-03-31 at 4 11 19 PM](https://user-images.githubusercontent.com/35946746/78002937-8008a800-736a-11ea-8e35-1ce602f42189.png)

**Suggestion**: Let's create a mixin for fonts (and any other such style) 

**Pros:** Our pug files will clear up to some extent and all css will be in one place.

As suggested by @jamessspanggg in PR #1104

**Comment by Tejas2805** [comment]
@fzdy1914 @jylee-git Can I get your review on this?

**Comment by jylee-git** [comment]
Yes, I think it can be done and doing so should reduce the clutters in the pug file
