### ISSUE TITLE
Checkstyle: Consider enforcing naming convention of exceptions in catch blocks

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1199]
Currently, it seems we have an undocumented naming convention that the names of exceptions in catch blocks should consist only of lower case letters.

Example of existing convention:
```
try {
  // code
} catch (GitCloneException gce) {
  // code
}


```

But our Checkstyle config also allows `camelCase` names for the exceptions, and hence we have to catch violations of this convention manually during review.

We can consider using the [CatchParameterName check](https://checkstyle.org/config_naming.html#CatchParameterName) in checkstyle to enforce the naming convention for exception names in catch blocks

**Comment by Tejas2805** [comment]
Good idea. I think it would be nice to enforce this.

**Comment by anubh-v** [comment]
@fzdy1914 @jylee-git may I get your thoughts on this suggestion?

Currently, there is only one instance where we do not follow this convention in our code:

In the snippet below, the name `actualException` uses camel case

https://github.com/reposense/RepoSense/blob/e963b68a890175fbba4c57910008de9599ea4591/src/test/java/reposense/util/AssertUtil.java#L27-L38

**Comment by fzdy1914** [comment]
I actually don't think it is so necessary to do so.

**Comment by damithc** [comment]
Yes, probably not worth the trouble.
