### ISSUE TITLE
include line deletions into the ramp chart

### ISSUE THREAD

**Issue by ongspxm** [reposense/RepoSense#120]
I am working on the single file template, currently going through the previous template to see how the ramp chart is generated. I realized the deletion count is not visualized, are there plans to include it into the report?

**Comment by harryggg** [comment]
The reason to leave out deletion is: 1. If  auyhor is editing a line, it will be 1 insert + 1 deletion.we shouldn't count both  2. If an author inserts a new line, there will only be insertion. 3. Deleting a line/ file is less of a contribution than inserting one?(debatable)

**Comment by harryggg** [comment]
Anyway it will be easy to add in deletion, so maybe we can leave it as it is for now ?

**Comment by ongspxm** [comment]
makes sense, roger that
