### ISSUE TITLE
Add Contribution Guide

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1200]
Since we are now moving towards our own MarkBind website, we should include our own contribution guide instead of redirecting the new developers to different pages, as it will 
also help them understand the way to contribute better.

**Comment by Tejas2805** [comment]
@damithc Need your opinion on this.

**Comment by damithc** [comment]
I have no objections. We don't want to duplicate the same thing in every project either, but that's battle we can fight another time.

**Comment by Tejas2805** [comment]
How about, we add a Contribution guide to the NUS-OSS Webpage? And all our Contribution guides can link to that one? With sections for the individual projects, regarding guidelines just for that project? Then no duplicates required.

Something like:

NUS-OSS Contribution Guide
[x] General Guidelines
[x] Code of Conduct 
........
.......

RepoSense:
[x] How to contribute to reposense
........

MarkBind:
[x] How to contirbute to markbind
.......

And so on and so forth.

**Comment by damithc** [comment]
For the moment, let's forget the duplication and improve each project separately. We can unify the common parts sometime in the distant future.

**Comment by damithc** [comment]
Closing in favor of #1500
