### ISSUE TITLE
Missing javadoc for functions

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1202]
There are many methods in the backend which don't have any javadoc This makes it difficult for first-time developers to understand the backend code. 

Suggestion: Let's add javadoc for missing functions so that it becomes easier for someone reading the code to do it.

**Comment by Tejas2805** [comment]
Let's make this a `FirstTimer issue`? It will help them understand backend better.

**Comment by anubh-v** [comment]
Which methods are these? (any specific class / package ? )

**Comment by Tejas2805** [comment]
The `addAuthorEmailsAndAliasesMapEntry` in AuthorConfiguration for example doesn't have it. Though it is not something too important to add, such methods when edited, cause an error in Travis, due to having no javadoc. Therefore, I feel it is better to find such methods and add them.

**Comment by anubh-v** [comment]
I think our checkstyle config does check for presence of javadocs.
Perhaps we can investigate if the config is sufficiently strict in detecting missing javadoc comments?

For the specific case you mentioned, I think it can be a first timer issue, but perhaps issue #1207 should be resolved first as it affects the same data structure

**Comment by HCY123902** [comment]
Hello, I am looking for a first time issue, and I am wondering whether this issue is still open? I seem to have found some functions without documentation and I think this may be a point for me to start.

**Comment by damithc** [comment]
I think it's best if someone who knows the codebase well writes the javadoc comments. The outcome can be of better quality that way.

**Comment by yhtMinceraft1010X** [comment]
Do we also need javadoc for private functions like the one below from `CommitResultAggregator`?
```
private static float getContributionVariance(List<AuthorDailyContribution> contributions,
            Date startDate, Date lastDate, String zoneId) {
        << Actual code not shown >>
    }
```

I can add them in if needed since I've explored most of the backend code while fixing #1601.
