### ISSUE TITLE
Usage of AuthorConfiguration#resetAuthorInformation can be made more readable

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1204]
I'm referring to the following snippet:

https://github.com/reposense/RepoSense/blob/1a34084e5379a86bd685c1f35847c1038a1c37de/src/main/java/reposense/model/RepoConfiguration.java#L385-L392

Line 390 can be confusing because it appears like we are
wiping out the author list that was set on the previous line (although the reader will realise this is not the case *if* they read the `resetAuthorInformation` method code)

We can consider renaming the method `resetAuthorInformation` to `resetFromAuthorList`.

Alternatively, we can consider breaking `resetAuthorInformation` into 2 methods: 
- `authorConfig.clear` : this will clear the author configuration's internal data structures
-  `authorConfig.buildFromAuthorList` : this will re-populate the author config's internal data structures based on the author list

Then, the above snippet can look like this:
```
public void setAuthorList(List<Author> authorList) { 
  authorConfig.clear();
  authorConfig.setAuthorList(authorList);
  authorConfig.buildFromAuthorList();
  authorList.forEach(author -> AuthorConfiguration.propagateIgnoreGlobList(author, this.getIgnoreGlobList())); 
}
```

Based on discussion with @jamessspanggg

**Comment by Tejas2805** [comment]
Looks like a good idea. Since, we have already removed one use case for the method.

**Comment by anubh-v** [comment]
Shall we decide between the 2 options before making it a first timers' issue?

Option 1: Rename the method `resetAuthorInformation` to `resetFromAuthorList`
Option 2: Break `resetAuthorInformation` into 2 methods:
- `authorConfig.clear` : this will clear the author configuration's internal data structures
- `authorConfig.buildFromAuthorList` : this will re-populate the author config's internal data structures based on the author list

**Comment by jamessspanggg** [comment]
> Option 2: Break resetAuthorInformation into 2 methods:

I'm up for option 2 as it will be much clearer in my opinion.

**Comment by Tejas2805** [comment]
Can go ahead with option 2.

**Comment by lm5lm5** [comment]
Hi, I am a first-time contributor and I would like to submit a PR for resolving this issue.
