### ISSUE TITLE
Provide help page in dashboard

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1205]
The current workflow of RepoSense is that users can setup a RepoSense dashboard and share the link to his/her peers or students. 

However, the people that are shared to may not understand how to interpret the report (such as what does the ramp size and ramp position represent etc). They are also highly unlikely to go to our User Guide to find out how to interpret the report. 

Perhaps we can provide sort of a help page (in terms of a modal) that provides all information to interpret the report? 

_p.s. asking for this because there were several occasions where i shared the dashboard to my peers but they can't understand what the ramp represents._

**Comment by jamessspanggg** [comment]
@damithc what do you think? since you are sharing to hundreds of students every semester, would this addition be good?

**Comment by damithc** [comment]
Yes, that's a good idea @jamessspanggg

**Comment by Tejas2805** [comment]
What all we plan to have in Help Page? Some specific sections of the UG?

**Comment by Tejas2805** [comment]
Do we still intend to provide this after the change in our docs? If yes, then what's the intendedd plan? I can work on this accordingly.

**Comment by damithc** [comment]
Let's add a `how to interpret this report` link somewhere appropriate and link it to the relevant place of the user guide.

**Comment by tlylt** [comment]
> Let's add a how to interpret this report link somewhere appropriate and link it to the relevant place of the user guide.

Hi @damithc, currently the page does include a link to the `user guide > Using reports` here:
> See the [User Guide](https://reposense.org/ug/usingReports.html)  to get a better understanding of how to interpret the report.

Would this be sufficient already or is there anything else left for this issue?

Screenshot for reference:
![image](https://user-images.githubusercontent.com/41845017/166439249-e7065050-632c-4e54-83a8-e21f29c507df.png)

**Comment by damithc** [comment]
> Would this be sufficient already or is there anything else left for this issue?

And there is another link to the user guide at the bottom of the left panel. Yes, I guess this is enough.
