### ISSUE TITLE
Duplicate keys detected when open Zoom

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1206]
1. open any recent surge preview based on latest master
2. open zoom for Eugene Peh (Eugene Peh) in reposense/testrepo-Alpha[master]
3. observe the commit result for each commit. same commit result appear twice

possible regression from #779 

error message in console: Duplicate keys detected: '136c6713fc00cfe79a1598e8ce83c6ef3b878660'. This may cause an update error.

**Comment by ang-zeyu** [comment]
Would be fixed by #1050!

**Comment by 0blivious** [comment]
A fix is already being implemented
