### ISSUE TITLE
Better naming of authorEmailsAndAliasesMap

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1207]
According to the discussion between me and @Tejas2805 in [here](https://github.com/reposense/RepoSense/pull/1189), the current `authorEmailsAndAliasesMap` in the class `AuthorConfiguration` has the following structure:

```
git id -> author
email -> author
alias -> author
```
while the naming entails the structure to be:
`email -> alias`

Perhaps we can rename the map to `authorDetailsToAuthorMap`? 

or perhaps we can separate to few maps instead of just using one?
`gitIdToAuthorMap` + `emailToAuthorMap` + `aliasToAuthorMap`

**Comment by Tejas2805** [comment]
I am all up for option 2. It will make the code more readable.

**Comment by anubh-v** [comment]
The first option: renaming to `authorDetailsToAuthorMap` sounds better to me.

Is there any additional benefit from splitting into distinct maps? (I don't see the benefit currently)
Having multiple maps may be slightly cumbersome as we have to update multiple objects when modifying an author in the author config.

Additionally, (at the moment), there isn't any behaviour that we need that requires multiple maps?

**Comment by Tejas2805** [comment]
> The first option: renaming to `authorDetailsToAuthorMap` sounds better to me.

Can do this too. It will be easier to implement agreed.

> Additionally, (at the moment), there isn't any behaviour that we need that requires multiple maps?

True.

**Comment by Tejas2805** [comment]
> perhaps we can separate to few maps instead of just using one?

This will make the code more readable. But implementation wise might be cumbersome as pointed out by @anubh-v

**Comment by Tejas2805** [comment]
Will do this once, #1189 and #1187 are merged.

**Comment by lm5lm5** [comment]
> Will do this once, #1189 and #1187 are merged.

Hi @Tejas2805 , I notice that #1187 has not been merged. Is it because it didn't pass Travis CI test?

**Comment by hopinxian** [comment]
Hi, I am looking for a first timer issue to work on. I was redirected here after reading the issue at #1202 . Is it fine if I take on this?

**Comment by jamessspanggg** [comment]
go ahead @hopinxian

**Comment by hopinxian** [comment]
Just to clarify, can I confirm that the conclusion of the discussion is to rename ```authorEmailsAndAliasesMap``` to ```authorDetailsToAuthorMap```?
