### ISSUE TITLE
Regressions from #1059

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1213]
PR #1059 separates extracts `v_summary_charts` out of `v_summary`, while passing data through props from `v_summary` to `v_summary_charts`.

Props such as `sortingOption`, `sortingWithinOption`, `isSortingDsc`, `isSortingWithinDsc` were not passed to `v_summary_charts`, even though they were used in `openTabZoom`.

Hence, in some cases, the zoom tab is not restorable after reloading the page.

**Comment by Tejas2805** [comment]
Can close this too then?

**Comment by jamessspanggg** [comment]
> Can close this too then?

The issue still occurs where zoom tab isn’t restorable. Check merge group -> click show all commits in a group -> change sorting option -> reload.
