### ISSUE TITLE
Authorship: Allowing to click of whole title area to toggle file

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#1217]
![image](https://user-images.githubusercontent.com/35621726/78868796-1e38f400-7a76-11ea-8eb3-4aa5756be0ab.png)

As title. Now, only clicking the text will toggle the file. Personally feels more intuitive to allow clicking for whole area.

**Comment by Tejas2805** [comment]
Actually, I had the exact opposite in mind. That, since we are adding the right-down icon to indicate file, is collapsible I was thinking we should make it as the only thing that will allow toggling the file.

**Comment by Tejas2805** [comment]
@fzdy1914 What about this one? I feel that now that we have the icon showing whether collapsed or expanded, the current implementation (consisting of clicking on the icon and the file name) works well enough. Or would you still prefer the whole area?

**Comment by fzdy1914** [comment]
Yep, I agree that the current implementation is good enough

**Comment by damithc** [comment]
I still prefer the whole area. It saves the user extra effort to move the mouse icon to a tiny icon. :-)

**Comment by fzdy1914** [comment]
@damithc Actually, clicking the file name will also toggle the file. The effective area is listed below.

![image](https://user-images.githubusercontent.com/35621726/102845715-1e80f000-4449-11eb-9db0-90fc77a2d94b.png)

Now, there is an extra file type label that takes some space in the whole title area, it is less meaningful to support clicking on the space that is on the right side of the file type.

**Comment by Tejas2805** [comment]
> @damithc Actually, clicking the file name will also toggle the file.

Yup.

**Comment by damithc** [comment]
> @damithc Actually, clicking the file name will also toggle the file. The effective area is listed below.

I see. In that case, should be fine. Thanks both for checking. 👍
