### ISSUE TITLE
Dev related code appeared on the UG

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#1219]
![image](https://user-images.githubusercontent.com/35756209/78973909-66721800-7b43-11ea-8bed-dc82a434416b.png)

**Comment by damithc** [comment]
I think this is unavoidable as MarkBind files (same with Jekyll etc.) contain some meta information at the top of the file. The more advance MarkBind features we use, the less the GitHub markdown preview is going to be. That's why all readers should be directed to the html version of the file.

**Comment by Tejas2805** [comment]
Once #1222 gets merged, we can remove all links pointing to the files and this way make sure the users/readers reach the html version only,

**Comment by Tejas2805** [comment]
Issue has been solved in #1281
