### ISSUE TITLE
More robust front end tests

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1220]
Our front end testing coverage is rather low, hence UI regressions can happen very often.

Let's add more front end tests, in particular:
- summary view's functionalities: 
  - [x]  `ctrl-clicking and zooming into specific range`
  - [x]  `ctrl-clicking and zooming into specific range when merge group`
  - [x]  `clicking on view all commits icon`
  - [x]  `merge group features`
  - [x] `filter breakdown features`
  - [x] `restoring of summary controls after page reloads`
- zoom view functionalities: 
  - [ ]  `show ramp chart for this period`, 
  - [x]  `hide/show all commit message bodies`, 
  - [x]  `reloading the page should restore zoom view`
- code view functionalities: 
  - [x]  `filter by glob`, 
  - [x]  `check file types`,
  - [x]  `hide/show all file details`, 
  - [x]  `reloading the page should restore code view`

These are some of the important tests that I can come up now.

**Comment by jamessspanggg** [comment]
@eugenepeh @fzdy1914 is it okay for us to have a more robust set of front end tests? This is so that we can better prevent the front end regressions. However, the downside is that running the tests will take slightly longer.

**Comment by eugenepeh** [comment]
Yes, we should.

**Comment by ckcherry23** [comment]
Checking the `filter by glob` tests for code view as they were added in #1841.
