### ISSUE TITLE
Improve the flexibility of merge group feature

### ISSUE THREAD

**Issue by niqiukun** [reposense/RepoSense#1221]
Currently the merge group feature only supports merging/expanding all groups. However, it may be useful if the user can merge all groups first, find a particular group, and expand that group to see the detailed distribution within the group. This is especially the case when there are many people and repos involved in the dashboard (e.g. [this one](https://nus-cs3281.github.io/2020-dashboard/)).

One solution is:

- Add a button after each group's title to expand/merge a particular group 
- Keep the existing merge group checkbox with the caption changed to "merge all groups"
- Change the `mergegroup` parameter in the page's url from `false`/`true` to  `all`/`none`/`0,1,2` (indices of merged groups joined together)

Shall we discuss whether there is a need for this feature?

**Comment by damithc** [comment]
Could be useful. I'll put it as low priority because we can live without it. If the cost is low, I don't mind adding it.
