### ISSUE TITLE
Implement style check on spacing

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1224]
1. there should be space before curly bracket in scss file, e.g.
```
.fileTypeLabel{  //missing space
}
```
2. there should be check for spacing before : in pug file, e.g.
```
'color' : getFontColor // false
'color': getFontColor // true
```

**Comment by niqiukun** [comment]
First one can be fixed by adding `"block-opening-brace-space-before": "always"` to `stylelintrc`. Second one I think so far there is no official support? Since it is linting `style=""` blocks in `pug` files I think should be done by `stylelint` as well.

**Comment by aidoxe-123** [comment]
Can I work on this?

**Comment by MarcusTXK** [comment]
@sopa301 Feel free to create a new issue if you feel that [eslint-plugin-vue-pug](https://github.com/rashfael/eslint-plugin-vue-pug) might be a good addition to the FE, so the team can discuss it further.
