### ISSUE TITLE
Remove Acknowledgement to Netlify

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1226]
Since we do not use netlify anymore in our project, we can remove it from our acknowledgements.

**Comment by Tejas2805** [comment]
@eugenepeh @damithc

**Comment by damithc** [comment]
Let's keep it for a while at least. It was useful for us for quite a long time; no harm giving them a bit of publicity in return.

**Comment by fzdy1914** [comment]
We do, for the netlify preview of master branch.

**Comment by Tejas2805** [comment]
Closing this issue.
