### ISSUE TITLE
CLI: add minify option to reduce json files size

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#1227]
Spaces and indentation take up a huge amount of space in the file size.

**Comment by anubh-v** [comment]
Currently, we are using the pretty printing option provided by Gson.
I can explore the difference if we create a compact json instead.

**Comment by anubh-v** [comment]
To accommodate a minify option, here is the key method that we need to change:
https://github.com/reposense/RepoSense/blob/abd896c584f321d349a02e8f6deab3c2360f1aa6/src/main/java/reposense/util/FileUtil.java#L91-L107

On line 95, we are turning on the "pretty print" option for the Gson instance, which results in nicely formatted JSON files.
If we do not use pretty printing, Gson will create a compact JSON string by default.

I tried running RepoSense without pretty printing.
The tables below shows that compact printing does significantly lower the amount of space taken up by the `authorship.json` / `commits.json` / `summary.json` files.

**Results for 2019/20 Semester 2 CS3281/2 repositories**

| Pretty / compact printing? | Total `authorship.json` file size | Total `commits.json` file size | `summary.json` file size |
| ---- | --- | ---- | ---- |
| Pretty printing | 39 MB |  492 KB | 8 KB |
| Compact printing | 26 MB | 344 KB | 8KB |


**Results for 2019/20 Semester 2 CS2103 repositories**

| Pretty / compact printing? | Total `authorship.json` file size | Total `commits.json` file size | `summary.json` file size |
| ---- | --- | ---- | ---- |
| Pretty printing | 178 MB | 9.5 MB | 16 KB |
| Compact printing  | 109 MB | 5.3 MB | 12 KB |

**Comment by damithc** [comment]
Looks like the gains are significant. Nice!
