### ISSUE TITLE
Link in footer to RepoSense UG

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1232]
Once PR #1222 gets merged, we can point the link in the footer to the UG in the website.

**Comment by Tejas2805** [comment]
![Screen Shot 2020-04-22 at 4 45 04 AM](https://user-images.githubusercontent.com/35946746/79912140-2587d680-8454-11ea-964d-f12beeda1708.png)

@damithc Planning to remove the highlighted part since `RepoSense` will take the user to the deployed site where UG is available.

**Comment by damithc** [comment]
Note that at some point we should start having two versions of the UG. One for the latest release and one for the latest master, similar to what MarkBind does.

**Comment by Tejas2805** [comment]
> Note that at some point we should start having two versions of the UG. One for the latest release and one for the latest master, similar to what MarkBind does.

Ya realized the same. I will do this deployment once the examinations end.

**Comment by Tejas2805** [comment]
Now that both sites are deployed. I was thinking of fixing this. 

Based on the previous conversation we had decided to make the `User Guide` point to the UG in the Production Site.

The issue with this is, in most places we use the master branch for generating the dashboard. So, in this case it is possible that the features visible in the dashboard and the features showcased in UG do not match with each other to some extent. 

Therefore, I was thinking that if the master branch is used for deployment, we can point to the latest UG. If the latest release is used, we can point to the UG in the production site.

**Comment by damithc** [comment]
> Therefore, I was thinking that if the master branch is used for deployment, we can point to the latest UG. If the latest release is used, we can point to the UG in the production site.

Sounds good.
