### ISSUE TITLE
ArgsParserTest: Some tests should be moved to separate file, as they test logic in RepoSense driver class

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1234]
The majority of the test cases in `ArgsParserTest` test whether the `CliArguments` object is correctly created by `ArgsParser` , in various situations.

However, there are a few tests which test whether the results of processing the `CliArguments` object in RepoSense's driver class are correct.

I am referring to the following tests:

- `parse_validGitRepoLocations_repoConfigurationListCorrectSize` - This verifies whether the RepoSense driver logic obtains the correct number of `RepoConfigs` when it processes the `CliArguments` object. This test indirectly involves the `RepoLocation` too.

-  `parse_configOrLocationsSimilar_success` - This verifies whether the RepoSense driver logic obtains the same `RepoConfigs`, regardless if the `CliArguments` was built using the `--config` argument or the `--repos` argument. This test indirectly involves `RepoConfigCsvParser` and `AuthorConfigCsvParser`.

- `parse_invalidRepoLocation_emptyRepoConfigurationList` - This verifies that the RepoSense driver logic ends up with an empty list of `RepoConfigs` when all repo locations in the `CliArguments` are invalid.

I think we should move these tests into a separate test file that is specifically meant for testing logic in the RepoSense driver class (i.e. `RepoSense.java`).

**Comment by fzdy1914** [comment]
Close with the discussion in #1530 .
