### ISSUE TITLE
Minimist version causes vulnerabilities

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1235]
GitHub is providing a security vulnerability warning with regards to the `minimist` dependency in our Cypress folder. Details are shown below:

<img width="762" alt="Screen Shot 2020-04-16 at 3 23 26 PM" src="https://user-images.githubusercontent.com/32864116/79426894-6b791080-7ff6-11ea-9c7f-bf5978368ce5.png">

**Comment by gerhean** [comment]
Already upgraded, can be closed.
https://github.com/reposense/RepoSense/blob/ed131f6294bf83fac436a6265bc4d53b022739f7/frontend/cypress/package-lock.json#L475
