### ISSUE TITLE
Commits Panel: add filetype tag to each commit

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1239]
With the recent merged #1192, we have the file type info of each commit. 

With this info, we can easily add the filetype tag(s) to each commit and allowing the filter of commits based on filetypes.  Similar to the UI implemented [here](https://github.com/reposense/RepoSense/pull/1093), but in Commits Panel.

**Comment by jamessspanggg** [comment]
@damithc your opinion on this?

**Comment by damithc** [comment]
> @damithc your opinion on this?

Go ahead.

**Comment by Boon-Jun** [comment]
Hi. I will be continuing the work on this issue.
