### ISSUE TITLE
Remove unused / undefined styles

### ISSUE THREAD

**Issue by ang-zeyu** [reposense/RepoSense#1248]
**Is the feature request related to a problem?**

There's some amount of unused classes in `authorship.pug` which don't have corresponding classes, e.g. `.file-picker`. ( likely more in other places )

**If possible, describe the solution**

Let's investigate and remove all unused classes, or classes used in templates without corresponding class definitions in stylesheets

**If applicable, describe alternatives you've considered**

na

**Additional context**

na

**Comment by Tejas2805** [comment]
Making it a first-timer issue.
