### ISSUE TITLE
Set font weight of file type label to be normal

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1251]
**What feature(s) would you like to see in RepoSense?**
The file type label in file title should not be bold for consistencies' sake.
<img width="852" alt="Screen Shot 2020-04-21 at 3 03 41 PM" src="https://user-images.githubusercontent.com/32864116/79835633-9b9f2580-83e1-11ea-81cb-3580b12a51cb.png">

**Is the feature request related to a problem?**
No. Just UI nit.

**If possible, describe the solution**
Set the font-weight to be normal for the file type label in file title.

**If applicable, describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Boon-Jun** [comment]
Hi, first time contributor here. Can I submit a PR for this if no one is fixing this issue?

**Comment by jamessspanggg** [comment]
Hi @Boon-Jun, definitely! Please check the [guidelines](https://se-education.org/guides/guidelines/PRs.html#submitting-a-pr) before submitting a PR.
