### ISSUE TITLE
Refactor flow of AuthorConfiguration

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1257]
**What feature(s) would you like to see in RepoSense?**

**Currently:** The `processLine` method calls `config.addAuthor` before the `Author` object is initialized with any emails and aliases. This means that no emails and aliases are stored in the `AuthorConfiguration` when `config.addAuthor` is called - because the Author object is not fully initialized yet.

**Suggestion:** Refactor the flow of events in `AuthorConfiguration`. We should initialize the `Author` instances before calling `config.addAuthor`. 

Based on suggestion and discussion with @anubh-v in PR #1187

**Comment by anubh-v** [comment]
Thanks for creating this issue @Tejas2805 
I removed the enhancement label, as this is a proposed refactor, and not an improvement of any functionality.

**Comment by Tejas2805** [comment]
I think we should solve this first? This will help in solving the issue with false positives. Better to solve the root first. What do you think @anubh-v ?

**Comment by anubh-v** [comment]
I've created a PR for this.
