### ISSUE TITLE
Csv Parser tests: Code used to load resources can be simplified

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1263]
In all the tests for our csv parsers (`AuthorConfigParserTest`, `GroupConfigParserTest`, `RepoConfigParserTest`), we make *repeated* use of the ClassLoader to obtain the path to each resource used in the tests. This results in verbose code.

Instead of repeatedly using the ClassLoader, we can get the path to the parent directory *once* and then use the file name of each resource to get the individual paths.
This method has been adopted in the `ArgsParserTest`.

Relevant snippet in `AuthorConfigParserTest` :
(though the issue is also present in other csv parsers' tests):
https://github.com/reposense/RepoSense/blob/454eda1b61564c068accb394084fa5ca6ee99548/src/test/java/reposense/parser/AuthorConfigParserTest.java#L20-L41

**Comment by anubh-v** [comment]
I've created a PR (#1264) to demonstrate this suggestion.
I think this change makes the code less verbose.
@fzdy1914 @jylee-git do you agree?

**Comment by fzdy1914** [comment]
The only issue is if we want to load resources from multiple class loaders.
But instead of the suggestion you made, I have the idea to make it a util method, the input is the class name and its relevant path.

**Comment by anubh-v** [comment]
> I have the idea to make it a util method, the input is the class name and its relevant path.

Sure, we can go with this. I'll update the PR.
