### ISSUE TITLE
Error related to file type filter being printed to console

### ISSUE THREAD

**Issue by niqiukun** [reposense/RepoSense#1275]
**Tell us about your environment**

* Latest master

**Please include the steps to reproduce the bug.**

1. Go to master's preview
2. Open browser console

**What was expected to happen?**

No error should appear.

**What actually happened? Please include a screenshot of the output.**

![image](https://user-images.githubusercontent.com/5328196/82907266-f9063380-9f98-11ea-8f4a-ae0ee2c0f143.png)

**Comment by jamessspanggg** [comment]
This is due the following lines, it should check if the checked file types are `undefined` instead of `null`.

https://github.com/reposense/RepoSense/blob/4292889a1c91dc83a6f22ff28d3226b69ca60099/frontend/src/static/js/v_summary.js#L262-L265

First timers are welcomed to fix this!

**Comment by dcshzj** [comment]
Hello, I am a first time contributor to this project. I would like to work on this issue if it is possible?

**Comment by jamessspanggg** [comment]
> Edit: I realised this bug has already been fixed in [46c0d8e](https://github.com/reposense/RepoSense/commit/46c0d8e3d9957aa6aa440bff1440d7a1eee1e6a3), this issue can be closed.

Thanks for notifying! There are other first timer issues that u can pursue!
