### ISSUE TITLE
PublishReposense default settings fail

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1278]
If you use the PubishReposense repo template and run the run.sh without any changes, it fails to generate a report. 

What I did was,
1. fork PubishReposense 
1. Set up Netlify with build command `pip install requests && ./run.sh`

But works with `--master` flag. I guess some bug got fixed since the last release? Should be do a new release?

**Comment by niqiukun** [comment]
Just to check if this is the error produced:
```
Exception in thread "Thread-1" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at reposense.system.StreamGobbler.run(StreamGobbler.java:35)
```

**Comment by damithc** [comment]
Yes, that's the error. In case you can see it, here is the link https://app.netlify.com/sites/lucid-booth-976d1f/deploys/5ed8a64d5d4068df8cbbf077

**Comment by damithc** [comment]
Unrelated but I also see this error in Netlify logs, although the build succeeds (with the latest master branch)
![image](https://user-images.githubusercontent.com/1673303/83786091-d379d800-a6c4-11ea-80e4-e38a7fdcef09.png)

**Comment by niqiukun** [comment]
> Yes, that's the error. In case you can see it, here is the link https://app.netlify.com/sites/lucid-booth-976d1f/deploys/5ed8a64d5d4068df8cbbf077

I suspect that the latest release jar file is not actually compiled by Java 8 (although the target platform is set to Java 8). There is a similar discussion about this: https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

We can follow the second approach outlined in this answer to fix this.

**Comment by niqiukun** [comment]
@jamessspanggg I downloaded the latest release (`v1.11`) jar file and tried using `jdk1.8.0_45` to run it on my local. I get the same error here. 

<img width="569" alt="Screenshot 2020-06-05 at 01 42 19" src="https://user-images.githubusercontent.com/5328196/83792716-02e11280-a6ce-11ea-889b-fcfda1f75362.png">

The jar file I generated myself using ShadowJar can run without this error. Can you help investigate this issue? Likely to be something wrong with the latest release jar file.

**Comment by jamessspanggg** [comment]
Updated the jar file for the latest `v1.11` release, thanks for the help @niqiukun

**Comment by damithc** [comment]
Thanks both. Seems to be working now.
