### ISSUE TITLE
Trailing white spaces in issue templates

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1282]
Spotted in travis logs. Not sure if intended.

![image](https://user-images.githubusercontent.com/1673303/83935932-da056e00-a7f0-11ea-9428-ac9ed9b62e86.png)

**Comment by Boon-Jun** [comment]
Hi, first time contributor here.  If no one else is fixing this, can I submit a PR for this issue to get use to the workflow?

**Comment by jamessspanggg** [comment]
> Hi, first time contributor here. If no one else is fixing this, can I submit a PR for this issue to get use to the workflow?

sure!
