### ISSUE TITLE
linebreak-style lint error on Windows

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1283]
I get this error when running `npm run lint` on Windows. Using Intellij.

![image](https://user-images.githubusercontent.com/1673303/83936533-19cf5400-a7f7-11ea-8183-5e4e3e6845b2.png)

These errors don't actually affect the build as the actual build is run on Unix. However, these errors prevent me from locating potential other problems that can actually break the build.

**Comment by fzdy1914** [comment]
Yes, I got this error too on windows.

**Comment by damithc** [comment]
I think we need to find a solution as we encourage devs to lint before they create PRs.

**Comment by HCY123902** [comment]
The style check `npm run lint` seems to work appropriately on Windows without throwing error on my side when running it from the terminal. Is there any more detailed steps about how this can be reproduced?

**Comment by fzdy1914** [comment]
This is fixed in a recent PR. Closing this.
