### ISSUE TITLE
Set up the workflow for deploying the reposense.org website after a release

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1285]
The reposense.org needs to be updated after each release and the website deployment is slightly different from the regular reposense/RepoSense website i.e., it needs to use a slightly different site.json file.

Suggestion: tweak the `site.json` in the `release` branch. One downside is that merge conflict might arise (rare) when merging `master` to the `release` branch (i.e., if the `master` branch modifies the `site.json` in a way that conflicts the tweaks done in the `release` branch)

Alternative: keep a separate `site-release.json` for the release website. The downside of this is the duplication and extra effort needed to keep the two files in sync.

**Comment by Tejas2805** [comment]
We can follow what MarkBind does in this case. I think they have a separate json for the release website.

**Comment by lm5lm5** [comment]
Hi Prof Damith, how will `site-release.json` be different from the original `site.json`? I'm checking if I can help solve this issue.

**Comment by damithc** [comment]
> Hi Prof Damith, how will `site-release.json` be different from the original `site.json`? I'm checking if I can help solve this issue.

Don't really remember now :-p  you'll have to compare the two files. If you tell me the difference, I can tell you the reason though.

**Comment by Tejas2805** [comment]
@lm5lm5 You can go through MarkBind's `site-release.json` and `site.json` to get a better understanding of it.

On a high level:
1. `site-release.json` contains documentation up to the latest UG. `site.json` contains documentation based on master branch.
2. Markbind has this feature of **tags** which you can use to easily distinguish between different sites.

And as Prof said you can go through the two files, and in case you want to understand something specific, can post it here.

**Comment by dcshzj** [comment]
Was done in #1474.
