### ISSUE TITLE
DG page title should be 'Project management'

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1290]
Is it supposed to look like this? @damithc 

1) 
![Screen Shot 2020-06-15 at 2 32 45 PM](https://user-images.githubusercontent.com/35946746/84625045-0f0e7080-af15-11ea-894c-b6788ad36f6c.png)

The dark blue in the middle looks a bit weird to me. 

2) 
![Screen Shot 2020-06-15 at 2 37 29 PM](https://user-images.githubusercontent.com/35946746/84625271-8512d780-af15-11ea-8241-a96f095271c2.png)

They should probably be same for consistency and follow sentence case.

**Comment by damithc** [comment]
First one is intended. The blue ones are linked, other ones are just headings (ideally, should not be bullets, but unavoidable because I'm reusing the siteNav here).

The second one is a bug. Will fix.
