### ISSUE TITLE
Migration to Java 11

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1304]
We should start migrating our code to Java 11 because from Gradle Version 6.0 onwards, it's compatible with Java 11.

As seen recently, our Gradle version was outdated and this led to 1/2 breaking changes. If we start moving to Java 11 from beforehand,  we can be ready and update our Gradle version as and when required.

**Comment by fzdy1914** [comment]
@damithc What do you think of this issue? Do you think we still need java8 compatibility?

**Comment by damithc** [comment]
> Do you think we still need java8 compatibility?

Would be nice to have (I think it was the last 'free' version of Java and some people might not upgrade beyond Java 8 fora while) but OK not to have it too.

**Comment by fzdy1914** [comment]
OK, will only upgrade it when we truly have to do so.

**Comment by dcshzj** [comment]
Lowering priority, as OpenJDK 1.8 is [supported until at least May 2026](https://access.redhat.com/articles/1299013).

**Comment by yhtMinceraft1010X** [comment]
As a side note, [Checkstyle 10](https://checkstyle.sourceforge.io/releasenotes.html) is now available but requires a minimal version of Java 11. If we decide to move fully to Java 11 and raise the minimum Java version, we can consider upgrading Checkstyle at the same time.

**Comment by supermii2** [comment]
The current build of RepoSense works on Java 11 and with Checkstyle 10.10.0, so we are able to migrate if needed

**Comment by damithc** [comment]
I don't mind upgrading to Java 11

**Comment by ckcherry23** [comment]
Let's continue the discussion in #2177
