### ISSUE TITLE
Locally ran report loads infinitely

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1333]
**Tell us about your environment**

* **RepoSense Version:**
Master branch

* **OS and Version:**
MacOS Catalina 10.15.7

* **Web Browser and Version (if applicable):**
Chrome

**Please include the steps to reproduce the bug.**

1. Run a reposense analysis locally
2. Open the report, report loads infinitely

**What was expected to happen?**
Report should finish loading after awhile.

**What actually happened? Please include a screenshot of the output.**
The loading page loads infinitely.
<img width="631" alt="Screen Shot 2020-09-29 at 8 15 21 PM" src="https://user-images.githubusercontent.com/32864116/94556957-8384d980-0290-11eb-8595-ae65bc2fdd24.png">

I suspect where it is due to the current code, where it is trying to call `startsWith` with `version` that is undefined.
<img width="630" alt="Screen Shot 2020-09-29 at 8 15 50 PM" src="https://user-images.githubusercontent.com/32864116/94557011-939cb900-0290-11eb-9059-00c23be098df.png">

**If possible, include the URL to your RepoSense report or log files (if any).**
N.A.

**Comment by jamessspanggg** [comment]
Caused by #1305 @Tejas2805

**Comment by fzdy1914** [comment]
I forget in which case the `repoSenseVersion` can be `None`, but see the previous code, it is indeed possible.

**Comment by fzdy1914** [comment]
Can you try to use `-v` tags in local development first to avoid this issue?

**Comment by jamessspanggg** [comment]
> Can you try to use `-v` tags in local development first to avoid this issue?

Running `-v` in local development still has this issue tho

**Comment by Tejas2805** [comment]
That’s weird. I have run locally a few times after it, has worked okay for me. 

Can share the command you used to build? 

I will look into the issue and submit PR in some time.

**Comment by jamessspanggg** [comment]
> Can share the command you used to build?

I used `--config ./config -v -s d1`

**Comment by Tejas2805** [comment]
Just checked. Making the PR.
