### ISSUE TITLE
Show non-blank lines count instead of blank-lines count

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1336]
Current: blank lines count is shown within brackets
![image](https://user-images.githubusercontent.com/1673303/94773661-d5dc0c80-03ee-11eb-943e-482a640f1063.png)

Suggestion: It's more useful to show the non-blank links count instead? 

Reason: To save the user from having to do the mental calculation.

**Comment by lm5lm5** [comment]
I will create a PR fixing this issue.
