### ISSUE TITLE
Generate weekly contribution dynamically from daily 

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#134]
The start day of the weekly contribution calculation is dependent on the date of first commit in the repository, within the specified period.

This can creates the problem of unequal comparison as the start date of all repositories may differ.

For simplicity, there are 2 solutions to this issue:
1. Fix the start day of calculation
2. Generate it dynamically from daily contributions

The second option would be preferable because:
1. Low cost / Cheap operation
2. Expandable to more options such as `select-able start day`, or `monthly contribution`.

**Comment by damithc** [comment]
In case this is relevant: we also want to do a per-commit view in addition to per-day and per-week views we currently have.

**Comment by ongspxm** [comment]
this is kind of done in #129, as of now, its sitting in the frontend branch

**Comment by yamidark** [comment]
Resolved in #163
