### ISSUE TITLE
Deprecate use of window.toggleNext in zoom panel

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1340]
Currently, `window.toggleNext` is being used by the ~segment, summary chart and~ zoom panels to toggle between displaying and hiding information. However, the authorship panel uses `v-show` to handle the same functionality. Even for the segment, summary chart and zoom panels, they each have their own ways of handling the toggling of the content.

We should deprecate the use of `window.toggleNext` and provide a common functionality for handling toggling of information. This would also allow other components to be aware of whether a particular element is hidden or is displayed.

Potentially related to #795.

**Comment by LuoZhijie-tom** [comment]
Hi is this issue still open? Is it ok to work on it?

**Comment by LuoZhijie-tom** [comment]
Hi @dcshzj, I wonder if this is still ongoing and if I can attempt it?

**Comment by damithc** [comment]
> Hi @dcshzj, I wonder if this is still ongoing and if I can attempt it?

@dcshzj what do you think?

**Comment by LuoZhijie-tom** [comment]
Hi @dcshzj, is this issue still unsolved? I wonder can I have a try?

**Comment by vvidday** [comment]
Hi, could I try taking this issue?
