### ISSUE TITLE
Report generation is slow on large repos

### ISSUE THREAD

**Issue by vig42** [reposense/RepoSense#1342]
RepoSense takes a very long time to generate report for large repos - notably those with a long history of commits, and with frequent changes to binary files. One of the main bottlenecks is the time taken to clone the repo. I tried it on [chromium](https://github.com/chromium/chromium), which took over 45min on my home wifi, and [nerd-fonts](https://github.com/ryanoasis/nerd-fonts), which took more than 15min.

Currently, RepoSense clones the entire history for the repo. Since the report only shows commits for the past month by default, I feel that we could make use of git's shallow clone functionality to reduce the amount of data that needs to be downloaded. Specifically we can make use of the `--shallow-since` parameter of `git clone`, to only clone the commit history for the last month (or after the 'since' date specified by the user). Using this parameter, the time taken to clone the chromium repo for the last month was cut from 45min to just about 5min on my wifi.

We could also consider using git's partial clone functionality, using the `--filter=blob:none` parameter. This clones the repo without downloading any of the blobs, which means the clone is almost instant. Git will instead download blobs as and when required, e.g. when running `git diff`.

**Comment by fzdy1914** [comment]
Close by 1449
