### ISSUE TITLE
Unused variable isFileTypesLoaded

### ISSUE THREAD

**Issue by Boon-Jun** [reposense/RepoSense#1344]
An unused variable in v_zoom.js was unintentionally introduced with commit ae5405e

![image](https://user-images.githubusercontent.com/35420846/97041720-81b5e980-15a2-11eb-84b6-97aead9ddf8f.png)

**Comment by Krit-K** [comment]
@damithc i'm interested in joining RepoSense for CS3281, may I work on this issue?

**Comment by damithc** [comment]
> may I work on this issue?

Sure @Krit-K
