### ISSUE TITLE
Authorship.json: give per-line last-modified-date

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1345]
Current:
![image](https://user-images.githubusercontent.com/1673303/97066478-74235280-15e8-11eb-809d-9dd6cd757c59.png)

I'm wondering is it possible to also give last-modified-date for each line. While not strictly not necessary for the dashboard, I can use that data in further processing when I grade students' work.

This will increase the size of the file significantly though. Perhaps we can disable by default with an option to enable it using a flag.

The time zone (if provided) needs to be considered as well.

**Comment by damithc** [comment]
@jamessspanggg @fzdy1914 Is this data readily available to be added to the json file or the processing logic needs to change significantly for this?

**Comment by fzdy1914** [comment]
I am not so familiar with the logic of this side. @jamessspanggg Your thought?

**Comment by Tejas2805** [comment]
As far as I know, Git blame provides the time of the last change for each line along with the timezone. And it is included in the code we already have written. We just need to make it accessible I think. 

![Screen Shot 2020-10-26 at 9 42 27 AM](https://user-images.githubusercontent.com/35946746/97125676-9abfc580-176f-11eb-9e7b-73852b8e3d2a.png)

**Comment by jamessspanggg** [comment]
Yes I believe this data is readily available and it doesn't need too much processing logic, just need to add the `lastModifiedDate` field to each line.

**Comment by jamessspanggg** [comment]
> As far as I know, Git blame provides the time of the last change for each line along with the timezone. And it is included in the code we already have written. We just need to make it accessible I think.

Yes agreed.

**Comment by damithc** [comment]
Great. Let's go ahead with it then. First, let's add it to the json file (no need to show in the UI).
It can be enabled or disabled by default (based on the performance cost) with the flag to enable/disable it as necessary.

**Comment by jamessspanggg** [comment]
@damithc the last modified date of each LoC is available now. How would u want to display the last modified date in the front end?

**Comment by damithc** [comment]
> @damithc the last modified date of each LoC is available now. How would u want to display the last modified date in the front end?

Let's leave it aside for now. I dont' want to add any more overheads to the front end as it's already slow for big classes.
