### ISSUE TITLE
Enable incremental report build

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#135]
Generate the entire report takes time, hence we should reduce the time of sub-sequence build by doing it incrementally. 

 Current idea to implement this:
- Do pre-processing to detect changes from the HEAD of last analysis (analysis->HEAD).
- Get list of file changes since the last analysis
  This can be done using `git diff --name-only <hash1> <hash2>`
- CommitsReporter:
  Count daily contribution and sum to existing
- AuthorshipReporter:
  Git blame only on the affected files

Some scenarios that we may have to skip pre-processing and regenerate the entire report
- If `analysis->HEAD` is not found
- If date param is set
- If previous report doesn't exist

**Comment by fzdy1914** [comment]
The issue mentioned is not a problem now, as we auto set the date range now.

**Comment by eugenepeh** [comment]
@fzdy1914 actually the idea of this is to avoid regenerating whole report from scratch in some sort of "append" or modify affected style in a continuous/incremental style.

E.g. 
RepoSense is scheduled to perform analysis daily, however if a target repo is still the same as the day before, we will skip performing analysis on it. 

This is meant to reduce unnecessary analysis.

**Comment by fzdy1914** [comment]
OK, got the idea.

**Comment by damithc** [comment]
Let's put this on hold as keeping data from the previous runs is not feasible when the report generation is done in a CI environment (e.g., on GitHub Actions), as is the case for all our RepoSense reports that are online at the moment.
