### ISSUE TITLE
Dashboard: the chart view should indicate which author is shown in code view

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1352]
![image](https://user-images.githubusercontent.com/1673303/97795999-1a560480-1c48-11eb-97f5-839d1f12cdee.png)

Steps:
* Click on the `</>` icon on the chart view
* Scroll down the code view

Problem: need to scroll to the top of the code view to recall who's code is being viewed

Suggestion: Highlight the `</>` icon when clicked? Not sure about the coding and performance costs though.

**Comment by fzdy1914** [comment]
It should be easy to implement.

**Comment by Tejas2805** [comment]
> Suggestion: Highlight the </> icon when clicked?

If the user scrolls down the summary panel too, the error will still remain. Better to have some mechanism of knowing whose code we are viewing at all points of time?
