### ISSUE TITLE
empty author tags not honored

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1354]
![image](https://user-images.githubusercontent.com/1673303/98432653-4ca9ab00-20fb-11eb-8f8a-49c9a1fcc396.png)

Guys, in the example above, the empty @@author tag at line 18 should mean the lines below it are not to be attributed to anyone until we encounter another non-empty @@author tag. But looks like some lines are being attributed to an author.
Is this a bug in the current logic?

File https://github.com/AY2021S1-CS2103T-W12-1/tp/blob/master/src/main/java/seedu/address/storage/JsonPatientRecordsStorage.java

**Comment by jamessspanggg** [comment]
Yes it is due to a bug in our current logic and it was due to: https://github.com/reposense/RepoSense/pull/1067

To provide more info, in `findAuthorInLine` it returns an `Optional.Empty()` when the author name is not provided in the `@@author` tag. This causes only the line of `@@author` to be set to author UNKNOWN whereas the rest to not be affected. @anubh-v correct me if im wrong here
https://github.com/reposense/RepoSense/blob/a3f21b35831266ba751924b327093d7465560938/src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java#L26-L47

**Comment by jamessspanggg** [comment]
Here's a breakdown of the logic used in processing the `@@author` tags.

- If we encounter a start tag (i.e. `@@author GIT_AUTHOR_NAME`), then:
  - If `GIT_AUTHOR_NAME` belongs to an author within the `AuthorConfiguration`, then `AnnotatorAnalyzer` will attribute the subsequent lines to this author (until an end tag `@@author` is encountered, or till end of file if no end tag is encountered).

  - If `GIT_AUTHOR_NAME` does not belong to any author within `AuthorConfiguration`, then `AnnotatorAnalyzer` will attribute the subsequent lines to a `UNKNOWN_AUTHOR` (until an end tag is encountered, or till end of file if not end tag is encountered)

- If we encounter an end tag (i.e. `@@author`), then:
  - If there has been a start tag (i.e. `@@author GIT_AUTHOR_NAME`) encountered previously, the line with the end tag will be attributed to author inferred from that start tag.
  - If no start tag has been encountered yet, then the line with the end tag is attributed to `UNKNOWN_AUTHOR`.

_Originally posted by @anubh-v in https://github.com/reposense/RepoSense/pull/1067#issuecomment-586616471_

From the changes in PR #1067, it seems like we did not take into account the situations where we treat `//@@author` as a start tag, we always treat it as the end tag.

**Comment by damithc** [comment]
I see. Thanks for the investigation @jamessspanggg 
Any idea if this can be fixed quickly? If not, we can ask students to use a dummy username e.g., `@@author unknown`, right?

**Comment by jamessspanggg** [comment]
> Any idea if this can be fixed quickly? If not, we can ask students to use a dummy username e.g., `@@author unknown`, right?

Yes asking the students to use a dummy username would solve the problem temporarily.

**Comment by jamessspanggg** [comment]
I'm not too familiar with the following code. @anubh-v any ideas if this can be fixed quickly>?

**Comment by anubh-v** [comment]
Sorry @jamessspanggg , @damithc, may I look into this in the second half of next week?

**Comment by damithc** [comment]
> Sorry @jamessspanggg , @damithc, I need some time to look into the fix for this.
> May I get back to this by Wednesday?

Sure @anubh-v

**Comment by anubh-v** [comment]
I have started a PR to treat empty author tags as new author annotations, if there isn't already an existing authorship annotation being applied.

The code change is minor. However, the expected output for our system tests needs to be changed. I'll need 3 - 4 days to finish this up.

**Comment by damithc** [comment]
@reposense/21-22-active-developer Guys, this is a high-priority issue. Can someone fix this soon?

**Comment by dcshzj** [comment]
Let me see if I can build on from the work on #1357.
