### ISSUE TITLE
Not use # in URLs

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1356]
Looks like the # in the RepoSense URLs are causing some problems. Is it possible not to use # in URLs?

https://github.com/nus-cs2103-AY2021S1/forum/issues/404

**Comment by jamessspanggg** [comment]
I think its possible to use `?` to encode the params but that will introduce a lot of changes within the front end code. @fzdy1914 your thoughts on this?

A simple manual workaround to this is to ask them to use url shortener (e.g. bitly) to shorten the link first, then place the shortened link in their pdf.

**Comment by damithc** [comment]
> A simple manual workaround to this is to ask them to use url shortener (e.g. bitly) to shorten the link first, then place the shortened link in their pdf.

Probably too much to expect from users as this can affect any RepoSense user.



> I think its possible to use `?` to encode the params but that will introduce a lot of changes within the front end code. @fzdy1914 your thoughts on this?

Can we make the code to work for either `#` or `%23`?
Was there some compelling reason to choose `#` in the first place?

**Comment by fzdy1914** [comment]
> I think its possible to use `?` to encode the params but that will introduce a lot of changes within the front end code. @fzdy1914 your thoughts on this?


Yes, I agrees that `?` should be a better choice. And we may utilize the functionality of `vue-router` to do parameter handling.

Meanwhile, I don't think we can make it work for both `#` or `%23`.

**Comment by jamessspanggg** [comment]
@fzdy1914 do u know the rationale of using `#` initially?

**Comment by fzdy1914** [comment]
> @fzdy1914 do u know the rationale of using `#` initially?

Don't know though. May because it is easy to implement?

**Comment by gerhean** [comment]
I can take this issue, doesn't actually need much changes in frontend.

The use of `#` is by convention + browser support, see: https://www.w3schools.com/jsref/prop_loc_hash.asp
