### ISSUE TITLE
Add confirm button for filter and sorting

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1367]
**What feature(s) would you like to see in RepoSense?**

![image](https://user-images.githubusercontent.com/16630400/101868642-c2041200-3bb8-11eb-906c-f7688c45f405.png)

Add confirm button for filter and sorting somewhere at the circled area.

**Is the feature request related to a problem?**

Right now changing any parameter causes the whole page to re-render, taking up to 20s for long lists. Indicating multiple parameters to sort and filter by is hence a big annoyance.

**If possible, describe the solution**

Add a confirmation button which re-renders the list only when pressed. Users only need to wait once instead of multiple times like currently. Accidentally selecting the wrong parameter will also be less of an issue.

**Comment by fzdy1914** [comment]
We have the plan to revamp the whole control panel. But we haven't decided how to do so now. See issue  #509.
