### ISSUE TITLE
Update contribution workflow to include drafting a commit message for PRs

### ISSUE THREAD

**Issue by wltan** [reposense/RepoSense#1369]
From https://github.com/reposense/RepoSense/pull/1368#issuecomment-743164813

**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

I was informed in #1368 that PRs should be accompanied with a proposed commit message when the PR is to be merged.

However, this step is not well-documented in the developer guide [contribution workflow](https://reposense.org/RepoSense/dg/workflow.html).

**What would you like added or modified in the documentation?**

The developer guide should note somewhere (perhaps under https://reposense.org/RepoSense/dg/workflow.html#workflow) that although there is no need to write elaborate commit messages for each commit (due to the squash merging), each PR should contain a proposed commit message in its description.

**Comment by dcshzj** [comment]
Fixed in #1378.
