### ISSUE TITLE
Use light theme for code

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1370]
RepoSense docs were written when MarkBind supported only the light theme for code. Recently, MarkBind switched to the dark theme as the default. However, our documentation doesn't look nice in the dark theme as there are many inline code fragments in the docs. An example is given below.
Perhaps switch back to light theme? Instructions for adding the setting to the `site.json` are [here](https://markbind.org/userGuide/siteJsonFile.html#style).

![image](https://user-images.githubusercontent.com/1673303/101975503-0e625700-3c78-11eb-8206-7abac5bbe232.png)

**Comment by kkangs0226** [comment]
Hi Prof. Damith and team, I am a first timer here and would like to contribute to this issue!
I've noticed that the label states "s.ToDiscuss", and if the team to decides to work on this, I would like to help resolve this issue.
Please let me know if it is ok for me to do so, after your discussion!

**Comment by kkangs0226** [comment]
Dear Prof. Damith, could I ask how I could reproduce this issue? The inline code are still in light theme on my side. (using Chrome)

Thank you!
![image](https://user-images.githubusercontent.com/66008784/102009120-43ea6b80-3d70-11eb-9054-d48378f27442.png)

**Comment by damithc** [comment]
> Hi Prof. Damith and team, I am a first timer here and would like to contribute to this issue!
> I've noticed that the label states "s.ToDiscuss", and if the team to decides to work on this, I would like to help resolve this issue.
> Please let me know if it is ok for me to do so, after your discussion!

As there have been no objections to the suggested change so far, we can go ahead. I've removed the `toDiscuss` label.
