### ISSUE TITLE
Documentation preview in PRs no longer exists

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1374]
**Tell us about your environment**

* **RepoSense Version:** Not important
* **OS and Version:** Not important
* **Web Browser and Version (if applicable):** Not important

**Please include the steps to reproduce the bug.**

1. Head to any pull requests
1. Click on the github checks, click on the surge docs deployment
1. Observe that the site does not exist

**What was expected to happen?**
The documentation preview should be deployed and accessible through the github checks

**What actually happened? Please include a screenshot of the output.**
<img width="582" alt="Screen Shot 2020-12-15 at 12 05 30 AM" src="https://user-images.githubusercontent.com/32864116/102104528-4086db00-3e69-11eb-91f3-95ce9a485293.png">

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by jamessspanggg** [comment]
Here's where it went wrong, can find it here https://travis-ci.org/github/reposense/RepoSense/jobs/749603168:

<img width="1200" alt="Screen Shot 2020-12-15 at 12 17 33 AM" src="https://user-images.githubusercontent.com/32864116/102105976-fe5e9900-3e6a-11eb-88cb-2769ab07d7eb.png">

**Comment by jamessspanggg** [comment]
@ang-zeyu could this be an issue from the Markbind side?

**Comment by ang-zeyu** [comment]
> Node.js v10.13.0 or higher installed

try ^

> npm install -g markbind-cli (travis.yml)

would recommend fixing the version as well in case there's more breaking changes; We listed node `v10` but never really quite used it till v2.17
