### ISSUE TITLE
Some typos, grammatical errors and inconsistencies in the User Guide and Developer Guide

### ISSUE THREAD

**Issue by kkangs0226** [reposense/RepoSense#1375]
**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

I have found some minor grammatical errors/typos/inconsistencies in the User Guide and Developer Guide, as shown in the screenshots below.

Example of grammatical errors: 
![Screenshot 2020-12-16 at 10 33 22 AM](https://user-images.githubusercontent.com/66008784/102298132-89cf4b80-3f8b-11eb-88ee-2a58e025f5d7.png)
→ sections 'explains' 

Example of typos:  
![Screenshot 2020-12-16 at 10 29 55 AM](https://user-images.githubusercontent.com/66008784/102298224-b2efdc00-3f8b-11eb-8965-e8884bf80d97.png)
→ 'tyring'

Example of inconsistencies:
![Screenshot 2020-12-16 at 10 29 32 AM](https://user-images.githubusercontent.com/66008784/102298275-ce5ae700-3f8b-11eb-9d7d-86d3679d4909.png)
![Screenshot 2020-12-16 at 10 29 38 AM](https://user-images.githubusercontent.com/66008784/102298284-d1ee6e00-3f8b-11eb-8ad8-6aa95dbb3038.png)

→ Hyperlink is around the section title only for the second screenshot, not so for the first screenshot

![Screenshot 2020-12-16 at 10 40 29 AM](https://user-images.githubusercontent.com/66008784/102298670-7e305480-3f8c-11eb-9382-aedb32639582.png)

→ The second line should have the first letter capitalised as well

**What would you like added or modified in the documentation?**

There are a number of such minor errors in the documentations, and I would like to correct them.

**Comment by damithc** [comment]
Thanks for reporting these @kkangs0226 
Yes, these should be fixed.

**Comment by Tejas2805** [comment]
@kkangs0226 @HCY123902 Glad to see you all so excited to contribute to RepoSense! Just a suggestion: Avoid opening duplicate PRs that fix the same issue, unless your way of fixing it is different. This will help the senior developers go through the PRs faster and look at one PR clearly. Keep up the good work!
