### ISSUE TITLE
Minor improvement to consistency and readability of Developer Guide section 

### ISSUE THREAD

**Issue by rolandyuwy** [reposense/RepoSense#1377]
**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

A minor improvement to the **Setting Up** section in the Developer Guide would allow the setting up process to be more seamless.

**What would you like added or modified in the documentation?**
For each bullet point, include a tip to find out the version of each prerequisite from the OS terminal. 

Suggestions:
- Type `java --version` on your OS terminal and ensure that you have the correct version of **JDK**.
- Type `npm -v` on your OS terminal and ensure that you have the correct version of **npm**.

![image](https://user-images.githubusercontent.com/59356158/102468350-5d4f2880-408c-11eb-9bab-8789c6b4cf7b.png)

**Comment by damithc** [comment]
Yes, that can be helpful. Not to make a big deal out of it, we can simply mention all three together in the tip. i.e., 
> You can use `java -version`, `npm -v`, and ... to verify that you have the correct version of each.
