### ISSUE TITLE
Functional test not testing parsing functionalities

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#138]
The functional test directly produces the files for testing by calling 
CsvConfigurationBuilder.buildConfigs(Path, Date, Date) and
RepoInfoFileGenerator.generateReposReport(
List<RepoConfiguration>, String) manually.

As such, the initial parsing of user-supplied input arguments is not 
covered by the functional test.

Since functional test is a skeleton of an end-to-end testing infrastructure,
the initial parsing of user-supplied input arguments should be covered
in the functional test as well.

Let's update functional test to call the RepoSense.main(String[]) method
to generate the files for testing.

**Comment by yong24s** [comment]
@eugenepeh 

Please close this issue. It has been resolved in #130.
