### ISSUE TITLE
Long contribution bar causes UI issue

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#1397]
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Mac OS 
* **Web Browser and Version (if applicable):** Chrome

**Please include the steps to reproduce the bug.**

1. Visit http://tnb-contribution-04-01-2020.surge.sh/?search=&sort=groupTitle&sortWithin=totalCommits%20dsc&since=2020-06-04&timeframe=commit&mergegroup=thenewboston-developers%2FAccount-Manager%5Bmaster%5D&groupSelect=groupByRepos&breakdown=false
1. Observe that the second group appends to the first group, instead of being at the next line of the first group

**What was expected to happen?**
Next group should be at the next line of the first group

**What actually happened? Please include a screenshot of the output.**
Second group appends to the first group
<img width="1053" alt="Screen Shot 2021-01-04 at 11 11 19 AM" src="https://user-images.githubusercontent.com/32864116/103497803-94d81600-4e7d-11eb-9a14-dc716c68f735.png">

**More context**
Currently, the length of the contribution bar is directly proportional to the LoC contribution. For repositories that have users with very big difference in contribution, the users with large contribution will have very long contribution bar, as shown below:
<img width="847" alt="Screen Shot 2021-01-04 at 11 13 01 AM" src="https://user-images.githubusercontent.com/32864116/103497866-d10b7680-4e7d-11eb-9d35-6fd50713c8ec.png">

Since we already have the LoC displayed for each user/group, I think it may not be necessary for the contribution bar to be directly proportional to the LoC. Perhaps we should re-think the logic to calculate the length contribution bars? Or limit the length of contribution bar to a certain amount?

**Comment by damithc** [comment]
> Since we already have the LoC displayed for each user/group, I think it may not be necessary for the contribution bar to be directly proportional to the LoC. Perhaps we should re-think the logic to calculate the length contribution bars? Or limit the length of contribution bar to a certain amount?

I would like to fix the UI issue while keeping the contribution bar length though. The highly visual nature of the contribution bar is a lot more useful than just numbers. If someone contributed way may than others, I want it to catch the eye immediately. But this is often a result of a student incorrectly committing library code. In such cases, it is good if the bar becomes an eye sore so that someone can catch it quickly and get the student to remove the code.

**Comment by damithc** [comment]
Good catch with the bug 👍 . I've seen a few cases of long contribution bars I failed to notice the bug :-(

**Comment by jamessspanggg** [comment]
> Good catch with the bug 👍 . I've seen a few cases of long contribution bars I failed to notice the bug :-(

Note that the first group is merged, while the rest aren't 😬

**Comment by HCY123902** [comment]
This is potentially related to #1467
