### ISSUE TITLE
v1.1 Release

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#140]
@ongspxm @yong24s @yamidark @AdityaA1998 

We should start finishing up the ongoing PRs and make our v1.1 release.
@yamidark can start refactoring some of the classes.

CHANGELOG:
- Performance increase
- Reduce in system load
- UI revamp 
- Simpler configuration file format

If you're not working on an ongoing PR, please ensure that our documentations are up to date.

Also, start planning or work on v1.2 deliverables. Currently we have
- Incremental report build
- Per commit view

**Comment by yamidark** [comment]
V1.1 has already been released [here](https://github.com/reposense/RepoSense/releases/tag/v1.1).
