### ISSUE TITLE
Typo in CLI syntax reference

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1409]
There is a typo in the example given in CLI syntax reference.

![Screen Shot 2021-01-17 at 10 15 29 PM](https://user-images.githubusercontent.com/35946746/104845684-b1f6f500-5911-11eb-86a5-9ec34b207b6c.png)

The actual parameter is:

![Screen Shot 2021-01-17 at 10 15 39 PM](https://user-images.githubusercontent.com/35946746/104845698-bd4a2080-5911-11eb-9526-0a2258ff13ef.png)

**Comment by Tejas2805** [comment]
@HCY123902 Maybe you can do it in your PR itself since you are touching that part of the document

**Comment by HCY123902** [comment]
Sure, no problem
