### ISSUE TITLE
Abstract code out from summary.js

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1420]
**What feature(s) would you like to see in RepoSense?**
Move code which does not rely on the state of `summary.js` out of `summary.js` to somewhere else.
Also can apply to other files.

**Is the feature request related to a problem?**
`summary.js` has over 900 lines and is very messy. Looking for relevant code can be hard
Also would help if we decide to move handling of repo data out of `summary.js` (maybe to Vuex).

**Comment by fzdy1914** [comment]
Yes, can go ahead. And you can choose to do it before or after morphing.

**Comment by damithc** [comment]
@gerhean is there more to do for this issue or done already?

**Comment by gerhean** [comment]
I'll close this first, not planning to do much about this at the moment.
