### ISSUE TITLE
Zoom reloading not function properly

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1426]
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** windows10
* **Web Browser and Version (if applicable):** Chrome

**Please include the steps to reproduce the bug.**

1. Visit https://nus-cs2103-ay2021s1.github.io/tp-dashboard/#breakdown=true&search=&sort=groupTitle&sortWithin=title&since=2020-08-14&timeframe=week&mergegroup=&groupSelect=groupByRepos&checkedFileTypes=docs~functional-code~test-code~other&until=2020-11-10&tabOpen=true&tabType=zoom&zFR=true&zA=sc-arecrow&zR=AY2021S1-CS2103-F09-1%2Ftp%5Bmaster%5D&zACS=2476&zS=2020-09-21&zFS=undefined&zU=2020-09-27&zMG=false&zFTF=commit&zFGS=groupByRepos
1. Open any zoom panel
2. Click on the ramp at the zoom panel
3. Refresh

**What was expected to happen?**
The page should reload with the zoom panel
![image](https://user-images.githubusercontent.com/39231750/105511790-43e47080-5d0b-11eb-92a2-250baecd72bc.png)

**What actually happened? Please include a screenshot of the output.**
Error in event handler for "restoreCommits": "TypeError: Cannot read property '0' of undefined"

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by fzdy1914** [comment]
Seems can not reproduce. Any other parameter specified?

**Comment by gerhean** [comment]
Can guess what happened, but cannot reproduce either.

**Comment by fzdy1914** [comment]
> Can guess what happened, but cannot reproduce either.

We need to reproduce it by `groupByRepos` option. I successfully reproduced it. That link is useful.

**Comment by gerhean** [comment]
I still cannot reproduce it. In any case this link does not reflect the current master branch.

In the current master branch, clicking on the ramp at the zoom panel brings one to the commit on the github website and should not cause any changes to state. Hence this issue might not be relevant anymore.

**Comment by fzdy1914** [comment]
> I successfully reproduced it. However this link does not reflect the current master branch
> 
> In the current master branch, clicking on the ramp at the zoom panel brings one to the commit on the github website and should not cause any changes to state. Hence this issue might not be relevant anymore.

Step to reproduce on current master:
1. open report
2. breakdown by filetyple
3. granularity by week
4. view any commit pannel
5. click on ramp
6. refresh

**Comment by gerhean** [comment]
Actually what exactly should be happening when i click the ramp.
![image](https://user-images.githubusercontent.com/16630400/106108054-b7aad100-6182-11eb-8eea-3a8d22a82709.png)
Why is it that when I filter by scss, when I click the ramp, the zoom page appears with commits without scss?
