### ISSUE TITLE
GitHub Actions conflict if multiple deployments are done in a short amount of time

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1429]
This issue is a follow up from #1408.

Due to the way the `dawidd6/action-download-artifact` action handles the detection of artifacts, it often results in a race condition where the wrong artifacts are used for certain `workflow_run` runs.

We should explore how to obtain the correct artifact for each `workflow_run`.

**Comment by fzdy1914** [comment]
![image](https://user-images.githubusercontent.com/35621726/105660610-5aa2e700-5f06-11eb-8787-dd646d57bf78.png)
Go check this.

**Comment by fzdy1914** [comment]
And do care about this attribute.

![image](https://user-images.githubusercontent.com/35621726/105660722-9fc71900-5f06-11eb-8c01-6c567f399913.png)

I think the best way to fix this is not adding this `auto_inactive` but to edit the name of the `env` to match the PR, i.e., dashboard-1444, docs-1444.
