### ISSUE TITLE
Some backend unit test cannot pass on Windows

### ISSUE THREAD

**Issue by HCY123902** [reposense/RepoSense#1444]
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Windows10
* **Web Browser and Version (if applicable):** Edge

**Please include the steps to reproduce the bug.**

1. Run `gradlew test` in the project directory

**What was expected to happen?**

All the unit test should pass successfully, as is the case when running them using Github Actions.

**What actually happened? Please include a screenshot of the output.**

![image](https://user-images.githubusercontent.com/54735123/106413550-52f2bd80-6485-11eb-9093-9354f7265f4c.png)

![image](https://user-images.githubusercontent.com/54735123/106413576-600fac80-6485-11eb-9d8e-c2676ec60719.png)

![image](https://user-images.githubusercontent.com/54735123/106413583-64d46080-6485-11eb-9b02-757e9e06096c.png)

3 test cases were not passing with exception thrown.

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by damithc** [comment]
@HCY123902 this is still happening?

**Comment by HCY123902** [comment]
@damithc Sorry for the late reply. This is still happening on my local computer but it may depend on the system environment. @dcshzj @gerhean Can I check whether you can reproduce it on your side? Thanks

**Comment by litone01** [comment]
Hi @HCY123902, I have tested on:

RepoSense Version: master
OS and Version: Windows10

following the instructions provided and found no errors and no failed cases. 

Do you still face the same issue now?

**Comment by HCY123902** [comment]
Thanks for the verification. I think this is caused by local setting. The issue will be closed at the moment
