### ISSUE TITLE
Charts panel: header info misplaced

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1460]
![image](https://user-images.githubusercontent.com/1673303/109681409-65613380-7bb8-11eb-89b2-9e813e73ba20.png)

https://nus-cs2103-ay2021s2.github.io/tp-dashboard/?search=&sort=totalCommits%20dsc&sortWithin=title&since=2021-02-19&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other

**Comment by gerhean** [comment]
I will try to fix.
