### ISSUE TITLE
Incorrect highlighting after merging/unmerging groups

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1464]
Example:

Highlighting is correct before merging groups:
![image](https://user-images.githubusercontent.com/1673303/110232780-e030a280-7f5a-11eb-9662-55198b7b1360.png)

After clicking on 'merge groups', the high-lighting is incorrect.
![image](https://user-images.githubusercontent.com/1673303/110232828-166e2200-7f5b-11eb-8990-2ecbbf9e9405.png)

I think highlighting should be removed upon merging/unmerging groups. It's better not to have a highlighting than to highlight the wrong one.

**Comment by Tejas2805** [comment]
I think the current implementation highlights the entire group right? So wish for that to be removed? Or is the wrong group being highlighted?

**Comment by damithc** [comment]
> I think the current implementation highlights the entire group right? So wish for that to be removed? Or is the wrong group being highlighted?

The correct group is being highlighted. But the code panel is not showing anything related to the entire group (it shows only the code of one member). That's the mismatch.

**Comment by Tejas2805** [comment]
> The correct group is being highlighted. But the code panel is not showing anything related to the entire group (it shows only the code of one member). That's the mismatch.

Ah true. That is the current implementation. We were thinking of it more in terms of the user gets to know where the highlight is coming from. If it's looking like a mismatch, then maybe better to remove this implementation and keep the highlight for the merged group, if the group code is being shown. @HCY123902 can take a look?

**Comment by HCY123902** [comment]
Sure, no problem

**Comment by HCY123902** [comment]
How about the situation where the group is expanded but the tab is still on the merged group? In this case, should the group still be highlighted?

**Comment by damithc** [comment]
> @damithc Hello professor, can I ask for your opinion on the the situation where the group is expanded but the tab is still on the merged group? In this case, should the group still be highlighted?

The requirement is, the highlighted item on the charts panel should match what is shown on the other tab. If there is no match, remove the highlight.

**Comment by HCY123902** [comment]
Thanks for the reply. I will remove the highlight when the group is merged
