### ISSUE TITLE
Dashboard loading empty if base URL is given

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1468]
Any idea why https://nus-cs3281.github.io/2021-dashboard is loading empty? The data shows up only if I click on the 'reset date' button

![image](https://user-images.githubusercontent.com/1673303/110240850-d2921180-7f88-11eb-8e91-22af998068e9.png)

Any recent change to URL parameters that could have caused this?

**Comment by fzdy1914** [comment]
@gerhean Can you check this one? It may cause by the `only filter once` PR or the `use computed since date` PR?

**Comment by fzdy1914** [comment]
Error warning.
![image](https://user-images.githubusercontent.com/35621726/110241005-8bf0e700-7f89-11eb-98e3-90ac7081543b.png)

**Comment by damithc** [comment]
Other things don't work too. e.g., can't load the code view. Need to locate the problematic PR and revert to quickly as all modules are using the latest version of RepoSense.

**Comment by gerhean** [comment]
This is a regression by #1421,
Ill try to fix by today.

**Comment by damithc** [comment]
> This is a regression by #1421,

@fzdy1914 can you revert the PR for the time being?

**Comment by damithc** [comment]
It doesn't seem to some dashboards though e.g., https://nus-tic4002-ay2021s2.github.io/ip-dashboard/

**Comment by fzdy1914** [comment]
@damithc, gerhean have identified the issue. I will merge his fix quickly.
