### ISSUE TITLE
Release for v1.13

### ISSUE THREAD

**Issue by HCY123902** [reposense/RepoSense#1470]
Let's make a release for v1.13. Please comment below and indicate the changes you think is necessary to be included in the release note. The current plan is to make a release up to the commit #1390, this is also to be discussed in the comment

# Documentation
* [v1.13 User Guide](https://reposense.org/ug/)

# Breaking Changes
 None

# New Features

## CLI and Behavioural Changes

* Add your changes here

## Code Panel

* Add your changes here

## Chart Panel

* Add your changes here

## Commits Panel

* Add your changes here

# UI Changes

## Documentation

*  The images for the summary view and authorship view architecture in the developer guide were replaced by puml diagrams.

## Chart Panel

* Add your changes here

## Code Panel

* Add your changes here

## Commits Panel

* Add your changes here

# Bug Fixes

## UI

* Add your changes here

## Non-UI

* Add your changes here

# Optimization

* Reduced the size of the commit and authorship summary Json file by using compact printing.

**Comment by HCY123902** [comment]
@reposense/21-22-active-developer Please indicate the changes that you think is appropriate to be included in the release note. Thanks

**Comment by damithc** [comment]
This doesn't need to be very elaborate though. See https://github.com/TEAMMATES/teammates/releases for an example.
I believe they auto-generate these release notes from the PR list. You can ask them for the script.

**Comment by HCY123902** [comment]
Thanks for the suggestion. I will take a look at it
