### ISSUE TITLE
Dashboard failing on CI after the new release

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1471]
v1.13

See https://github.com/nus-cs3281/2021-dashboard/runs/2072256241?check_suite_focus=true

**Comment by fzdy1914** [comment]
The most possible reason is that the JAVA file is not generated using JAVA 1.8.

**Comment by HCY123902** [comment]
Let me check immediately

**Comment by HCY123902** [comment]
@damithc Hello professor, I have updated the release. Can you try again to see if it works now on your side?
