### ISSUE TITLE
Allow disabling of the code panel for private repositories

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1479]
**What feature(s) would you like to see in RepoSense?**
There should be a way for users of RepoSense to disable access to the code panel for specific repositories. This is mainly intended for allowing RepoSense to generate a report for private repositories without disclosing the underlying code unintentionally.

**Is the feature request related to a problem?**
Currently, users are limited to using RepoSense for public repositories. Corporate entities would not be able to generate a RepoSense report for their internal projects, unless the users of the report are also authorised to view the code for those repositories. Individuals would also not be able to showcase their contributions to private repositories.

**If possible, describe the solution**
In the RepoSense report, the link to the code panel should be disabled and the code panel itself should not be generated in the final report. A potential mockup of how it looks like is as follows:

![image](https://user-images.githubusercontent.com/27919917/111064710-7e3ee280-84f0-11eb-91bb-7a0b809683e9.png)

This setting can be set on a repo-level or on the report-level.

**Comment by dcshzj** [comment]
Putting this task on hold unless there is significant interest in having this feature. On a side note, RepoSense should be tested to ensure that it actually works for private repositories when generating reports locally, and also that RepoSense works for other Git repository platforms such as GitLab and BitBucket.

**Comment by damithc** [comment]
> Putting this task on hold unless there is significant interest in having this feature. On a side note, RepoSense should be tested to ensure that it actually works for private repositories when generating reports locally, and also that RepoSense works for other Git repository platforms such as GitLab and BitBucket.

Yup, I think some may want to use RepoSense on Private repositories but I don't think many will want to publish the dashboard of such repos, even if we disable the code panel.

**Comment by damithc** [comment]
Let me close this for now, to keep the issue tracker clean. We can reopen it later.
