### ISSUE TITLE
Choosing language for reposense wizard backend. 

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1483]
Why we need a backend:

We decided that we do not want to prompt users for token.
However token is needed to modify any github repository.
We can use our own token but it must be used in the backend as it is unsafe to store tokens in the frontend.

Choosing language:

Nodejs (javascript):
The wizard is a small application so ideally it can be managed by 1 person working on both the front and backend. As frontend is done in javascript, there is a smaller learning curve.

Java:
Reposense is written in Java so those working on the main Reposense backend would have a smaller learning curve for maintaining this.

YML and shell script:
It's what github actions use, I don't know much about it though.

**Comment by damithc** [comment]
My vote is for Nodejs.

**Comment by dcshzj** [comment]
I'm curious how CATcher is able to do it without a backend it seems. The authentication logic is in [`src/app/core/services/auth.service.ts`](https://github.com/CATcher-org/CATcher/blob/ccd7754c215deec50b3ceff9474940a87930a4ba/src/app/core/services/auth.service.ts#L113-L127) and it looks like it is able to popup the OAuth page for the user to authorise the app.

If we are able to achieve something similar, we may not need a backend. Can we explore how they do this?

**Comment by damithc** [comment]
CATcher has a backend just for authentication. That part is hosted on DigitalOcean while the rest is hosted on github.io

**Comment by dcshzj** [comment]
@damithc Is CATcher hosted on a droplet? I was wondering if we can host it together with them, since the usage rate of the wizard should be very little and would be more cost efficient if the server was shared.

**Comment by damithc** [comment]
> @damithc Is CATcher hosted on a droplet? I was wondering if we can host it together with them, since the usage rate of the wizard should be very little and would be more cost efficient if the server was shared.

Yes, it's a free-tier account. No need to share costs -- in fact, best not to share as it can increase the usage beyond the free limit.

**Comment by dcshzj** [comment]
@gerhean I think let's go ahead with NodeJS as you suggested for authentication purposes. We will work out on how to deploy to DigitalOcean on another issue.
