### ISSUE TITLE
Error in connection between chart panel and code panel. 

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1485]
Can check the video below. 
1: The file-breakdown doesn't go away from the commits panel though the commit goes.
2: On restoring, the ramp appears first but the commits don't appear. 

https://user-images.githubusercontent.com/35946746/111701934-81322e00-8876-11eb-8e08-d61844cf85b9.mov

**Comment by gerhean** [comment]
Regression caused by #1390.
