### ISSUE TITLE
Move DevOps guide in the wiki to the developer guide

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1493]
The [DevOps guide](../wiki/DevOps-guide) in the wiki should be moved to a page of its own in the [RepoSense developer guide](https://reposense.org/dg/index.html).

This task is good for first timers to understand the workflow for contributing to RepoSense.

**Comment by damithc** [comment]
Related: When adding info to the DG, try not to mix info needed by developers at different levesl e.g., those needed by new/regular devs, those needed by senior devs, those needed by maintainers
