### ISSUE TITLE
Zoom inconsistent labels

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1498]
![image](https://user-images.githubusercontent.com/16630400/111968088-c33bc800-8b33-11eb-9751-3a3784596c95.png)

![image](https://user-images.githubusercontent.com/16630400/111968051-b9b26000-8b33-11eb-8474-5d9d8b11f551.png)

When I untick `tests`, the commit containing both `tests` and `backend` remain, but the label for `tests` disappears.

Even if this is intended behavior, I find it rather unintuitive. What do you think?

**If possible, include the URL to your RepoSense report or log files (if any).**
https://dashboard-1462-pr-reposense-reposense.surge.sh/

**Comment by damithc** [comment]
I don't think that is ideal. As long as the commit remains, the label should remain as well, or else it can be misleading, right?

**Comment by jbkim1999** [comment]
I agree with @damithc. I believe that CSVParser commit should still have test label in it.

Perhaps I can take on with this issue? :)

**Comment by chan-j-d** [comment]
@jbkim1999 Issue has been assigned to you
