### ISSUE TITLE
Declare props explicitly and give proptypes 

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1499]
**What feature(s) would you like to see in RepoSense?**

For props to be explicitly declared for every component, and for the proptype to be added.

**If possible, describe the solution**

Declare at the top like this:
![image](https://user-images.githubusercontent.com/16630400/112822578-b3376180-90ba-11eb-9090-4a68dbdc602b.png)

https://vuejs.org/v2/guide/components-props.html

**Comment by ckcherry23** [comment]
Hi, can I take this issue as a new contributor?

**Comment by dcshzj** [comment]
@ckcherry23 Sure, go ahead. Let us know if you encounter any issues!
