### ISSUE TITLE
Add a 'Learn the basics' section to the DG

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1500]
In https://reposense.org/dg/index.html , we can insert the following step (and a page to go with it).

>2\. **Learn the basics** of the background knowledge required to work in the RepoSense project

This step is to guide new developers on what basic tools/technologies they need to know to be able to work in RepoSense.
It can contain what to learn, in what order, which resources are recommended, and small tasks the reader can do to test their knowledge (e.g., modify a certain feature in RepoSense)

We don't expect the reader to learn everything in that page though. It depends on what they already know, what part of RepoSense they want to work on etc. They can also come back to this page later as they do PRs, to learn more.

**Comment by dcshzj** [comment]
Related issue: #1200
