### ISSUE TITLE
Unchecking breakdown by file type does not reset the file type boxes.

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1510]
**Tell us about your environment**

* **RepoSense Version:**
* **OS and Version:**
* **Web Browser and Version (if applicable):**

https://dashboard-1490-pr-reposense-reposense.surge.sh/

**Please include the steps to reproduce the bug.**

1. Check breakdown by file type
2. Uncheck `All`
3. Uncheck breakdown by file type
4. Open authorship tab
5. Check breakdown by file type

**What was expected to happen?**
![image](https://user-images.githubusercontent.com/16630400/112782268-333fd600-907f-11eb-8038-30e462013570.png)

**What actually happened? Please include a screenshot of the output.**

![image](https://user-images.githubusercontent.com/16630400/112782290-3e930180-907f-11eb-99e0-8508e39435d0.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by yhtMinceraft1010X** [comment]
Related to this issue, I noticed that if I were to open commits tab at step 4, all file type boxes in commits tab would be checked. 

On the other hand, opening the authorship tab at step 4 shows that none of the boxes in authorship tab would be checked.

I would like to try my hand at this issue.
