### ISSUE TITLE
run.sh: Support using a version at a specific commit

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1515]
See https://reposense.org/ug/runSh.html

Current: We can configure run.sh to use a specific tag (as long as there is a matching RepoSense release).

Suggested: Is it possible to support running RepoSense at a specific commit?

Reason: If the master branch breaks, we can use this feature to freeze run.sh at the commit immediately before the broken commit until we can use the latest tip of the branch again. Currently, we have to fall back on the released version which may be many commits behind the master branch.

**Comment by dcshzj** [comment]
Should be trivial to implement, as the `get_reposense.py` script already supports building the Jar file from source, although we will need to check if the commit exists first, similar to how the tags are checked. I'll propose a patch in a while.
