### ISSUE TITLE
Code view: make the glob filter input box wider

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1538]
![image](https://user-images.githubusercontent.com/1673303/114263140-73f00580-9a16-11eb-8a53-162a1550967c.png)

We can make this input text box wider as there is plenty of spare space here.

**Comment by sophiastr** [comment]
Hello, i want to deal with this issue.
Can i have it?

**Comment by Zhou-Jiahao-1998** [comment]
@sophiastr Thank you for your interest. We welcome any form of contribution!

You might want to checkout our [developer guide](https://reposense.org/RepoSense/dg/index.html) for more info on the basics. As this is a frontend issue, you might also want to check out the section on [frontend](https://reposense.org/RepoSense/dg/report.html). Hope this helps!

**Comment by Punpun1643** [comment]
Hi, is this issue still relevant? Would it be ok for me to work on this?

**Comment by chan-j-d** [comment]
@Punpun1643 You're welcome to work on the issue
