### ISSUE TITLE
Commits Panel: "Show ramp chart for this period" does nothing

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1543]
**Tell us about your environment**

* **RepoSense Version:** c176c03da990669634a7d725ec97e97bc6ec001b
* **OS and Version:** Windows 10 Build 19041
* **Web Browser and Version (if applicable):** Google Chrome 90.0.4430.93

**Please include the steps to reproduce the bug.**

1. Visit https://dashboard-1529-pr-reposense-reposense.surge.sh (preview dashboard for the commit above).
1. Click on Commits Panel for anyone.
1. Click on "[Show ramp chart for this period]" link near the top of the commits panel.

**What was expected to happen?**
Something is supposed to happen, although I am not entirely sure what. Based on the link text, some ramp chart should appear, but it is already present.

**What actually happened? Please include a screenshot of the output.**
The page does a very quick refresh but nothing visual changed.

**If possible, include the URL to your RepoSense report or log files (if any).**
https://dashboard-1529-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=zoom&zFR=false&zA=jamessspanggg&zR=reposense%2FRepoSense%5Bmaster%5D&zACS=99.28792569659443&zS=2017-10-09&zFS=&zU=2021-04-26&zMG=false&zFTF=commit&zFGS=groupByRepos&tabAuthor=jamessspanggg&tabRepo=reposense%2FRepoSense%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=tests~docs~frontend~backend&authorshipIsBinaryFileTypeChecked=false&until=2021-04-26

**Comment by gerhean** [comment]
What that link does is that it forces this:
![image](https://user-images.githubusercontent.com/16630400/117787547-22d36b80-b279-11eb-82bc-dd09109e6ffb.png)
to match with this: 
![image](https://user-images.githubusercontent.com/16630400/117787611-3252b480-b279-11eb-893e-4b708d32cb4d.png)

I have no idea why this exists however.

**Comment by gerhean** [comment]
Since it is just removing a feature, I think this can be a good first timer issue.

**Comment by damithc** [comment]
> Since it is just removing a feature, I think this can be a good first timer issue.

Yes, but need to trace back when the feature was added to find all relevant code and remove the feature _fully_. Just removing it from the front end is not enough.
