### ISSUE TITLE
Ubuntu CI failing with no backend code changes.

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1544]
**Tell us about your environment**

* **RepoSense Version:** PR #1527
* **OS and Version:** ubuntu-20.04 JDK 8
* **Web Browser and Version (if applicable):**

**What was expected to happen?**

Since I did not change any backend code (and lint passed), I expected the CI to pass.

**What actually happened? Please include a screenshot of the output.**

![image](https://user-images.githubusercontent.com/16630400/117525395-ad576900-aff4-11eb-8a3c-279bf61028eb.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by dcshzj** [comment]
Couldn't reproduce, probably a hiccup with GitHub Actions.
