### ISSUE TITLE
User trying to run RepoSense with private repos

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1545]
A user is trying to run RepoSense with private repos. He has tried running it against GitHub and against a local copy of the private repo, but failing in both. I'm waiting for more info from the user.
Meanwhile, should the above be possible with the current release version? Can do a trial to confirm?

**Comment by damithc** [comment]
@reposense/21-22-active-developer @reposense/stage-1-active-reviewer  any ideas?

**Comment by damithc** [comment]
Thanks for checking @gerhean  Will update here if I receive further info.

**Comment by gerhean** [comment]
(Windows) Confirmed that it can analyze online private repo if you can already access them from command line with git commands (or that running `git ls-remote https://github.com/username/reponame` shows that the repo can be accessed).

**Comment by chan-j-d** [comment]
I believe we can close this issue as the investigation some time back. Reposense works if users already have access to the repo via their own git commands.
