### ISSUE TITLE
Generating reports for local repos: relative paths don't work

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1546]
When generating a report for a local repository, the following cases don't seem to work.
* Relative paths
* Paths containing a space in them
* If there is a trailing `\` at the end

![image](https://user-images.githubusercontent.com/1673303/117763782-f4946280-b25d-11eb-8bb6-bc66b111318c.png)

**Comment by damithc** [comment]
Thanks for checking @gerhean Let's fix all three cases.
Is this of suitable difficulty for first-timers? Or perhaps break into three PRs?

**Comment by leongwaikay** [comment]
> * Relative path not working is as git does not seem to support it, solution is to convert relative path to absolute before passing to git.

Git definitely supports relative paths and trailing slash:
![image](https://user-images.githubusercontent.com/2689401/117824382-0519fc80-b2a1-11eb-8400-af083fb0e131.png)

**Comment by gerhean** [comment]
I guess I tested it wrongly, git works with relative paths but it bases itself on the top level of the current repository.

**Comment by chan-j-d** [comment]
Hi, is anyone handling this issue at the moment? Else I would like to attempt it.

**Comment by gerhean** [comment]
Seeing how there hasn't been any PR made for this issue for over a month, I believe that no one is currently tackling this issue

**Comment by chan-j-d** [comment]
Hi @damithc, for the case of the trailing '\' is there a sample execution which causes the issue? I have had difficulty replicating for that specific case as it seems to work fine on my computer when using the jar file of the current master branch. Works with quotes and without.

![image](https://user-images.githubusercontent.com/65345505/125813627-252214fc-2f6f-4bd4-a3c1-5e8839010c85.png)

**Comment by damithc** [comment]
> Hi @damithc, for the case of the trailing `\` is there a sample execution which causes the issue? I have had difficulty replicating for that specific case as it seems to work fine on my computer when using the jar file of the current master branch. Works with quotes and without.

Perhaps it is no longer a problem @chan-j-d You can ignore it if you can no longer reproduce it.
