### ISSUE TITLE
[Help Requested] Gradlew run failed with unexpected error

### ISSUE THREAD

**Issue by litone01** [reposense/RepoSense#1551]
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Window 10
* **Web Browser and Version (if applicable):** Chrome, but not applicable

**Please include the steps to reproduce the bug.**

0. Followed the 'setting up' guide, run 'gradlew clean build' and 'gradlew test systemtest' finished with message 'SUCCESSFUL'.
1. at project root,  enter 'gradlew run'

**What was expected to happen?**
1. A sample reposense report should be built successfully.

**What actually happened? Please include a screenshot of the output.**
1. Command prompt says built successfully, but when opening the summary.html generated, it says unexpected results happened.
2. A suspected cause is that "Branch nonExistentBranch does not exist in https://github.com/reposense/testrepo-Delta.git" and caused termination in analysis.

![image](https://user-images.githubusercontent.com/56266729/122630515-e5bf8c00-d0f6-11eb-8d7e-b74f8311bbaa.png)
![image](https://user-images.githubusercontent.com/56266729/122630525-f53ed500-d0f6-11eb-99a6-5918a4fb28d6.png)
![image](https://user-images.githubusercontent.com/56266729/122630551-23241980-d0f7-11eb-8869-a422064cae6d.png)

If I try to gradle run in intellij, 'Error: ftp://github.com/reposense/RepoSense.git is an invalid location.' appeared

![image](https://user-images.githubusercontent.com/56266729/122631078-641e2d00-d0fb-11eb-85e7-bd5148bfe0a2.png)

**If possible, include the URL to your RepoSense report or log files (if any).**
The link to the log file can be provided if that helps. Please let me know.

**A side note**
However, testing with the latest jar file released works and is able to generate the report.

**Comment by damithc** [comment]
> 2\. A suspected cause is that "Branch nonExistentBranch does not exist in https://github.com/reposense/testrepo-Delta.git" and caused termination in analysis.

I could be wrong but based on the log message, that error message seems to be expected i.e., a test case seems to be checking if RepoSense is able to detect if a config file specified a non-existent branch and give the appropriate error message.

So, the problem you are encountering is unlikely related to that error message shown in the log.

The `analysis terminated` refers to that repo only. The analysis of other repos should continue nevertheless. On a related note, we can refine that error message to state that only that repo is excluded from the analysis.

**Comment by litone01** [comment]
@damithc Thanks Prof. In this case, where should I look into further? Maybe the log file?

**Comment by damithc** [comment]
Glad to hear you sorted it out @litone01 👍
