### ISSUE TITLE
[Help Requested] No change after gradlew run despite change in files for front end

### ISSUE THREAD

**Issue by litone01** [reposense/RepoSense#1552]
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Window 10
* **Web Browser and Version (if applicable):** Chrome 91.0.4472.101

**Please include the steps to reproduce the bug.**

1. I was following the [learning the basics section for the front end part](https://reposense.org/RepoSense/dg/learningBasics.html). The first task about 'Highlight the selected author name in the summary view'. 
2. I followed the suggested solution and changed the v_summary.scss and summary_charts.pug file accordingly:
`  .active-user {
    color: mui-color('green');
  }`
`        .summary-chart__title--name(
          v-if="filterGroupSelection !== 'groupByAuthors'",
          v-bind:class="{ warn: user.name === '-', 'active-user': user.name === activeUser && user.repoName === activeRepo }"
        ) {{ user.displayName }} ({{ user.name }})
`
3. went to command prompt and entered `gradlew run -Dargs="--view"`
4. Also, tried `gradlew clean run -Dargs="--view"`or `gradlew clean build` and then `gradlew run -Dargs="--view"`.

**What was expected to happen?**
1. the changes are reflected since it has the correct logic and is the suggested solution

**What actually happened? Please include a screenshot of the output.**
1. Nothing happened, no change to the user display name and user.name
2. I tried to remove other parts such as, removing the background style when an user is selected  by removing the line 89 circled in the screenshot. However, the background style still persists. I tried to remove the v:bind of 'active-icon' for other buttons as well, and the same issue still persists.
![image](https://user-images.githubusercontent.com/56266729/122648710-ee4aad80-d15c-11eb-9d76-f0eed364141f.png)
3. Thanks so much and sorry for asking such fundemental questions!

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by litone01** [comment]
It may be linked to this issue https://github.com/reposense/RepoSense/issues/605, but no solution or cause provided.

**Comment by litone01** [comment]
[Update] it works now, and let me try to figure out what is the cause if I can.

**Comment by HCY123902** [comment]
I think when `./response-report` is used, the rendering will be based on the report that was built previously

**Comment by HCY123902** [comment]
![image](https://user-images.githubusercontent.com/54735123/123426723-57677080-d5f6-11eb-8090-67727e42fcda.png)
