### ISSUE TITLE
Update documentation website to use MarkBind v3

### ISSUE THREAD

**Issue by HCY123902** [reposense/RepoSense#1557]
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Windows10
* **Web Browser and Version (if applicable):** Edge

**Please include the steps to reproduce the bug.**

1. Open the Dev site of RepoSense at https://reposense.org/RepoSense/

**What was expected to happen?**

The rendered layout should be similar to the layout in the production site at https://reposense.org/

**What actually happened? Please include a screenshot of the output.**

![image](https://user-images.githubusercontent.com/54735123/124064975-6fad1480-da68-11eb-899e-8de9996e0c85.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by dcshzj** [comment]
This is likely due to the upgrading of MarkBind from v2 to v3, which requires changing the way we handle layouts. Marking as high priority as it breaks documentation previews.

**Comment by dcshzj** [comment]
A quick fix was applied in d40f71f66077c2c6b5b20f5090de7109bc478e6a, but we should move to MarkBind v3 once it is stable.

**Comment by damithc** [comment]
> A quick fix was applied in [d40f71f](https://github.com/reposense/RepoSense/commit/d40f71f66077c2c6b5b20f5090de7109bc478e6a), but we should move to MarkBind v3 once it is stable.

@dcshzj did the fix work?

**Comment by dcshzj** [comment]
@damithc The following line needs to be updated too:
https://github.com/reposense/RepoSense/blob/d40f71f66077c2c6b5b20f5090de7109bc478e6a/.github/workflows/integration.yml#L82

**Comment by damithc** [comment]
> @damithc The following line needs to be updated too:
> [RepoSense/.github/workflows/integration.yml](https://github.com/reposense/RepoSense/blob/d40f71f66077c2c6b5b20f5090de7109bc478e6a/.github/workflows/integration.yml#L82)

Did it just now.

**Comment by dcshzj** [comment]
@damithc You mentioned that MarkBind v3 is not stable yet, should we try to attempt this migration and provide feedback to the MarkBind team, or wait till say next year?

**Comment by damithc** [comment]
> @damithc You mentioned that MarkBind v3 is not stable yet, should we try to attempt this migration and provide feedback to the MarkBind team, or wait till say next year?

I'll do the migration soon (and provide feedback to the MarkBind team). Probably sometime in this month.
