### ISSUE TITLE
https://reposense.org outdated

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1560]
It looks like https://reposense.org/ was updated last in Jun 2020. That means it's not matching the current release version, right?

**Comment by HCY123902** [comment]
Yes, it has not been updated since release V1.12

**Comment by HCY123902** [comment]
Yes, it has not been updated since V1.12. I will try to make a documentation release this week

**Comment by damithc** [comment]
Thanks @HCY123902

**Comment by FH-30** [comment]
![Screen Shot 2021-08-10 at 12 00 29 AM](https://user-images.githubusercontent.com/61911161/128744416-d5e9113b-fa3e-42e3-9bac-6251695a0004.png)

Hi, just wondering if the lack of documentation for the git folder here is intended or is it because the UG is outdated as mentioned in this issue?

**Comment by HCY123902** [comment]
> ![Screen Shot 2021-08-10 at 12 00 29 AM](https://user-images.githubusercontent.com/61911161/128744416-d5e9113b-fa3e-42e3-9bac-6251695a0004.png)
> 
> Hi, just wondering if the lack of documentation for the git folder (ex: GitCatFile is not documented) here is intended or is it because the UG is outdated as mentioned in this issue?

Yes, this is created in #1449. I will adjust the documentation accordingly

**Comment by dcshzj** [comment]
The website still seems to be outdated even with the v2.0 release. @HCY123902 are you able to update the website?

**Comment by HCY123902** [comment]
> The website still seems to be outdated even with the v2.0 release. @HCY123902 are you able to update the website?

I have attempted to deploy the documentation, It seems that the changes cannot be pushed to /reposense with empty `baseUrl` in `site.json`. Let me create a corresponding issue on the Markbind side

**Comment by damithc** [comment]
@HCY123902 Are you following the instructions in https://reposense.org/dg/projectManagement.html#deploying-the-production-website ?

In particular, are you on the release branch? It has a slightly different site.json file

**Comment by HCY123902** [comment]
Yes, there is the `CNAME` pointing at `reposense.org` and the `filterTags` has been set to `production` in `site.json`, as is indicated in the deploy guide. However, the site is still deployed to `reposense.org/RepoSense`

**Comment by HCY123902** [comment]
Can I check who published the site in June last year?

**Comment by damithc** [comment]
> Can I check who published the site in June last year?

Looks like it was me :-p

@HCY123902 I think the site.json should be updated as follows (on the `release` branch):

```html
"deploy": {
    "message": "Site Update.",
    "repo": "https://github.com/reposense/reposense.github.io.git",
    "branch": "master"
  }
```

**Comment by HCY123902** [comment]
Oh I see. Can I get the push access to the repository?

**Comment by damithc** [comment]
> Oh I see. Can I get the push access to the repository?

Let me do it this time too, and figure out exactly how things need to change in the release branch. Will let you know.

**Comment by HCY123902** [comment]
Sure, no problem. According to https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site, the site deployed with the `gh-pages` branch in `RepoSense` seems to be a project site attached to the organization

![image](https://user-images.githubusercontent.com/54735123/135410131-3ede7591-f643-475e-a5c0-d1e20fd60503.png)

**Comment by damithc** [comment]
Guys, I think we need to do a new release first. The current release branch was last updated in Dec 2020, and hence, doesn't contain the MarkBind V3 compatible site that we migrated recently. We can update the main website after the release -- given it was showing an outdated version all this time, it can remain outdated for a few more days :-p
Can we do a new release soon?

**Comment by HCY123902** [comment]
> Guys, I think we need to do a new release first. The current release branch was last updated in Dec 2020, and hence, doesn't contain the MarkBind V3 compatible site that we migrated recently. We can update the main website after the release -- given it was showing an outdated version all this time, it can remain outdated for a few more days :-p Can we do a new release soon?

Actually, the release 2.0 already polished the latest documentation with MarkBind 3.0.6

![image](https://user-images.githubusercontent.com/54735123/135416320-4c571f6f-1105-4f91-a857-45fb3eb18a1d.png)

I will push the latest changes to the `release` branch separately today

**Comment by HCY123902** [comment]
> > Oh I see. Can I get the push access to the repository?
> 
> Let me do it this time too, and figure out exactly how things need to change in the release branch. Will let you know.

The release branch should match release version 2.0 now

**Comment by damithc** [comment]
@HCY123902 I've updated the production website and also pushed a commit to the release branch, to tweak the site.json to match the production website.
