### ISSUE TITLE
Allow forcing of a fresh repository close for some test cases

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1563]
As identified in #1562, #1478 introduced a regression that caused certain test cases that test the cloning mechanism to skip cloning entirely. One such example is `GitClone.java` and the two system tests, `testSinceBeginningDateRangeWithShallowCloning` and `test30DaysFromUntilDateWithShallowCloning`, which handles shadow cloning.

There should be a mechanism for individual tests to specify if they wish to obtain a fresh clone of a repository, and to also ensure that it does not affect subsequent tests on the same repository.

**Comment by aidoxe-123** [comment]
Can I work on this?

**Comment by dcshzj** [comment]
Sure! Let us know if you need any assistance.
