### ISSUE TITLE
Analysis incorrectly identifies valid file path as invalid

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1571]
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Windows 10
* **Web Browser and Version (if applicable):** N.A.

**Please include the steps to reproduce the bug.**

1. Run program on intellij with the following CLI arguments `--repos https://github.com/reposense/RepoSense.git --since 31/12/2018`

**What was expected to happen?**
Analysis completed without issue and report is generated.

**What actually happened? Please include a screenshot of the output.**
Analysis identifies two files as invalid file paths ignores them and proceeds to generate the report.
![image](https://user-images.githubusercontent.com/65345505/126543961-812f4786-c5b1-4b69-861d-90575d983621.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by chan-j-d** [comment]
On further investigation, the exception is thrown in the method `FileUtil::isValidPath`. The point where the error occurs seems to be from 
https://github.com/reposense/RepoSense/blob/6b94f82545bbd84852f7bd110af72e495ad23652/src/main/java/reposense/authorship/FileInfoExtractor.java#L104-L121

where the regex matching seems to cause additional spaces to be added to the end of the file path causing it to no longer be valid. 

I believe most files are actually validated twice in the same `FileInfoExtractor::getEditedFileInfos` method, once in the use of the `getFiles` method and the `isValidTextFile` method. However, the two files above actually pass the first validation and only fail on the second likely due to some issue with the pattern matching.

**Comment by chan-j-d** [comment]
Upon further investigation, it seems the regex as is works fine and it is the git diff output that has peculiar behaviour. 

Image below is the git diff output placed into a text file. 
![image](https://user-images.githubusercontent.com/65345505/126967459-7117c844-1462-4509-9b25-c8581a691ef3.png)

The file at the bottom contains spaces and as a result has a tab (`\t`) character at the end. I further investigated if a solution like removing the tab at the end would work since Linux does allow tab characters in filenames. It seems with tabs (and possibly other control characters), the filename becomes wrapped in quotation marks. 

If the filename has both a tab and space then the tab character at the end is added after the quotation marks.

Would like to know if anyone else does encounter the same problem and if this issue is worth fixing.

**Comment by damithc** [comment]
@chan-j-d what's the impact of this issue on users/devs?

**Comment by chan-j-d** [comment]
For users of reposense, all files within a repo that contains a space will be skipped over. I believe in theory, control characters (like tab) in filenames would cause a similar problem.

**Comment by damithc** [comment]
> For users of reposense, all files within a repo that contains a space will be skipped over. I believe in theory, control characters (like tab) in filenames would cause a similar problem though this latter case seems very unlikely.

If this is indeed the case, this is a serious problem that need to be fixed as having a space in the _middle_ of a file/folder name is legit and even a common practice.

@chan-j-d However, check if the problem applies to trailing/leading spaces only, as the examples you have given have trailing spaces in the file name, which is not a common practice. If that is the case, the problem is not severe as such spaces are most likely a user mistake.

**Comment by damithc** [comment]
Thanks for the investigation @chan-j-d 
In that case, it's a severe problem and we need to fix it, even if it is less common to use spaces in names of files containing source code.

**Comment by FH-30** [comment]
Hi @chan-j-d and @damithc , I tried running RepoSense with ```--repos https://github.com/reposense/RepoSense.git --since 31/12/2018``` as the CLI Argument but I did not come across the same issue. As shown here:

![Screen Shot 2021-07-27 at 5 21 13 PM](https://user-images.githubusercontent.com/61911161/127129875-78aab91a-935d-4242-8a80-b17832518ae3.png)
 
I'm not sure if its Operating System related. I am using MacOS whereas @chan-j-d appears to be using Windows

**Comment by chan-j-d** [comment]
@FH-30 My windows runs git on `2.31.1.windows.1`. I have also run `git diff` on ubuntu 18.04 with git version 2.17.1 where the additional tab character also appears, though I have not tried running Reposense on it specifically. 

Would be nice to have some confirmation that others are also facing the same issue with windows or linux

**Comment by FH-30** [comment]
If git diff happens to have spaces and tab characters in both OSes but it can work in Ubuntu but not in Windows, I guess the problem is not with git diff then?

**Comment by chan-j-d** [comment]
It appears that `git diff` still is the problem with the additional tab character. On Ubuntu and mac, the `\t` is a valid character in file paths so the validity check in `FileUtil::isValidFile` passes since it uses `Paths.get()` which only checks if the given string can be converted into a path and not if the path exists. On windows however, it does check if the char is valid, causing it to fail here with an exception thrown:
![image](https://user-images.githubusercontent.com/65345505/127152208-010f6f95-1f5d-43c5-be8d-b96598b918a0.png)
Image taken from `WindowsPathParser` that `Paths.get()` uses in debug mode with the same arguments as the OP.

Ubuntu and Mac are able to convert the string into a path object but it is not the same path that is in the repository since it has the extra tab character. So it is ignored __without warning__. Relevant segment of code:
https://github.com/reposense/RepoSense/blob/6b94f82545bbd84852f7bd110af72e495ad23652/src/main/java/reposense/authorship/FileInfoExtractor.java#L119-L121


When running RepoSense with the arguments `--repos https://github.com/reposense/RepoSense.git --since 31/12/2018 -i` on Ubuntu 18.04, it generates the report with no warning. On viewing the report, I see this:
![image](https://user-images.githubusercontent.com/65345505/127153560-26aff7b3-0a0e-4550-bcdf-436b1675fda5.png)
The 4 lines are correct as 4 `.txt` file lines were changed in that commit but only 2 are attributed to me because 2 files fail without warning (and the above methods are within the `authorship` package.

When running the same arguments again but with change in backend code to have the added `\t` char removed, the lines reflected under my name becomes accurate.
![image](https://user-images.githubusercontent.com/65345505/127153677-ccd4e68d-2b0c-4812-a158-58741bb442d8.png)

So in fact the `git diff` is still the problem, but ubuntu and macs overlook it.

**Comment by FH-30** [comment]
@chan-j-d I can double confirm that you are correct! Since you seem to have come up with a fix based on slack, I'll leave the rest to you.
