### ISSUE TITLE
Remote repos: allow different types of URLs besides the `http`s `github` type

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1572]
**What feature(s) would you like to see in RepoSense?**

Allow for Reposense to accept Git URLs other than the `https` `github` one. Idea originates from the following comment https://github.com/reposense/RepoSense/issues/1546#issuecomment-838572658.

**Is the feature request related to a problem?**

N.A.

**If possible, describe the solution**

We can remove the location verification performed. There are also several places where a regex match with the `https` `github` url is used to identify repo name and organisation which would also need to be updated. In particular, the differentiation of local and remote repo is done with the above regex matching. Instead, GIT URLs mostly have a standard form as described in https://git-scm.com/docs/git-clone#_git_urls which would allow us to differentiate them. 
> This syntax is only recognized if there are no slashes before the first colon. This helps differentiate a local path that contains a colon.

A sample [PR](https://github.com/chan-j-d/RepoSense/pull/3) with some code changes to demonstrate the feasibility of such a change. Passes all test cases except those directly tied to the existing location verification (which are removed in the PR).

**If applicable, describe alternatives you've considered**

**Additional context**

**Comment by damithc** [comment]
No objections from me but I'd like to hear from the dev team too. @reposense/active-devs
