### ISSUE TITLE
SE Principle: Catch Non PR commits and flag them against the contributors of the analyzed repositories

### ISSUE THREAD

**Issue by FH-30** [reposense/RepoSense#1573]
**What feature(s) would you like to see in RepoSense?**

Allow for RepoSense to catch commits that didn't go through a pull request. Idea originated from the PR I worked on for phase 2 of IWM and the fact that such commits do not adhere to good software engineering principles.

**Is the feature request related to a problem?**

N.A.

**If possible, describe the solution**

In the PR I made for Phase 2 [here](https://github.com/FH-30/RepoSense/pull/1), I implemented it by querying from a URL (repository URL + ```"/branch_commits/"``` + the commit hash) that Github itself utilizes to check whether a certain commit is linked to a PR (I found it through playing around in the developer tools). However, I feel this solution might not work if Github makes any changes to how they query from their API. I also did not test this solution on a large scale and I am not sure whether large amounts of requests concurrently from a certain IP address will make Github block access to that API (A Denial of Service prevention measure).

**If applicable, describe alternatives you've considered**

There are two alternatives I have came across:
* We can use the official Github API [here](https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests#search-by-commit-sha).

* An NPM package called ```Oktokit/rest``` that provides an api call for this [here](https://octokit.github.io/rest.js/v18#repos-list-pull-requests-associated-with-commit). However, I am not sure if a Java Backend can work with this package. 

I have yet to check if these two solutions require a certain workflow (ex: OAUTH) to access the APIs. They might also have rate limits (therefore requiring to subscribe).

**Additional context**

**Comment by damithc** [comment]
Interesting idea @FH-30 Didn't occur this feature to me before. My reservations:
* We want RepoSense to be independent of GitHub so that it can be used with other tools
* We don't want RepoSense to be prescriptive of a certain process. While most OSS projects use a PR-based workflow, that doesn't mean that is better than other workflows or it is 'wrong' to push commit outside of a PR
* Also note that GitHub API require authentication and there are quota/throttling constraints -- that's why we've been avoiding it until now

**Comment by FH-30** [comment]
Thanks for the insights prof, so I guess I'll close the issue?

**Comment by damithc** [comment]
> Thanks for the insights prof, so I guess I'll close the issue?

Yup. I'm closing it for now. We can reopen if we decide to go in this direction in the future.
