### ISSUE TITLE
Investigate occasionally failing test when running system tests on Github CI Ubuntu 18.04

### ISSUE THREAD

**Issue by FH-30** [reposense/RepoSense#1588]
**Tell us about your environment**

* **RepoSense Version:** Most recent commit hash `387401fa99f8cdb5db65938e4e3e5aa82c85d38c` (Not yet part of official release)
* **OS and Version:** MacOS Big Sur 11.5.2 (Bug does not appear in this environment)
* **Web Browser and Version (if applicable):** NA

**Please include the steps to reproduce the bug.**

1. Make a PR to the master branch (Assuming you already have pulled the latest changes till commit hash `387401fa99f8cdb5db65938e4e3e5aa82c85d38c`)
2. Observe that usually on the first ubuntu 18.04 Github CI run it fails, however the error disappears whenever tests are rerun.

**What was expected to happen?**
Ubuntu 18.04 tests should have passed deterministically, not succeeding and failing on different runs.

**What actually happened? Please include a screenshot of the output.**
The possible error thrown:
![](https://user-images.githubusercontent.com/58925632/132934649-8f673f44-2a9c-4cc3-8045-4ffeef501393.png)
![Screenshot 2021-09-13 at 6 36 11 PM](https://user-images.githubusercontent.com/61911161/133069385-d27be7c5-65bb-4b76-be21-1ee4598804fc.png)

Notice here that the one on top fails with testrepo-Delta and in another run below it failed with testrepo-Charlie making it difficult to debug.

Observe that the both errors originates from parsing of date in ```analyzeCommit()``` method of ```CommitInfoAnalyzer.java```

**If possible, include the URL to your RepoSense report or log files (if any).**
[Failing run for testrepo-Charlie on Ubuntu 18.04](https://github.com/reposense/RepoSense/pull/1565/checks?check_run_id=3522077832)
[Failing run for testrepo-Delta on Ubuntu 18.04](https://github.com/reposense/RepoSense/pull/1570/checks?sha=744206197ee2eaafe87e0e8894d5ba62158e0242)

**Comment by FH-30** [comment]
This issue might potentially be because of how RepoSense employs concurrent cloning making the behaviour a bit unpredictable, it will be best if someone with an Ubuntu 18.04 device can look into this.

**Comment by dcshzj** [comment]
I am closing this as it is part of #1601 where most of the discussion lives.
