### ISSUE TITLE
Omit percentile if the list is sorted alphabetically

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1591]
This percentile is meaningless and potentially confusing to the viewer when the list is sorted alphabetically.

![image](https://user-images.githubusercontent.com/1673303/134794571-f0d68178-0dd7-4d5a-b7e0-92f2756505da.png)

Suggested: omit it if the list is sorted by title

**Comment by gerhean** [comment]
Actually I'm not very sure of why the percentile is even there for in the first place.

From what I have seen it is just the index of the repo in the list divided by number of repos, which is mostly useless since you can already easily gauge which index you are at by looking at scroll bar.

**Comment by dcshzj** [comment]
It was originally introduced in #922 which I understand is to help in the grading.

**Comment by gerhean** [comment]
In that case I think it's better to just leave it for consistency, since it would be even more confusing to have a number which only appears there sometimes for a seemingly arbitrary reason (It's not obvious to anyone who isn't grading what this number is for).

**Comment by damithc** [comment]
It is not a major feature; just to easily find things such as _what is the 20th percentile of LoC contribution_. It only matters when the list is sorted by a quantitative criterion. In fact the only time I use it is when the sorting is done by the contribution. Perhaps we show it only when sorted by contribution?
