### ISSUE TITLE
Omit 'ignore globs' files from processing

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1594]
This dashboard takes about 9 minutes, whereas it should take about 3-4 minutes only.
I suspect it is because one team has included a 9K data files https://github.com/AY2122S1-CS2113T-W12-2/tp/tree/master/data
However, even after I add `/data/**` to the 'Ignore globs' of that repo (in repo-config.csv), it still takes 9 minutes. So, I suspect even ignored files undergo heavy processing at first and are omitted only later in the processing pipeline. 
Is that the case?
If so, is it possible to omit them from processing earlier?

**Comment by lawwm** [comment]
I will be looking into this.
