### ISSUE TITLE
Dev Guide: Tweak documentation of doing a release

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1595]
Suggested tweaks to documentation:
* Before doing a release, merge master to the release branch, and do the release using the release branch rather than the master branch.
* Use a merge commit for the above, so that we have a visual history of releases 

We can also document the procedure for hot-patching a past release
1. PR against the release branch
2. Merge the PR, and release a new version (using the release branch)
3. Merge the release branch back to the master branch

The above is what we do in some of the other NUS-OSS projects, but I'm open to other suggestions.

**Comment by HCY123902** [comment]
I agree with the hot patching process. Let me create a pull request for this

**Comment by HCY123902** [comment]
> Suggested tweaks to documentation:
> 
> * Before doing a release, merge master to the release branch, and do the release using the release branch rather than the master branch.
> * Use a merge commit for the above, so that we have a visual history of releases
> 
> We can also document the procedure for hot-patching a past release
> 
> 1. PR against the release branch
> 2. Merge the PR, and release a new version (using the release branch)
> 3. Merge the release branch back to the master branch
> 
> The above is what we do in some of the other NUS-OSS projects, but I'm open to other suggestions.

Is there a need to create a separate pull request to merge the release branch back to the master branch? It is usually not possible to merge directly

**Comment by damithc** [comment]
> Is there a need to create a separate pull request to merge the release branch back to the master branch? It is usually not possible to merge directly

Yes, I guess so (because the master branch is protected).
