### ISSUE TITLE
Duplicate error message for missing repos

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1597]
Each error is shown twice:
![image](https://user-images.githubusercontent.com/1673303/136682644-daab28b3-0db8-4619-a3ef-778daf1c9f39.png)

https://nus-tic2002-2021.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt&since=2021-08-09

Settings:

https://github.com/nus-tic2002-2021/ip-dashboard

**Comment by gerhean** [comment]
Multiple error as the problem repo is listed in both `author-config.csv` and `repo-config.csv` and Reposense does not really record down problematic repos to skip.

Solution is probably to remove duplicates in error message list before writing to json
