### ISSUE TITLE
ubuntu-16.04 JDK 8 checks are missing

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1606]
**Tell us about your environment**

* **RepoSense Version:**
* **OS and Version:**
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

Just push a PR

**What was expected to happen?**

Github workflow checks run

**What actually happened? Please include a screenshot of the output.**

![image](https://user-images.githubusercontent.com/16630400/145679776-8e7c81cb-df16-42cd-ba81-f61d53940311.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by dcshzj** [comment]
This was [removed as a possible image](https://github.com/actions/virtual-environments/pull/4336) on 16 October 2021. Let me remove that option from the workflow file.
