### ISSUE TITLE
Github action deployments are not working

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1607]
**Tell us about your environment**

* **RepoSense Version:**
* **OS and Version:**
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

Check any recent PR

**What was expected to happen?**

The changes are deployed to surge.

**What actually happened? Please include a screenshot of the output.**

![image](https://user-images.githubusercontent.com/16630400/145680113-e0795d7e-967a-45f5-945b-956f0fbfca3f.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by dcshzj** [comment]
This is a side effect of #1606, as the deployments will not happen if there are any jobs that failed along the way.
