### ISSUE TITLE
Refactor file validation method in GitLsTree

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1619]
**Currently**: `GitLsTree` contains only one public method, `validateFilePaths` and two private methods. Of the two private methods, only one of them uses a Git command directly.

**Suggestion**: Move the `validateFilePaths` and `isValidWindowsFilename` methods to `FileUtil` and change the method `getFilePaths` (that uses the `git ls-tree` command) to `public`. 

This would put the `GitLsTree` class more in-line with the other git classes which contain methods mainly to run a specific git command. At the moment, the current method `validateFilePaths` performs verification on all the files in the repository and throws an exception if any of the files contains an invalid filename for Windows computers. I believe that the logic on how to verify and what actions to perform if a file fails verification should not be located in the Git class itself.

**Comment by chan-j-d** [comment]
@dcshzj Seeking approval for this refactoring suggestion. Thanks!

**Comment by dcshzj** [comment]
This sounds like a good idea to do, feel free to perform this refactoring!

**Comment by chan-j-d** [comment]
While working on #1616, I'm not entirely sure if the validation method for Windows filenames is still necessary. The `validateFilePaths` method is currently only used once in a line of code that I am suggesting to be removed in PR #1628. 

Additionally, perhaps a better way to implement it would be to use Java's `Paths.get(...)` which already performs an identical series of check by checking OS and then valid filenames. I believe it would be better to piggyback off their implementation and use the already available `FileUtil::isValidPath` which does largely the same functionality.
