### ISSUE TITLE
Upgrade highlight.js to version 11

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1622]
The highlight.js package used by the frontend is currently using version 10.7.3, which is [no longer supported](https://github.com/highlightjs/highlight.js/blob/main/SECURITY.md). The package should be upgraded to version 11 by following [the upgrading guide](https://github.com/highlightjs/highlight.js/blob/main/VERSION_11_UPGRADE.md).

**Comment by Zhou-Jiahao-1998** [comment]
@dcshzj I am not too sure if I am doing it correctly. After upgrading to version 11, everything seems to work fine. All the test passed and there are no errors in the project. Is that normal?

**Comment by gerhean** [comment]
Usually nothing breaks when package is upgraded to be honest.

**Comment by gerhean** [comment]
Want to close this in favor of #1633.

**Comment by dcshzj** [comment]
> Want to close this in favor of #1633.

Yup, let's do that.
