### ISSUE TITLE
Propose moving bottom "Generated by" statement to top

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1624]
**What feature(s) would you like to see in RepoSense?**

The URLs for the RepoSense webpage, version and user guide are currently at the bottom of the report page. I propose moving these links and the bottom "Generated by..." statement to the top along with the report settings.

**Is the feature request related to a problem?**

For large reports with many repositories, it may be tedious to scroll all the way down to the bottom to access these links. It would be more convenient for users to access all the general features of the report at the top and scroll down only when they need to access a specific repository. This also helps when debugging since version checking can be done more easily.

**Additional context**

This might be a useful issue for first-timers.

**Comment by damithc** [comment]
hmm... this kind of info usually belongs in a footer? They have no functional value to the user (except perhaps the link to the UG) -- so, not sure we should use prime screen real estate on them at the top of the report.

**Comment by gerhean** [comment]
Can confirm that I have never ever clicked on the "generated by" link. The generation date is also not really important to end users since the filter clearly states the "until" date.

**Comment by dcshzj** [comment]
I have to agree that this information is usually only relevant for debugging, and a user of the report should not be concerned about the version that they use. I think this information should remain at the bottom of the report where it currently is.

**Comment by gerhean** [comment]
Can we close this issue?

**Comment by yhtMinceraft1010X** [comment]
Closing since the consensus is to keep the statement at the bottom of the page.
