### ISSUE TITLE
Gradle lint duplicate dependency

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1626]
**Tell us about your environment**

* **RepoSense Version:**
Master branch

* **OS and Version:**
Github actions

* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/RepoSense/RepoSense/build.gradle' line: 14

* What went wrong:
Plugin with id 'com.palantir.git-version' was already requested at line 12
```

As detected with #1096

**If possible, include the URL to your RepoSense report or log files (if any).**

https://github.com/reposense/RepoSense/runs/4906908212?check_suite_focus=true

**Comment by dcshzj** [comment]
The issue is in #1096 itself and not in the master branch, the PR added a duplicate line.
