### ISSUE TITLE
Replace cdn links to import from `node_modules` instead

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1634]
**What feature(s) would you like to see in RepoSense?**
Replace [this](https://github.com/reposense/RepoSense/blob/c4d7690e7b2c3b2626187a2c26ee447d99adf15a/frontend/src/app.vue#L317-L322) with `node_module` imports

**Is the feature request related to a problem?**

Dependabot can track outdated packages in `package-lock.json` files, but not if they are imported directly in the code. Furthermore, it would be good if the frontend only had a 'single source of truth' for all externally imported packages, making the project easier to manage.

**Comment by Zhou-Jiahao-1998** [comment]
@gerhean Looking at [normalize.css@8.0](https://classic.yarnpkg.com/en/package/normalize.css), it seems like it is not reviving any updates. After removing the import, the visual changes are insignificant. Do you think we can simply remove this import?

**Comment by gerhean** [comment]
@Zhou-Jiahao-1998 may I know what insignificant visual changes they are?

**Comment by Zhou-Jiahao-1998** [comment]
![Screenshot 2022-03-07 at 11 38 42](https://user-images.githubusercontent.com/54730603/156964139-66557725-1550-482f-b0cb-f4fa0591df77.png)
![Screenshot 2022-03-07 at 11 40 10](https://user-images.githubusercontent.com/54730603/156964152-15595c71-6b27-4bcd-82ce-46e185e20898.png)
The middle line is slightly thicker and the + icon in the code is more centred.

**Comment by gerhean** [comment]
@Zhou-Jiahao-1998 actually let's leave it in so that web pages styles behave and look consistent across web browsers. As described [here](https://jeffry.in/normalize-css-or-not/).

**Comment by Zhou-Jiahao-1998** [comment]
@gerhean Alright! I am looking into this issue now while Vue 3 upgrade is in progress.
