### ISSUE TITLE
Multiple local paths with the same final directory causes one report to overwrite others

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1637]
**Tell us about your environment**

* **RepoSense Version:** master branch
* **OS and Version:** Windows 10
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

1. Run `git clone https://github.com/chan-j-d/ip.git parent1/same-name`
2. Run `git clone https://github.com/chan-j-d/tp.git parent2/same-name`
1. Run `java -jar RepoSense.jar --repos parent1/same-name parent2/same-name --since 01/06/2020 --view`

**What was expected to happen?**
Both repositories are analyzed and displayed.

**What actually happened? Please include a screenshot of the output.**
![image](https://user-images.githubusercontent.com/65345505/151711992-8a26eeff-896a-4c7e-9768-6a0438e653bd.png)

The repo name is defaulted to the parent directory name of the `.git` folder which both have the same name. As such, the reports are both generated in the same folder `same-name_master`. It could be that one report overwrites the other or the existing report prevents another report form being written. Regardless, only one report is generated. 

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by damithc** [comment]
Thanks for catching this @chan-j-d 
Might cause issues for cases where we are dealing with forks of the same upstream repo, as they could all have the same folder name locally.
Lets fix this soon.

**Comment by chan-j-d** [comment]
Changing priority as this should have been fixed together with #1644 as a consequence of the generalized naming system used in the PR that resolves this issue. I think the issue can be properly closed once #1746 is merged for system tests catering to this scenario to prevent regression.
