### ISSUE TITLE
Wrongly scaled contribution bar when contribution is significantly lower than average

### ISSUE THREAD

**Issue by gok99** [reposense/RepoSense#1638]
**Tell us about your environment**

* **RepoSense Version:** c4d7690
* **OS and Version:** Fedora 34
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

1. Generate reposense report for https://github.com/cheeaun/sgbusdata.git since 01/01/2021

**What was expected to happen?**

Correct report with appropriately scaled contribution bars

**What actually happened? Please include a screenshot of the output.**

Committer with only a 1 line diff has the longest contribution bar when the average contribution is 1547905 lines.

![image](https://user-images.githubusercontent.com/34594184/151713508-fff51035-8081-4301-9e27-4c1131e459a4.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

https://sneaky-toes.surge.sh

**Comment by damithc** [comment]
Looks like a serious bug. Thanks for catching it @gok99 How often can this occur?

**Comment by gok99** [comment]
@damithc The bug occurs when a committer's contributions are low enough that Javascript represents the ratio of their contributions to the average in scientific notation (e.g. `3.2301723943006836e-7`). 

Javascript seems to start doing this only at 10^-7, so I suspect this will only happen in large enough repositories with contributors who make small changes (which seems quite likely in big open source projects), or when contributors temporarily use a different git user profile (as was the case in the repository I used).

**Comment by damithc** [comment]
Thanks for the investigation @gok99 Yes, looks like rare to happen. We should fix it nevertheless, as it still _can_ happen.
