### ISSUE TITLE
Change how `ConfigSystemTest` is done by using `RepoSense::main`

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1645]
**What change(s) would you like to see in RepoSense?**

Change how system tests are run by using the `RepoSense::main` method to provide full end-to-end validation through supplying CLI arguments and comparing the output JSON files. 

**Is the feature request related to a problem?**
Adding new system tests can be difficult as the existing methods use the config files in the `resources` folder by default. This makes it difficult to perform tests on more specific scenarios such as using a new config file to test against a specific branch of a specific repo only. 

The current setup with the [`ConfigSystemTest::generateReport` method](https://github.com/reposense/RepoSense/blob/731a268e7eeee66b8894fecccea4fc0c27b50465/src/systemtest/java/reposense/ConfigSystemTest.java#L152) also bypasses the parsing of the original CLI arguments and setting up of `RepoConfiguration`s. If the `main` method is changed, then this method would also have to be changed with it. I believe it would be beneficial to use `RepoSense::main` instead for the full end-to-end validation. 

Setting up test cases would then be similar to specifying the exact CLI arguments that we would normally run against the RepoSense.jar file. 

**If possible, describe the solution**
Rewrite the `runTest` method similar to something in this experimental PR [here](https://github.com/chan-j-d/RepoSense/blob/testing-systemtest-refactoring/src/systemtest/java/reposense/ConfigSystemTest.java#L90). Only one test case has been rewritten here to be as similar to the original as possible. The output for the authorship files are not exactly the same as the one used currently and I have not been able to replicate it properly using only the CLI arguments. 

**Additional context**

_Immediate drawbacks_
- The current implementation of RepoSense with this change will be unable to avoid multiple repeated cloning of the same few repositories for system test. One possible way to overcome this is to leave one test that performs clone and delete. For other tests, a copy of the remote repo is cloned locally and the tests are performed against the local copies instead.
- There are some parameters such as `shallowCloning` and `findPreviousAuthors` that still have to be passed to the `runTest` method as they directly affect the behaviour of the test case. 
- The time generated for the report summary would be different from the expected JSON files. Some sort of bypass is needed to compare the summary JSON files while ignoring the time the report is generated.

**Comment by SkyBlaise99** [comment]
@chan-j-d, I think this can be done using `InputBuilder`. I realise that in `generateReport()`, these 2 are handled by

``` java
if (shallowCloning) {
    inputBuilder = inputBuilder.addShallowCloning();
}
if (findPreviousAuthors) {
    inputBuilder = inputBuilder.addFindPreviousAuthors();
}
```

I believe the same can be done for the other variables. Namely `TEST_REPORT_GENERATION_TIME` and `shouldFreshClone` can be included into `ArgsParser`. Perhaps we can specify a `Test Mode Flag` in `ArgsParser` which is used for this senario.

**Comment by SkyBlaise99** [comment]
@chan-j-d can I try this issue? My idea is to add new flags into `ArgsParser`, like a `-T` test flag etc, and make `main` react differently, but minimally, when this flag is found.

**Comment by chan-j-d** [comment]
I'm not too sure I understand the approach you're taking. Drawback 3 has been somewhat addressed in this PR https://github.com/reposense/RepoSense/pull/1746. I think that PR was the main direction I had in mind where we construct tests in the form of CLI command arguments and just pass it into `main` instead of doing part of the parsing and config setting in the system test class. 

You could share your implementation branch and I could take a look. If possible, I'd prefer not to add a flag just for testing to production code though you might have thought of something to make it work.

**Comment by SkyBlaise99** [comment]
A new flag is definitely required for `shouldFreshClone` though

**Comment by SkyBlaise99** [comment]
@chan-j-d you can take a look at PR #1816 I just made.
