### ISSUE TITLE
Duplicated method in GitRevList.java

### ISSUE THREAD

**Issue by gok99** [reposense/RepoSense#1655]
**Currently**

`getCommitHashBeforeDate` and `getCommitHashUntilDate` in `GitRevList` have identical logic. This can be confusing for readers who are deciding between the methods to use. It is also easy to forget to update one of the methods because it's not immediately obvious that they do the same thing.

https://github.com/reposense/RepoSense/blob/728a9f9c14f706ace6873cae8696647b91ff3ffb/src/main/java/reposense/git/GitRevList.java#L19-L47

https://github.com/reposense/RepoSense/blob/728a9f9c14f706ace6873cae8696647b91ff3ffb/src/main/java/reposense/git/GitUtil.java#L27-L28

**Proposed Suggestion**

If there is no reason to keep the duplicated methods, perhaps we could remove one of them. `getCommitHashBeforeDate` seems to be a better description of what the methods are doing.

**Comment by chan-j-d** [comment]
Seems like according to the specification at https://git-scm.com/docs/git-rev-list#Documentation/git-rev-list.txt---untilltdategt, there are actually two flags that do the same thing as seen in the image below
![image](https://user-images.githubusercontent.com/65345505/153691741-7cc68837-9b44-4e26-a1e1-80d4c167a0d5.png).

I think we should actually retain the `UntilDate` one and actually replace the flag with the `--until` flag to be in line with a similar `--until` flag we use for RepoSense.

**Comment by gok99** [comment]
Thanks for taking a look at this! It seems then that `getCommitHashBeforeDate` is using the wrong flag value semantically. 

> I think we should actually retain the UntilDate one and actually replace the flag with the --until flag to be in line with a similar --until flag we use for RepoSense.

I agree with this. We can retain both date formats, and `getCommitHashUntilDate` can actually use the `--until` flag in the command.

**Comment by gok99** [comment]
@dcshzj I'll proceed to do this refactor if it makes sense.

**Comment by dcshzj** [comment]
Sorry @gok99 I missed out this one. Do you mean that you wish to replace the `--before` flag with the `--until` flag in `getCommitHashUntilDate`, and no other changes are to be made?

**Comment by gok99** [comment]
@dcshzj This will also remove `getCommitHashBeforeDate`, replacing all references to it with `getCommitHashUntilDate`.

**Comment by dcshzj** [comment]
I see, yes I think you should proceed with this proposed refactoring.
