### ISSUE TITLE
Backend tampering with frontend build files  

### ISSUE THREAD

**Issue by gok99** [reposense/RepoSense#1659]
**Currently:**

In ReportGenerator.java, the backend makes edits to the content of index.html generated by the frontend (for changing the title of the generated report). This breaks the separation of responsibility of the files generated by the frontend and backend. Even if only the title is being modified, there can arise hard-to-catch bugs like the one fixed in #1656. `index.html` is also not included in systemtests despite being modified by the backend, which is likely why the issue slipped through.

**Possible Solution:**

The value of `reportTitle` is currently stored in `summary.json` generated by the backend. The report title can be dynamically modified by the frontend after loading `summary.json`, so that the backend will not have to touch `index.html`. This is likely to cause a negligible but noticeable delay before the title of the report is corrected (since the title in `index.html` is currently manually corrected by the backend, this delay doesn't exist). An ideal solution will maintain separation of responsibility while also loading the title instantly.

**Comment by gok99** [comment]
If we choose to keep with the current implementation, we should probably consider including `index.html` in the systemtests.

**Comment by dcshzj** [comment]
This was discussed in #1343 where this functionality was introduced. I personally would prefer a separation.

**Comment by gerhean** [comment]
I am in favor of the separation in order to ensure that frontend builds and report generation are independent, as I mentioned in #1630
