### ISSUE TITLE
Upgrade Gradle to at least 7.3

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1661]
**What feature(s) would you like to see in RepoSense?**

As mentioned in #1635, Gradle 5.2.1 doesn't support Java 17. There is thus a need to move to a minimum of Gradle 7.3 since that is the first Gradle version to support Java 17. 

**If applicable, describe alternatives you've considered**

~~Gradle has also released 7.4 very recently. This version also incorporates the [latest mitigation for the log4j vulnerability](https://github.com/gradle/gradle/issues/19526). I suggest going straight for 7.4 if possible.~~
Gradle has released 7.4.1 recently. I suggest going straight for it.

**Update**
There are 3 issues described below that may not be easy to solve if we are to jump straight to `7.4` or even `7.3`. ~~In the meantime, I will try to upgrade Gradle to `6.9.2`.~~

**Comment by gerhean** [comment]
Seems fine, you don't need to create an issue for simple tasks like this, if it involves only a simple version upgrade (with no refactoring), and does not break backwards compatibility (which you should mention).

**Comment by yhtMinceraft1010X** [comment]
I have encountered some issues with third-party plugins when attempting to move to Gradle 7.4:

**1. Property without annotation error in `com.liferay.gradle.plugins.node.tasks.ExecutePackageManagerTask`**

When running `gradlew`, I noticed this error:
![Screenshot (91)](https://user-images.githubusercontent.com/69678785/153754619-d5112a08-7b7b-41b8-b5d1-20171dce05c6.png)

After some googling, I discovered that Gradle 7 implemented stricted validation checks as described in this [link](https://dev.to/runningcode/a-problem-was-found-with-the-configuration-of-the-gradle-7-task-3ej1)

Possible remedy: There's another Gradle plugin that might work, [gradle-node-plugin](https://github.com/node-gradle/gradle-node-plugin). It is described as being tested for Gradle 7.4, although I wish to open this for discussion before deciding whether to change plugins.

**2. No compatibility with Java 8 for latest available version of `com.github.psxpaul.execfork`**

The latest available version for the aforementioned plugin is `0.1.15`. However, trying to use this version results in the below error:
![Screenshot (93)](https://user-images.githubusercontent.com/69678785/153755105-1f57167e-6ff0-46bb-adb8-763eaf4ec702.png)

Possible remedy: Using version `0.1.13` does not throw the same error. 

**3. The correct version `0.2.0` for `com.github.psxpaul.execfork` does not exist**

Although it is mentioned on the `README.md` of https://github.com/psxpaul/gradle-execfork-plugin, attempting to use version `0.2.0` results in the following error:
![Screenshot (94)](https://user-images.githubusercontent.com/69678785/153755180-bbdc8507-3981-4a6d-8009-9bf42e5c6202.png)

Gradle's [plugin page](https://plugins.gradle.org/plugin/com.github.psxpaul.execfork) still considers `0.1.15` to be the latest version.

**Conclusion**
Given these 3 issues, I intend to try to upgrade to Gradle 6, in particular version `6.9` to close the gap between our current version and version `7.4`.

**Comment by gerhean** [comment]
I am in favour of changing plugins if you believe that the plugins currently being used are not well maintained and causing problems.

Preferably switch to a popular plugin with more than 1000 github stars.
