### ISSUE TITLE
Rename frontend component files to remove `v-`

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1665]
**What feature(s) would you like to see in RepoSense?**

Rename frontend component files to remove the `v-` in front of every file.

I would also like some input on whether the names should be changed within the code, for example from `v-summary` to `summary` or some other standardized way to refer to components. Most reserved syntax used by Vue uses the `v-` prefix, like `v-bind`, so I would prefer to avoid it. Maybe use `c-` for component?

**Is the feature request related to a problem?**

Vue component files can easily be told apart from non-component files, as only component files use the `.vue` file extension. Hence the `v-` in front is redundant.

**Additional context**

Documentation needs to be changed as well.

**Comment by LuoZhijie-tom** [comment]
Hi is this issue still open? It is OK to work on this issue?

**Comment by dcshzj** [comment]
@LuoZhijie-tom Sure! I have assigned you this issue. Let us know if you have any questions!

**Comment by LuoZhijie-tom** [comment]
Thanks! May I ask do I need to remove the "v-" prefix from all components in the front end? Or do I need to replace "-v" with "-c"?

**Comment by dcshzj** [comment]
I think it would be good to just remove the "v-" prefix, not just for components but for all the files that contain it.

**Comment by LuoZhijie-tom** [comment]
Hi can I add "-c" in front of each component? It turns out that "summary" is a build in html element, thus "v-summary" can't be renamed to "summary". But except for that, all other components can be renamed.

**Comment by dcshzj** [comment]
Done in #1836.
