### ISSUE TITLE
Refactoring `AnnotatorAnalyzer` class

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1667]
**What ideas would you like to see in RepoSense?**

Refactoring the `AnnotatorAnalyzer` class.

**Is the feature request related to a problem?**

The current `AnnotatorAnalyzer` class' methods are difficult to understand. There are many null checks even though the optional class is being used. Additionally, there is a `ArrayIndexOutOfBoundsException` caught that seems to perform normal program flow logic. 

https://github.com/reposense/RepoSense/blob/ed131f6294bf83fac436a6265bc4d53b022739f7/src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java#L99-L103

The lines above are not tested by any test cases as well.

**If possible, describe the solution**

Change the logic in `extractAuthorName` to prevent the index exception from occurring at all.
Additionally, make use of `Optional` class methods like `filter` and `map` to perform operations instead of checking against `null`. 

**If applicable, describe alternatives you've considered**

**Additional context**

**Comment by chan-j-d** [comment]
@dcshzj would like to move forward on this refactoring suggestion if it makes sense.

**Comment by dcshzj** [comment]
Sounds like a good idea, I think we can go ahead with your proposed refactoring.
