### ISSUE TITLE
Config and repo flag priority is vague in User Guide

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1676]
**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

The current `cli.md` for the user guide only mentions that the `--repos` and `--config` flags cannot be used with each other. This however is vague on which one is preferred over the other.

**What would you like added or modified in the documentation?**

Since `ArgsParser` prioritises `--repos` over `--config`, let's mention in `cli.md` that the `--repos` flag will override the `--config` flag.

**Comment by gerhean** [comment]
I don't think undefined or unallowed flag combinations need to be documented. In fact would it not be better to just throw an error if users use both these flags together?
