### ISSUE TITLE
Broken links to remote repositories

### ISSUE THREAD

**Issue by gok99** [reposense/RepoSense#1689]
This issue consolidates issues with links in the report to remote repositories. These links should be fixed for when (a) no remote repositories exist or (b) remote repository is not yet supported by RepoSense (is not Github, GitLab or Bitbucket). The following report links redirect to broken links if either of the above conditions are satisfied.

1. Commit ramp link (also mentioned in #231):
![image](https://user-images.githubusercontent.com/34594184/155609367-f765c9ca-44b8-4a07-833f-2a548787d94d.png)
1. Link to author profile
![image](https://user-images.githubusercontent.com/34594184/155609405-4e110179-ea0e-4db1-b106-6b36839e95b7.png)
1. Link to group repo tree
![image](https://user-images.githubusercontent.com/34594184/155609331-b594a0d8-c353-4498-9f82-9ca13805a7f7.png)
1. Link to blame view
![image](https://user-images.githubusercontent.com/34594184/155609437-a27bffe9-5855-4663-a779-70c56f806fc1.png)
1. Link to history view
![image](https://user-images.githubusercontent.com/34594184/155850825-42462e4b-86f1-456a-852c-3b855c362278.png)

**To discuss:**

What should be the expected behaviour in the above scenarios if either (a) or (b) is satisfied? Some options:
- Hide the links entirely
- Popover that explains that link is not available

**Comment by gok99** [comment]
Report links with remote repositories that are supported and not GitHub (either GitLab or Bitbucket) is expected to be fixed in #1644

**Comment by chan-j-d** [comment]
**Current links behaviour on master branch as of 1 April 2022** 

#1644 has standardized the behaviour of links to be 
- Repository cloned from GitHub/GitLab/BitBucket - All links work
- All other types of repos (local or unsupported remote) - Links are disabled but buttons look identical

#1679 should allow partial support of local repos cloned from remote repos to support links that are already present on the remote repo.

**Comment by chan-j-d** [comment]
Besides the two suggestions you have, I might add an 'intermediate' suggestion where 
- The buttons are present but the hover message states that the link does not work

**Comment by Zhou-Jiahao-1998** [comment]
@chan-j-d Actually I prefer the button to be hidden entirely or disabled because sometimes we click the button before seeing the hover message.

**Comment by gok99** [comment]
> Actually I prefer the button to be hidden entirely or disabled

I think I agree. There is no ambiguity that a link is not supported if there isn't a link (icon) in the first place

**Comment by LuoZhijie-tom** [comment]
Hi is this issue still open? It is OK to work on this issue?

**Comment by gok99** [comment]
Sure, I've assigned you the issue!

**Comment by LuoZhijie-tom** [comment]
OK thanks! Shall I hide the button when the link doesn't work?

**Comment by gok99** [comment]
Yes, that appears to be the conclusion from above. 

@Zhou-Jiahao-1998, do update this thread if you have better ideas for handling missing/unsupported remotes.

**Comment by Zhou-Jiahao-1998** [comment]
@gok99 Actually now that I think about it again, I prefer disabling the button and add a hover message. That way the user won't be able to click and is likely gonna see an explanation in the hover message. Hiding without stating anything might cause confusion?

**Comment by gok99** [comment]
@Zhou-Jiahao-1998 That makes sense!

@LuoZhijie-tom You could do this instead

**Comment by LuoZhijie-tom** [comment]
OK sure!
