### ISSUE TITLE
Search bar on code panel

### ISSUE THREAD

**Issue by LiXiaoooowei** [reposense/RepoSense#170]
Currently user is only able to view the files changed in order of decreasing number of insertions, it would be better if user can specify the type of files to see. For example, by typing `java` on the search bar, only files end with `.java` will be shown to user.

**Comment by eugenepeh** [comment]
putting it as low priority for now as its not part of v1.2 scope

**Comment by yamidark** [comment]
Closing this issue as it is resolved in #448

**Comment by damithc** [comment]
As the original issue was for search by file type, let me close this one and open a new issue for 'search by glob' feature.
