### ISSUE TITLE
Syntax coloring for the code view

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1706]
I'm wondering how feasible it is to apply syntax coloring to the code view, for known file types. Is it feasible at all, and if yes, what kind of a performance hit it would result in, etc. ...

**Comment by dcshzj** [comment]
It used to exist, but it was possibly broken in #1412. The issue tracking this regression is in #1633.

**Comment by damithc** [comment]
> It used to exist, but it was possibly broken in #1412. The issue tracking this regression is in #1633.

Oh, I forgot we had it before. Some things you don't notice when they are around but you start missing them when they are gone ha ha :-D I'll close this now, as it is already being looked into.
