### ISSUE TITLE
File-size limit for backend processing 

### ISSUE THREAD

**Issue by gok99** [reposense/RepoSense#1716]
**What feature(s) would you like to see in RepoSense?**

Part of #1504. 

The PR #1647 currently processes all files, and ignores sufficiently large files (in file size) that could potentially crash the frontend. It might be a good idea to introduce a similar limit for files that the backend processes as well (i.e. if a file exceeds a limit, the backend will skip the file instead of analyzing it), to prevent excessively long report generation times.

The limit probably should be high enough that this situation will be **very** rare, and should only really applicable in cases of deliberate ill-intent or extreme accidents.

**Comment by gerhean** [comment]
Personally I feel that most code files are under 1mb. Anything more can be marked as too large to process. Furthermore can consider having an command line argument to process these files regardless.
