### ISSUE TITLE
Question on indentation for throws statements

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1717]
While working on #1692, I noticed in the [Java coding standard](https://se-education.org/guides/conventions/java/index.html#comments) Javadoc example that the `throws` statement in the method header has an indentation of 4. However, I could not find a specific rule for `throws` line-wrapping. The closest rule I can think of is the [general 8 spaces rule](https://se-education.org/guides/conventions/java/index.html#layout). 

Question: Should we follow 8 spaces or 4 spaces for line-wrapping `throws` statements?

**Comment by damithc** [comment]
Thanks for spotting this @yhtMinceraft1010X It's a bug in the coding standard. I've fixed it now. It should be 8 spaces.

**Comment by dcshzj** [comment]
Seems to be fixed.
