### ISSUE TITLE
Confirm/remove/modify npm prerequisite for github actions

### ISSUE THREAD

**Issue by gerhean** [reposense/RepoSense#1720]
**What feature(s) would you like to see in RepoSense?**

Probably related to #1286.

This package installs node into `./build/node/` directory when gradle is set up.
https://github.com/reposense/RepoSense/blob/a4ee1877a9fc47abde0592201ae489911a4bb604/build.gradle#L10

Tasks of type `com.liferay.gradle.plugins.node.tasks.ExecuteNpmTask` uses the node in `./build/node/` to run.
https://github.com/reposense/RepoSense/blob/a4ee1877a9fc47abde0592201ae489911a4bb604/build.gradle#L114-L117

Investigate if it is okay to remove node requirement in `./.github/workflows/integration.yml`
https://github.com/reposense/RepoSense/blob/a4ee1877a9fc47abde0592201ae489911a4bb604/.github/workflows/integration.yml#L37-L40

Alternatively maybe change `com.liferay` to use local node instead of downloading it into the build folder.

**Is the feature request related to a problem?**

The presence of node in github actions is confusing if it is not being used.

**Comment by yhtMinceraft1010X** [comment]
Closing this issue so that it can be refreshed as #1886, otherwise it will be pushed to the bottom (and likely forgotten) with more issues being raised.
