### ISSUE TITLE
The package.json version is 1.0.0

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1725]
**Tell us about your environment**

* **RepoSense Version:**
* **OS and Version:**
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

1. Found in [`frontend/package.json`](https://github.com/reposense/RepoSense/blob/master/frontend/package.json) line 3.

**What was expected to happen?**
The version field lists the latest release version available or the next imminent release.

**What actually happened? Please include a screenshot of the output.**
The version is still stuck at `1.0.0`.

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by gerhean** [comment]
Reposense is not published on npm, and nobody really reads the `package.json` for version, so I feel this might be redundant.

**Comment by yhtMinceraft1010X** [comment]
> Reposense is not published on npm, and nobody really reads the `package.json` for version, so I feel this might be redundant.

Closing this issue since it's likely to be a hassle to update `package.json` every time a new release is made.
