### ISSUE TITLE
Update how Codecov is invoked in pull requests

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1734]
We have always been using [Codecov Bash uploader](https://docs.codecov.com/docs/about-the-codecov-bash-uploader) to perform code coverage checks for our pull requests, and to annotate on the pull request files on the specific lines that are not covered by tests. However, this practice [has been deprecated since 1 February 2022](https://about.codecov.io/blog/introducing-codecovs-new-uploader/).

We should update the way we invoke Codecov as part of our pull request checks, particularly in 2 aspects:
1. Make use of new/updated ways to invoke Codecov
2. Make Codecov aware of Windows-specific code, so that code are not flagged unnecessarily when they are actually covered in our Windows-based tests

**Comment by damithc** [comment]
@dcshzj does this apply to AB3 too? https://github.com/se-edu/addressbook-level3

**Comment by dcshzj** [comment]
> @dcshzj does this apply to AB3 too? https://github.com/se-edu/addressbook-level3

Seems like it, because AB3 is using `codecov/codecov-action@v1` from [what I see in the gradle.yml file](https://github.com/se-edu/addressbook-level3/blob/865de62540a50cf0690abc36a212eea1e0b4617a/.github/workflows/gradle.yml#L41), and [based on their changelog](https://github.com/codecov/codecov-action/blob/master/CHANGELOG.md#200), they will sunset that version at the same time as the bash uploader.

**Comment by damithc** [comment]
> Seems like it, because AB3 is using `codecov/codecov-action@v1` from [what I see in the gradle.yml file](https://github.com/se-edu/addressbook-level3/blob/865de62540a50cf0690abc36a212eea1e0b4617a/.github/workflows/gradle.yml#L41), and [based on their changelog](https://github.com/codecov/codecov-action/blob/master/CHANGELOG.md#200), they will sunset that version at the same time as the bash uploader.

Thanks for checking @dcshzj . Is the deprecated one still working? If yes, when is it expected to stop working altogether?

**Comment by dcshzj** [comment]
> Thanks for checking @dcshzj . Is the deprecated one still working? If yes, when is it expected to stop working altogether?

I could not find any authoritative information about the exact deprecation timeline. There is [one pending PR to update the deprecation warning](https://github.com/codecov/codecov-action/pull/661) but it has not yet been merged or looked into. I am guessing that we can expect it to stop working "very soon".
