### ISSUE TITLE
Ignore case when comparing GitHub usernames to Git author name

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1754]
Is it possible to ignore case when identifying the author of a commit based on the Git author name (as given in `author-config.csv`), or at least for the GitHub username?
Reason: in some cases students give us the GitHub username that may be case-wise different to the actual username (because GitHub usernames are case insensitive)

**Comment by SkyBlaise99** [comment]
Hi prof, can I take this issue?

I would also want to clarify that `GitHub usernames` refers to `Author's GitHub ID` and `Git author name` refers to `Author's Git Author Name`?

**Comment by damithc** [comment]
> Hi prof @damithc, can I take this issue?
> 
> I would also want to clarify that `GitHub usernames` refers to `Author's GitHub ID`?

@SkyBlaise99 sure, go ahead. Yes, in your case it would be `SkyBlaise99`

**Comment by SkyBlaise99** [comment]
Hi prof @damithc, I need some clarification from you regarding this.

> GitHub usernames are case insensitive

Does this apply to `Git author name` as well? Currently what I'm doing is to store `gitId` and `authorAliases` in lower case when `Author` object is constructed. Therefore when `getAuthor` is called, the lowercase will give a match which is case-insensitive.

**Comment by damithc** [comment]
> Does this apply to `Git author name` as well?

@SkyBlaise99 We automatically consider the GitHub username as one of the Git author names. So, at least that author name needs to be case insensitive. But it's OK to make the reset of the Git author names case insensitive as well.
