### ISSUE TITLE
publish-reposense's author-config.csv is out of date

### ISSUE THREAD

**Issue by tlylt** [reposense/RepoSense#1768]
**Tell us about your environment**
Ubuntu-latest (In GitHub Actions CI)

* **RepoSense Version:** a4ee1877a9
* **OS and Version:** Ubuntu-latest (In GitHub Actions CI)
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**
Check the config file at https://github.com/reposense/publish-RepoSense/blob/master/configs/author-config.csv

**What was expected to happen?**
Should work with the latest release (?), which is v2.1

**What actually happened? Please include a screenshot of the output.**
Does not work with v2.1. In particular, the following warning was shown if I use the config files as-is, after checkout to the publish-RepoSense repo:
> 08:46:07 - [WARNING] Unknown column(s) found: Author's Email (./configs/author-config.csv)

I believe the column is now named `Author's Emails` instead of `Author's Email`

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by RyanCheungJF** [comment]
hi, can i take on this issue?

**Comment by dcshzj** [comment]
@RyanCheungJF Sure, go ahead. Let us know if you encounter any issues!
