### ISSUE TITLE
Implement more Checkstyle checks

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1769]
**What feature(s) would you like to see in RepoSense?**

While working on https://github.com/se-edu/addressbook-level3/pull/133, I found additional checks that could be useful for us:
* [JavadocTagContinuationIndentation](https://checkstyle.sourceforge.io/config_javadoc.html#JavadocTagContinuationIndentation) - Check for Google Java Style Guide requirement of [4 whitespaces for continuation lines in block tags](https://google.github.io/styleguide/javaguide.html#s7.1.3-javadoc-block-tags)
* [DefaultComesLast](https://checkstyle.sourceforge.io/config_coding.html#DefaultComesLast) - Ensures that all cases in `switch` statement are before `default`
* [NoWhitespaceBeforeCaseDefaultColon](https://checkstyle.sourceforge.io/config_whitespace.html#NoWhitespaceBeforeCaseDefaultColon) - E.g. `default :` would not be allowed

**If possible, describe the solution**

Before implementing any new checks, we should look through [other available checks](https://checkstyle.sourceforge.io/checks.html) and see which checks are suitable. By having as many checks as possible in a single PR, this will allow us to avoid revisiting this issue with multiple PRs in the future.

**Comment by damithc** [comment]
Looks like the bot auto-closed this. Should it be closed?

**Comment by yhtMinceraft1010X** [comment]
I plan to keep this open since there may be more checks that we need to implement.
