### ISSUE TITLE
Parallelize backend tests

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1770]
**What feature(s) would you like to see in RepoSense?**

The `Test` class in Gradle has a [`maxParallelForks` property](https://docs.gradle.org/6.9.2/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks) that would allow multiple JUnit test classes to run at the same time. Running test classes in parallel can reduce the build time.

**Potential Problem**

A potential problem lies in the `GitTestTemplate` class and test classes that extend it:
https://github.com/reposense/RepoSense/blob/b12d3485d4b7a3aca5f2545404b5545a5277ff5e/src/test/java/reposense/template/GitTestTemplate.java#L107-L111

The `@BeforeAll` annotation indicates that the method is called once when a test class such as `AnnotatorAnalyzerTest` is started. Within this method, the repo is cloned (in short, the `testrepo-Alpha.git` remote is cloned to the same output folder every time a test class that extends `GitTestTemplate` starts):
https://github.com/reposense/RepoSense/blob/b12d3485d4b7a3aca5f2545404b5545a5277ff5e/src/test/java/reposense/util/TestRepoCloner.java#L28-L33

If 2 test classes that extend `GitTestTemplate` run in parallel, it is possible that while 1 test class is still running through some test methods, the other class is re-cloning the repo, which could interfere with the first test class.

**Limitation**

According to [this website](https://kousenit.org/2020/11/22/simple-demo-of-gradle-parallel-tests/), the methods within a single test class do not run in parallel. This means that there won't be time savings for `ConfigSystemTest`.

**Comment by SkyBlaise99** [comment]
For this, I think maybe we can try to change `outputFolderName`. So even if they are the same repo, the `outputFolderName` will be different and hence the 2 tests that relies on the same repo can be executed concurrently.

**Comment by SkyBlaise99** [comment]
According to this [website](https://www.baeldung.com/junit-5-parallel-tests), the following can be added to `junit-platform.properties` file in `src/test/resources folder`.

Test Parallelization Within a Class: `junit.jupiter.execution.parallel.mode.default=concurrent`
Test Parallelization Within a Module: `junit.jupiter.execution.parallel.mode.classes.default=concurrent`

**Comment by SkyBlaise99** [comment]
Currently I can lower it down to about 25s (originally ~40s?). But there are still some test cases that didnt pass. Got a half working branch [here](https://github.com/SkyBlaise99/RepoSense/tree/1770-parallelize-backend-tests).

Only problem left is the `.git-blame-ignore-revs` as it is now in a different directory as the others.

**Comment by SkyBlaise99** [comment]
@yhtMinceraft1010X what do you think about my idea?

**Comment by SkyBlaise99** [comment]
@yhtMinceraft1010X 

For `systemtest`, I realized that it may not be possible to achieve parallel execution since the code for RepoSense doesn't really support parallelism. There are a lot of `static` variables that causes error when I try to run something in parallel.

I tried to break the methods down to achieve as much parallelism as possible. But the improvement in timing is pretty small (~3s). So perhaps I can make a PR for the `test` to be parallel first?

**Comment by SkyBlaise99** [comment]
Note to anyone who wishes to work on this, `test` is now running in parallel. More details are in the merged PR above.

`systemtest` is not in parallel, which you can still work on. Of course, you are still welcome to improve on `test` if you wish to.

**Comment by yhtMinceraft1010X** [comment]
Closing this issue so that the description for `systemtest` can be better phrased.
