### ISSUE TITLE
System Test Failed

### ISSUE THREAD

**Issue by SkyBlaise99** [reposense/RepoSense#1783]
**Tell us about your environment**

* **RepoSense Version:** `master` branch in [my forked repo](https://github.com/SkyBlaise99/RepoSense)
* **OS and Version:** Windows 11
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

Following the [setup guide](https://reposense.org/dg/settingUp.html#verifying-the-setup) here until step 3

1. `./gradlew clean build`
1. `./gradlew test systemtest`

**What was expected to happen?**

All tests passed

**What actually happened? Please include a screenshot of the output.**

All tests passed for `test` only. `systemtest` failed.

Screenshot 1

![image](https://user-images.githubusercontent.com/69448615/172040277-5736eb83-7ea9-4a88-b561-8fe698bd98b0.png)

Screenshot 2

![image](https://user-images.githubusercontent.com/69448615/172040404-3fcd82b4-cb0b-4e8b-b54f-f89567038561.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Note**

I have checked into the files and from Screenshot 1, there seem to be a small typo in [repo-config.csv](https://github.com/reposense/RepoSense/blob/master/src/systemtest/resources/ConfigSystemTest/repo-config.csv) and [author-config.csv](https://github.com/reposense/RepoSense/blob/master/src/systemtest/resources/ConfigSystemTest/author-config.csv). The last row is missing a `h` infront.

**Comment by yhtMinceraft1010X** [comment]
Thanks for opening this issue.

I have opened PR #1776 to fix the failing system test issue. Feel free to contribute what's mentioned in the **Note** .

**Comment by SkyBlaise99** [comment]
I'm not sure if this is the intended behavior since I'm new here. I did try to add a `h` into it and it seems to fix the error but the passing rate drops from 57% to 14%.

**Comment by yhtMinceraft1010X** [comment]
> I'm not sure if this is the intended behavior since I'm new here. I did try to add a `h` into it and it seems to fix the error but the passing rate drops from 57% to 14%.

Actually, this is intended. The missing `h` is meant to demonstrate logging the detection of an invalid link, but this shouldn't result in the test failing.

**Comment by SkyBlaise99** [comment]
So it's ok to leave the `system test` as such?

**Comment by yhtMinceraft1010X** [comment]
> So it's ok to leave the `system test` as such? If so then I think I should close this issue.

Yes.
