### ISSUE TITLE
GitHub Actions: Cypress tests are failing

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1784]
**Tell us about your environment**

* **RepoSense Version:** `master` latest
* **OS and Version:** GitHub Actions CI
* **Web Browser and Version (if applicable):** Chrome 102
* **Cypress Version:** 9.7.0

**Please include the steps to reproduce the bug.**

1. Run the cypress frontend tests on GitHub Actions for the latest CI

**What was expected to happen?**
All the tests pass

**What actually happened? Please include a screenshot of the output.**
Tests which involve interacting with elements fail because the elements being tested are covered by some other element.
![Screenshot (289)](https://user-images.githubusercontent.com/69678785/172078507-80517bb7-b4d2-4bad-b916-a0feff755cdc.png)

![Screenshot (288)](https://user-images.githubusercontent.com/69678785/172078519-8c02accb-8c4c-4ca4-8377-3d5e0fbaacaa.png)

**If possible, include the URL to your RepoSense report or log files (if any).**
Latest CI run: https://github.com/reposense/RepoSense/actions/runs/2443533819

**Update:**
The elements that are blocking interaction with the elements being checked are `vld-background` and `vld-icon`, which are for the `vue-loading-overlay`. My hypothesis is that the tests are stuck on the loading screen.

**Comment by yhtMinceraft1010X** [comment]
I have created a [new branch](https://github.com/reposense/RepoSense/tree/1784-investigate-failing-cypress) to investigate this since I intend to use `{force: true}` as a hotfix to get CI to pass again.

**Comment by yhtMinceraft1010X** [comment]
To add-on, I noticed these 2 lines in the GitHub Actions whenever Cypress fails:
![Screenshot (290)](https://user-images.githubusercontent.com/69678785/172097758-00e7901c-b261-4d24-8bbe-73938e4f9b46.png)

The elements that are blocking interaction with the elements being checked are `vld-background` and `vld-icon`, which are for the `vue-loading-overlay`. My hypothesis is that the tests are stuck on the loading screen.

This is what I got when I googled the first line: https://stackoverflow.com/questions/69037458/selenium-chromedriver-gives-initializesandbox-called-with-multiple-threads-in, which sounds similar to what we are experiencing now.

**Comment by damithc** [comment]
> My hypothesis is that the tests are stuck on the loading screen.

Not sure if related but these recent iP dashboards are stuck at loading screen too:

https://nus-cs2103-ay2122s2.github.io/ip-dashboard/
https://nus-tic4002-ay2122s2.github.io/ip-dashboard/

But these tP dashboards are not stuck
https://nus-cs2103-ay2122s2.github.io/tp-dashboard/
https://nus-tic4002-ay2122s2.github.io/tp-dashboard/

**Comment by yhtMinceraft1010X** [comment]
> I have created a [new branch](https://github.com/reposense/RepoSense/tree/1784-investigate-failing-cypress) to investigate this since I intend to use `{force: true}` as a hotfix to get CI to pass again.
> 
> If anyone wants to investigate this issue, please use that branch.

Branch is deleted now that issue is solved.

**Comment by damithc** [comment]
> Not sure if related but these recent iP dashboards are stuck at loading screen too:
> 
> https://nus-cs2103-ay2122s2.github.io/ip-dashboard/ 
> https://nus-tic4002-ay2122s2.github.io/ip-dashboard/

These two are working now. Thanks everyone who helped to solve it 💯
