### ISSUE TITLE
Intended behavior of `extractDate()` in `TimeUtil`?

### ISSUE THREAD

**Issue by SkyBlaise99** [reposense/RepoSense#1789]
Hi RepoSense devs,

In Phase 2, I discovered this weird part of `extractDate()` in `TimeUtil`. As seen [here](https://github.com/reposense/RepoSense/blob/master/src/main/java/reposense/util/TimeUtil.java#L165-L175), `extractDate()` extracts the date only if it matches `DATE_FORMAT_REGEX`, else returns the input `date`.

According to `DATE_FORMAT_REGEX`, I believe the accepted format is in `dd/mm/yyyy` (e.g. `01/01/2022`). However, the program also runs when I input `1/1/2022`.

The reason is that `extractDate()` returns `1/1/2022` since the `if` condition fails. But `1/1/2022` is a valid date that can be recognized by `LocalDateTime`, hence the program is able to process this input.

So it seems to me that this might be an unintended behavior, although a good feature as it allows users to input `d/m/yyyy` format as well. More details and possible fix can be found in my [PR link](https://github.com/SkyBlaise99/RepoSense/pull/2) for Phase 2. Another suggestion is to make `extractDate()` throw an exception if it is unable to extract the date.

**Comment by SkyBlaise99** [comment]
I'm not sure how to add a `c.Question` tag for this

**Comment by SkyBlaise99** [comment]
Hi, any update on whether this is a bug that need to be fixed?

**Comment by yhtMinceraft1010X** [comment]
`1/1/2022` is also intended to work here.

The real problem lies in the use of `01/01/2022addedstring` vs `1/1/2022addedstring`. For the former, the `DATE_FORMAT_REGEX` can extract out `01/01/2022`. For the latter, it will fail.

Feel free to fix this peculiarity. Do take note of the following:
* It's great that your PR also takes into account `dd/m/yyyy` and `d/mm/yyyy`
* Right now, we are not supporting any other format besides `dd/mm/yyyy` (although the day or month can be double or single digits). Feel free to create a separate issue for suggesting new date formats so that this can be discussed further

**Comment by SkyBlaise99** [comment]
Sure, I will make it a feature request and put my PR under that. Will this be ok?

**Comment by yhtMinceraft1010X** [comment]
> Sure, I will make it a feature request and put my PR under that. Will this be ok?

Ok. For the PR for this issue, please remove the changes which add new date formats or uses `.` or `-` instead of `/` before opening the PR.

**Comment by SkyBlaise99** [comment]
Alright, thank you!

**Comment by damithc** [comment]
> According to `DATE_FORMAT_REGEX`, I believe the accepted format is in `dd/mm/yyyy` (e.g. `01/01/2022`). However, the program also runs when I input `1/1/2022`.
> 
> The reason is that `extractDate()` returns `1/1/2022` since the `if` condition fails. But `1/1/2022` is a valid date that can be recognized by `LocalDateTime`, hence the program is able to process this input.

I think this (un-advertised) behavior is good to retain. Reason: It allows a slightly looser interpretation of the given format, as some users might not realize `dd` means strictly two digits.

**Comment by SkyBlaise99** [comment]
I agree it should be retained.

As a quick summary of my doubt, I found out that

1. `01/01/2022`: accepted
1. `01/01/2022 abc`: accepted
1. `1/1/2022`: accepted
1. `1/1/2022 abc`: error

Hence I was confirming that we are allowing single digit dates as inputs, and depending on the answer, update the behavior for the last row.

This [PR]() that I created resolves this by updating the regex. Now the last row can be processed as well.

**Comment by damithc** [comment]
> I agree it should be retained.
> 
> As a quick summary, I found out that
> 
> 1. `01/01/2022` is accepted
> 2. `01/01/2022 abc` is accepted as `extractDate()` will extract out `01/01/2022`
> 3. `1/1/2022` is accepted
> 4. `1/1/2022 abc` shows an error as it does not match `DATE_FORMAT_REGEX`
> 
> Hence I was confirming that we are allowing single digit dates as inputs, and depending on the answer, update the behavior for the last row.
> 
> This [PR](https://github.com/reposense/RepoSense/pull/1795) that I created resolves this by updating the regex. Now the last row can be processed as well.

Regarding 2 and 4, either both should be allowed or both should be rejected. So, there's definitely something to be fixed. What's the justification for allowing it?

**Comment by SkyBlaise99** [comment]
Basically the same reason as you mentioned here.
> I think this (un-advertised) behavior is good to retain. Reason: It allows a slightly looser interpretation of the given format, as some users might not realize dd means strictly two digits.

**Comment by damithc** [comment]
> Basically the same reason as you mentioned here.
> 
> > I think this (un-advertised) behavior is good to retain. Reason: It allows a slightly looser interpretation of the given format, as some users might not realize dd means strictly two digits.

Right. At first I thought `01/01/2022 abc` was actually an incorrect input due to `abc` but realized it's a legit input.

**Comment by SkyBlaise99** [comment]
`01/01/2022 abc` is a valid input as it will be processed by `extractDate()` which will return `01/01/2022`. Since `01/01/2022` and `01/01/2022 abc` are both accepted, I believe that both `1/1/2022` and `1/1/2022 abc` should be accepted. Therefore it is a bit strange to only accept one of them.

And I think it is pity to drop this feature, hence I modified the regex to accept it.

**Comment by damithc** [comment]
> `01/01/2022 abc` is a valid input as it will be processed by `extractDate()` which will return `01/01/2022`. Since `01/01/2022` and `01/01/2022 abc` are both accepted, I believe that both `1/1/2022` and `1/1/2022 abc` should be accepted. Therefore it is a bit strange to only accept one of them.
> 
> And I think it is pity to drop this feature, hence I modified the regex to accept it.

Yes, I agree @SkyBlaise99
