### ISSUE TITLE
Support multiple repos for one author

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#18]
In some projects/courses, students work on multiple repos. It is nice to be able to aggregate activities of a student on multiple repos in one chart. 

Note: this feature is unlikely to be in v1, but keep this in mind when making architectural decisions.

**Comment by damithc** [comment]
We can omit the github username in the author-config.csv to indicate that the row should be combined with the author in the previous row.


Repository's Location | Branch | Author's GitHub ID | Author's Display Name | Author's Git Author Name | Ignore Glob List
-- | -- | -- | -- | -- | --
https://github.com/W10-1/main.git | master | ahan| AHAN ...PTA | ahan
https://github.com/W10-1/main.git | release | | | ahan2
https://github.com/W10-1/main.git | master | kong| KONG ...JIN | kong|

**Comment by fzdy1914** [comment]
@damithc Do the current `merge group` for the `group by author` does what you need? Now, we can use the commit panel already. Do you need to view the authorship pannel also? The authorship panel may be a bit confusing if we combine it from different repos.

**Comment by damithc** [comment]
> @damithc Do the current `merge group` for the `group by author` does what you need? Now, we can use the commit panel already. Do you need to view the authorship pannel also? The authorship panel may be a bit confusing if we combine it from different repos

Yes, it does. And yes, I guess no need for the code panel to show all code.
