### ISSUE TITLE
Wrong URL for author's profile link for supported repos (GitLab and BitBucket)

### ISSUE THREAD

**Issue by SkyBlaise99** [reposense/RepoSense#1801]
**Tell us about your environment**

* **RepoSense Version:** [`44c44f5`](https://github.com/SkyBlaise99/RepoSense/tree/1726-more-icons)
* **OS and Version:** Windows 11
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

1. Run `hotReloadFrontend` or
   ```
    java -jar Reposense.jar -r https://bitbucket.org/skyblaise/testrepo-bitbucket.git https://gitlab.com/reposense/testrepo-gitlab.git -v
    ```
1. Select `Click to view author's profile` for `GitLab` or `BitBucket`

**What was expected to happen?**

Redirects like how it is done for GitHub.

**What actually happened? Please include a screenshot of the output.**

For both GitLab and BitBucket, redirects to a page that shows `404 not found`.

![image](https://user-images.githubusercontent.com/69448615/176624894-c8877853-7395-4d54-9233-4b0409a44e2e.png)

For GitLab, it seems to be redirecting to the wrong link. Should be [https://gitlab.com/zsc990124](https://gitlab.com/zsc990124) instead of [https://gitlab.com/SHICHEN%20ZHANG](https://gitlab.com/SHICHEN%20ZHANG).

![image](https://user-images.githubusercontent.com/69448615/176625100-caadb796-f216-492c-b176-b5907e7a7a0e.png)

![image](https://user-images.githubusercontent.com/69448615/176624938-97e62a76-4bb7-40bc-9fa9-251f761c1804.png)

For BitBucket, I couldn't find the profile page. So maybe there isn't one in the first place.

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by SkyBlaise99** [comment]
@gok99 I think it is better to discuss what you mentioned ([link](https://github.com/reposense/RepoSense/issues/1726#issuecomment-1171256530)) here.

I feel like this is 2 separate issues. In #1689, you mentioned that either (a) or (b) is satisfied. In my case, both are not. That is, the remote repo exists and is supported by RepoSense. What I found is that the link for Github works but not for GitLab and Bitbucket.

**Comment by chan-j-d** [comment]
Add this line 
`https://bitbucket.org/skyblaise/testrepo-bitbucket.git,master,skyblaise,,Shichen Zhang,SHICHEN ZHANG,`
to your `author-config.csv` file. 

I am not sure if a cloned remote repo actually has information relating to your actual GitHub ID that is part of your GitHub URL. When cloning a remote repo where all the commits are merged directly on the site itself via pull requests, the default name for every commit is the user's display name. 

From my experience, the author links only work under 3 scenarios.
- The user has no display name, so their ID is their display name. Something like this profile https://github.com/Zhou-Jiahao-1998, compared to mine and yours. 
- The author's profile is listed in the `author-config.csv` config file before analysis.
- The remote repository itself has a `_reposense/config.json` that has the author's profiles listed in them

It's something that I noted too some time back and couldn't find a reasonable way to obtain the author's actual ID through git.

**Comment by chan-j-d** [comment]
Side note, should probably link the branch itself (https://github.com/SkyBlaise99/RepoSense/tree/1726-more-icons) and specify `HEAD` commit instead of referencing it from `reposense` as I cannot directly clone from the link you provided. Had to browse around to find which remote branch the commit existed on. 

Additionally, I believe the steps for replication could be simplified to something like running the command
`java -jar Reposense.jar -r (bitbucket url) (gitlab url) -v`

**Comment by SkyBlaise99** [comment]
I see, I will update `author-config.csv` into #1800.

Thanks for the side notes, still quite new to this. I have updated it accordingly.
