### ISSUE TITLE
Unclear percentage meaning under summary-charts when groups are sorted by contribution

### ISSUE THREAD

**Issue by jbkim1999** [reposense/RepoSense#1809]
**What feature(s) would you like to see in RepoSense?**

<img width="705" alt="image" src="https://user-images.githubusercontent.com/60286063/180609307-cce9cf74-0772-40e8-a61b-008e3df6b349.png">
When the groups are sorted by the amount of contribution, a percentage label appears; however, no other information is provided for that number, which could be confusing to the viewers. <br/><br/>

**If possible, describe the solution**

This was done as part of my [phase 2](https://github.com/jbkim1999/RepoSense/pull/2/files), in which I have attached a help icon next to the percentage, and if the viewers click on it, they can see a modal describing what the number means.
![image](https://user-images.githubusercontent.com/60286063/180609571-cc46c5c8-3fbe-4543-b693-7485fd734826.png)
![image](https://user-images.githubusercontent.com/60286063/180609574-e00c1203-5a7d-4d2e-861b-a17b4747c95c.png)

However, since modal is quite a departure from the current design, for this issue, I would like to address it in a way that when a viewer hovers on the help icon, a small pop up message (like all others) shows up and displays the description.

**Comment by damithc** [comment]
> However, since modal is quite a departure from the current design, for this issue, I would like to address it in a way that when a viewer hovers on the help icon, a small pop up message (like all others) shows up and displays the description.

Yes, a popup containing a short description might work. But watch out for the increase in page size too. I'm a bit worried that adding a repetitive content can bloat the page size too much.

**Comment by jbkim1999** [comment]
@damithc 

I see your concern.

Is there a way to verify whether the page size has increased? 
Is looking at the file size for `index.html` under `reposense-report` directory a correct way to verify it?

**Comment by damithc** [comment]
> Is there a way to verify whether the page size has increased?
> Is looking at the file size for `index.html` under `reposense-report` directory a correct way to verify it?

Probably, but best verified by a senior dev.

**Comment by dcshzj** [comment]
> Is there a way to verify whether the page size has increased? Is looking at the file size for `index.html` under `reposense-report` directory a correct way to verify it?

The page size would be affected by the size of `js/app.js` in the `reposense-report` directory. I think this change should be not too significant, and only the text needs to be adjusted for each instance of the modal.

In the future, it is likely that we need to do proper profiling of the frontend performance to see where our bottlenecks are.

**Comment by jbkim1999** [comment]
@dcshzj 

I see. Then could you assign me on this one? I will see how the size varies after the change.
