### ISSUE TITLE
Inconsistent thickness (height) of different contribution lines

### ISSUE THREAD

**Issue by AdityaA1998** [reposense/RepoSense#181]
The height of the contribution appears to be different for different contibutors.

Let's fix this to make it look consistent for every contributor.

![image](https://user-images.githubusercontent.com/23259003/42622624-6006c55c-85f3-11e8-85f5-3957c2fbdb3b.png)

**Comment by eugenepeh** [comment]
unable to replicate this. @AdityaA1998 can you provide more details?
The browser and its version that you've used, link if any etc.

**Comment by AdityaA1998** [comment]
Tried the preview of this [Netlify Dashboard](https://deploy-preview-171--reposense.netlify.com/#search=&sort=totalCommits&reverse=false&repoSort=true&since=2017-10-05&until=2017-11-18)

I tested on both chrome and firefox. I faced similar issue on both the browsers. Not sure if this has to do with the different resolution of mac.

**Comment by damithc** [comment]
> Tried the preview of this Netlify Dashboard

They do appear to be of slightly different thickness in this case. Not a big problem though. Certainly not something we want to spend time on at this time.

**Comment by fzdy1914** [comment]
By a rough investigation, it is because we use `rem` to represent the height, which result in a non-integer `px` value. And the browsers may display floating-point `px` differently. We can just set the height of the pixel to be `4px`.
