### ISSUE TITLE
Filter by glob input does not allow user input

### ISSUE THREAD

**Issue by dcshzj** [reposense/RepoSense#1810]
**Tell us about your environment**

* **RepoSense Version:** https://github.com/reposense/RepoSense/commit/11421c8394bdca3464957d550186715e9a94bf0a (bug seems to have appeared since a very long time ago)
* **OS and Version:** macOS 12.3.1
* **Web Browser and Version (if applicable):** Google Chrome 103.0.5060.53

**Please include the steps to reproduce the bug.**

1. Navigate to the RepoSense dashboard
2. Click on anyone's author contribution panel
3. Click on the "Filter by glob" input

**What was expected to happen?**
As a user, I should be able to provide user input to the "Filter by glob" input box.

**What actually happened? Please include a screenshot of the output.**
The input functions like a button, causing the report to refresh. It is not possible for the user to input anything into the "Filer by glob" input box.

**If possible, include the URL to your RepoSense report or log files (if any).**
https://dashboard-1780-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=tests~docs~other~frontend~backend&authorshipIsBinaryFileTypeChecked=false&authorshipIsIgnoredFilesChecked=false

**Comment by Punpun1643** [comment]
Hi, I also notice this bug earlier when working on the issue. Can I work on this?

**Comment by dcshzj** [comment]
@Punpun1643 Sure! Please go ahead, I have assigned the issue to you.
