### ISSUE TITLE
Continuous Integration for macos-10.15 is always cancelled

### ISSUE THREAD

**Issue by SkyBlaise99** [reposense/RepoSense#1817]
**Tell us about your environment**

* **RepoSense Version:** linked the PRs
* **OS and Version:** Windows 11
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

1. push my branch to trigger github checks

**What was expected to happen?**
The checks run and either pass or fail.

**What actually happened? Please include a screenshot of the output.**
`Continuous Integration / macos-10.15 JDK 8 (pull_request)` is always cancelled for all 3 PRs.

#1806 
![image](https://user-images.githubusercontent.com/69448615/181216301-9c8712b1-d984-4665-9d24-c3d075737c29.png)

#1807 
![image](https://user-images.githubusercontent.com/69448615/181216332-687b3e74-ed4a-40fd-9122-f8f0879f29e6.png)

#1816 
![image](https://user-images.githubusercontent.com/69448615/181216375-ef1eceab-9d44-48c0-8784-73c8f060dd7c.png)

A bit too much of a coincidence when all 3 PR's mac is cancelled. I tried to push new commits but same keep happening.

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by yhtMinceraft1010X** [comment]
The GitHub Action for `macos-10.15` is being [deprecated](https://github.com/actions/virtual-environments/issues/5583).

I noticed from your screenshot timestamp that the date and time is within the brownout period of `July 27, 00:00 UTC - July 28, 00:00 UTC`.

We are in the midst of [removing support for this version](https://github.com/reposense/RepoSense/pull/1811). There is no need to worry about this CI being cancelled.
