### ISSUE TITLE
Use `InputBuilder` for `LocalRepoSystemTest`

### ISSUE THREAD

**Issue by SkyBlaise99** [reposense/RepoSense#1818]
**What feature(s) would you like to see in RepoSense?**

In #1746, all the test cases uses CLI inputs like this:

```java
String cliInput = String.format("-r %s %s -s d1 -u %s -o %s -t %s", ...);
```

This can be troublesome and error-prone.

**If possible, describe the solution**

`ConfigSystemTest` on the other hand uses `InputBuilder` which offers methods to craft and build CLI inputs.

```java
InputBuilder inputBuilder = new InputBuilder().addConfig(configFolder)
                .addFormats(formats)
                .addTimezone(TEST_TIME_ZONE)
                .addXXX(...);

String cliInput = inputBuilder.build();
```

**Comment by SkyBlaise99** [comment]
@chan-j-d what do you think about this?

**Comment by chan-j-d** [comment]
@SkyBlaise99 Sounds good to me. If you don't intend to work on this issue, I think we can set it as a good first timer issue

**Comment by SkyBlaise99** [comment]
Sure no problem.

**Comment by SkyBlaise99** [comment]
@chan-j-d gentle reminder to add the first timer tag if you still want to.

**Comment by lawwm** [comment]
I'll be working on this issue.

**Comment by dcshzj** [comment]
@lawwm Sure! I've assigned you the task, let us know if you have any questions!
