### ISSUE TITLE
User Guide: Give more info on the File Size Limit

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1825]
In https://reposense.org/ug/configFiles.html#repo-config-csv the following description of the `File Size Limit` appears.

![image](https://user-images.githubusercontent.com/1673303/185080994-9da6fad4-2560-45d5-80d4-a0fa3c5b6779.png)

Suggestions/questions:
* Specify the default file size referred in the description
* Give an example
* Also mention how the file size limit (default or otherwise) affects the report?
* Why is this column marked as a multi-valued column?

**Comment by gok99** [comment]
Hi prof @damithc,

- I think it makes sense to include the exact limit in the documentation. I believe I omitted it at the time to avoid having to remember to fix documentation if/when we decide to adjust the limits, but the benefits of clarity from including it in the documentation is probably greater than the cost.
- There exists an example of the file size limit column in the example [repo-config.csv](https://reposense.org/ug/repo-config.csv) in the section. Do you think this is sufficient?
- That makes sense. Perhaps something like `If file analysis is not skipped, files exceeding the file size limit will be marked as ignored and only the file name and line count will be reflected in the report.`
- I believe the + denotes an overridable column. The file size limit in `repo-config.csv` can override the one specified in the standalone config.

**Comment by damithc** [comment]
> * I think it makes sense to include the exact limit in the documentation. I believe I omitted it at the time to avoid having to remember to fix documentation if/when we decide to adjust the limits, but the benefits of clarity from including it in the documentation is probably greater than the cost.

👍 

> * There exists an example of the file size limit column in the example [repo-config.csv](https://reposense.org/ug/repo-config.csv) in the section. Do you think this is sufficient?

Good to give one here too. For example, how to indicate a size of 1MB.

> * That makes sense. Perhaps something like `If file analysis is not skipped, files exceeding the file size limit will be marked as ignored and only the file name and line count will be reflected in the report.`

👍 

> * I believe the + denotes an overridable column. The file size limit in `repo-config.csv` can override the one specified in the standalone config.

Ah, misread it. Somewhat related: add a line break here?
![image](https://user-images.githubusercontent.com/1673303/185201210-e3c5c4a0-0d22-41b9-aacc-528494b13afe.png)
