### ISSUE TITLE
Glob filter is not editable

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1831]
Using latest master branch, on Chrome 104.0.5112.102

https://nus-cs2103-ay2223s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt

![image](https://user-images.githubusercontent.com/1673303/187333747-e66f0774-2e8b-422f-83cd-b35b018d1431.png)

I'm not able to enter anything into this text box

**Comment by gok99** [comment]
@damithc This issue has been documented in #1810 and should be fixed by #1827 (still open currently)

**Comment by damithc** [comment]
> @damithc This issue has been documented in #1810 and should be fixed by #1827 (still open currently)

Got it. Thanks for checking @gok99  Let's get it merged soon as it is main feature in the UI.
