### ISSUE TITLE
Add Test Cases for Filter Glob User Input

### ISSUE THREAD

**Issue by Zhou-Jiahao-1998** [reposense/RepoSense#1833]
**What feature(s) would you like to see in RepoSense?**

#1810 was fixed by #1827. However, no frontend test cases were added for this PR due to the high priority.
Please add Cypress test cases to ensure this feature works as expected and facilitate future testing.

**Is the feature request related to a problem?**

**If possible, describe the solution**

**If applicable, describe alternatives you've considered**

**Additional context**

**Comment by Zhou-Jiahao-1998** [comment]
@Punpun1643 Hi you can work on this issue now. I am unable to assign the issue to you. Can you try assigning it to yourself?   You can refer to other test cases under `cypress` to get an idea on how to write the frontend test cases.

**Comment by Punpun1643** [comment]
@Zhou-Jiahao-1998 Yup ok 👍

**Comment by Punpun1643** [comment]
Hi @Zhou-Jiahao-1998, I have made a PR for this at #1841, may I have a review for this? Thank you!
