### ISSUE TITLE
Debugging with Arguments

### ISSUE THREAD

**Issue by clyveycui** [reposense/RepoSense#1848]
**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

This issue is specific to debugging with Intellij.

Relevant sections of the Documentation:
[Learning the Basics, Backend, Step 2](https://reposense.org/dg/learningBasics.html)

While learning the architecture and playing around with the code base, I realized that debugging without any arguments is fairly useless. There is then a need to provide additional arguments in the run configuration for Intellij. However, due to the way Gradle run works, it is not possible to supply the argument flags directly as one would normally when debugging with args:
![image](https://user-images.githubusercontent.com/38873431/207951508-ef1ca809-4f30-40b0-b386-e79e8465556c.png)
This leads to the following error:
![image](https://user-images.githubusercontent.com/38873431/207951650-5692603a-64e4-412c-b247-b44954c03777.png)

The correct way to supply args as stated [here](https://stackoverflow.com/questions/52267489/how-do-i-use-gradle-bootrun-with-args-in-intellij) is this:
![image](https://user-images.githubusercontent.com/38873431/207957500-96d49dc5-51d4-4936-9b2d-7d4a6a6a718b.png)

I feel this is rather counterintuitive and should really be mentioned.

However, the current documentation makes no mention of this, and simply redirects the developer to an introduction to debugging article for Intellij.

**What would you like added or modified in the documentation?**

Just a quick tooltip with a screenshot telling the user how to provide arguments would help a lot with figuring out how to perform debugging. 

Another possible solution is to add a debug entry point inside the code base so that the developer can provide the command line arguments there:

```
DebugEntry{
    public static void main(String[] args) {
        String cliArg = "--since 01/01/2017";
        String[] args = cliArg.split();
        RepoSense.main(args);
    }
}
```

**Comment by parth-io** [comment]
Just curious, which run configuration did you select? I specifically selected the Gradle run configuration (in the top-left dropdown in the screenshot), and it works fine for me without any additional fiddling needed, just as I'd expect it to from the terminal
![image](https://user-images.githubusercontent.com/67057645/208171222-ede8f30c-4f6f-4197-a641-cc76c6d873de.png)

**Comment by clyveycui** [comment]
I ran RepoSense.main() as a Gradle task, as configured in the screenshot below:
![image](https://user-images.githubusercontent.com/38873431/208202520-aeb39e67-e7af-4bb0-a994-d60c110b25e0.png)

I don't really see any other options when I first configured the project, so I am not too sure what's causing the difference here.

**Comment by parth-io** [comment]
Oh this is because our Intellij versions are different :laughing: 
I think you're using the 2021.1 version, the docs for that are different and seem to match your screenshot: https://www.jetbrains.com/help/idea/2021.1/run-debug-gradle.html

But yes, we need to write `run --Dargs="<your RepoSense args>" because the CLI args for the Gradle command and for RepoSense are different. The CLI args for the `RepoSense::main` are themselves included as an argument for Gradle, so `--Dargs` tells Gradle that these are the args to use when running `RepoSense::main`.

Incidentally, I just realised there's a difference between `--Dargs` and `--args`. The `-D` flag is for system properties, also used to override any local properties we might have set

**Comment by clyveycui** [comment]
>I think you're using the 2021.1 version, the docs for that are different and seem to match your screenshot

Oh yeah that totally went over my head. I didn't realize that there were separate docs for the 2021 version.
Just as a side note, do you mind telling me what versions of Intellij are you guys running?

**Comment by parth-io** [comment]
The latest version, 2022.3 - it doesn't auto-update lol
