### ISSUE TITLE
Use realistic person names for test repos

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#185]
Current:
![image](https://user-images.githubusercontent.com/1673303/42670976-68af6018-8690-11e8-9aca-063e5b0d02af.png)

Problem: It's unlikely that real use case will be for such short names. Using this kind of _too simple_ test cases can cause bugs to go unnoticed (e.g., a bug in handling spaces or special chars in a name) and also can cause the actual UI to look different from the UI we see in test cases (e.g., text overflows due to long names).

Suggestion: Use a variety of names that cover various equivalence partitions of the test input. e.g., names with a slash (`Ravi s/o Ramesh`)

**Comment by anubh-v** [comment]
Hi everyone,
This issue seems to involve the system tests. May I work on it?

**Comment by Tejas2805** [comment]
Does this issue require the change in names in 'author-config' in the configs folder or in 'author-config'?
And can I add repositories of people who fit the equivalence partitions or will I have to just manage with the repositories already given.

**Comment by damithc** [comment]
> And can I add repositories of people who fit the equivalence partitions or will I have to just manage with the repositories already given.

Ideally, try to manage with the repos we already have, unless it's not possible for some reason.

> Does this issue require the change in names in 'author-config' in the configs folder or in 'author-config'?

Whichever produces the desired outcome. First, find out where the names are coming from in the current set up.

On a related note, ideally, realistic names should be tested in both cases as a bug in name parsing can affect one but not the other.

**Comment by Tejas2805** [comment]
Since there is no specific restriction on the possibility of names (e.g., length can't be more than x, or the name cannot contains special characters like @), do I need to account for such edge test cases. E.g., a name that contains 5 dots (Tejas.....Bhuwania)

**Comment by damithc** [comment]
> Since there is no specific restriction on the possibility of names (e.g., length can't be more than x, or the name cannot contains special characters like @), do I need to account for such edge test cases. E.g., a name that contains 5 dots (Tejas.....Bhuwania)

Yes. Focus on cases that are likely to cause problems. It is unlikely five dots will cause a problem if two dots work.
