### ISSUE TITLE
Failing CI for MacOS only 

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1853]
**Tell us about your environment**

* **RepoSense Version:** `master` branch, on GitHub Actions
* **OS and Version:** MacOS 12
* **Web Browser and Version (if applicable):** Google Chrome Version 108.0.5359.125

**Please include the steps to reproduce the bug.**

1. Run continuous integration on GitHub Actions

**What was expected to happen?**
No errors

**What actually happened? Please include a screenshot of the output.**
CI fails but only for MacOS. Here is a sample [CI report](https://github.com/reposense/RepoSense/actions/runs/3720179430) with the error.

The screenshot below shows that there is an AssertionFailedError for certain tests in `CommitInfoAnalyzerTest.java`:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/69678785/210397795-ad17420d-954c-4d73-87d7-1a4bb39383c3.png">

The screenshot below shows that certain tests in `GitLogTest.java` also have AssertionFailedError:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/69678785/210398233-4594b96c-b512-4fdc-98f5-18061b414a82.png">

The first instance of this CI failure occurred on December 17 2022 at 9.08 pm. The last successful CI run was on the same day, but at 5.50 am:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/69678785/210398591-b8587ce4-0a51-4087-a10f-c7feb8e991d5.png">

This cannot be seen from looking at the picture alone. It is necessary to go to the [workflows page](https://github.com/reposense/RepoSense/actions/workflows/integration.yml), find the workflow runs for #1844 and #1499 and hover the cursor over the "2 weeks ago" line.

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by dcshzj** [comment]
It was due to an update to the Git version to 2.39.0 which I [identified here](https://github.com/reposense/RepoSense/pull/1851#issuecomment-1366394177). The tests run fine on Git version 2.38.1 but will break once it is upgraded to 2.39.0.

I think some adjustments will be needed to add support for the new Git version, or we have to find a way to downgrade the Git version used on the GitHub Actions runner.

**Comment by yhtMinceraft1010X** [comment]
I did some investigations and I suspect it's because `git log` (used in `CommitInfoExtractor`) did not return anything in MacOS.

Here's a sample git log command for author harryggg: `git log --no-merges -i  --pretty=format:">>>COMMIT INFO<<<%n%H|%n|%aN|%n|%aE|%n|%cI|%n|%s|%n|%w(0,4,4)%b%w(0,0,0)|%n|%D|" --numstat --shortstat --author="^fakeAuthor <.*>$\|^eugenepeh <.*>$\|^Yong Hao TENG <.*>$\|^.* <\(.*+\)\?harryggg.users.noreply.github.com>$\|^harryggg <.*>$" -- "*.adoc" -- "*.cs" -- "*.css" -- "*.fxml" -- "*.gradle" -- "*.html" -- "*.java" -- "*.js" -- "*.json" -- "*.jsp" -- "*.md" -- "*.py" -- "*.tag" -- "*.txt" -- "*.xml"`

**Comment by dcshzj** [comment]
Was the change in the output due to the difference in version? I found it weird that this issue only exists for macOS but not for Windows and Ubuntu.

**Comment by yhtMinceraft1010X** [comment]
> Was the change in the output due to the difference in version? I found it weird that this issue only exists for macOS but not for Windows and Ubuntu.

Can confirm that Windows has no problem when I tested it locally.

**Comment by Zhou-Jiahao-1998** [comment]
I am using MacOS and the problem occurs locally only after I updated my git version to the latest one.

**Comment by yhtMinceraft1010X** [comment]
> I am using MacOS and the problem occurs locally only after I updated my git version to the latest one.

@Zhou-Jiahao-1998 Have u tried running the git log command manually?

**Comment by zhoukerrr** [comment]
It does not return any result when `--author="^fakeAuthor <.*>$\|^eugenepeh <.*>$\|^Yong Hao TENG <.*>$\|^.* <\(.*+\)\?harryggg.users.noreply.github.com>$\|^harryggg <.*>$"` is added. I will look into the problem further.

**Comment by yhtMinceraft1010X** [comment]
> [Git version 2.39.0 release notes for reference](https://github.com/git/git/blob/v2.39.0/Documentation/RelNotes/2.39.0.txt)

I checked the release notes and I noticed something about the mac osx regex:
>  * With a bit of header twiddling, use the native regexp library on
   macOS instead of the compat/ one.

This might have been the reason why our code broke

**Comment by yhtMinceraft1010X** [comment]
> * With a bit of header twiddling, use the native regexp library on
>   macOS instead of the compat/ one.

Here is the [exact commit](https://github.com/git/git/commit/410a0e520dcc91d13f77fd812f068161859883fc) that changed it
