### ISSUE TITLE
Possible Concurrency Issue - RepoConfigParserTest

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1856]
**Tell us about your environment**

* **RepoSense Version:** N/A (development)
* **OS and Version:** Ubuntu 22.04 CI
* **Web Browser and Version (if applicable):** N/A

**Please include the steps to reproduce the bug.**
(Concurrency issue - may not be reproducible)
1. Run a test

**What was expected to happen?**
All tests pass

**What actually happened? Please include a screenshot of the output.**
When I was creating a PR for #1853, there was one failing test - `RepoConfigParserTest - merge_twoRepoConfigs_success()` in one run of the CI workflow. Running the CI workflow again results in the test passing:
![Screenshot (506)](https://user-images.githubusercontent.com/69678785/211193746-c9a5aad1-f507-4c30-8816-2b3009b0688d.png)

**If possible, include the URL to your RepoSense report or log files (if any).**
The relevant workflow run is here: https://github.com/reposense/RepoSense/actions/runs/3866800055. There were 2 workflow run attempts for the Ubuntu OS.

**Note about test concurrency**
Backend tests were parallelized in #1806. This was done due to the sheer number of tests cases we have.

**Comment by chan-j-d** [comment]
https://github.com/reposense/RepoSense/actions/runs/4130785264/jobs/7137805345#step:11:244 seems like it's not an isolated incident as well and just occurred again here
