### ISSUE TITLE
Some commits/tags missing in the RepoSense report

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1876]
Compare these two:
* RepoSense report https://nus-cs2103-ay2223s2.github.io/ip-dashboard/?search=jnjy&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt&since=2023-01-13&tabOpen=true&tabType=zoom&zA=jnjy&zR=jnjy%2Fip%5Bmaster%5D&zACS=260&zS=2023-01-13&zFS=jnjy&zU=2023-01-30&zMG=false&zFTF=commit&zFGS=groupByRepos&zFR=false
* https://github.com/Jnjy/ip/commits/master

Problem: some commits present in the repo are not shown in the RepoSense report

For example, GitHub shows 5 commits on Jan 29th but RepoSense shows only 2.

![image](https://user-images.githubusercontent.com/1673303/215505170-8d1f25c3-1f63-47eb-995a-d2d38fbaa180.png)

![image](https://user-images.githubusercontent.com/1673303/215505080-05f71780-97c7-43ea-a320-2be72683bfcc.png)

Furthermore, the commit https://github.com/jnjy/ip/commit/ae74c08f0d8086e775c2bcedacdbde5ba6a43f06 is shown in the report but a tag on that commit (`Level-9`) is not shown.
![image](https://user-images.githubusercontent.com/1673303/215506546-0b6390ca-c094-4577-bcc6-e7a11ae8bb2d.png)

**Comment by chan-j-d** [comment]
This could be related to https://github.com/reposense/RepoSense/issues/389 as I believe currently, RepoSense completely ignores merge commits. I'm not sure about the missing tag though.

**Comment by damithc** [comment]
> This could be related to #389 as I believe currently, RepoSense completely ignores merge commits. I'm not sure about the missing tag though.

Ah, right. Perhaps we can reconsider including merge commits in the ramp chart and the commit list. Perhaps we can show merge commit as very thin ramps (as they do not add new code)?

**Comment by chan-j-d** [comment]
Sounds good to me!

For anyone that wants to take up this issue, there are two parts: 
1. Show merge commits in the ramp charts (related to #389)
2. Finding out why the tag `Level-9` tag is missing from the commit

**Comment by chan-j-d** [comment]
Also to add, it seems that as of Git 2.36, Git supports finding out changes during conflict resolution in merge commits which might be relevant in the future. Source: https://stackoverflow.com/a/71181334

**Comment by damithc** [comment]
> 2\. Finding out why the tag `Level-9` tag is missing from the commit

Not sure why Github shows that tag in that particular commit -- because that tag actually resides in a different commit (which happens to be a merge commit). So, I assume the tag is missing because it's in a merge commit.

![image](https://user-images.githubusercontent.com/1673303/215518681-8d80ce48-6836-4e57-a20a-958d2f50afc4.png)

**Comment by damithc** [comment]
Closing in favor of #1877
