### ISSUE TITLE
code panel: de-emphasize untouched code

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#188]
Current:
![image](https://user-images.githubusercontent.com/1673303/42672822-c6b9a218-869a-11e8-8683-16798214d51a.png)

Suggested: A subtle symbol e.g., just `...` in grey

Justification: Untouched code is of less/no importance. They should not stand out more than the touched code.

**Comment by ongspxm** [comment]
i agree, will do together with the other UI changes

**Comment by damithc** [comment]
> i agree, will do together with the other UI changes

No hurry. Do one change at a time. Easier to merge/revert that way.

**Comment by AdityaA1998** [comment]
<img width="600" alt="screen shot 2018-07-25 at 16 35 55" src="https://user-images.githubusercontent.com/23259003/43189326-e1f281f2-9028-11e8-969d-d43039f87b82.png">

@damithc prof, does this look okay?

**Comment by damithc** [comment]
> @damithc prof, does this look okay?

Looks better now. May be remove the horizontal lines as well? This is how Gmail does it:

![image](https://user-images.githubusercontent.com/1673303/43192080-3004267e-902f-11e8-936d-a6e5c1694bf8.png)

BTW, I wonder if we can show the code in a white background? Can be a separate issue.

**Comment by damithc** [comment]
@AdityaA1998 can finish before deadline? If not, ask someone else to take over.

**Comment by AdityaA1998** [comment]
I will complete it @damithc
