### ISSUE TITLE
Code coverage report generation failure

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1902]
https://github.com/reposense/RepoSense/actions/runs/4144402216/jobs/7167473857#step:12:36
https://github.com/reposense/RepoSense/actions/runs/4143516826/jobs/7165453327

Code coverage is currently failing in some of our CI runs.

**Comment by yhtMinceraft1010X** [comment]
> Perhaps configure CI to go through even if code coverage tasks fails?
> 
> `fail_ci_if_error: false`

Is there any reason why we have been going with the default behaviour of failing the CI if codecov has an error? I thought about changing this but hesitated because it might be important.

**Comment by damithc** [comment]
I think normally we don't want a PR to reduce code coverage significantly.
After changing this setting, I expect PR reviewers have a higher responsibility of keeping an eye on how the PR affects the code coverage. One question is, after changing this setting, if the Codecov task completes (i.e., no error during upload) but the code coverage drops, would that cause the CI to fail?

**Comment by dcshzj** [comment]
> Is there any reason why we have been going with the default behaviour of failing the CI if codecov has an error? I thought about changing this but hesitated because it might be important.

It is an important aspect for observability. If we do not fail the CI when Codecov has an error, we would not know if the code coverage reports are correctly uploaded. Instead, by knowing it failed and why it failed, we can either re-run the CI or bypass the check entirely if the failure happens for an extended period of time.

**Comment by chan-j-d** [comment]
It seems it was some upstream issue that caused the CodeCov to fail. CIs are passing without issue now. I'll leave the issue open for a bit to discuss what we should do about the CI in event of codecov failure. I'm of the opinion that we can leave it as it is

**Comment by damithc** [comment]
> It seems it was some upstream issue that caused the CodeCov to fail.

Yes, this is an intermittent issue with Codecov that's been going on for a while.

**Comment by chan-j-d** [comment]
I think I'll close this issue as the outages seem to have occurred on two separate instances in the past week and not much before  which seems fine to me. Codecov is only run in 3 out of 6 of the CI runs and we can use the other 3 CI runs to look at whether the test cases pass. If the outages become worse then we can reconsider failing CI on codecov error.

**Comment by yhtMinceraft1010X** [comment]
> I think I'll close this issue as the outages seem to have occurred on two separate instances in the past week and not much before which seems fine to me. Codecov is only run in 3 out of 6 of the CI runs and we can use the other 3 CI runs to look at whether the test cases pass. If the outages become worse then we can reconsider failing CI on codecov error.

Just want to point something out: For each OS, if the Codecov run fails before the other run completes, the other run will be cancelled. However, I have a PR, #1885, that will stop them from cancelling.
