### ISSUE TITLE
Refactor CliArguments and subclasses to better utilize polymorphism

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1909]
### Currently, the logic of parsing of user inputs up to setting up repoConfigurations is as such
1. `ArgsParser::parse` does the following (1) sanitizes and formats the inputs (2) decides whether the reposense run should be a simple view, a CLI run or a config file run
2. After returning an instance of `CliArguments`, `RepoSense` main class decides based on the class type how to construct the corresponding `repoConfigurations` and `groupConfigurations`.

Note that once the `repoConfigurations` and `groupConfigurations` are setup, it no longer matters whether it is a CLI run or config file run.

### The alternative design I am proposing is as such:
1. `CliArguments` becomes a pure data (non-abstract) class that contains all the necessary fields that a user can provide
2. `RepoSense` (main class) looks at the fields and decide if it should immediately start a view mode (replacing `ViewCliArguments`)
3. If not a view run, `RepoSense` passes the `CliArguments` to a new class `RunConfigurationDecider` (better name suggestions are welcome) which will look at the `CliArguments` and decide if it should be a config file run or a CLI run in the form of an interface
4. Implement a new interface `RunConfiguration` with methods `getRepoConfigurations` and `getGroupConfigurations`, and concrete implementations `CliRunConfiguration` and `ConfigRunConfiguration` replacing `ConfigCliArguments` and `LocationsCliArguments` which handles the logic of how the respective `repoConfigurations` and `groupConfigurations` are constructed.

### I believe this design has the following advantages:
1. Reduces the length of `ArgsParser::parse` which is currently an extremely long method is likely doing too much.
2. Encapsulates specific run configuration behavior (CLI or config) to a specific class which makes it easier to maintain.
3. Allows us a slightly more extensible approach to implementing possible new run configurations via including the conditions in `RunConfigurationDecider` and implementing the new class.

**Comment by sikai00** [comment]
Overall I believe that this would be a good change and well worth the effort, for greater maintability, and clearer readability. When I first read through the code, I found myself easily confused by the large blocks of code handling the different types of run configurations sprawling throughout. This change can help us in creating better happy paths, which I believe is needed in the current RepoSense source code.

1. I believe there is no strong reason for the  current use of the polymorphism in CliArguments other than to check for the use of only 2 flags (--view for ViewCliArgument, --repos for LocationsCliArguments) and subsequently decide what to do. Working from a single CliArgument is far sleeker in my opinion, and can result in cleaner code.

   1. Small drawbacks: We will likely need default values for the fields unused. We will also need to be more prudent when accessing CliArgument to prevent accidental misuse of a field.

2. Currently, in ArgsParser.parse(), the CliArguments are returned in multiple places, resulting in low levels of readability. By reducing the CliArguments to become one single concrete class, we can create a better happy path, and abide to SLAP more easily.

3. I find ConfigRunConfiguration and CliRunConfiguration to be better names than ConfigCliArgument, LocationCliArgument, ViewCliArgument, given that these are the current two main ways to run RepoSense, and makes more intuitive sense.

**Comment by MarcusTXK** [comment]
An additional design change that I propose to implement would be changing `CliArguments` to use the builder pattern. This allows for producing different configurations of the `CliArguments` as well as avoiding having to use a giant constructor. The builder pattern also allows for new fields to be easily added if needed, so the config is easily extendible.
