### ISSUE TITLE
Commits view: sort everything in reverse chronological order

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1917]
Current: days are sorted in reverse chronological order while commits are sorted in chronological order

![image](https://user-images.githubusercontent.com/1673303/221339089-49570a1a-1aa4-4fe6-8245-9b3a49afd80f.png)

Suggested: Both should be sorted in reverse chronological order so that the full commits list in that page appear in the reverse order they were committed

**Comment by damithc** [comment]
Is this easy enough for a first-time contributor? If so, let's label as such.

**Comment by vvidday** [comment]
> Is this easy enough for a first-time contributor? If so, let's label as such.

Yup it should be fairly straightforward! To any new contributors who wish to attempt this, you might want to look into how commits are sorted in the zoom view.

**Comment by ckcherry23** [comment]
To anyone who is considering attempting this, just wanted to give a heads-up that there are a few frontend cypress tests that would break if we change the sorting order, which need to be fixed as well.

We could also consider making changes to the cypress tests such that they do not depend on the ordering of commits.

**Comment by pratham31012002** [comment]
Can I take up this issue if it isn't outdated? I had tried to fix this during phase 2 [here](https://github.com/pratham31012002/RepoSense/pull/1). Although this PR doesn't fix the cypress tests.

**Comment by ckcherry23** [comment]
Hi @pratham31012002, thanks for working on this. You can take up this issue and let us know if you face any issues with the Cypress tests.
