### ISSUE TITLE
Missing commit information from some authors

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#192]
A legacy problem has been highlighted in #187; some authors had contributed to the repository, however their commit information were not reflected in the dashboard.

>hmm, from the repo, it seems that [codeeong](https://github.com/CS2103JAN2018-F14-B1/main/commits?author=codeeong) do have some work though. I think we need to further investigate this.

It may be due to accurate author name were not provided. However, to be safe, lets investigate this issue.

**Comment by eugenepeh** [comment]
Hmm for the `lohtianwei`, it seems like authorship is able to recognise his contribution, hence I don't think its author name problem.

![image](https://user-images.githubusercontent.com/19277206/43032847-88d8d6c2-8cf2-11e8-86fd-e7c1365fcc12.png)

**Comment by yamidark** [comment]
For `lohtianwei` his `author name` that is set on the `git log` is actually `Tianwei`, but he set the name for collate correctly as `lohtianwei`, thus his line contribution is marked with collate, while his commits aren't.
https://github.com/CS2103JAN2018-F14-B1/main/blob/369aa760dc407e03fb999ae45d6dd7eb0a81b482/src/main/java/seedu/address/logic/commands/KeyCommand.java#L3-L6

For `codeeong`, her `author name` that is set on `git log` is actually `Codee`, and she also set the same name for collate as `Codee`, thus both her line and commit contribution are not recorded.
https://github.com/CS2103JAN2018-F14-B1/main/blob/369aa760dc407e03fb999ae45d6dd7eb0a81b482/src/main/java/seedu/address/ui/PlayerDetails.java#L15-L18

**Comment by eugenepeh** [comment]
>For codeeong, her author name that is set on git log is actually Codee, and she also set the same name for collate as Codee, thus both her line and commit contribution are not recorded.
https://github.com/CS2103JAN2018-F14-B1/main/blob/369aa760dc407e03fb999ae45d6dd7eb0a81b482/src/main/java/seedu/address/ui/PlayerDetails.java#L15-L18

Hmm, but then there is still 1 LoC credited to her. Need to investigate this further.

**Comment by yamidark** [comment]
>Hmm, but then there is still 1 LoC credited to her. Need to investigate this further.

From my investigation, getting the `git log`, that line was made inside this merge commit:
```
commit a48dbc91300e160b7975500c90a19db0510a5287
Merge: d4c419dc 70e8854a
Author: codeeong <33129797+codeeong@users.noreply.github.com>
Date:   Fri Apr 13 13:33:05 2018 +0800

    Merge branch 'master' into v1.5-tests


```
Since it is a merge commit, it is ignored by our `CommitInfoExtractor` since we set the flag `--no-merges`.
Also, as the merge was (probably) made inside Github, the author name set here is `codeeong` github ID.

However, when we do a `git blame`, the result is:
```
15f4d36a4 (lithiumlkid 2018-04-15 23:25:05 +0800  143)         }
e97b6d8ea (Codee       2018-04-11 20:20:51 +0800  144) 
15f4d36a4 (lithiumlkid 2018-04-15 23:25:05 +0800  145)         team.setPersons(new UniquePersonList());
a48dbc913 (codeeong    2018-04-13 13:33:05 +0800  146)     }
3eb959bf7 (jordancjq   2018-04-06 04:58:07 +0800  147) 
15f4d36a4 (lithiumlkid 2018-04-15 23:25:05 +0800  148)     /**
```
where that 1LOC is attributed to the github ID `codeeong`.
This is due to the `git blame` analysis not ignoring merge commits, and thus (somehow) attributed that line to `codeeong` after analyzing that merge commit.

**Comment by eugenepeh** [comment]
Great findings, may be a bit difficult to fix this trivial issue. Dropping priority for now.

**Comment by damithc** [comment]
Didn't affect any ongoing RepoSense reports since then. Let's close for now. Can reopen if it becomes relevant again.
