### ISSUE TITLE
Increase minimum version required for Git

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [reposense/RepoSense#1927]
### What feature(s) would you like to see in RepoSense

The [minimum version of Git required for RepoSense to run is `2.14`](https://reposense.org/ug/generatingReports.html). However, there is an additional requirement of Git version `2.23` for [the `--find-previous-authors` flag](https://reposense.org/ug/cli.html#find-previous-authors-f).

### Is the feature request related to a problem?

Having this additional requirement adds complexity - the need to check for the Git version when running RepoSense to support 2 different scenarios:

- Git versions `2.14` to `2.22`
- Git versions `2.23` and above

At this point in time, it is unlikely for anyone to have such an old version of Git. [Some versions](https://en.wikipedia.org/wiki/Git) had their last patch release in 2021, which suggests that they may not be worked on anymore.

### If possible, describe the solution

I propose raising the Git version requirement for both users and developers to `2.23`. 

Additionally, I suggest getting rid of the `GitVersion` checker entirely and letting the program fail when trying to find previous authors with an incompatible Git version. 

### Additional context

This should be flagged as a breaking change. Any release incorporating this should be numbered RepoSense `3.x.x` (assuming the current major version is still 2)

**Comment by MarcusTXK** [comment]
I agree with this suggestion to remove support for versioning below `2.23` as the last minor release for `v2.22` was March 9 2021 for [v2.22.5](https://github.com/git/git/releases/tag/v2.22.5).

Removing this versioning checks helps reduce the complexity of having to overwrite each of the configs for `isFindingPreviousAuthorsPerformed` as `false` if the version is within `2.14` to `2.22` in `setToFalseIsFindingPreviousAuthorsPerformedToRepoConfigs`, helping to reduce complexity and improve maintainability.

**Comment by jq1836** [comment]
Would like to ask for the status of this issue! Would like to work on this issue if it is still in need and not currently being worked on by someone else.

**Comment by ckcherry23** [comment]
Hi @jq1836, this issue is still open and relevant! 
Do let us know if you face any issues while working on it.

**Comment by jq1836** [comment]
Alright thanks for the quick reply! Would like to clarify the scope of this issue.

For the issue to be completed, the following have to be completed:
1. Removal of logic related to the detection of git version `2.23` and higher for the `--find-previous-authors` flag to be enabled/disabled.

Do correct me if I am wrong!

**Comment by ckcherry23** [comment]
@jq1836 Yes, that should be it, along with relevant documentation (and maybe tests).
