### ISSUE TITLE
Add missing CommitResultAggregatorTest

### ISSUE THREAD

**Issue by sikai00** [reposense/RepoSense#1932]
### What feature(s) would you like to see in RepoSense

Currently, there exist a `FileResultAggregatorTest` for the authorship side, but not for its counterpart in the commits side, `CommitResultAggregatorTest`. As mentioned in #1916, let's add this missing test.

### If possible, describe the solution

The solution will involve the creation of a branch in testRepo-Alpha in a similar fashion to that of its counterpart test. The test itself will have a similar logic to CommitsReporter.java, where the output of the test from aggregating the commits results will be checked against the actual output from the method through assertEquals.

**Comment by sikai00** [comment]
Upon further investigation, the purpose of the test done in FileResultAggregator was to test for the side effect of `FileResultAggregator::aggregateFileResult` clearing lines from `fileResult`, introduced in #1647. As `CommitResultAggregator::aggregateCommitResults` do not have any side effects anymore due to the changes in #1915, it seems that having a CommitResultAggregatorTest would be unnecessary.

@chan-j-d any thoughts on this?

**Comment by chan-j-d** [comment]
I don't really have any strong opinions on this. Seems like there's not much behavior we actually want to enforce here so it's fine. You can close the issue if you think there's nothing that you want to test.

**Comment by sikai00** [comment]
Closed as non-issue.
