### ISSUE TITLE
Link to DevOps guide is broken

### ISSUE THREAD

**Issue by sikai00** [reposense/RepoSense#1933]
### What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?

1. Under the [DevOps section in the developer guide](https://reposense.org/dg/learningBasics.html), the link to DevOps guide leads a Wiki link instead of redirecting to the DevOps guide on the actual Reposense website.
2. This is likely due to #1548, where the DevOps guide was shifted from Wiki to DG but the learning basics page itself was not updated.

### What would you like added or modified in the documentation?

1. Fix the broken link
2. If possible, look through the entire Reposense documentation for any other possible broken links.

**Comment by yhtMinceraft1010X** [comment]
I disagree with the use of the `FirstTimers` label. While first timer tasks should not be too daunting, they shouldn't be too simple (changing a single link) to the point where the contributor doesn't learn much.

Additionally, to check for links that lead to wrong sites (particularly sites that give 200 OK but are not the intended sites) in all our documentation is quite daunting. A first timer is unlikely to have enough experience with developing RepoSense to know exactly which link should go where.

**Comment by sikai00** [comment]
I see, removed the First Timers tag. My initial thought to do so was in consideration of those who had never made any PRs, etc.
