### ISSUE TITLE
Incomplete/wrong author name in commits panel after merge group

### ISSUE THREAD

**Issue by ckcherry23** [reposense/RepoSense#1934]
### Tell us about your environment

* **RepoSense Version:** Latest
* **OS and Version:** MacOS Monterey
* **Web Browser and Version (if applicable):** Chrome v110

### Please include the steps to reproduce the bug.

1. Merge a repo group having more than 1 author on the summary panel.
2. Click on the icon to see the commits panel for this merged group.

### What was expected to happen?
The author name is not shown OR the complete list of authors is shown.

### What actually happened? Please include a screenshot of the output.

The commits panel shows only the first author as the author name for all commits, just below the title. 

<img width="1440" alt="Screenshot 2023-03-08 at 2 26 48 AM" src="https://user-images.githubusercontent.com/68203159/223515812-dff9f162-0822-49db-a6c4-f3eb68274c2e.png">

### If possible, include the URL to your RepoSense report or log files (if any).
https://dashboard-1860-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=reposense%2Ftestrepo-Alpha%5Bmaster%5D&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=zoom&zA=chan-j-d&zR=reposense%2Ftestrepo-Alpha%5Bmaster%5D&zACS=118.69540229885058&zS=2017-10-09&zFS=&zU=2023-02-28&zMG=true&zFTF=commit&zFGS=groupByRepos&zFR=false&isTabOnMergedGroup=true

**Comment by damithc** [comment]
Good catch @ckcherry23
