### ISSUE TITLE
Link to all types of first timer issues in DG

### ISSUE THREAD

**Issue by ckcherry23** [reposense/RepoSense#1981]
### What feature(s) would you like to see in RepoSense
Add a link to all types of first-timer issues in the 'Workflow' section of the Developer Guide. 

### Is the feature request related to a problem?
Currently, the section is only linked to backend and frontend issues. However, there could be many other first-timer issues classified under `a-DevOps`, `a-Testing`, `a-Docs`, etc. that the potential contributors may miss out on. 
Though the 'Contributing' section links to all first-timer issues, it is more likely that new contributors will start looking for issues from the 'Workflow' section after they have completed setting up the project.

<img width="1440" alt="Screenshot 2023-04-08 at 12 27 37 AM" src="https://user-images.githubusercontent.com/68203159/230643650-af5a2e48-ef61-4353-8892-494f533a2080.png">

### If possible, describe the solution
* The ideal solution is to change our label assignment criteria such that each first-timer issue comes under at least one of `a-Backend` or `a-Frontend`. 
* If that is not possible or is hard to enforce, an alternative is to add more links to other types of first-timer issues such as DevOps issues, Testing issues, and Documentation issues into the workflow section.

**Comment by HCY123902** [comment]
May I suggest using the same link as that in the Contributing section instead? While `DevOps` can be a standalone category, `Doc` and `Testing` are more of affiliates of the main categories, and it will be difficult to strictly categorize them. Having the unified link seems sufficient since there are not that many first time issues

**Comment by logical-1985516** [comment]
I agree that we should use the unified link. If this issue has not been resolved, may I try it?

**Comment by ckcherry23** [comment]
Yes @logical-1985516, it's better if we make this change soon to help new contributors.
