### ISSUE TITLE
Wrong `sort within groups by` when visiting by url

### ISSUE THREAD

**Issue by MarcusTXK** [reposense/RepoSense#1982]
### Please include the steps to reproduce the bug.

1. If the url contains anything for `sort within groups by` for anything other than `↑ title`, it will get replaced by `↑ title`.
2. Observe  the gif below, where `↓ contribution` is selected and the changes are updated in the url. However upon copying the url and revisiting the page, the sort is changed back to `↑ title`.

![sortWithinGroupsByBug](https://user-images.githubusercontent.com/50147457/230679835-dfb5fad6-97c6-40b2-b508-5654f912b775.gif)

### What was expected to happen?
The sort should remain as configured by the user in the url.

**Comment by damithc** [comment]
Good catch, @MarcusTXK
