### ISSUE TITLE
Glob filter automatically reset after the second refresh

### ISSUE THREAD

**Issue by HCY123902** [reposense/RepoSense#1987]
### Tell us about your environment

* **RepoSense Version:** master 10
* **OS and Version:** Windows 10
* **Web Browser and Version (if applicable):** Edge

### Please include the steps to reproduce the bug.

1. Open a [report](https://dashboard-1911-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2018-03-01&timeframe=commit&mergegroup=reposense%2Ftestrepo-Alpha%5Bmaster%5D&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&zFR=false&tabAuthor=luozhijie-tom&tabRepo=p-repo-sense-test-repo%2Fcode%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=txt~java~md~fxml~gradle~xml~properties~gradlew~bat~MF~rej~TXT&authorshipIsBinaryFileTypeChecked=false&authorshipIsIgnoredFilesChecked=false)
1. Open any authorship contribution panel, such as this
![image](https://user-images.githubusercontent.com/54735123/230727701-8b4f1fc3-aca5-4af8-b83c-6d3ea051b6a6.png)

1. Enter a regex path in the glob filter to filter the file list, such as this
![image](https://user-images.githubusercontent.com/54735123/230727722-0f8d85ff-f9a4-40d6-9236-a0e87a3d68c2.png)

1. Refresh the page 2 times

### What was expected to happen?

1. The glob filter and list of remaining files should stay the same regardless of the number of times of refresh.

### What actually happened? Please include a screenshot of the output.

1. The glob filter input and list of remaining files stay the same after the first refresh
![image](https://user-images.githubusercontent.com/54735123/230727738-6d9058ba-a348-4506-b785-717e4d713d05.png)

1. However, after the second refresh, the glob filter and file list are reset to the initial state
![image](https://user-images.githubusercontent.com/54735123/230727826-0caef391-0a59-47f3-a3f9-0321e0d12ba8.png)

### If possible, include the URL to your RepoSense report or log files (if any).

https://dashboard-1911-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2018-03-01&timeframe=commit&mergegroup=reposense%2Ftestrepo-Alpha%5Bmaster%5D&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&zFR=false&tabAuthor=luozhijie-tom&tabRepo=p-repo-sense-test-repo%2Fcode%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=txt~java~md~fxml~gradle~xml~properties~gradlew~bat~MF~rej~TXT&authorshipIsBinaryFileTypeChecked=false&authorshipIsIgnoredFilesChecked=false

**Comment by ckcherry23** [comment]
Fixed by #2086
