### ISSUE TITLE
Reduce the scope of the try-catch block in ArgsParser::parse

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1989]
https://github.com/reposense/RepoSense/blob/53d5197d841fb1b801541b8f8414c04878d04913/src/main/java/reposense/parser/ArgsParser.java#L260-L261

Currently, the above `try` block covers the entire method. The scope of it should be reduced to cover only the method/s that throw these exceptions.

**Comment by MarcusTXK** [comment]
@nseah21 I noticed you made a PR addressing both #1989 and #1990 on your fork, https://github.com/nseah21/RepoSense/pull/1. Would you like to make a PR to RepoSense directly?

Also as a side note, we try to only address a single issue per PR, so it would be good if you could split that PR up before merging it in.

**Comment by nseah21** [comment]
@MarcusTXK I have split the original PR and opened two separate PRs for issues #1989 and #1990.
