### ISSUE TITLE
Update frontend DG documentation

### ISSUE THREAD

**Issue by ckcherry23** [reposense/RepoSense#1996]
### What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?
The HTML report section of the DG is not up-to-date with recent changes made in the project, such as the implementation of a Vue Router through issue #1974, which fundamentally altered the frontend structure. Moreover, some file names are still using `.js` extensions which also need to be changed to `.ts`.

### What would you like added or modified in the documentation?
Let us update the project's documentation to ensure it is relevant for the next release and reflects all recent changes made to the project.

**Comment by MarcusTXK** [comment]
To add on to this, I feel that the naming of the file names in [HTML report](https://reposense.org/dg/report.html) is outdated, as the names currently use underscores instead of dashes. (e.g. `c_summary.vue`, instead of `c-summary.vue`)
![image](https://user-images.githubusercontent.com/50147457/233600652-86ee3942-0bde-4733-902f-a4891a318837.png)

**Comment by yhtMinceraft1010X** [comment]
Results of a broken link scan run today on our doc site:
```
{
  "Date Generated": "23/04/2023 09:12",
  "URL List": [
    {
      "url": "https://github.com/reposense/RepoSense.git~master%7Crelease%7Ccypress",
      "status": 404,
      "state": "BROKEN",
      "parent": "https://reposense.org/RepoSense/ug/authorConfigSyntax.html"
    },
    {
      "url": "https://github.com/MarkBind/markbind/tree/vue3-migration;https://github.com/reposense/RepoSense.git~master%7Ccypress",
      "status": 404,
      "state": "BROKEN",
      "parent": "https://reposense.org/RepoSense/ug/authorConfigSyntax.html"
    },
    {
      "url": "https://github.com/reposense/RepoSense.git;https://github.com/MarkBind/markbind.git",
      "status": 404,
      "state": "BROKEN",
      "parent": "https://reposense.org/RepoSense/ug/authorConfigSyntax.html"
    },
    {
      "url": "https://github.com/reposense/RepoSense/blob/master/frontend/src/utils/api.js",
      "status": 404,
      "state": "BROKEN",
      "parent": "https://reposense.org/dg/report.html"
    },
    {
      "url": "https://www.java.com/en/",
      "status": 0,
      "state": "BROKEN",
      "parent": "https://reposense.org/ug/generatingReports.html"
    }
  ]
}
```

<img width="424" alt="image" src="https://user-images.githubusercontent.com/69678785/233814104-7e1e787d-fbc1-47c3-a18e-c4fba480d2c2.png">

For the first 3 examples, I noticed that the examples for the advanced syntax are treated as active links. I'm not sure if there's a way to disable the hyperlinks for these sites, so these can be left alone if there is no choice.

The last link for java is likely to be a false positive based on my previous experience running the link scan. The api.js link is the main link to change.
