### ISSUE TITLE
Dashboard: prevent crash due to excessive diff size

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#202]
When an author's contribution is beyond a certain size, we need a way to prevent the dashboard crashing if the user tries to view the code of that author.

**Comment by jamessspanggg** [comment]
Should we impose a limit on the number of lines we can display per file? e.g. if the number of lines of a file has > 5000 lines, we show a message such as:
`unable to display large file > 5000 lines, please click on the [here] to view the code`, where `[here]` links to the blame view of the file on GitHub.

**Comment by damithc** [comment]
Yes, we can limit. If the file is bigger, we can open the code view of that file only in a separate tab? Redirecting to GitHub is not nice because the details we display is different from what GitHub displays.

**Comment by jamessspanggg** [comment]
Hmm there might still be cases where the commits contain extremely large files as below and loading them might still not be feasible:

<img width="1097" alt="Screen Shot 2019-07-08 at 2 36 00 PM" src="https://user-images.githubusercontent.com/32864116/60788028-46fe2700-a18e-11e9-970b-a796304a1360.png">
<img width="991" alt="Screen Shot 2019-07-08 at 2 37 36 PM" src="https://user-images.githubusercontent.com/32864116/60788030-482f5400-a18e-11e9-8e31-796b2b6b88f6.png">

**Comment by damithc** [comment]
It's fine if an extremely large file cannot be opened but we cannot pre-determine the threshold because it depends on the user's machine. If we warn about the big file and allow the user to open it in a separate tab, if the page fails to load, the user can always kill the tab and go back without losing the entire report?

**Comment by chan-j-d** [comment]
Closed in view of both https://github.com/reposense/RepoSense/pull/1750 and https://github.com/reposense/RepoSense/pull/1647 being merged which puts limits on the file size being analyzed and limits on the number of characters being displayed when viewing the report which were aimed at solving a similar issue in https://github.com/reposense/RepoSense/issues/1504.
