### ISSUE TITLE
Authorship: incorrect line authorship when analyzing date range

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#203]
```
When a date range is supplied, the FileInfoAnalyzer will only
git blame on the range of commits that fall within the given
date range.

This may cause the authorship of certain lines that have not
been touched at all during the date range to be incorrectly
authored to a random author that commited in that date range.

Let's update the git blame command to run the git blame from
initial to the latest commit of that date range. In addition, let's
also update FileInfoAnalyzer to only analyze files that have been
modified during that commit range.
```

**Comment by damithc** [comment]
Can this be part of the upcoming release?

**Comment by yamidark** [comment]
>Can this be part of the upcoming release?

Working on it, should be done by the next release.

**Comment by yamidark** [comment]
As discussed with @damithc, we will be removing the `copy and move detection` in the `git blame` command when analyzing authorship. This is because the users commits should correspond to their contribution, and if necessary, users may use `collate` if they wish to identify if certain codes belong to them, instead of us trying to identify the 'original' author by ourselves. 

These `copy and move detection` may be brought back in the future as a user-supplied argument if they wish to have a 'stronger' analysis.
