### ISSUE TITLE
URL Changes upon refresh

### ISSUE THREAD

**Issue by SkyBlaise99** [reposense/RepoSense#2058]
### Tell us about your environment

* **RepoSense Version:** Current latest [5cd529f](https://github.com/reposense/RepoSense/commit/5cd529fb46809a7b8e1c9c27dc04f428b83e89f5)
* **OS and Version:** Windows 11
* **Web Browser and Version (if applicable):** Chrome Version 118.0.5993.71 (Official Build) (64-bit)

### Please include the steps to reproduce the bug.

1. Generate a report and view it `java -jar RepoSense.jar -repo https://github.com/reposense/RepoSense.git -v`
1. Click to view author's (Eugene's) contribution
1. Input `README.md` into `Filter by glob`
1. The current URL is http://localhost:9000/?search=&sort=groupTitle%20dsc&sortWithin=title&since=2018-05-03&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&zFR=false&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFilesGlob=README.md
1. Refresh the webpage, the URL changes to http://localhost:9000/?search=&sort=groupTitle%20dsc&sortWithin=title&since=2018-05-03&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&zFR=false&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFilesGlob=README.md%23%2F (extra `%23%2F`)
1. The search bar is now `README.md#/`

### What was expected to happen?
The search bar should remain at `README.md`

### What actually happened? Please include a screenshot of the output.

Before:
![image](https://github.com/reposense/RepoSense/assets/69448615/71578a82-99ee-4194-af67-ae61d939619a)

After referesh:
![image](https://github.com/reposense/RepoSense/assets/69448615/c5e1d5a8-4073-46fd-b98c-93f2fb20ca50)

**Comment by SkyBlaise99** [comment]
It seems to be related to #1987 in some ways, from what I observe, `%23%2F` is first attached to the url, causing the search input to be different, hence returning different or no results. At this point of time, the `authorshipFilesGlob` param seem to disappear from the url subsequently, hence upon the 2nd refresh, the Glob filter automatically resets.

**Comment by ckcherry23** [comment]
Fixed by #2086
