### ISSUE TITLE
Same Repository different branch overriding each other

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#206]
In the `.csv` config file, we may supply the same organization and repository,
but different branches for different authors.

In `CsvParser`, these will be separated these into two different `RepoConfiguration`s
,and analysis will be run separately, generating separate reports.

However, as we set the display name for each `RepoConfiguration` to only be the 
'organization' and 'repository', these different `RepoConfiguration`s will override each
other's report file as they are being generated into the same folder.

**Comment by yamidark** [comment]
[teammates.txt](https://github.com/reposense/RepoSense/files/2208142/teammates.txt)
The above file (converted to `.txt`) has 1 author `dalessr` in the `recycling-bin` branch, and 6 other authors in the `master` branch.

However, the report generated from this config file (as shown below) only shows the stats for the 6 authors in `master` branch, since the `recycling-bin` branch report has been overridden.
![screenshot from 2018-07-19 11-52-15](https://user-images.githubusercontent.com/18352498/42920628-3f03cd62-8b4a-11e8-9864-471762445f16.png)

**Comment by yamidark** [comment]
@eugenepeh @damithc  For your acknowledgement.

**Comment by damithc** [comment]
> @damithc For your acknowledgement.

ACK. I didn't notice it before. Good catch. Yes, let's go for a simple solution now (even if not efficient)

**Comment by yamidark** [comment]
Closed via #207
