### ISSUE TITLE
Add contributors section to the README

### ISSUE THREAD

**Issue by Kalyanimhala** [reposense/RepoSense#2061]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file!
![contributors](https://github.com/reposense/RepoSense/assets/147402107/6540a8c3-37b2-4722-8b46-37071a97486e)

**Comment by ckcherry23** [comment]
Hi @Kalyanimhala, thanks for creating this issue. Can I know if there is any approach you have in mind already to implement this? I think the @all-contributors bot from https://github.com/all-contributors/all-contributors can help.
