### ISSUE TITLE
Some browsers show extra element

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#209]
![image](https://user-images.githubusercontent.com/19277206/42927544-693027ee-8b67-11e8-9648-5f536949c53b.png)

This can be fixed by setting the `mui-select->label`
    `overflow-x` property to `visible`

e.g.
```
.mui-select>label {
    position: absolute;
    top: 0;
    display: block;
    width: 100%;
    color: rgba(0,0,0,.54);
    font-size: 12px;
    font-weight: 400;
    line-height: 15px;
    overflow-x: visible;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

**Comment by ongspxm** [comment]
eh, just checking, which browser are you using? windows right?

**Comment by damithc** [comment]
> eh, just checking, which browser are you using? windows right?

I get the same. Using Windows 10, Chrome.

**Comment by eugenepeh** [comment]
>eh, just checking, which browser are you using? windows right?

Yes windows, Edge.
