### ISSUE TITLE
Forward/Backward Navigation Using Browser Buttons

### ISSUE THREAD

**Issue by sopa301** [reposense/RepoSense#2090]
### What feature(s) would you like to see in RepoSense

Enable forward and backward navigation for RepoSense using the browser buttons.

### Is the feature request related to a problem?

No.

### If possible, describe the solution

Configure the Vue Router's currently used [Hash Mode](https://router.vuejs.org/guide/essentials/history-mode#Hash-Mode) to be able to handle this.

### If applicable, describe alternatives you've considered

Use the [HTML5 Mode](https://router.vuejs.org/guide/essentials/history-mode#HTML5-Mode) instead.

### Additional context

#2086 describes a PR that may be affected depending on whether this feature is implemented.

**Comment by MarcusTXK** [comment]
Hi @sopa301, this issue is a duplicate of #642, perhaps we could shift the discussion of the issue there

**Comment by ckcherry23** [comment]
Hi @sopa301, while this issue is a duplicate, it does contain more implementation details than the previous one. Hence I suggest we close that and keep this one open.
