### ISSUE TITLE
Improve UX of error message box when there are many error messages

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#2098]
When there are many error messages (e.g., many repos missing), the error message box becomes quite tall, pushing the primary report content too far down the page. An example is given below:
![image](https://github.com/reposense/RepoSense/assets/1673303/617bb1ba-f0fc-4ac9-a247-8d8a4803591c)

While not a big problem, it can be an eyesore during early stages of a project course, and can even give the impression that the entire report is broken (because the viewer can't see any non-error content at the first glance).

Perhaps we can show only a limited number of error message lines with a `show all ...` link to show the rest?

**Comment by ckcherry23** [comment]
Thanks for the suggestion prof. We can also try stating more specific, human-readable messages like 'The repository X could not be found' instead of 'Failed to clone X', if possible.
