### ISSUE TITLE
Ramp chart: optimize vertical space further

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#21]
![image](https://user-images.githubusercontent.com/1673303/37524650-6d6e8fda-2965-11e8-9440-9875a075f348.png)

Red lines can be moved closer to the main bar.
Names can be as small as font size of code (but can show in bold)

**Comment by ongspxm** [comment]
i think i shall start with this

**Comment by damithc** [comment]
Good idea.  :+1:

**Comment by ongspxm** [comment]
![image](https://user-images.githubusercontent.com/1430854/40156342-8c6c3aae-59cb-11e8-98b5-ba627b14ed79.png)

**Comment by damithc** [comment]
Can show a few more options of progressively closer?

**Comment by ongspxm** [comment]
![image](https://user-images.githubusercontent.com/1430854/40163634-e9865206-59e9-11e8-9c59-649b40cde4dd.png)
bar height @ 5px

**Comment by damithc** [comment]
bar height @ 3px is fine. Can you bring it closer to the ramp chart? I want to make it as close as possible.

**Comment by ongspxm** [comment]
![image](https://user-images.githubusercontent.com/1430854/40213436-026d5686-5a88-11e8-9f53-09eab314f49b.png)
bar height @ 3px, as close to the ramp chart as possible

**Comment by damithc** [comment]
May be a 1px or 2px gap between ramp chart and the contribution bar? Also, how does it look like when there are two bars i.e., the bar hits the right end and start again on the left?

**Comment by damithc** [comment]
One more thing: we can also reduce the gap between authors so that we can show more authors in less vertical space.

**Comment by ongspxm** [comment]
![image](https://user-images.githubusercontent.com/1430854/40215207-d3acbdf0-5a91-11e8-8a5e-b914f7bf6b82.png)
- double lined bar
- less vertical space

**Comment by damithc** [comment]
Nice. May be a tiny gap between the two bars in the double bar? Let's go bark to 3px width for bars. Otherwise I'm ok with the latest.

**Comment by ongspxm** [comment]
![image](https://user-images.githubusercontent.com/1430854/40215488-57112ba8-5a93-11e8-9355-ef67ab04727e.png)
one last time for confirmation

**Comment by damithc** [comment]
Looks good 👍
