### ISSUE TITLE
Align report title with right panel

### ISSUE THREAD

**Issue by ckcherry23** [reposense/RepoSense#2127]
### What feature(s) would you like to see in RepoSense
The report title inserted using the `title.md` asset must be aligned with the top of the contents of the right panel.

### Is the feature request related to a problem?
Misalignment leads to inconsistencies in the design.

### If possible, describe the solution
Adjust the padding of the various headings shown on the right panel (default case, Code Panel, Commits Panel) to be top-aligned with the report title. This is part of the bigger design goal to remove inconsistencies between the panels #1004.

### Additional context
Related to #2102

**Comment by jedkohjk** [comment]
Hi can I work on this issue?

**Comment by ckcherry23** [comment]
Sure @jedkohjk, let us know if anything isn't clear.
