### ISSUE TITLE
View report: handle 'nothing to show' situation gracefully

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#213]
v1.1.1

Context:
I ran the RepoSense with a future -since date, by mistake.
The analysis completed pretty quickly but I wasn't able to load the report generated. When I tried to load the zip file, nothing happened.

Suggested:
Load an empty dashboard, as 'nothing to show' is a legit usage scenario.

**Comment by damithc** [comment]
I used interns.csv I shared earlier. Note that it was v1.1.1, not v1.1.1a if that matters.

**Comment by jylee-git** [comment]
Can this be closed? #790 should have addressed this issue

**Comment by Tejas2805** [comment]
Can we close this issue now or still needs some work ? 

![Screen Shot 2019-10-17 at 2 39 41 PM](https://user-images.githubusercontent.com/35946746/66983818-077b9b00-f0ec-11e9-8a90-8c4ee98d1390.png)

**Comment by damithc** [comment]
> Can we close this issue now or still needs some work ?

I think so.
