### ISSUE TITLE
Code panel: not showing the correct files

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#214]
When switching from one to the other code panel's result, the corresponding files was not updated.
E.g. below should show KeyCommand.java but its still the README.adoc from the other author `Ahm (lithiumlkid)`

![image](https://user-images.githubusercontent.com/19277206/43033549-ad4e4238-8cfe-11e8-8806-dd1a8230e696.png)

**Comment by eugenepeh** [comment]
@ongspxm for your reference

**Comment by ongspxm** [comment]
Good catch. This is solved in #168, will clean it up and schedule for merge.
