### ISSUE TITLE
Show tags on the ramp chart

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#2148]
Somewhat related to #2109 

I'm wondering if we should support the ability to see the tags on the ramp chart side. For example,
![image](https://github.com/reposense/RepoSense/assets/1673303/0f3f94d8-023e-4073-8dad-05259fd26dd1)

Benefits: Easy to see which repos has which tags, can do a Ctrl+F for a tag

Considerations: performance, UI clutter

There is some overlap with #2109 but they are not exactly the same

If we were to implement it, most likely tags shouldn't be shown by default, but the user can make the appear by ticking a checkbox.

**Comment by jonasongg** [comment]
@damithc 
here's a screenshot showing:
1. the checkbox to toggle viewing all tags on top
2. what it looks like if the tags overflow into a new line
3. what it looks like if the tags don't overflow 
![image](https://github.com/reposense/RepoSense/assets/120372506/4a72806c-93b5-4727-b895-b9c84749fe34)
