### ISSUE TITLE
Support a minimal project.json

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#217]
The idea is to allow `{target repo}/_reponses/project.json` to provide RepoSense with some repo/author config data

More info in the [google doc](https://docs.google.com/document/d/17qDXIJ4jKKWlMuKcPmtOoLjr98hkel-l2Dt66tyK7vA/edit?usp=sharing)

To keep thing simple, we can allow project.json to override RS's own config files. We'll add an 'ignore repo-supplied config' flag in a future version.

We can download the files directly from the repo using an http request. We can look for a better way to get the files in a later version.

**Comment by eugenepeh** [comment]
Is this to allow the repo owner to key in their own particulars? E.g. white list authors, their author names etc?

**Comment by damithc** [comment]
> Is this to allow the repo contributors to key in their own particulars? E.g. white list authors, their author names etc?

Yes. If you remember, we decided to let the repo use a single json file instead of maintaining their own versions of author-config.csv and repo-config.csv.

**Comment by damithc** [comment]
Any suggestions for a better name? `_reponses/config.json`?

**Comment by eugenepeh** [comment]
>Any suggestions for a better name?

Since it records the authors' details, perhaps ` _reponses/authors.json`?

**Comment by damithc** [comment]
> Since it records the authors' details, perhaps _reponses/authors.json?

It records both author details and repo-wide details, such as file exclude patterns.

**Comment by eugenepeh** [comment]
>It records both author details and repo-wide details, such as file exclude patterns.

I see, then `_reponses/config.json` is fine i guess

**Comment by yamidark** [comment]
Resolved in #232
