### ISSUE TITLE
Migrate to Java 11 Syntax and Features

### ISSUE THREAD

**Issue by asdfghjkxd** [reposense/RepoSense#2177]
### What feature(s) would you like to see in RepoSense

The current language support on which our codebase is written is based on Java 8. However, we should look into migrating to Java 11 LTS for better security, features and APIs.

**EDIT:** After checking the API documentation, it appears that the `HttpServer` implementation introduced in JDK 11 is part of the `com.sun` package, which is discouraged from use due to the JRE-specific implementation of these packages, meaning that users of other JREs other than `openjdk` may not be able to use it without breaking. As such, it might not be prudent to change the existing HTTP server packages that we are using right now for the new, implementation-specific HTTP server internal package offered by the JDK.

### Is the feature request related to a problem?

Related to #1304.

### If possible, describe the solution

We could refer to these websites on the new features introduced in [Java 9](https://www.baeldung.com/new-java-9), [Java 10](https://www.baeldung.com/java-10-overview) and [Java 11](https://www.baeldung.com/java-11-new-features), and evaluate if the new features offered by Java 9, 10 and 11 can be implemented into the current codebase.

### If applicable, describe alternatives you've considered

N/A

### Additional context

This is potentially a large issue and may require multiple issues and PRs to resolve. The following are tasks that we need to complete to successfully migrate from Java 8 language support to Java 11 language support.

- [x] Update CI/CD to Java 11 [in progress at #2183, related to #2161 and #2172]
- [x] Update checkstyle to v10
- [x] Update APIs to Java 11
- [x] Update Syntax to Java 11

**Comment by asdfghjkxd** [comment]
Closing this issue as we have migrated over to Java 11, and have introduced Java 11 syntax that is non-compatible with older versions of Java.

**Comment by ckcherry23** [comment]
We can create a new issue for upgrading checkstyle.
