### ISSUE TITLE
Unintended color change in line numbers

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#2184]
![image](https://github.com/reposense/RepoSense/assets/1673303/18fa4b17-fc43-4d79-ac1b-bf897479327a)

All line numbers should be the same color, right?

**Comment by sopa301** [comment]
Apologies prof, it seems to be another bug that came from moving the Segment CSS into the Segment file.

The bug occurred when the CSS for the Segment file was set to scoped, which somehow interfered with the overriding of the hljs CSS.

I'll push a fix and tests ASAP.
