### ISSUE TITLE
Lines changed not appearing correctly

### ISSUE THREAD

**Issue by jonasongg** [reposense/RepoSense#2193]
For the current Cypress configuration, the user `WANG CHAO` for `reposense/publish-RepoSense[master]` appears to have 0 lines changed which does not match up with the actual commits made.

The same issue happens when running `./gradlew run -Dargs="--repos https://github.com/reposense/publish-RepoSense.git --since 31/1/2017"` followed by `./gradlew hotReloadFrontend`.

![image](https://github.com/reposense/RepoSense/assets/120372506/55304f34-b444-48db-90fb-8b3646873652)
![image](https://github.com/reposense/RepoSense/assets/120372506/5778ac90-92d5-427e-a0d0-7efa56c1d68a)
![image](https://github.com/reposense/RepoSense/assets/120372506/cddebf29-f35a-40c6-b530-8b24f64c17f4)

**Comment by ckcherry23** [comment]
Thanks for bringing this up @jonasongg! 

I took a look at the commit history, and it appears that the code analysis is working as expected. The user Wang Chao (fzdy1914) only has those commits under his authorship as he was the one who merged the PRs. The original PRs were authored by Hsu Zhong Jun (dcshzj) as seen in https://github.com/reposense/publish-RepoSense/pull/9 and https://github.com/reposense/publish-RepoSense/pull/10. The lines shown as changed by Wang Chao are the same lines edited by Hsu Zhong Jun in his PRs. 

Hence, everything seems to be accurately reflecting the contributions from both users. Let me know if I missed something, else we can close this issue. Thanks for your attention to detail!
