### ISSUE TITLE
Standardize term: dashboard vs report

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#220]
Do we need both terms? If not, let's choose one and eliminate the other.

**Comment by eugenepeh** [comment]
I always thought that dashboard refers to the UI, while report refers to entire thing with the results.

It feels weird to me that we mentioned `generate the dashboard` when its actually the data that we are generating.

**Comment by damithc** [comment]
You have a point. But can become confusing to users. May be use `dashboard data`, as in _generate dashboard data_ and  _view dashboard_?

**Comment by damithc** [comment]
Looks like we ended up using _report_. Closing.
