### ISSUE TITLE
run.sh: provide a flag to indicate major version

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#2208]
Context: see https://reposense.org/ug/runSh.html

Suggested: provide a way to specify that the latest release of a specific major version should be used.
For example `--version 3.*` will use the latest version that starts with `3.`

Justification: This way, the user can take advantage of latest bug fixes while avoiding breaking changes (assuming breaking changes will only be introduced in new major versions)

**Comment by jedkohjk** [comment]
Hi, I'm interested in taking this issue, but it appears that it will require changes to the [publish-RepoSense repo](https://github.com/reposense/publish-RepoSense/tree/master)? Should we make a PR to that repo?

**Comment by ckcherry23** [comment]
@jedkohjk Yes, you can make a PR to the [publish-RepoSense repository](https://github.com/reposense/publish-RepoSense/tree/master).

**Comment by jedkohjk** [comment]
Hi, is it okay to do this as an extension of the `--tag` flag instead? That is, allowing `--tag` to take in an expression with the wildcard `*`, then picking the latest version that fits that expression.

**Comment by gok99** [comment]
Hi @jedkohjk, sounds good to me. This'd be a natural extension of the `--tag` flag.

**Comment by jedkohjk** [comment]
Hi, I made a PR related to this 3 days ago. Can anyone review it? Thank you!
