### ISSUE TITLE
blurbs.md: Allow blank lines before repo/branch

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#2209]
Current:

In the `blurbs.md`, the following works:
```
https://github.com/org1/repo1/tree/master

some info about repo1

<!--repo-->--------------------------------------------------------
https://github.com/org2/repo2/tree/master

some info about repo2
```
but the following does not (due to the blank line below the separator):
```
https://github.com/org1/repo1/tree/master

some info about repo1

<!--repo-->--------------------------------------------------------

https://github.com/org2/repo2/tree/master

some info about repo2
```

Suggestion: While not very important, we can also allow the 2nd one, simply by doing a `trim()/strip()` before processing each block of text.

Justification: the 2nd one is easier on the eye, when authoring the `blurbs.md`.

**Comment by jedkohjk** [comment]
Hi, I made a pull request for this issue!
