### ISSUE TITLE
'group by repo' is behaving like 'group by branch'

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#222]
v1.1.1a

Branches of the same repo are shown as different groups
Example:
![image](https://user-images.githubusercontent.com/1673303/43042599-2956f5e4-8db5-11e8-9b51-35956b808b9e.png)

On a related note, using underscore format may not be best here as any of the three names can have their own underscores e.g, my_org_my_repo_some_branch_name
May be `[org][repo][branch]`?

**Comment by ongspxm** [comment]
so we are using the square brackets kind of as delimiters?

**Comment by damithc** [comment]
> so we are using the square brackets kind of as delimiters?

Yes, instead of underscore. Other suggestions welcome.

**Comment by eugenepeh** [comment]
`/` is not allowed to be used in org and repo name on GitHub. Perhaps `org / repo [branch]` would be better? It is closer to the GitHub `org / repo` style so I think it would be more intuitive to the users.

**Comment by damithc** [comment]
Main issue no longer relevant. Will open a new issue for the naming problem.

**Comment by Tejas2805** [comment]
Closing this issue as the issue is no longer relevant.
