### ISSUE TITLE
Possible typo in UG

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#2220]
Refer https://reposense.org/ug/authorConfigSyntax.html

![image](https://github.com/reposense/RepoSense/assets/1673303/4117b497-5499-4a2c-8ef0-ed53c06ec759)

Should this cell be empty (because branches are specified in the first cell already)?

**Comment by gok99** [comment]
I think the column might have been left specified to demonstrate the point on precedence:

> The branch specified through the delimiter syntax will take precedence over the Branch column

I agree this might be confusing on first glance, and am okay to empty the cell

**Comment by damithc** [comment]
> I think the column might have been left specified to demonstrate the point on precedence:
> 
> > The branch specified through the delimiter syntax will take precedence over the Branch column

@gok99 Yes, that might have been the intention. I didn't spot it at first. 


> I agree this might be confusing on first glance, and am okay to empty the cell

Yes, I think best to remove it, as it is better for main example to follow the expected/proper way to use the feature being explained.

**Comment by logical-1985516** [comment]
Hi, may I check if this issue has been resolved, and if not, may I try it?

**Comment by ckcherry23** [comment]
Hi @logical-1985516, this issue isn't resolved yet, you can work on it.
