### ISSUE TITLE
Dashboard: default view: sort by name within repo

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#223]
v1.1.1a

Current: the default view is grouped by repo and sorted by contribution within the group.

Suggested: group by repo but sort by name within the group

Reason: Sort by contribution puts an unnecessary focus on the contribution LoC which may not be a true reflection of the true contribution.

**Comment by eugenepeh** [comment]
@damithc , would you prefer the default view to be sorted by the config input order instead?
If we sort by name in lexicographical order, Wednesday group `WXX` will always be listed at the back.

**Comment by damithc** [comment]
> @damithc , would you prefer the default view to be sorted by the config input order instead?

That's an excellent point. Yes, it is better for the default order to be the one specified in the config files.
