### ISSUE TITLE
Add back the bookmark feature

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#224]
In v1.0 we had a feature to generate a permalink that users can bookmark to visit a particular view of the dashboard. This feature is very important because tutors should be able to go to a specific filtered view in one step. 

v1.1.1a doesn't seem to have this feature anymore.

Suggested: add the feature back.

**Comment by eugenepeh** [comment]
>In v1.0 we had a feature to generate a permalink that users can bookmark to visit a particular view of the dashboard. This feature is very important because tutors should be able to go to a specific filtered view in one step.

I am not sure if this is necessary. The link is always updated whenever user adjust the search settings; they can simply use the browser's bookmark function.

**Comment by damithc** [comment]
> I am not sure if this is necessary. The link is always updated whenever user adjust the search settings; they can simply use the browser's bookmark function.

Yes, that's even better. That feature is not working ATM. Let's leave this issue open until it's working again.
