### ISSUE TITLE
Update report generation datetime format

### ISSUE THREAD

**Issue by jedkohjk** [reposense/RepoSense#2240]
### What feature(s) would you like to see in RepoSense

Currently, the report generation datetime is shown as `E MMM dd HH:mm:ss yyyy z`.

![Screenshot](https://github.com/user-attachments/assets/24bbcf2c-034c-4b9e-a3b5-f6768d480aee)

Separating the year from the rest of the date is unintuitive. A format like `E dd MMM yyyy HH:mm:ss z` may be more intuitive.

### If possible, describe the solution

Change the datetime formatter to use the proposed format.

**Comment by damithc** [comment]
> Separating the year from the rest of the date is unintuitive.

Yes, it may be better to put the year together with the rest of the date.
