### ISSUE TITLE
Dashboard does not work with microsoft edge

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#239]
![image](https://user-images.githubusercontent.com/19277206/43246393-1aa21d80-90e4-11e8-8477-412cd8d31800.png)

![image](https://user-images.githubusercontent.com/19277206/43246376-0be4a10a-90e4-11e8-8219-b0e1f2711f99.png)

**Comment by damithc** [comment]
If this is not going to be fixed by next milestone, may be mention it in user docs first?
