### ISSUE TITLE
Ignore glob list does not propagate to code view

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#262]
Following #218 and #248, file exclusion glob patterns can be supplied in the
`csv config files` and `_reposense/config.json`.

Files excluded by the glob patterns only apply to ramps but not code snippet in code view.

In the below diagram, `**.java` is excluded. 
Notice that exclusion works on ramps but not code view.

![codee](https://user-images.githubusercontent.com/2003406/43525730-343a67de-95d5-11e8-88b6-2aff46502e7e.png)

**Comment by yong24s** [comment]
@yamidark 

`git log` and Java's `PathMatcher` may use a different `glob` standards?

As far as I know, `ramps` use `git log` for `glob` and `code view` use `PathMatcher`. 
Is that correct?

**Comment by yamidark** [comment]
I believe this may be because of the annotations did not ignore for the file path, will go test and resolve it asap.
