### ISSUE TITLE
Add timezone to ramp's github redirect link

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#263]
Occasionally, clicking a ramp will show no commits found for the specified user. This is because our git log command uses a constant timezone (Singapore UTC+8) and this mis-align with the GitHub time system.

Let's fix this by adding the timezone to the github redirect link as well.

**Comment by yamidark** [comment]
https://github.com/reposense/RepoSense/commits/master?author=eugenepeh&since=2018-05-02&until=2018-05-03 no commit
but https://github.com/reposense/RepoSense/commits/master?author=eugenepeh&since=2018-05-02'T'00:00:00+08:00&until=2018-05-03'T'23:59:59+08:00
