### ISSUE TITLE
Dashboard: remove unused icon in the code view

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#270]
This seems to serve no purpose
![image](https://user-images.githubusercontent.com/1673303/43589766-042d9f3e-96a2-11e8-8bc4-22d4fb241534.png)

Remove if not needed.

**Comment by ongspxm** [comment]
this is to future proof when we have the "list" view and the "diff" view
- list view to view list of commits of a specific time period, also to
remove dependency on github
- diff view to view diff of particular commit, after per commit view is in

**Comment by damithc** [comment]
Ah I see. Let's remove it until it is actually needed. Generally we shouldn't add things 'to be used in future' (see [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)). We can always revert the commit when we actually need it.

**Comment by ongspxm** [comment]
roger that, i will remove it
