### ISSUE TITLE
Allow author-config.csv to step in when config.json is missing

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#272]
e.g., `repo-config.csv` has 2 repos `foo`, `bar`
* `foo` has provided a `config.json`. 
* `bar` has not provided a `config.json`

We should be able to provide author data of repo `bar` in `author-config.csv` while using `config.json` for `foo`.

Justification: to cater for cases where student team hasn't added the json file on time.

**Comment by damithc** [comment]
@yong24s is this already supported?

**Comment by yong24s** [comment]
@damithc Yes, you can test it with the interns config files.
Remove RepoSense contributors in `author-config.csv`.

**Comment by damithc** [comment]
Great. In that case we can rescope this issue as follows:
* if author-info are present in both config.json and author-config.csv, use config.json
* But allow repo-config.csv to overrule config.json i.e., an additional column containing a flag

Reason: this is to cater for cases where config.json is valid and present but we don't want to follow it e.g., it excludes some files that we don't want to exclude.
