### ISSUE TITLE
Code view: tweak the collapse/expand button

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#273]
Current:
![image](https://user-images.githubusercontent.com/1673303/43592697-bf8dbc2c-96a8-11e8-90c9-3ad6d5e2a8c3.png)

Suggestions:
* Reduce vertical space used. No need for such a big gap between touched and untouched code. 
* Move the button closer to green/grey gutter lines. it can even overlap the lines
* Use `+` and `-` instead of `...`?

e.g.,
```
 ||
 ||
(+)
 ||
```

**Comment by ongspxm** [comment]
@AdityaA1998 i refactored the toggling code in #289, might wanna work from there instead

**Comment by eugenepeh** [comment]
Similar issue as #312
