### ISSUE TITLE
User Guide: add FAQ section to address common problems

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#297]
E.g. 
- _How does formats and ignore glob list works?_
- _Does RepoSense work on private repositories?_ 

This helps to resolve some TLDR issues.

**Comment by yamidark** [comment]
Can perhaps also add this [link](https://help.github.com/articles/changing-author-info/) on a script to change author name, since we now invalidate some author names but they may have a long list of commits that uses those invalid characters

**Comment by yamidark** [comment]
our local git copy will still be the original local author name right, which may need to be changed?

**Comment by eugenepeh** [comment]
> our local git copy will still be the original local author name right, which may need to be changed? 

Yep, just that that alone isn't totally full proof cause of GitHub feature.
E.g. if a repository that uses only squash merge, will experience no difference changing the local author name.

**Comment by yamidark** [comment]
Our repo uses only squash merge and I could change the local author names to ignore commits in #261?

**Comment by eugenepeh** [comment]
>Our repo uses only squash merge and I could change the local author names to ignore commits in #261? 

Oh I thought u mean just changing the author name for future commits, as described in [user guide](https://github.com/reposense/RepoSense/blob/master/docs/UserGuide.md#git-author-name). Though its not practical (because need to overwrite the master branch), but I guess we can put it into FAQ section as well. Will need to mention the github profile name needs to be updated too.
