### ISSUE TITLE
Report: add a link to direct user to user guide

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#298]
As per title.

**Comment by apoorva17** [comment]
@eugenepeh do you want a User Guide button located on the dashboard which opens the user guide in a new window? Is there any position on the dashboard where you would like the User Guide button to be located?

**Comment by eugenepeh** [comment]
> @eugenepeh do you want a User Guide button located on the dashboard which opens the user guide in a new window? Is there any position on the dashboard where you would like the User Guide button to be located?

Since we already have a link which direct user to the RepoSense, this issue is kind of resolved.
Sorry that i have forgotten to close this issue.

**Comment by eugenepeh** [comment]
Resolved in #321
