### ISSUE TITLE
Add a testrepo with minimal standalone config

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#319]
This is to test all the default values.

**Comment by bluein-green** [comment]
Do you mean that the test repo should only have a standalone config? And that it should only have the mandatory fields filled in (i.e. only `githubId`)?

**Comment by eugenepeh** [comment]
Can't remember the exact need for this at the moment, let me recall and get back to you @bluein-green 

@yong24s do you remember why we had this need before?

**Comment by yong24s** [comment]
Don't think we assign default values to any fields in `StandaloneConfig`.

**Comment by eugenepeh** [comment]
Ahh, yes. This PR is to leave as many field empty as possible, so that we can check that all the others get assigned default value and are correct. Thanks @yong24s @bluein-green

**Comment by bluein-green** [comment]
Do you mean something like [this](https://github.com/reposense/testrepo-minimalStandaloneConfig)?

**Comment by eugenepeh** [comment]
Don't even need author name, the repository can be empty as well since we don't test the content in the repo.

**Comment by bluein-green** [comment]
I've updated the repo as desired.

**Comment by eugenepeh** [comment]
>I've updated the repo as desired.

Thanks @bluein-green , would you also be putting up the unit test for the standalone config?

**Comment by bluein-green** [comment]
I can do that. Should it target `RepoConfiguration#update` in `ReportGenerator#updateRepoConfig`?

**Comment by eugenepeh** [comment]
>I can do that. Should it target RepoConfiguration#update in ReportGenerator#updateRepoConfig?

Yes, I believe so if i remember correctly.
