### ISSUE TITLE
Docs: terminology revise

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#330]
We should revise some of the terminologies such as:
- Standalone Config
- CSV Config - repo-config, author-config
- Chart Panel / Chart View
- Code Panel / Code View

**Comment by damithc** [comment]
@eugenepeh is this resolved?

**Comment by eugenepeh** [comment]
@damithc not yet... we can probably discuss on the 19th.

**Comment by anubh-v** [comment]
What was the outcome of the discussion?
My view is that `standalone config` should be given a more distinct name from the CSV config files, especially since the `--config` option is used for the CSV configs.

**Comment by eugenepeh** [comment]
>What was the outcome of the discussion?

- Standalone Config
- CSV Config - repo-config, author-config
- ~~Chart Panel~~ / **Chart View**
- ~~Code Panel~~ / **Code View**

Standalone config and the csv configs could still use better names if you have any suggestions.

**Comment by fzdy1914** [comment]
Closing it as we are using standardlized:

- Standalone Config
- CSV Config - repo-config, author-config
- Chart Panel
- Code Panel
