### ISSUE TITLE
Dashboard crashes when modify date to be out of range

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#336]
When we try to modify the date of the Since or Until filter in the dashboard,
if the date specified is out of range, like setting year 2020 for until date,
or any year for the since date (since typing the 1st number will set it to be that year 1st), 
the dashboard will hang, and then crash.
This can also occur while shifting the numbers using the arrow keys.

**Comment by eugenepeh** [comment]
Hmm think we need to set a cap to the range, and also some delay to accept user input.

**Comment by ongspxm** [comment]
We can do a set global min and max date then set that as the cap?

**Comment by eugenepeh** [comment]
>We can do a set global min and max date then set that as the cap?

That works too
