### ISSUE TITLE
Add empty repo test

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#338]
While its not logical to do it, it is possible to clone an empty repository.

Let's make our application foolproof to this scenario.

** created https://github.com/reposense/testrepo-Empty for this case.

**Comment by eugenepeh** [comment]
> @eugenepeh you do not want it to clone an empty repo or you just want to test the scenario where it clones an empty repo? Because currently when cloning an empty repo, it still terminates the analysis as no branch exists.

Actually, more like I want to handle this scenario more gracefully. Instead of branch does not exists, perhaps empty repo would be a more appropriate response. 

Anyway this is just a low priority issue, can work on other more important issues at hand for now.

**Comment by fzdy1914** [comment]
Close this by #644
