### ISSUE TITLE
Collapsed chunks: cosmetic tweaks

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#34]
![image](https://user-images.githubusercontent.com/1673303/37822191-bfc99c38-2ec0-11e8-8fcf-b7939e584733.png)

Collapsed chunks should not attract too much attention
Things to try:
*  Remove boarder
* Use grey, non-bold text
* Use a glyphicon or symbols instead of text e.g.,
  >← · · · →

**Comment by ongspxm** [comment]
duplicate of #188
