### ISSUE TITLE
Lone search result with no contribution shown as full-length bar

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#342]
![image](https://user-images.githubusercontent.com/1673303/45914126-17866400-be73-11e8-93c4-62a7bf53a6d0.png)

Steps:
Go to a dashboard (e.g., https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard) and search for the name of an author who doesn't have any contribution yet. Choose the keyword in such a way only that author will appear in search results.

Expected: empty contribution bar

Actual: full-length contribution bar

**Comment by eugenepeh** [comment]
> In fact, the length of the bar seems to vary based on which authors are displayed. That should not be the case. The scale used for the bar should be fixed for a given period irrespective of which authors are displayed. In other words, search filters should simply filter out certain authors without changing anything else.

Actually I brought the log-scale into discussion previously was precisely due to this issue.
If we set a fixed scale for the length of the bar e.g. 1 full bar = 1000 lines, an author who suddenly throw in a large json file will have tens to hundreds bars.

Suggestion :
Have several bars with logscale implementation
1st bar -> 0-1,000 lines (green)
2nd bar -> 1,000-10,000 lines ( yellow)
3rd bar -> 10,000 - 100,000 (orange)
4th bar -> 100,000 - 1,000,000+++ (red)

**Comment by eugenepeh** [comment]
This way we still can easily identify the difference in users' contribution, e.g. between 3,000 and 4,000.

**Comment by damithc** [comment]
This problem is not related to log scale. Once a scale has been calculated for a data set, it has to be applied consistently for all search results. The scale should not be calculated dynamically for each search result. The same author should not be shown with different length bars just because he is appearing among different authors. In other words, _search_ is simply a way to filter out some authors without changing anything else.

**Comment by eugenepeh** [comment]
> This problem is not related to log scale. Once a scale has been calculated for a data set, it has to be applied consistently for all search results. The scale should not be calculated dynamically for each search result. The same author should not be shown with different length bars just because he is appearing among different authors. In other words, search is simply a way to filter out some authors without changing anything else.

I see. I guess, in that case, we can probably solve it with a global variable.
