### ISSUE TITLE
Implement progressive loading in code view

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#351]
as per title, loading a huge change often takes long time. 

_"It's important to deliver something meaningful to the user as soon as possible — the longer they wait for the page to load, the bigger the chance they will leave before waiting for everything to finish."_
Quoted from the Mozilla

**Comment by eugenepeh** [comment]
> Eh... if we want to do this, we might have to split up the json file for
the authorship worh

Possible to tackle the reading of data later and fix the ui generation first?

**Comment by ongspxm** [comment]
You want read a bit print a bit ah? Cos in the end still need read thru all
the files worh. I would think its the parsing of all the files that is
lagginf it, not really the display.

**Comment by eugenepeh** [comment]
![image](https://user-images.githubusercontent.com/19277206/46326532-c5420180-c62f-11e8-8b6a-636da1b666f3.png)

The breakdown on the loading of huge file. Seems like rendering takes up most of the time as well.

**Comment by ongspxm** [comment]
Wut do you have in mind? We split up the authorship data?

**Comment by ongspxm** [comment]
Then we can do bit by bit as the files roll in

**Comment by damithc** [comment]
Closing for the time being as this doesn't seem to affect current use cases.
