### ISSUE TITLE
Add quick guide for users to use reposense with Netlify

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#352]
So that user can easily fork our repo, update the repo-config.csv and author-config.csv and view the analysis of their repository on Netlify

**Comment by yamidark** [comment]
Do you mean to analyze the forked `RepoSense` repository, or their own repository?
If it is for their own repository, we should be asking them to add the `.jar` file into their repository so they can run `RepoSense` on their own repository for `Netlify?

**Comment by eugenepeh** [comment]
> Do you mean to analyze the forked RepoSense repository, or their own repository?
If it is for their own repository, we should be asking them to add the .jar file into their repository so they can run RepoSense on their own repository for `Netlify?

Eh I mean to analyze their own repository. Like how we preview our Netlify result everytime.

**Comment by Tejas2805** [comment]
@eugenepeh I looked into this. What you are saying is possible:

1) If the user authorizes Netlify to access their forked repository and sets up Netlify for production deploy or branch deploy accordingly.
2) Only if it is a pull request. I can't seem to find a way to preview with Netlify for commits.

> use their main repo's webhook to trigger the forked repo's Netlify.

I have tried looking into this point but can't seem to find a way to make it work. I tried it on my repository too but it's opening the preview of the main repo. Can you let me know how to make this work? I will accordingly try it and then do a PR to update the UG.

**Comment by eugenepeh** [comment]
The idea is to fork this repository, create a netlify page using this repository, and then bind the webhook url with the main repository.

It should look like something below such that it will notify the netlify to perform the build, whenever the master branch of the main repository is updated.

Note 
* by main repository, I mean the target repository of the user's organization.
* you will need to find the netlify api that triggers the "rebuild" for specific repository because the example shown below is likely not to work in this scenario. GitHub only posts json data of the calling repository in webhook and it is non-customisable.

![image](https://user-images.githubusercontent.com/19277206/66922048-de5dfa80-f058-11e9-9bd4-46c85c5d31b1.png)

**Comment by Tejas2805** [comment]
@eugenepeh I have set up the webhook for my fork of RepoSense successfully.. These are the steps:

1) Set up Netlify in forked repository. 
2) Build hook for the branch of your specific repository.
3) Add webhook your Github repository. 
 
From next time onwards, Netlify will start deploying the page.

Issue: The deployed page asks for a zip file.
