### ISSUE TITLE
NullPointerException occurs when utilizing remote configurations

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#366]
![image](https://user-images.githubusercontent.com/19277206/46848662-af95be80-ce1d-11e8-8c97-a566992fdae7.png)

**Comment by eugenepeh** [comment]
This happens because it is trying to access a null field, displayName.

![image](https://user-images.githubusercontent.com/19277206/46848790-64c87680-ce1e-11e8-8384-43c6c683fbbd.png)

**Comment by damithc** [comment]
The display name is not compulsory, right? If it is not supplied, do we fall back on our own or use GitHub username instead?

**Comment by eugenepeh** [comment]
Yup, if its not supplied, we fall back to GitHub ID. Hence its not a compulsory field.
