### ISSUE TITLE
Show total contribution in code panel

### ISSUE THREAD

**Issue by apoorva17** [reposense/RepoSense#369]
Code panel currently only shows the contribution lines per file. i.e. ```docs/AboutUs.adoc (21 lines) ``` It would be good if the code panel could also show the total contributions by that author so that the user could see at a glance what is the total contribution in the code panel i.e. ```Total contribution: 278 lines```

**Comment by eugenepeh** [comment]
This information is already covered by the contribution bar.
Instead of doing this, which may be seen as redundant repetition of information, we should probably make this information more clearly visible in the summary view.

**Comment by damithc** [comment]
> This information is already covered by the contribution bar.
> Instead of doing this, which may be seen as redundant repetition of information, we should probably make this information more clearly visible in the summary view.

Showing the total here is just the start. We'll be adding a more detailed summary (e.g., breakdown of file types) here incrementally. That kind of information is not suitable to show in the chart view. Besides, the chart view is independently scrollable which means it is still useful to show the total in both views.

At the same time, we can try showing total more visibly in the chart view too (as a separate PR) but not sure it will clutter the view too much or, will require extra vertical space for each author. Can try anyways.

**Comment by eugenepeh** [comment]
>Showing the total here is just the start. We'll be adding a more detailed summary (e.g., breakdown of file types) here incrementally. That kind of information is not suitable to show in the chart view. Besides, the chart view is independently scrollable which means it is still useful to show the total in both views.

I would propose that information to be display as a bar / list in that case, combining the filtering and information into one. Adding a single line just to show the total lines, is not very useful because its not scale-able towards that objective.

**Comment by damithc** [comment]
> I would propose that information to be display as a bar / list in that case, combining the filtering and information into one.

Yup. Eventually, something like that is the aim -- but it will take quite a bit of design and implementation. For now, let's proceed in small steps so that @apoorva17 can build up her expertise incrementally. If we try to do too much in one step, we end up dragging PRs over long periods.

@apoorva17, as for the mock-up, perhaps show the total in a slightly different style, to distinguish from individual file details?

**Comment by apoorva17** [comment]
@damithc would this be fine?
![dashboard](https://user-images.githubusercontent.com/19278550/46917834-d4e12300-cffd-11e8-81a4-0bc49509a6db.png)

**Comment by apoorva17** [comment]
Sure, is this fine?
![dashboard](https://user-images.githubusercontent.com/19278550/46918599-6bb1dd80-d006-11e8-9b86-552f179a571b.png)

**Comment by damithc** [comment]
> Sure, is this fine?

Yes.
