### ISSUE TITLE
Code view: cosmetic tweaks to panel headings

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#37]
Things to try:
* smaller font
* a more subdued background color
* no border (in fact, try getting rid of all border lines everywhere in the code view. They are visual clutter that we can do without, in most cases)

![image](https://user-images.githubusercontent.com/1673303/37823005-253a04de-2ec3-11e8-8542-d61d189007f3.png)

vs

![image](https://user-images.githubusercontent.com/1673303/37823056-4bb38d06-2ec3-11e8-9204-0ea47d9992bc.png)

**Comment by ongspxm** [comment]
duplicate of #188
