### ISSUE TITLE
InvalidPathException thrown during run time due to Illegal char <:> in file name

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#370]
![image](https://user-images.githubusercontent.com/19277206/46914510-5ff7f400-cfd1-11e8-8618-17baf6e3dd2a.png)

**Comment by eugenepeh** [comment]
Apparently some teams have actually tried putting `:` in the file name
https://github.com/CS2103-AY1819S1-T13-3/main/blob/master/_reposense:config.json

**Comment by yamidark** [comment]
Windows disallow certain characters for file names `/\:*?"<>|` while other OS like Linux does not, so when git tries to clone/update the repo, they will actually 'skip' these files instead (`_reposense:config.json` becomes an empty `_reposense` file).

Should we make reposense just skip these 'invalid' files (catch the exception and throw a log message)?
This may result in reposense giving different results in different OSes though if such files do exist.

**Comment by damithc** [comment]
> Should we make reposense just skip these 'invalid' files (catch the exception and throw a log message)?
> This may result in reposense giving different results in different OSes though if such files do exist.

I'm fine with that.

**Comment by eugenepeh** [comment]
>Should we make reposense just skip these 'invalid' files (catch the exception and throw a log message)?
This may result in reposense giving different results in different OSes though if such files do exist.

Yup, that's good for a hot fix.

In the future version, we can actually probably use the git blame functionality to get the latest modifier of each line, along with the lines?

![image](https://user-images.githubusercontent.com/19277206/46915353-fe3d8700-cfdc-11e8-9d3c-96a703ba84a1.png)
