### ISSUE TITLE
Use copy instead of clone for local repository

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#379]
As people tend to perform trial and error for the json config file before committing to the repository. However, the json config file will not be included when we perform the clone on the local repository.

This means that we should probably use copy instead of clone for local repository.

Note: along with this change, unstaged files will also be carried along to the analysis, we probably need to include the `-f` flag for the checkout command for this change.

**Comment by damithc** [comment]
Oh, I didn't realize this. That means our instructions are wrong. Their new json file is not used (unless it is committed) when they run RepoSense locally. Can we do a quick fix?

**Comment by damithc** [comment]
If it is going to take time to fix, we might have to update the user guide to ask users to commit changes (possibly in a branch) when they are testing RepoSense. The next week project progress recommendation specifically asks students to make their code RepoSense-compatible.

**Comment by yamidark** [comment]
>This means that we should probably use copy instead of clone for local repository.

Did some tests with this, some problems with copying all the files instead of clone, is that we will copy all the files inside `.gitignore` as well. As `FileInfoExtractor#getAllFileInfo(...)` will generate all `FileInfos` through traversing the directory, the app will crash if some of those files that has their file formats is inside our whitelist, but we are unable to run 'git blame' analysis on them.

One solution for this would be to like `FileInfoExtractor#getEditedFileInfo(...)`, for `FileInfoExtractor#getAllFileInfo(...)` should also get all files to be tracked and analyzed by using 'git' commands instead. This will probably take quite some time to research and implement, so for now might just want to update the UserGuide 1st.

**Comment by damithc** [comment]
Perhaps we should abort this approach and ask users to commit changes (possibly in a separate branch) before running RepoSense locally?

**Comment by eugenepeh** [comment]
>Perhaps we should abort this approach and ask users to commit changes (possibly in a separate branch) before running RepoSense locally?

Actually they can do `git commit --amend` when doing trial and error with the `config.json`, just that I'm not sure if students know how to do that in source tree.

**Comment by damithc** [comment]
> Actually they can do `git commit --amend` when doing trial and error with the `config.json`, just that I'm not sure if students know how to do that in source tree.

Yes. Using a separate branch (something they should know how to do) is the worst case scenario.

**Comment by damithc** [comment]
> Let's do this quickly while we look for an alternative?

Reminder. Updating the UG needs to be done urgently as students could be following the current _incorrect_ instructions right now. Someone already mentioned this to me at the last Friday lecture (i.e., RepoSense not following the provided config.json file) but I didn't connect the dots at the time.

**Comment by yamidark** [comment]
>As people tend to perform trial and error for the json config file before committing to the repository. However, the json config file will not be included when we perform the clone on the local repository.

Discussed this with @eugenepeh and @yong24s, we can try copying and overwriting just the local standalone config file instead of the whole repository, making it easier for students to test their standalone config before committing it.

**Comment by damithc** [comment]
Students rarely run RepoSense locally these days. Hence, this use case is rare. Closing.
