### ISSUE TITLE
FileInfoExtractor#getAllFileInfo(...): may generate FileInfo for directories

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#380]
https://github.com/reposense/RepoSense/blob/be94eedde7dd797793cd29b2af425a5d2e69f486/src/main/java/reposense/authorship/FileInfoExtractor.java#L166-L172

If we have a directory that has is name within the format white list, e.g. `.gradle` (mostly it is inside `.gitignore` so we didnt have this problem so far), it will actually have its `FileInfo` generated (as seen in our current code implementation above), which will cause the app to crash later when we try to `git blame` this directory.

We could append the 'else-if' white listed formats check to the directory check, so directories
won't have their `FileInfo` generated, or we could make `FileInfoExtractor#generateFileInfo(...)`
return a 'false' value so that we will not add any files which we have error reading into
the list to be analyzed.

**Comment by emer7** [comment]
Is this issue still relevant? Can I take it?

**Comment by yamidark** [comment]
>Is this issue still relevant? Can I take it?

Yep

**Comment by yong24s** [comment]
Since we use `String#endsWith` for comparison, an exception will be thrown when we `git-blame` a directory named `something.java`.
