### ISSUE TITLE
Annotation tagged author may not appear in report

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#382]
By default, if no configurations were found, RepoSense will perform the analysis for all the authors found in commit history.

However if the author named in the annotation tag, `@@author`, is not found in the commit history, her contribution won't show up in the report.

This can be a very rare case, hence putting this is up for discussion on whether should we fix it in the near future.

**Comment by damithc** [comment]
I guess we should show both: all authors in commit history + all authors mentioned in `@@author` tags ? 
Not a high priority though.

**Comment by aidoxe-123** [comment]
Hi, can i still work on this?
