### ISSUE TITLE
Show breakdown of file type for total contribution in code panel

### ISSUE THREAD

**Issue by apoorva17** [reposense/RepoSense#385]
Code panel only shows the total contribution i.e. ```Total contribution: 327 lines```. It would be better if the code panel could also show a breakdown of total contribution by file type i.e. ```[java: 121 lines] [css: 10 lines]``` etc. 

![dashboard](https://user-images.githubusercontent.com/19278550/47540936-e1bd1b00-d909-11e8-870e-67ee4b3fa4f8.png)

**Comment by apoorva17** [comment]
@reposense/devs @damithc pls provide ur feedback for this issue

**Comment by damithc** [comment]
This is fine as the next incremental step of showing a summary of the contribution. @apoorva17 Can you also create an issue to show the date range on the code panel as well?

**Comment by apoorva17** [comment]
> This is fine as the next incremental step of showing a summary of the contribution. @apoorva17 Can you also create an issue to show the date range on the code panel as well?

@damithc i've created this issue

**Comment by eugenepeh** [comment]
Looks good to me, perhaps the total contribution line can be also an element? E.g. [Total: XXX lines]

For the date range, perhaps we can show it next to the author's name. 
E.g. `Metta Ong (ongspxm) contribution from XXX to XXX`?

@damithc do you think this is cleaner for the ui?

**Comment by damithc** [comment]
> For the date range, perhaps we can show it next to the author's name.
> E.g. `Metta Ong (ongspxm) contribution from XXX to XXX`?
> 
> @damithc do you think this is cleaner for the ui?

Yes, that works.

**Comment by apoorva17** [comment]
@damithc should i retain the total contribution line or change it to ```[Total: XXX lines]```as suggested by @eugenepeh?

**Comment by damithc** [comment]
> @damithc should i retain the total contribution line or change it to `[Total: XXX lines]`as suggested by @eugenepeh?

Perhaps better to keep the total as a separate line as the total and the breakdown are alternative representations of the same info. Also, it is easier for the eye to locate the total when it is at the end of the line. On a similar vein, you can bold only the total and leave everything else non-bold? We can remove the repetition of `lines` too. e.g.,

>Total LoC contributed: **254**
>→ java: 120, adoc: 34, other: 100

**Comment by damithc** [comment]
> Actually I was thinking that the next incremental step would be to make each of the elements `[java: XXX]` clickable, and upon click, they filter the files according to file types. Hence, upon clicking `[Total: XXX]`, it resets the filter. Though similar thing can be imposed on the `Total LoC contributed: 254` itself but not sure if its intuitive.

I'm hoping to have a separate (and more flexible) filter mechanism as it's likely we'll want to do more flexible filtering than just by file type. e.g., using a glob to filter all test-related java files, or see all java and fxml file but not others, ...

**Comment by damithc** [comment]
> Hmm... we can make it even better by integrating them together. Clicking on the elements changes the value in the search box which will be then automatically apply the filter. Of course, advance users can just use the search box directly, but since the thing is there, might as well add more purpose to it by making them clickable.

That's true. Let's implement a search box first, starting with basic filters, and adding more advanced filtering features incrementally. Once we have a solid search bar, we can add more convenient ways to use it e.g., making the numbers clickable and linking them to the search box.
