### ISSUE TITLE
Should we include merge commit in the ramp chart?

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#389]
Some merge commits may contain merge changes (lines change), perhaps we should include them in the ramp chart?

**Comment by damithc** [comment]
What does the current RS do with merge+squash commits? treat as normal commit?

For merge commits, we can show them but in a different way? It will be misleading to show the commit ramp as usual as it makes the same change appear twice in the ramp chart.

**Comment by eugenepeh** [comment]
> What does the current RS do with merge+squash commits? treat as normal commit?

Yes.

>For merge commits, we can show them but in a different way? It will be misleading to show the commit ramp as usual as it makes the same change appear twice in the ramp chart.

The actual problem is for example we do this

![image](https://user-images.githubusercontent.com/19277206/47637658-64a6d580-db97-11e8-98f1-6c3bfe86b515.png)

![image](https://user-images.githubusercontent.com/19277206/47637681-77b9a580-db97-11e8-8d0e-5e39947986f3.png)

There's a commit on the `merge-conflict` branch which has helped to resolve the conflict (make some changes and etc) but wasn't reflected in the git log when we set the flag `--no-merges`.

![image](https://user-images.githubusercontent.com/19277206/47637804-ce26e400-db97-11e8-9881-d7e72a152f4a.png)

![image](https://user-images.githubusercontent.com/19277206/47637921-10502580-db98-11e8-96a6-4663eb16b0d3.png)

So what we get will be all 3 commits happily contributed 3 lines each. But in the actual fact, the merge commit has removed one line, left 8 lines, in the process and this was not reflected in our commit analysis.

I think we need someways to track the changes made in the merge commit.

**Comment by eugenepeh** [comment]
More info:

![image](https://user-images.githubusercontent.com/19277206/47639096-6ffc0000-db9b-11e8-9e60-21fc6d8d8076.png)

The final analysis is still correct though, just that no ramp shows up for my GitHub account even though it made the effort to resolve the merge conflict.

**Comment by damithc** [comment]
> The final analysis is still correct though, just that no ramp shows up for my GitHub account even though it made the effort to resolve the merge conflict.

It is fair to show a ramp for the merge commit, but what about the size of the ramp? Can we make it reflect the size of the conflict resolution?

**Comment by eugenepeh** [comment]
>It is fair to show a ramp for the merge commit, but what about the size of the ramp? Can we make it reflect the size of the conflict resolution?

I guess we could because the line counts doesn't match up, total lines contributed is 9 but the files only show 7, this might pose a problem in the future. 

We might have to introduce zero and negative lines ramps to show the contributions and also to make up for the problem above.

**Comment by damithc** [comment]
As a compromise, perhaps show merge commits as 0 length ramps? i.e., it will still show up in the ramp chart but will not affect the contribution bar.

**Comment by eugenepeh** [comment]
>As a compromise, perhaps show merge commits as 0 length ramps? i.e., it will still show up in the ramp chart but will not affect the contribution bar.

I think we need to include negative as well for the contribution bar to be accurate if i remember correctly. Because in the example I gave earlier, the merge commit removed the conflicting lines, hence produce a mismatch between the contributed lines and the total number of lines from all files.

**Comment by damithc** [comment]
> I think we need to include negative as well for the contribution bar to be accurate if i remember correctly.

How do we calculate the ramp size when the commit delete more lines than it adds/edits?

**Comment by eugenepeh** [comment]
>How do we calculate the ramp size when the commit delete more lines than it adds/edits?

We can probably use a different color, e.g. dark red, to indicate it as a negative value while the ramp size can still use the absolute number.

**Comment by damithc** [comment]
> We can probably use a different color, e.g. dark red, to indicate it as a negative value while the ramp size can still use the absolute number.

I'm sure there are normal commits that has a negative LoC contribution. How do we show them in the ramp chart _now_?

**Comment by eugenepeh** [comment]
>I'm sure there are normal commits that has a negative LoC contribution. How do we show them in the ramp chart now?

This is a very interesting question, it brings up more points that we need to investigate/discuss on.

Currently, our contribution line does not include negative LoC contribution; it is an indicator of "ownership". 

E.g. If author A deletes 10 lines from the code that is contributed by author B,
Author A receives no new ownership of lines, while
Author B will have 10 lines silently deducted from contribution.

_A quick correction: This question has made me come to realize that the problem indicated in this issue may only occurs if the merge commit is the last commit; changes that were introduced in the last merge commit may not appear in the analysis for contribution bar. (need further investigation)_

Similarly to an extent, ramps only represent positive changes. So given a commit that has performed 2 additions and 30 deletions, it will be represented by a ramp length of 2 lines.

Base on the above rationale, it make sense to award a 0 length ramp for such merge commit. However, this also means that base on the ramp chart alone, we can't tell if there's any resolving done within the commit. E.g. PR that can be merged without issue (0 length) vs PR that needs resolve prior to merge (deleting duplication or etc) can also produce a 0 length ramp.

This brings the question on, whether we should tweak the calculation used for the length of ramps because negative lines should also be a form of contribution. Using the previous example, if a 2 lines of new code can replace 30 lines of existing code, that 2 lines of change can be weigh equivalently effective as a 30 lines change.

**Comment by damithc** [comment]
How about this?
* Ramps represent _changes_ (not contribution). Hence, their size matches the number of lines touched (added | edited | deleted)
* Contribution bar represents _authorship of lines that are still in the code_ of the code. i.e., they do not capture deleted code.

**Comment by eugenepeh** [comment]
>Ramps represent changes (not contribution). Hence, their size matches the number of lines touched (added | edited | deleted)

Yes, that would actually be better to gauge the amount of work done. In fact, I think we can probably implement one more setting, which allows user to switch between 
* Addition 
* Deletion 
* Net Changes - the absolute of Addition minus Deletion
* Total - Addition + Deletion

Don't think git provides edit, we may have to implement our own algorithm for that if that is preferable.

**Comment by damithc** [comment]
> Don't think git provides edit, we may have to implement our own algorithm for that if that is preferable.

We can go with what Git provides. The size of the ramp chart is just a visual cue; no need to be so accurate. For the moment, let's simply update the code so that the ramp chart reflects add+delete. Adding more options can be considered in the future.

**Comment by damithc** [comment]
Closing in favor of #1877
