### ISSUE TITLE
Revamp the override option

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#390]
As discussed earlier with Akshay, there doesn't seems to be a clean way to override just a specific field for the json config.

Some ideas that we can possibly revamp this:
1. Make the cli param highest order which can override any single field
2. Make single field override-able option, to override some fields of the json config (if any), in the csv config instead of override the entire thing.

Can discuss other alternatives.

**Comment by eugenepeh** [comment]
Another way is to when ignore SA config (can be rename to override SA) is selected, 
override only values that are not empty in the config. 
However, as there are probably fields that we wish to set it as empty, we probably need a `empty` or `default` key to keep it that way.

**Comment by damithc** [comment]
Would this work?
If a field value in the csv file is prefixed with `override:`, the value in the SA config is ignored.

**Comment by eugenepeh** [comment]
>If a field value in the csv file is prefixed with override:, the value in the SA config is ignored.

Sounds good to me

**Comment by fzdy1914** [comment]
The #602 fixes part of the problem but not fully.

**Comment by fzdy1914** [comment]
The priority of CLI is not decided.

**Comment by fzdy1914** [comment]
Close as #430 deals with the same issue.
