### ISSUE TITLE
File paths may not be handled in OS independent manner

### ISSUE THREAD

**Issue by okkhoy** [reposense/RepoSense#391]
Issue identified while running Reposense on CS2113 repositories.

CS2113 post related to the issue: https://github.com/nusCS2113-AY1819S1/forum/issues/79

Screengrab of the files in the affected repository: 
![image](https://user-images.githubusercontent.com/1023494/47698226-7052d480-dc49-11e8-987a-aba7ede8eeee.png)

(Note: the files above have been renamed/fixed, so have to make-do with the image for reference)

From @eugenepeh 
>Seems like their repo file system follows a linux setup
can't perform git clone on their repo on windows os

**Comment by eugenepeh** [comment]
@emer7 , why was this closed?

**Comment by emer7** [comment]
@eugenepeh oops I saw it is referenced and I thought it is fixed. My bad

**Comment by eugenepeh** [comment]
>@eugenepeh oops I saw it is referenced and I thought it is fixed. My bad

No worries. Note that we don't close issues that were hot-fixed. Its just a temporary and not a permanent solution.
