### ISSUE TITLE
Provide a link to repo even when not grouped by repo

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#396]
Current: a link to the repo is only available when the chart view is grouped by repo.

![image](https://user-images.githubusercontent.com/1673303/47981150-9ffc5380-e105-11e8-9975-9cbbe7acac23.png)

Suggested: also provide a way to reach the repo when not grouped by repo.

**Comment by yamidark** [comment]
Yes, closing as issue is resolved in #426.

**Comment by damithc** [comment]
@fzdy1914 remember to put the correct `Fixes #1234` in the PR so that the issue gets auto-closed when the PR is merged.
