### ISSUE TITLE
code view: auto-scroll to top when loading code of a new person

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#405]
Current: the code panel holds the scroll position of the previous view even after loading code of a new person

Suggested: auto-scroll to the top

**Comment by eugenepeh** [comment]
similar issue to https://github.com/reposense/RepoSense/issues/190, closing the other...

**Comment by yamidark** [comment]
>This issue is resolved, right?

Yes, closing this issue as it is resolved in #428.
