### ISSUE TITLE
Gradle task npmRunSpuild is not working as intended

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#409]
@ongspxm , seems like you've recently updated your spuild library and the npmRunSpuild task in gradle is not working the same as before. Could you please fix it?

**Comment by ongspxm** [comment]
paiseh, didnt thought it will affect, okay i go now

**Comment by eugenepeh** [comment]
@ongspxm thanks! do close this issue when its fixed.

**Comment by eugenepeh** [comment]
Thanks @ongspxm !
