### ISSUE TITLE
MacOS CI Environment: `Error: invalid option: --with-pcre2`

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#413]
In the latest travis [build](https://travis-ci.org/reposense/RepoSense/jobs/465465879), it seems that the `--with-pcre2` is no longer a valid option.

![image](https://user-images.githubusercontent.com/19277206/49729927-cb003700-fcb1-11e8-954c-821eb7d46824.png)

**Comment by eugenepeh** [comment]
@yong24s , can you look into this? #144 is no longer working.

**Comment by yong24s** [comment]
Preliminary findings:

`--with-pcre2` should be still in-use. As listed in `https://formulae.brew.sh/formula/git`

Also, we are using the default macosx image `Xcode 9.4.1`, so the newly released image should not be the cause. `https://blog.travis-ci.com/2018-11-01-xcode-10-1-is-now-available`,
