### ISSUE TITLE
Can not analyze a folder that contains space in its folder name

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#419]
Step to reproduce:
Analyze a git folder that contains space
![image](https://user-images.githubusercontent.com/35621726/49852751-f9038980-fe1f-11e8-92d7-bef4be26517f.png)

**Comment by yong24s** [comment]
@fzdy1914 

When dealing with folder with spaces, you can use `\` or `""`.

Try `"E/Inventory Manager"` or `E/Inventory\ Manager`.

This applies for all command-line interfaces. Therefore, it is not an unexpected behavior.

**Comment by fzdy1914** [comment]
@yong24s 
Actually，I have tried these command.
![image](https://user-images.githubusercontent.com/35621726/49944243-f76fb980-ff24-11e8-9134-b87b5c9a3e68.png)
![image](https://user-images.githubusercontent.com/35621726/49944321-1ec68680-ff25-11e8-9e92-6e6d9777b4df.png)

**Comment by fzdy1914** [comment]
I found that this problem can be solved without using gradle, i.e. run the application directly using intellij.

**Comment by eugenepeh** [comment]
You should be able to use single quote with double quote in this situation. 
E.g. `gradlew run -Dargs="-repos 'somewhere over the rainbow' "`

Please close the issue if it solves your problem.
