### ISSUE TITLE
Files that have whitespace in their paths lead to test failures

### ISSUE THREAD

**Issue by amrut-prabhu** [reposense/RepoSense#435]
**Bug:**
For example, the following exception is encountered due to whitespace in **`Abc Xyz`**, which is in the file path to the test file `standardBlameOutput.txt`. 

```java 
   Path STRINGS_UTIL_TEST_DIRECTORY = ...

20 Path gitBlameStandardOutputFile =
21                Paths.get(STRINGS_UTIL_TEST_DIRECTORY.toString(), "standardBlameOutput.txt");
22 List<String> lines = Files.readAllLines(gitBlameStandardOutputFile);
```

```java
java.nio.file.NoSuchFileException: C:\Users\Abc%20Xyz\git\RepoSense\out\test\resources\StringsUtilTest\standardBlameOutput.txt

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	...
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at reposense.util.StringsUtilTest.filterText_standardInput_success(StringsUtilTest.java:22)
```
**Cause:**
The exception occurs since `Path.toString()` returns the path with the spaces replaced by `%20`. But, `java.io.File` accepts spaces in the `String pathname`, not `%20`.

**Fix:**
I think it can be fixed by replacing such instances by 
` String decodedPath = URLDecoder.decode(Path.toString(), "UTF-8");`

**Comment by yamidark** [comment]
Yes, we probably need to change all the `Path` that uses `ClassLoader` in test to use the decoder to handle this case.

However, there are currently too many of such `Path` that uses the `ClassLoader`, which is already very long, and it is too troublesome to go edit all of them.

Probably want a different issue to refactor them all out into a common utility method 1st for ease of future usage, and then update that method to use the decoder.

@eugenepeh Your opinion on this?

**Comment by eugenepeh** [comment]
> Probably want a different issue to refactor them all out into a common utility method 1st for ease of future usage, and then update that method to use the decoder.

I think it can be done in a single PR, since updating the method would probably be a few line change afterwards.

**Comment by fzdy1914** [comment]
When I work around with this issue, only adding URLDecoder is not enough. For the directories in `Argsparser`, they will be passed in as an argument. An argument does not allow to have whitespace within it.

**Comment by Tejas2805** [comment]
@jamessspanggg your PR fixed this issue too right? Or was it just for spaces in the file name and not the file path?

**Comment by chan-j-d** [comment]
Hi, I would like to work on this issue even though it is marked as `ToVerifyRelevance`. I believe I already have most of the fix after spending some time on it as the project couldnt be built on my own computer because of the issue.

**Comment by fzdy1914** [comment]
> Hi, I would like to work on this issue even though it is marked as `ToVerifyRelevance`. I believe I already have most of the fix after spending some time on it as the project couldnt be built on my own computer because of the issue.

Go ahead.

**Comment by damithc** [comment]
Go ahead @chan-j-d

**Comment by HCY123902** [comment]
> Hi, I would like to work on this issue even though it is marked as `ToVerifyRelevance`. I believe I already have most of the fix after spending some time on it as the project couldnt be built on my own computer because of the issue.

I previously worked on this issue. I think part of the reason why it is marked as ToVerifyRelevance is that the problem with Path.toString() does not exist when used along with Paths.get() for higher version of Java. Additionally, the suggestion of using URLDecoder.decode() may bring problem when parsing path containing special character such as the plus sign. You may need to pay attention to this special case
