### ISSUE TITLE
User Guide: Minor errors in example.

### ISSUE THREAD

**Issue by dlworldpeace** [reposense/RepoSense#444]
User guide has minor error that could be misleading

Not urgent.

#439

**Comment by damithc** [comment]
@dlworldpeace thanks for reporting. Can you state what the error is too?

**Comment by dlworldpeace** [comment]
> @dlworldpeace thanks for reporting. Can you state what the error is too?

A mistake was made in the example given for 'until' flag. It should state '-until' instead of 'since'.
