### ISSUE TITLE
Split author level configurations from RepoConfiguration

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#457]
Before #238, RepoSense only required 1 configuration file, which
holds all the repo and author level settings.

After splitting them into repo and author level configuration files in
#238, we still use the RepoConfiguration class to represent an author
configuration file, as most of the settings were still similar back
then.

However, after many changes to the configuration files, such as adding
commit exclusion settings in #261 and ignore standalone config
settings in #288 at repo level, the 2 configuration files now differ largely
from one another, making it harder to maintain the RepoConfiguration
class to represent them both, as any changes to 1 of the configuration file
will affect the other.

Let's create a new class AuthorConfiguration to represent the
author config file settings, splitting it from the RepoConfiguration.

**Comment by myteo** [comment]
I am working on this issue.
