### ISSUE TITLE
Allow user to choose any timezone

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#459]
Current: Uses SGT timezone e.g., timestamp shown at the bottom of the report

![image](https://user-images.githubusercontent.com/1673303/50766994-3a1f7a00-12b6-11e9-9fa5-e451ebcac7aa.png)

Suggest: Allow user to choose any timezone

**Comment by damithc** [comment]
> Or "Asia/Shanghai"? Or just UTC +/-?

`UTC +/-` might be better, as it is short (less error-prone)

**Comment by fzdy1914** [comment]
> `UTC +/-` might be better, as it is short (less error-prone)

@damithc Need to notice that now we represent the time using the time zone abbreviations `SGT`. If the user enters the time zone using UTC +/-. We may need to change the way of representing our time. Like ` Fri, 08 Nov 2002 09:42:22 +0800` .
