### ISSUE TITLE
Config files: allow specifying commit range to specify

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#460]
Current: each commit to ignore needs to be specified individually in config files
![image](https://user-images.githubusercontent.com/1673303/50767145-aac69680-12b6-11e9-844a-ad154f0381a9.png)

Suggested: Allow specifying commit ranges

**Comment by yamidark** [comment]
For this, we can try following the git notation for specifying range of commits  `A..B`.
However, as our ignore commit features checks for individual commit hashes, we would need to get all the commit hashes in between by ourselves using `git rev-list` first, before running the analysis.

**Comment by anubh-v** [comment]
Thanks for the info @yamidark. I'll attempt an implementation for this using your suggestion.
