### ISSUE TITLE
Code view: give link to history and blame views of each file

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#466]
Suggestion: in the code view, we can give link to go to the history view and the blame view of a file (on GitHub)

![image](https://user-images.githubusercontent.com/1673303/50768000-dd25c300-12b9-11e9-86c1-4da5de88e232.png)

e.g.,
https://github.com/reposense/RepoSense/blame/release/docs/UserGuide.md
https://github.com/reposense/RepoSense/commits/release/docs/UserGuide.md

**Comment by fzdy1914** [comment]
@damithc I am considering adding two icons beside the line of the name. History's one can be 
![image](https://user-images.githubusercontent.com/35621726/51421850-0874b000-1be0-11e9-8290-ce7e8959ba3a.png)
Which kind of icon do you think is better for blame?

**Comment by damithc** [comment]
Remember to consider copyrights when using icons. You can try fontawesome for free icon fonts.

> Which kind of icon do you think is better for blame?

Not sure myself. Give me some options. :-)

**Comment by fzdy1914** [comment]
> Not sure myself. Give me some options. :-)

I am using fontawesome. The icon I choose now is 
![image](https://user-images.githubusercontent.com/35621726/51423403-8645b500-1bfa-11e9-8c45-0c227a0acecd.png)
Can check with the preview of my pr.
