### ISSUE TITLE
Add per-commit granularity to the report

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#468]
Current: only `day` and `week` granularities are supported
![image](https://user-images.githubusercontent.com/1673303/50772699-9dff6e00-12c9-11e9-88b6-0de6da505779.png)

Suggestion: also support per commit granularity

I suspect this will need major changes in the backend

**Comment by ongspxm** [comment]
:+1: i will make the changes to the frontend. so we will shift the consolidation of the day informaiton to frontend?

**Comment by yamidark** [comment]
>so we will shift the consolidation of the day information to frontend?

I believe daily is still consolidated in the backend though, just that each day will contain an array of all the commits for that day.

**Comment by ongspxm** [comment]
so it be like `[{
    sinceDate: 20190101,
    untilDate: 20190102
    insertion:0,
    deletion:0,
    commits:[{...}, {...}]
}]` ?

**Comment by yamidark** [comment]
From my previous commit in the `per-commit-view`:
```
{
        "insertions": 408,
        "deletions": 96,
        "date": "2017-10-01",
        "commitResults": [
          {
            "hash": "353cbca2cca5671ddb0d358e4bf07ef838221a2a",
            "message": "[W09-B2] Added more Non Functional Requirements to the Developer Guide",
            "insertions": 7,
            "deletions": 2
          },
....
```

**Comment by yamidark** [comment]
Closing this as the discussion moved to #468
