### ISSUE TITLE
Explore periodic report updates using Travis cron jobs

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#470]
Suggestion: explore if users can use Travis cron jobs to set a reposense report to be auto-updated periodically. If possible, describe the steps in the user guide.

Example:
1. Create a GitHub repo
2. Set it up with RepoSense config files.
3. Set up Travis gitHub for the repo.
4. Travis will run the cron job periodically, which will use the config in the repo to re-generate the report and publish it to the github pages of the repo.

**Comment by yong24s** [comment]
We can use **Netlify**. 

It offers a step-by-step wizard to setup `Continuous Deployment`, which provides a `live site address` and a `webhook` to trigger the `Continuous Deployment`. Also, this option is close to running RepoSense on CLI, where sophisticated commands could be used.

Draft example quick start for `Continuous Deployment`:

1. Clone `https://github.com/yong24s/RepoSense-cron`
2. Edit `run.sh` to preferences, the default uses `repo-config.csv`
3. Setup Netlify `Continuous Deployment` on the cloned repository in the above step,
again build setting assumes default configuration
![image](https://user-images.githubusercontent.com/2003406/50947309-9235c680-14d8-11e9-9794-3593eac38e35.png)
4. After the above step, we should get a `live site address` and a `webhook`, 
`https://competent-agnesi-f9bda4.netlify.com` and `https://api.netlify.com/build_hooks/5c36c98996325495b12bdf56`, respectively
5. Now, we can choose any service to trigger the webhook. In my case, I used **Travis-CI**
6. Edit `webhook.sh` to use the webhook from 4
7. Setup Travis-CI on the cloned repository

Limitation: 
In my example, `download.sh` downloads the `latest` jar from our releases, which may not contains the new features from the master branch. 

Seems to work well - https://competent-agnesi-f9bda4.netlify.com 😄

**Comment by damithc** [comment]
Thanks for the follow up @yong24s Looks promising. 

Would this work for cases like CS2103 dashboard which monitors 50+ repos and the build time could run into several hours once we enable code movement detection? Note that no commits are pushed to the repo containing the report after the initial set up.

Would this work when the repos being analyzed are very big? e.g., TEAMMATES repo is nearly 1GB. That is, can Netlify take the load?

**Comment by yong24s** [comment]
**Netlify** and **Travis-CI** will terminate after 15 and 50 minutes, respectively.
Additionally, **Travis-CI** will terminate early if there is no terminal output in the last 10 minutes.

I tested the performance of running analysis with RepoSense on **Netlify** and **Travis-CI** with the configs of `CS2103-AY1819S1` repositories from `https://github.com/nus-cs2103-AY1819S1/cs2103-dashboard/tree/master/config`. 

**Netlify** took `12 min 7 sec` and **Travis-CI** took `11 min 10 sec`.

The main differences between these two are: 
- **Netlify** is easier to setup
- **Travis-CI** can run up to 50 minutes but RepoSense needs to include a progress bar to leverage this
- **Netlify** webhook can be used with external programs/services, allowing specific time/frequency of trigger (Not sure about Travis-CI on this)

> Would this work for cases like CS2103 dashboard which monitors 50+ repos and the build time could run into several hours once we enable code movement detection? Note that no commits are pushed to the repo containing the report after the initial set up.

@yamidark has been testing copy detection `-CC`. It seem like it will increase the analysis time by **10** folds.

> Would this work when the repos being analyzed are very big? e.g., TEAMMATES repo is nearly 1GB. That is, can Netlify take the load?

**Netlify** can clone the repository pretty quickly, but the analysis takes up too much time even **without** copy detection.


> Source code
https://github.com/yong24s/reposense-cd-netlify 
https://github.com/yong24s/reposense-cd-travis

**Comment by damithc** [comment]
> * **Travis-CI** can run up to 50 minutes but RepoSense needs to include a progress bar to leverage this

Just regular logging output that we already have is not enough? 

> * **Netlify** webhook can be used with external programs/services, allowing specific time/frequency of trigger (Not sure about Travis-CI on this)

Is there an easy way to trigger the webhook every 1 hour?

Overall, we may have to provide both options: Netlify for light jobs and Travis for bigger jobs. Furthermore, we might have to do some tweaks on RepoSense so that we can leverage Travis to do longer jobs.

**Comment by yong24s** [comment]
> Just regular logging output that we already have is not enough?

Depending on the size of the repo, for TEAMMATES the output was blocked at
 `Extracting relevant file info from...` for more than 10 minutes.

> Is there an easy way to trigger the webhook every 1 hour?

There are a lot paid services but I think IFTTT should work fine 
https://ifttt.com/create/if-every-hour-at-then-make-a-web-request

**Comment by yong24s** [comment]
It seems like copy detection `-CCM` is faster on CS2103-AY1819S1? 😱

Live Site: https://reposense-cd-travis.netlify.com
Code changes: https://github.com/yong24s/RepoSense/commit/e2af5bcbb3e4d6a35572099a1ac10e22282669d9
Travis Log: https://travis-ci.org/yong24s/reposense-cd-travis
Time taken:  `Ran for 17 min 13 sec`

**Comment by damithc** [comment]
> Ran for `28 min 14 sec`

This is just one team, right? No hope when we have 100 teams next year :-p

BTW, I came across this:

![image](https://user-images.githubusercontent.com/1673303/51041669-69572380-15f5-11e9-9dda-2a3229c1e7b9.png)
