### ISSUE TITLE
File type doesn't match file content

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#473]
Not sure what's going on here:

![image](https://user-images.githubusercontent.com/1673303/51074766-d9c97780-16bd-11e9-8319-d6771960a532.png)

**Comment by eugenepeh** [comment]
seems like something that we missed out in the #448, will need to get it fixed soon. 
@chelseyong, would you be able to fix it?

**Comment by chelseyong** [comment]
Okay I will look into it
