### ISSUE TITLE
CLI: -view should not accept a PATH when used with -config or -repos

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#476]
Following #446, `-view` can be used together with `-config` or `-repos`, in an atomic fashion, to launch the generated report after analysis.

In the discussion https://github.com/reposense/RepoSense/pull/446#discussion_r243760364, it was raised that `-view` when used together with `-config` or `-repos` should not be expecting an argument.

As it may unintuitive and insecure, `i.e.` `java -jar RepoSense.jar -config path/to/configs -output path/to/output -view /etc` will **not** execute analysis but the report will be launched at given **PATH** `/etc`.

**Comment by eugenepeh** [comment]
putting it as low priority for now as its not something that user would do intentionally.

**Comment by yong24s** [comment]
I believe 1 is undesirable. 

If an user generates the report in */home/user/reposense-report* but **mistakenly** use view on */home/user*. It would be disastrous for the user. 😢

But I can't get it serve any arbitrary directory. 🤔

**Comment by myteo** [comment]
In that case would 2 be better? I think the intention of most users would be to view the report that was just generated by the analysis so doing it this way would solve the typo errors like you mentioned.

**Comment by eugenepeh** [comment]
2 is fine with me, however we should at least display a warning message to user; keeping them informed that it a redundant step to provide args to `-view` when used in conjunction with `-config` or `-repos`.
