### ISSUE TITLE
ArgsParser: Extract magic strings into constants

### ISSUE THREAD

**Issue by myteo** [reposense/RepoSense#479]
Mentioned in https://github.com/reposense/RepoSense/pull/437#discussion_r242410159: in ArgsParser.java, ``"config"`` (and other similar strings) is a magic string repeated in multiple places and should be defined in a central location as a constant.

**Comment by yong24s** [comment]
Edited issue to include original comment.

**Comment by fzdy1914** [comment]
Close via #526
