### ISSUE TITLE
Use Cypress to automate front-end testing

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#480]
```
Netlify is useful for previewing changes made to the dashboard.

However, only using it for manual testing may result in poor coverage and consistency.

Let's automate dashboard testing for better coverage and consistency.
```

**Comment by emer7** [comment]
Are we thinking of having a screenshot testing or e2e test?

**Comment by yong24s** [comment]
Could be both. Will it be harder to maintain the expected screenshots since we are rapidly updating the UI?

**Comment by yong24s** [comment]
@eugenepeh @yamidark 

Puppeteer seems useful for us. This example has two basic tests.

![puppeteer](https://user-images.githubusercontent.com/2003406/52525057-e8b44180-2cde-11e9-867b-5da490ca2621.gif)

Test PR: https://github.com/yong24s/RepoSense/pull/7/
Travis-CI: https://travis-ci.org/yong24s/RepoSense/builds/491008607

:octocat:

**Comment by damithc** [comment]
I've also heard good things about https://www.cypress.io/ too

**Comment by yong24s** [comment]
> I've also heard good things about https://www.cypress.io/ too

Looks good. The tool makes testing a lot easier but we won't be using the dashboard as it is free only for up to 3 users.

I'm writing tests with it but can't seem to get `enter` key to work 🤔.

**Comment by yong24s** [comment]
The following illustrates the syntax difference between Puppeteer and Cypress. Overall, Cypress should be easier to debug. 

I'll integrate it to Travis later. 🐙 

@reposense/devs Do share your opinion on this. Frontend tests are coming. :octocat: 


**Puppeteer**
```
describe('search non-existent author', function () {
  it('shows no result', async function () {
    const page = await browser.newPage();
    await page.goto('http://localhost:9000', {timeout: 0, waitUntil: 'domcontentloaded'});
    await page.type('div#summary input', 'AAA%AAsAABAA$AAnAACAA-AA(AADAA;AA)');
    await page.keyboard.press('Enter');
    const actual = await page.evaluate(() => document.querySelector('#summary-charts').children.length);

    expect(actual).to.be.equals(0);
  });
});
```

**Cypress**
```
describe('search non-existent author', function () {
  it('shows no result', function () {
    cy.visit('/');

    cy.get('#summary-wrapper input[type=text]')
      .type('abcdef')
      .type('{enter}');
    
    // Enter does not work, let's manually submit form
    cy.get('#summary-wrapper form.summary-picker')
      .submit();

    cy.get('#summary-wrapper #summary-charts').then(($ele) => {
        // $ele is a JQuery object
        const content = $ele.html();

        debugger // Can insert breakpoint like this and debug using Chrome DevTools

        expect(content).to.be.empty;
    });
  });
});
```
