### ISSUE TITLE
Enforce ESLint check on travis

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#502]
ESLint doesn't seems to be enforcing style check on any of the ci platforms. @ongspxm can you look into it?

**Comment by ongspxm** [comment]
hao bah, let me check

**Comment by emer7** [comment]
Just wondering, should we use CRLF or LF?

**Comment by eugenepeh** [comment]
>Just wondering, should we use CRLF or LF?

I believe all our files use LF, there are shell script enforcing this in the repo.
