### ISSUE TITLE
Uncaught exception when user uploaded non .zip file

### ISSUE THREAD

**Issue by emer7** [reposense/RepoSense#506]
Current:
There is uncaught exception when user uploaded a non .zip file, while for now there is no any negative effect, but for better software engineering practice we should aim to catch it and do something with it (see Suggestion below).

Suggestion:
Implement a pop-up to remind the user to upload .zip file.
This will also be in line with currently being implemented pop-up if loading of resources failed.

**Comment by emer7** [comment]
>Strictly speaking, the answer is no. The developer cannot prevent the user from choosing files of any type or extension in the native OS file select dialog box.
>
>But still, the accept attribute of \<input type = "file"\> can help to provide a filter in the file select dialog box of the OS

https://stackoverflow.com/questions/4328947/limit-file-format-when-using-input-type-file

**Comment by damithc** [comment]
> Not sure if we have users using this zip feature 🤔

We can remove it if not useful.

**Comment by jylee-git** [comment]
I've made a PR to alert the user when non .zip file is added. 

At the same time, I've added code such that when the user clicks ob "browse" to look for files to upload, only .zip files will be filtered. However, user can still overwrite this and upload any other files that are not .zip (though this will be taken care of by rejecting the file and alerting the user of this issue).
