### ISSUE TITLE
Remove unused CheckStyle plugin

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#510]
@damithc , tanghao seems to have sort of planned to integrate checkstyle into RepoSense but doesn't seems to be working nor complete. 

Do you still require this feature or should we remove it from repository for now?

**Comment by yamidark** [comment]
Closing this issue for now, as we are completely removing this feature in #597 as it is not in our immediate plan. Do reopen if we plan to add this in again.

**Comment by eugenepeh** [comment]
Since the result of the discussion is to remove it, can just change the title accordingly and have the #597 reference this issue.
