### ISSUE TITLE
Violations in report sorting tool

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#517]
When having the console of the chrome developer tools open, modifying the sorting option trigger violation messages. As the chrome suggest that the page could've been more responsive, let's investigate and fix this issue.

![image](https://user-images.githubusercontent.com/19277206/51830923-e4297980-232b-11e9-9de1-f4d14f6c052a.png)

![image](https://user-images.githubusercontent.com/19277206/51830913-df64c580-232b-11e9-81de-ec7020bd1eca.png)

**Comment by emer7** [comment]
I tried a blank plain HTML file with only 1 select element
```
<select>
  <option>a</option>
  <option>b</option>
</select>
```
and the violation still shows

**Comment by fzdy1914** [comment]
Seems can not reproduce now? Can you kindly recheck? @eugenepeh

**Comment by eugenepeh** [comment]
Could it be because we're now running vue in development mode?
I think the optimization is intended for production. 

Can leave this issue for now, in case we decide to publish in production in future.
