### ISSUE TITLE
Ramp chart: show up to report generation date, not last commit date

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#518]
When a report is generated with no `-until` flag, the ramp chart should show up to _today_, not the last commit date.

Example:
https://nus-cs3281.github.io/2019-dashboard (the three dates don't match)
![image](https://user-images.githubusercontent.com/1673303/51877887-b33b5a00-23a8-11e9-903e-43ce2d365eda.png)
![image](https://user-images.githubusercontent.com/1673303/51878008-1d53ff00-23a9-11e9-9556-753a3d1cceb5.png)
![image](https://user-images.githubusercontent.com/1673303/51877927-d5cd7300-23a8-11e9-8d68-dcfda017ebdd.png)

**Comment by emer7** [comment]
I found that this is intended behavior in `frontend\src\static\js\v_summary.js:226`
```
maxDate = date2;
```

**Comment by damithc** [comment]
> I found that this is intended behavior in `frontend\src\static\js\v_summary.js:226`

maybe developer-intended, not user-intended :-p

**Comment by eugenepeh** [comment]
would be best to implement this after #542 is rectified

**Comment by eugenepeh** [comment]
changes in the requirement: https://github.com/reposense/RepoSense/issues/610#issuecomment-474423709
