### ISSUE TITLE
Custom grouping of files

### ISSUE THREAD

**Issue by apoorva17** [reposense/RepoSense#520]
This is an end-to-end feature to allow users to specify custom groupings of files in a repository e.g. ```test, docs, etc.```.

A new column called ```Groups``` can be added to ```repo-config.csv```, which allows users to specify groupings of files through a text file. The text file can contain the group(s), and filepaths belonging to that group e.g. ```test: src/test/java/Test.java```

This information can be propagated to the front-end. When groupings are specified by users, these groups can be added as a checkbox option in the Code View, such that you can only view files belonging to that group in the Code View when it is selected. 

Since this is an end-to-end feature, it could be done incrementally, by implementing the backend first, followed by front-end.

**Comment by apoorva17** [comment]
@reposense/devs @damithc kindly provide your feedback on this issue

**Comment by eugenepeh** [comment]
I think prior to this issue, we should implement the search bar to make this sort of easier?
Because from the users' POV, it may bring questions like why is the search bar not implemented first; it is more relevant to implement this after search bar is implemented and still not sufficient.
