### ISSUE TITLE
Implement style checker on .jade and .scss files

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#522]
We have CheckStyle and ESLint to check our java and javascript files automatically, however, .jade and .scss files were not covered by any of these tools.

**Comment by jamessspanggg** [comment]
I am trying to implement pug-lint to check our .pug files, but I realised that we do not have a coding standard guidelines for .pug files. So I am unsure of which rules to set for the pug-lint. Should we follow a specific organisation's coding standard for .pug files?

**Comment by eugenepeh** [comment]
Can use any popular config then customize it to adhere our coding standard stated in the [process guidelines](https://github.com/reposense/RepoSense/blob/master/docs/Process.md#how-to-contribute-to-the-reposense-repository)
