### ISSUE TITLE
author-config.csv: allow multiple repos in one row

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#528]
Current:

Repo | branch | ...
----- | --------- | ---
https://github.com/reposense/reposense.git | master | ...
https://github.com/markbind/markbind.git | release| ...

Suggested:

Repo/branch | ... |
-------------- | --- |
https://github.com/reposense/reposense.git/master; https://github.com/markbind/markbind.git/release | ...|

Reason: to avoid duplicating remaining columns, when one person in working in multiple repos

Example: https://github.com/nus-cs3281/2019-dashboard/blob/master/configs/author-config.csv

**Comment by yong24s** [comment]
@damithc 

Does this issue supersede #18?

**Comment by damithc** [comment]
> Does this issue supersede #18?

Yup :-p

**Comment by damithc** [comment]
Although the proposed solutions are slightly different. We can decide which way is better.

**Comment by eugenepeh** [comment]
we can always make branch a multi-value field 🤔

**Comment by eugenepeh** [comment]
Since they're different branches of the same repo, other setting should be roughly the same.
It save user some work and organization, but if the user wants it to be different, he/she can still use multiple rows.

**Comment by eugenepeh** [comment]
Oops, misread the table. Thought it was just combining repo and branch to form single column.

Multiple (different) repos is unlikely to be useful though, they tend to have different setup and can be rather disorganized for users who view using google sheets.

Also, because of the difference in configurations, the aggregation of activities will still be a backend (or frontend) work in the end to avoid major architectural change; we can't support 2 different model styles (repo focus and author focus) without a major change. Hence, I would suggest that we work towards the multiple repos single author feature via a `group by author` option (mutually exclusive with `group by repo/branch`), identified by GitHub ID,  in the frontend.

Perhaps we can put this on hold till #18 is transpired?

**Comment by damithc** [comment]
> Multiple (different) repos is unlikely to be useful though, they tend to have different setup and can be rather disorganized for users who view using google sheets.

We aleaready have a use case for this, in CS3282 https://github.com/nus-cs3281/2019-dashboard/blob/master/configs/author-config.csv

> Also, because of the difference in configurations, the aggregation of activities will still be a backend (or frontend) work in the end to avoid major architectural change; we can't support 2 different model styles (repo focus and author focus) without a major change. Hence, I would suggest that we work towards the multiple repos single author feature via a `group by author` option (mutually exclusive with `group by repo/branch`), identified by GitHub ID, in the frontend.

The proposed changes is just a simplification to the csv file, to reduce duplication. 

> Perhaps we can put this on hold till #18 is transpired?

Sure. This is almost the same as #18, with a slight difference in the proposed change to the csv file.

**Comment by eugenepeh** [comment]
>We already have a use case for this, in CS3282 https://github.com/nus-cs3281/2019-dashboard/blob/master/configs/author-config.csv

🤔 We already have added some form of support for this in #441 though, although not that effective in your current use case, we can probably enhance it by adding an additional option `Hide authors without contribution`? This way you can even save the time keying in the repos.

**Comment by damithc** [comment]
> 🤔 We already have added some form of support for this in #441 though, although not that effective in your mentioned use case, we can probably enhance it by adding an additional option `Hide authors without contribution` in repo-config.csv? This way you can even save the time keying in the repos in author-config.csv.

Yes, the current form results in too many combinations. `Hide authors without contribution` is not necessarily a good thing either; sometimes you want to see an empty row when a certain author was _expected_ to contribute but did not contribute. In most cases we want to specify the exact author+repo+branch combination that we are interested in.

**Comment by fzdy1914** [comment]
It seems the improvement mentioned in #18 is more doable, we just need to record the author information of the previous line, and add it to the config if this line's author is empty.

**Comment by anubh-v** [comment]
>  **Suggested**

> Repo/branch | ...
> -- | --
> https://github.com/reposense/reposense.git/master; https://github.com/markbind/markbind.git/release | ...

Compared with #18, I think this style will be better for user experience as it results in fewer rows.

However, suppose a user works on multiple repos and has different file paths for **ignore glob list** for each repo.

In that case, would they have to use the existing method of specifying one repo-location per row?

Or do we want to support some special syntax such that multiple sets of **ignore glob lists** can be placed in the same row?For example, we might use a symbol like `+` to indicate that we have multiple sets of **ignore glob lists**.

In the example below, the `docs**` pattern would belong to the second repo-location.

|...| Ignore glob list |
| --| ---------------------|
| ..| src/main** ; src/test** + docs**|

**Comment by eugenepeh** [comment]
>Or do we want to support some special syntax such that multiple sets of ignore glob lists can be placed in the same row? We could use a symbol like + to indicate that we have multiple sets of ignore glob lists. In the example below, the docs** pattern would belong to the second repo-location.

This is complicating things. We shouldn't implement complicated logic for some unusual use cases, not to mention that this is also not very user friendly. We can assume that the `ignore glob list` entered will be applied to all the repos. If the user have differing requirements for different repos, they should key in as separate rows.

**Comment by anubh-v** [comment]
Thanks for the response @eugenepeh 

Will proceed with this:
> We can assume that the ignore glob list entered will be applied to all the repos. If the user have differing requirements for different repos, they should key in as separate rows.

**Comment by anubh-v** [comment]
I've started a draft implementation in #1098

Here is a breakdown of the new `author-config.csv` format:

1. The `Repository Location` column accepts a list of repository locations. The list of locations can contain both git URLs or paths to git repositories
2. For the git URLs provided in the `Repository Location` column, users can **optionally** append the branch name to the URL, (as shown below). For such URLs, the `Branch` column is ignored.

Example:

Repo/branch | Branch
-- | --
https://github.com/reposense/reposense.git/release; https://github.com/markbind/markbind.git/gh-pages | master

In the above csv, the `AuthorConfiguration` instances created for `reposense` and `markbind` will use the `release` and `gh-pages` branches respectively, and not the `master` branch.

3. If a particular git URL does not have the branch name appended onto it, then the branch field is taken from the `Branch` column.

Example:

Repo/branch | Branch
-- | --
https://github.com/reposense/reposense.git/release; https://github.com/markbind/markbind.git | master

The `AuthorConfiguration` instance created for `markbind` will use the `master` branch, as specified in the `Branch` column

4. For file paths to git repositories, users cannot append the branch name to the file path. The branch name must be specified in the `Branch` column, just like the current usage.

5. The settings in the remaining columns (author's GitHub ID, author's emails, author's display name, git authornames, author's ignore glob list) are applied to all `AuthorConfiguration` instances created for that row.

@damithc @eugenepeh is this format appropriate?
Specifically, I want to clarify point 4 above.

**Comment by damithc** [comment]
> 1. For file paths to git repositories, users cannot append the branch name to the file path. The branch name must be specified in the `Branch` column, just like the current usage.

What's the reason for this restriction?

**Comment by anubh-v** [comment]
Thanks for the response @damithc 

> What's the reason for this restriction?

I wanted to confirm whether we would like to allow users to append the branch name to the git repository file paths, before proceeding with the implementation.

In the current PR, users can provide a list of file paths to git repos, but the branch name for all of these is taken from the `Branch` column.

In my view, allowing users to append the branch name to file paths would increase user friendliness.
However, we cannot use `/` or `\` to specify the branch name (as we have done with the git URLs).
This is because file paths may use an arbitrary number of slashes.

I can propose some other syntax for specifying the branch name in the file path string.

**Comment by damithc** [comment]
> I wanted to confirm whether we would like to allow users to append the branch name to the git repository file paths, before proceeding with the implementation.

It is better to support the feature for both types.

> I can propose some other syntax for specifying the branch name in the file path string.

Can we find a syntax that works for both? e.g., `#`

**Comment by anubh-v** [comment]
> It is better to support the feature for both types.
Can we find a syntax that works for both? e.g., #

Ok. I will propose a common syntax for URLs / file paths.

**Comment by eugenepeh** [comment]
How about this:
* We support this syntax https://github.com/reposense/RepoSense/tree/master in the repo list configuration.
* In the event that the user does not provide a branch in the url, e.g. just https://github.com/reposense/RepoSense, we will either take the value from branch column or use the default branch

For file path, we shall assume the current checkout branch by default - unless specified otherwise in branch column

**Comment by anubh-v** [comment]
@eugenepeh, thanks for the response.

I have some clarifications:

> We support this syntax https://github.com/reposense/RepoSense/tree/master in the repo list configuration.

That is similar to Prof's original suggestion, which was to support URLs of the form:
`https://github.com/reposense/reposense.git/master`  (i.e. the branch appended to the **git** URL)

Are you suggesting that we use the web URL instead?
We do need the **git** URL subsequently to clone the repository.

> In the event that the user does not provide a branch in the url, e.g. just https://github.com/reposense/RepoSense, we will either take the value from branch column or use the default branch

Yes, my current implementation takes the value from branch column. If no value is present in the branch column, then the default branch is assumed.

> For file path, we shall assume the current checkout branch by default - unless specified otherwise in branch column

I think Prof wants to allow users to optionally append the branch to the file paths, though.
Is there a reason not to allow this behaviour?

**Comment by eugenepeh** [comment]
>Are you suggesting that we use the web URL instead?
We do need the git URL subsequently to clone the repository.

Even though its not clone-able, it is still a legitimate url on github which can be more intuitive and easier for users to remember. It will also easier for us to reuse it on other part of the program, e.g. repo url.

>I think Prof wants to allow users to optionally append the branch to the file paths, though.
Do you see a reason not to allow this behaviour?

iirc when you clone a local repo, you will only get the current working branch.
If you want all the branches, you need to do a copy. However, copy will comes with the problem of uncommitted changes, so its better use copy.

**Comment by anubh-v** [comment]
Thanks for the reply @eugenepeh.

There are no implementation issues if we want to use the repo's web url in the `author-config.csv` file, since the git url is present in the `repo-config.csv`.

However, I want to clarify the following:
- Would this mean we only accept a repository's web url in the location field of `author-config.csv`, or we accept **either** the git url or web url? We may need to accept either for backward compatibility purposes (i.e. so that users in cs2103 / cs3281 do not need to rewrite the `author-config`)

- In my opinion, it is more user friendly to use the same url type in both `repo-config.csv` and `author-config.csv`. With this approach, users would have to provide the web url in `author-config` and git url in `repo-config`. What do you think?

**Comment by eugenepeh** [comment]
>Would this mean we only accept a repository's web url in the location field of author-config.csv, or we accept either the git url or web url? We may need to accept either for backward compatibility purposes (i.e. so that users in cs2103 / cs3281 do not need to rewrite the author-config).

Either would be nice, we should be able to extract the org and repo name from the url easily given that they have similar structure.

>Taking a step back, the reason for having the location and branch fields in author-config is to allow us to match the author with the repos in repo-config. We could consider even removing the need for explicit URLs in author-config. Instead of providing the url or file path, users could just provide the organisation name and reponame (or the directory name of the repo on disk). These names can be used to identify the repo in repo-config.

The reason for url implementation is that it is easy for user to copy and paste from the address bar itself. If we change the implementation to force user to enter organisation name and reponame, they may need to key them in manually, which can be not very user-friendly.

**Comment by anubh-v** [comment]
> Either would be nice, we should be able to extract the org and repo name from the url easily given that they have similar structure.

Thanks for the response. I will proceed with this.
