### ISSUE TITLE
Identify file types automatically

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#531]
Current: If file types are not specified in the config files, RepoSense analyzes a set of default file types
Suggested: If file types are not specified, analyze all file types modified during the analysis period

**Comment by eugenepeh** [comment]
Sounds good to me. Shouldn't take a major change.

**Comment by jylee-git** [comment]
![image](https://user-images.githubusercontent.com/35756209/58316681-b02c1400-7e46-11e9-8dc1-b263e422275a.png)

I believe this is the result of the suggested solution, such that if user does not specify any file extension type, all files that were modified will be captured. But how are we going to deal with the binary files (such as .zip)?

**Comment by eugenepeh** [comment]
We have binary file check within the code so that binary files wouldn't appear in the code view. This seems like a bug.

**Comment by jylee-git** [comment]
> Our binary file check within the code supposed to ensure that the binary files wouldn't appear in the code view. This seems like a bug.

Ok. Will file an issue regarding this.

**Comment by jylee-git** [comment]
![image](https://user-images.githubusercontent.com/35756209/58464458-4ecab480-8168-11e9-84a6-a5203f95e2de.png)


Would this be the intended result (where user does not specify any file types, and any file types will be captured as a result)?

**Comment by eugenepeh** [comment]
>Would this be the intended result (where user does not specify any file types, and any file types will be captured as a result)?

Seems good, but the formats on the chart view doesn't match those on the code view.
