### ISSUE TITLE
Code View: Show untouched code button does not work after #490

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#534]
Broke in this commit: https://deploy-preview-490--reposense.netlify.com/#search=&sort=displayName&since=2017-10-09&until=2019-01-22&timeframe=day&reverse=false&repoSort=true

A commit before: https://deploy-preview-505--reposense.netlify.com/#search=&sort=displayName&since=2017-10-09&until=2019-01-22&timeframe=day&reverse=false&repoSort=true

**Comment by eugenepeh** [comment]
@fzdy1914 , seems like your implementation has accidentally broke the untouched code feature. Could you please help to rectify it?

**Comment by fzdy1914** [comment]
Reived message, will look into it now.
