### ISSUE TITLE
gradlew run: tasks in incorrect order causes the NullPointerException or use of outdated templateZip

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#537]
To replicate:

1. Make some changes to the js files in `./frontend/src/static/js` 
1. Run `./gradlew run -Dargs="-view"`; there should not be any changes
1. Run `./gradlew run -Dargs="-view"`; changes are reflected

**Comment by eugenepeh** [comment]
I believe its the execution order. 

```
task zipReport(dependsOn: 'npmRunSpuild', type: Zip) {
    from 'frontend/build/'
    baseName = 'templateZip'
    destinationDir = file('src/main/resources')
}
```

If we execute `build` follow by zipReport, it will throw the zip file to source but it will not be in the `build` for current process, hence there wouldn't be any changes. Only in the following `build`, it will move the zip file to `build` folder for the program to utilize.

**Comment by yong24s** [comment]
Similarly, on a clean checkout (`git clean -fdx`), gradle `run` does not copy `templateZip` in to the Jar, resulting in `NullPointerException`.

```
> Task :run FAILED
08:37:55 - Log folder has been successfully created
Exception in thread "main" java.lang.NullPointerException: in is null
        at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:101)
        at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:80)
        at reposense.util.FileUtil.unzip(FileUtil.java:115)
        at reposense.util.FileUtil.copyTemplate(FileUtil.java:145)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:49)
        at reposense.RepoSense.main(RepoSense.java:53)
```

**Comment by yong24s** [comment]
This also fix race condition that appears almost every run in AppVeyor and rarely on Travis-CI.

```
> Task :zipReport
> Task :systemtest FAILED
reposense.ConfigSystemTest > testDateRange FAILED
    java.lang.NullPointerException at ConfigSystemTest.java:83
reposense.ConfigSystemTest > testNoDateRange FAILED
    java.lang.NullPointerException at ConfigSystemTest.java:83
2 tests completed, 2 failed
```
