### ISSUE TITLE
Perform cloning in parallel with analyzing

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#540]
Cloning takes significant amount of time if the target repo is big even with a relatively fast internet. However, it does not takes much processing power, perform cloning in parallel with analyzing shouldn't increase much cpu load. As analyzing contribution can take significantly long and no bandwidth is being utilized in this state, we can speed up the process by doing both in parallel. 

Let's clone the next repo to be analyzed during the analysis to essentially remove cloning from waiting time.

**Comment by damithc** [comment]
Threading can cause debugging nightmares. We shouldn't use threading unless there is a significant time saving, like 20%+

**Comment by yong24s** [comment]
It may be easier if we git clone everything at the start in a ThreadPool? As we may need to handle race condition when cloning while analyzing. 🤔 

Also this issue may supersede #337.

**Comment by damithc** [comment]
> It may be easier if we git clone everything at the start in a ThreadPool? 

Also consider the space requirement. 50 big repos could add up to 25 GB!

**Comment by damithc** [comment]
> This can save us a lot of time when analyzing the 2103 repos. Taking the cloning and analysis time to be equal (AB4 is pretty big considering that some students added lots of dependencies, jar, documents, images, gif and etc to AB4 which causes it to be rather big and the network speed, it can sometimes takes awhile to download), we can effectively cut the entire process to half the time.

Sounds good. 50% is a significant gain.
