### ISSUE TITLE
Page unresponsive when loading report of many repos with huge date gap

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#542]
As per title. 

For e.g. If we set up the dashboard demo to show the analysis for period of a year, the page will become unresponsive for a long while (even though most of the actual contributions are within 3 months) which makes it near unusable.

**Comment by emer7** [comment]
I'll look into this

**Comment by emer7** [comment]
Sorry for the late response

The culprit is from this line of code.
We are running a for loop that will loop each single day for each user in each repo.
Naturally for a larger date range, it will loop longer, hence the unresponsiveness.

v_summary.js
```
331.  let diff = getIntervalDay(userFirst.date, sinceDate);
...
334.  for (let dayId = 0; dayId < diff; dayId += 1) {
```

**Comment by eugenepeh** [comment]
hmm, can we do away with empty commits as a whole?

**Comment by emer7** [comment]
> hmm, can we do away with empty commits as a whole?

If I understood correctly, merging the empty commit become 1 big empty commit?

**Comment by eugenepeh** [comment]
>If yes, I think it could be done, it will need change to how report is generated (empty commit is lumped together. I need to look into how it is done) and also change v_summary.js#getSlicePos

Hmm actually what I thought of is that let the `commits` stores nothing other than non-empty commits. 
You can try it out, research on this issue on how can we be more memory/computational efficient and present your findings in your PR.
