### ISSUE TITLE
Implement grouping of ramp charts by authors

### ISSUE THREAD

**Issue by chelseyong** [reposense/RepoSense#543]
Current: Main page allows grouping of the ramp charts by repository.
Suggested: Group ramp charts by authors, so that it is easier to check on a particular user's progress.

**Comment by emer7** [comment]
Are you going to work on this? @chelseyong

**Comment by chelseyong** [comment]
@emer7 yep :)

**Comment by apoorva17** [comment]
@chelseyong are you working on this?

**Comment by chelseyong** [comment]
@apoorva17 I will be working on it soon.
