### ISSUE TITLE
FAQ: add another entry to propose email as alternative to GitHub ID

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#546]
as per title

**Comment by yong24s** [comment]
Should also explain adding GitHub name in the author names of config, if one uses branch and merge workflow.

**Comment by eugenepeh** [comment]
>Should also explain adding GitHub name in the author names of config, if one uses branch and merge workflow.

It is already there.
https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#q-my-commit-contributions-does-not-appear-in-the-ramp-chart-despite-appearing-in-the-contribution-bar-and-code-panel
