### ISSUE TITLE
Tick boxes and expand/collapse button don't play well together

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#549]
Ticking file types tick boxes (in particular, the `All` tick box) and expand/collapse button in tandem can result in inconsistent states. An example given below:

From https://nus-cs3281.github.io/2019-dashboard

![image](https://user-images.githubusercontent.com/1673303/52517242-7c502880-2c73-11e9-9512-c71f5713b364.png)

**Comment by yong24s** [comment]
Duplicate of #521. 
Will resolve in PR #529. :-)

**Comment by fzdy1914** [comment]
Close via #529
