### ISSUE TITLE
ChartView: add a PR view

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#562]
While GitHub do provide means for users to track the PR done by a specific author, it is by no means a good summary view. With the provided information and our ui setup, it is possible for us to provide such a service to our users.

E.g. List out all the PRs opened by each authors on the chart view, using ramp size to visualize the gross LoC changes, and ramp color to represent the PR status. This will help the reviewers not only look at the work done by the author, but also the work that are in progress.

As this info cannot be derive purely on the cloned repository, do explore the use of [GitHub api](https://developer.github.com/v3/pulls/).

**Comment by damithc** [comment]
As of now, we are unlikely to go into features requiring GitHub API. Closing for now.
