### ISSUE TITLE
Generated archieve.zip contains non-relevant json file

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#567]
As mentioned in the title, when generating the archieve.zip, we include all the json file in the output directory. However, if they are other directories that are left out in the output directory(e.g. analyze the other repos before), the json file will also be included in the archeve.zip. 

This behavior should not be the intended behavior of our project.

**Comment by emer7** [comment]
I think this can be solved by before writing into the zip, we check what should be zipped based on `summary.json`, what do guys think? @reposense/stage2-reviewers 

If okay I can take this issue

**Comment by fzdy1914** [comment]
Can base on RepoConfigurations I believe.

**Comment by eugenepeh** [comment]
Before starting on this issue, do verify that the report still works when opening as a file (without a server).
This functionality may be obsolete by now.

**Comment by jylee-git** [comment]
If this issue isn't being fixed right now, can I attempt to fix this issue?

**Comment by fzdy1914** [comment]
Yes, I believe you can fix this issue.
I suggest you can try to make use of the existing `RepoConfigurations`.
