### ISSUE TITLE
refactor frontend to move v_summary and v_authorship into sub component files

### ISSUE THREAD

**Issue by ongspxm** [reposense/RepoSense#576]
In #573, we have done some major refactoring to the frontend, moving out files into their own components. This is done as part of the effort to make reposense's dashboard much more extendable in the future.

As such, we should move `v_summary` and `v_authorship` into their own `.pug` templates as well. This should be done asap, but after the current frontend PRs are closed.

**Comment by Tejas2805** [comment]
@eugenepeh @damithc @yong24s for refactoring v_summary which of the following options do you all think I should go ahead with?

**Option 1:**
Refactoring the whole `v_summary` into one sub-component file.

**Option 2:**
Refactoring the `v_summary` and `summary-charts` into different sub-component files.

**Comment by fzdy1914** [comment]
@Tejas2805 Latter is preferred. For the same issue, you may also explore to separate a `summary-charts.js` from `v_summary.js`.
