### ISSUE TITLE
CodeView#filter: add interactive selection switch

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#581]
As discussed in https://github.com/reposense/RepoSense/pull/532#pullrequestreview-204250162, `the filter selection's radio button serves nothing more than an "indicator"`. Changing option doesn't do anything until the corresponding controls are modified. Hence, it is rather redundant for users to manually switch the selection. To simplify things in #532, this has been discussed to be implemented separately in another PR. 

Hence, we should improve the users' satisfaction by implementing this change after the addition of #532. That is to `Instead of disabling the deselected option, let's make interaction switch the selection`.

**Comment by fzdy1914** [comment]
@eugenepeh 
Hi, I want to clarify one thing.
For example, if we use *.java to filter out all the java files, is the checkboxes bellow should be updated or not?
![image](https://user-images.githubusercontent.com/35621726/53939026-f1851100-40ec-11e9-815d-e552fbda09d9.png)

**Comment by eugenepeh** [comment]
@fzdy1914 

For this issue, what I intend is to have the radio buttons `serves nothing more than an "indicator"`. So basically make them non selectable and highlight the last control used `that match the current state of the shown code view`.

So the expected behavior should be, 
First scenario:
1. User type the glob patterns and press `search`
2. Code view filter according to the glob patterns
3. Code view update the radio button to highlight that the `search` bar was used.

Second scenario:
1. User check/uncheck the checkboxes
2. Code view filter according to the check boxes pattern
3. Code view update the radio button to highlight that the checkbox control was used.

**Comment by fzdy1914** [comment]
> For this issue, what I intend is to have the radio buttons `serves nothing more than an "indicator"`.

Since it is a radio button, is it better to retain its original function? If it is only an indicator, we may even use other symbols to indicate that.

**Comment by eugenepeh** [comment]
>Since it is a radio button, is it better to retain its original function? If it is only an indicator, we may even use other symbols to indicate that.

I think its fine to use radio button as an indicator for now. We can replace it subsequently, the main thing for now is that user shouldn't be required to perform meaningless interaction. 

E.g. having to switch the radio button selection to enable controls and update value afterward.

Also, the checkbox were reset and files get refreshed before any actual change to the filter parameters were changed when switching the radio button is also not desirable. 
These are all redundant actions.
