### ISSUE TITLE
Give a way to set website properties

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#590]
Current:
The deployed dashboard doesn't have a name, favicon, etc.
![image](https://user-images.githubusercontent.com/1673303/53924951-1b244500-40b9-11e9-9427-84216317be00.png)

Suggestion: Give a way to specify such website properties.

Items to do:
- [ ] A way to set favicon
- [ ] A way to set page title

**Comment by fzdy1914** [comment]
Related to #467. I am considering to add a new config in our codebase with serves the role to configure the generated report. Including title, icon, intro or anything else which may need in the future to configure the report.

**Comment by damithc** [comment]
> Related to #467. I am considering to add a new config in our codebase with serves the role to configure the generated report. Including title, icon, intro or anything else which may need in the future to configure the report.

Good idea. Note that a config file not may be the best format to hold HTML content, to be used in the intro, unless you restrict the intro to plain text only. The alternative is to expect these info to be in a specific files e.g., `/site_config/favicon.ico`  `/site_config/intro.html` etc.

**Comment by Tejas2805** [comment]
@damithc What else do we have left for this? Anything else left or can we close this?

**Comment by damithc** [comment]
> @damithc What else do we have left for this? Anything else left or can we close this?

I updated issue description to add the required tasks
