### ISSUE TITLE
Use better error display in frontend report

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#598]
```
The generated report uses a generic placeholder for repositories that
failed analysis.

The placeholder looks similar to a blank rampchart, which may be
overlooked as it blends in with other rampcharts.

Also, the placeholder does not show useful errors to `Repo Owners` [1],
which may be useful for troubleshooting, as they may not necessary have
the CLI logs.

[1] CS2103/CS2113/CS3281 students
```

**Comment by jylee-git** [comment]
Would it be good to have a conspicuous message on top stating which repos failed to analyze and the reasons for that?

![image](https://user-images.githubusercontent.com/35756209/59173627-59317900-8b80-11e9-8789-3f7fb42b1ea7.png)

**Comment by yong24s** [comment]
I'm thinking of having a tool tip at the repo to show more detailed errors. It's helpful to propagate error logs caused by misconfiguration, say https://github.com/reposense/RepoSense/pull/564.

![image](https://user-images.githubusercontent.com/2003406/59174492-30ab7e00-8b84-11e9-9067-5e03d080380a.png)

Not sure if we should do this issue yet. What do you think @damithc?

**Comment by damithc** [comment]
It is cleaner if error'ed repos are reported separately as @jylee-git has suggested, rather than within the chart as we do now. But I'm not sure how much extra work is needed for that. @jylee-git any idea about how much extra work it will take?

**Comment by jylee-git** [comment]
Up to 3 days to make a PR if everything is smooth sailing.

If we are going to work on this, should we modify `summary.json` to include an object to store list of error messages?

**Comment by damithc** [comment]
OK, give it a try. While the functionality is not so important from the user POV, I think it is good to have a proper way of communicating error information to the frontend.

**Comment by jylee-git** [comment]
@damithc  need your opinions on which may be a better choise: -

![image](https://user-images.githubusercontent.com/35756209/59413287-dd3e6780-8df1-11e9-9976-c9406ff4dc8c.png)

vs
![image](https://user-images.githubusercontent.com/35756209/59413301-e3ccdf00-8df1-11e9-8b42-16e9a3b81876.png)

**Comment by damithc** [comment]
Both look ok, but I prefer the second one.
For exclamation mark, use font icons rather than emoji (similar to the icons used to link to the code view)
The title can be left-aligned to match the rest.

**Comment by jylee-git** [comment]
Updated look: -
![image](https://user-images.githubusercontent.com/35756209/59415724-9ef77700-8df6-11e9-98d2-e24097ee4196.png)

Will clean up the codes and make a PR once done.

**Comment by damithc** [comment]
Looks good 👍

**Comment by yong24s** [comment]
@damithc 

Should we have a dismiss button to remove the error messages? It should also persist in the report state.

Use case: User wants to share the report but its unprofessional to show the errors and it takes a long time to regenerate the whole report?

**Comment by damithc** [comment]
> @damithc
> 
> Should we have a dismiss button to remove the error messages? It should also persist in the report state.
> 
> Use case: User wants to share the report but its unprofessional to show the errors and it takes a long time to regenerate the whole report?

That's a good idea. But low priority as reports are not supposed to have errors in the first place. It can be done as a separate issue, or left alone for future contributors.

**Comment by fzdy1914** [comment]
@damithc 
The font size is a little bit too big from my perspective (comparing with other font sizes in v_summary ), should the font be smaller?

**Comment by damithc** [comment]
> @damithc
> The font size is a little bit too big from my perspective (comparing with other font sizes in v_summary ), should the font be smaller?

Yes, we can adjust it to match the text size of the toolbar.

**Comment by jylee-git** [comment]
![image](https://user-images.githubusercontent.com/35756209/59574778-2ab91e00-90eb-11e9-8e8e-ce4132df2e12.png)

How about this size?

**Comment by fzdy1914** [comment]
> ![image](https://user-images.githubusercontent.com/35756209/59575528-73260b00-90ee-11e9-81b8-92a27af70f93.png)
> 
> How about this size?

The font is OK, but maybe let `!` be smaller?

**Comment by damithc** [comment]
Ok for me.
As for colors, here's an alternative:
![image](https://user-images.githubusercontent.com/1673303/59984149-a40bc000-9659-11e9-9a72-0cdae89df2f1.png)

**Comment by jylee-git** [comment]
![image](https://user-images.githubusercontent.com/35756209/60067449-2b7e2f80-973d-11e9-9b6f-ff0c42c01235.png)


How about this? @damithc @fzdy1914

**Comment by damithc** [comment]
Looks good.
