### ISSUE TITLE
Add coverage test for RepoSense

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#600]
As title. It is import for our project to have some kind of coverage test to enhance code quality.

**Comment by fzdy1914** [comment]
![image](https://user-images.githubusercontent.com/35621726/54866846-0384d600-4db4-11e9-879c-4cb778ef682b.png)
It seems that we now have good coverage, maybe we can add the coverage task to our repo.

**Comment by fzdy1914** [comment]
@eugenepeh Your opinion on this?

**Comment by eugenepeh** [comment]
>@eugenepeh Your opinion on this?

We pushed off the plan to add it in because our coverage was low in the past and have lots of architecture change. Feel free to integrate it in
