### ISSUE TITLE
Differ of Commit date and Author date confuses the github link in RampChart

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#603]
The problem is like below:

From this [link](https://deploy-preview-29--ecstatic-goldwasser-4c5dd4.netlify.com/#search=&sort=displayName&since=2018-12-01&until=2019-03-16&timeframe=day&reverse=false&repoSort=true&breakdown=false), we are able to see 3 ramps in my contribution to checkstyle. However, only the last link opened in GitHub will show the commit info correctly.

The reason is that the commit date and the author date is not the same for my first two commits. 

See the following commit as an example:
![image](https://user-images.githubusercontent.com/35621726/54471655-621be400-47f7-11e9-9bf4-eca179aec24d.png)
![image](https://user-images.githubusercontent.com/35621726/54471663-824ba300-47f7-11e9-9fef-cae68283edd3.png)

Repo Sense caught my commit on 12/2, which is my author date. However, when using this date to filter on github, i.e. open the corresponding [link](https://github.com/checkstyle/checkstyle/commits/master?author=fzdy1914&since=2019-02-12%27T%2700:00:00+08:00&until=2019-02-12%27T%2723:59:59+08:00). Github will not return correct result.

**Comment by eugenepeh** [comment]
Yes, because GitHub uses the commit date
![image](https://user-images.githubusercontent.com/19277206/54474335-8212ce00-481e-11e9-89ad-53a7a9949863.png)

Maybe we should use commit date instead of author date too.
