### ISSUE TITLE
CodeView: page unresponsive when loading large code

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#604]
When loading code view for JACOB in https://nus-cs3281.github.io/2019-dashboard/

![image](https://user-images.githubusercontent.com/19277206/54474181-c0a78900-481c-11e9-9088-858ef9490415.png)

**Comment by okkhoy** [comment]
In fact, the page dies with a "aw snap" in my case 😞

**Comment by eugenepeh** [comment]
>In fact, the page dies with a "aw snap" in my case 😞

@okkhoy did it break for your 2113 classes?

**Comment by okkhoy** [comment]
@eugenepeh yes. This happened for the CS2113 class. I am yet to set it up on CS2103.

**Comment by okkhoy** [comment]
Additional details of the issue:

The landing page loading itself takes VERY long (order of few minutes).

Once the page is loaded, try to open any student's code. The entire page crashes.

Please take a look at this: https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=&sort=displayName&since=2019-02-07&until=2050-03-18&timeframe=day&reverse=false&repoSort=true&breakdown=false

**Comment by damithc** [comment]
Hmm... we need to solve this quickly

**Comment by damithc** [comment]
@okkhoy why is this 2050?
![image](https://user-images.githubusercontent.com/1673303/54578134-8ebf3e00-4a39-11e9-8ff6-c783bf6c7f93.png)

**Comment by okkhoy** [comment]
@damithc  no clue 😜 that is the default it took. This is exactly the reason I asked on slack if we can add other options along with `--config` yesterday. Want to give the timeline just for the semester

**Comment by damithc** [comment]
> @damithc no clue 😜 that is the default it took. This is exactly the reason I asked on slack if we can add other options along with `--config` yesterday. Want to give the timeline just for the semester

Set start and end date to specific dates. Example https://github.com/nus-cs3281/2019-dashboard/blob/master/run.sh

**Comment by damithc** [comment]
@eugenepeh is this (i.e., using 2050 as end date) a bug? Or possibly one of the repos has a rouge commit with a 2050 timestamp?

**Comment by eugenepeh** [comment]
>@eugenepeh is this (i.e., using 2050 as end date) a bug? Or possibly one of the repos has a rouge commit with a 2050 timestamp?

That is most likely the case. It is possible to commit and change the date after all.

**Comment by fzdy1914** [comment]
Close this as covered by #666
