### ISSUE TITLE
Unknown bug of gradle npminstall

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#605]
I have encountered a problem for the frontend.
After I edit the js file, no matter how many time I run the `gradlew run`, the output js will not change.

**Comment by fzdy1914** [comment]
Bug does not occurs now...

**Comment by litone01** [comment]
Hi @fzdy1914, I have also encountered the same problem, can I kindly check what have you done to resolve the issue?

**Comment by fzdy1914** [comment]
@litone01 Try to run the command twice? The first `gradlew run` after code change will not take effect though.

**Comment by litone01** [comment]
@fzdy1914 I tried several times but it's the same:(

**Comment by fzdy1914** [comment]
@litone01 No worries.
