### ISSUE TITLE
You may want to use a dummy account for the GitHub token

### ISSUE THREAD

**Issue by okkhoy** [reposense/RepoSense#606]
I feel it is better to use a dummy account to generate the token and add the dummy account as a collaborator to run dashboard update/deploy in the Travis build.

Relevant document to update: https://github.com/reposense/RepoSense/blob/release/docs/PublishingGuide.md

**Comment by eugenepeh** [comment]
Thanks for the feedback! Yes we can add that as an alternative to 7. 
`Ensure that the Display value in build log is switched off for security reasons ...`

**Comment by yong24s** [comment]
[Deploy Keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) may be better suited at this role, where access can be controlled at repo level.

When I was doing the guide, I wanted to keep things simple so I used GitHub Token over Deploy Keys.

Perhaps, we can explore using Deploy Keys.
