### ISSUE TITLE
Cloning in parallel makes some of log message unclear

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#609]
As, titile.

See the log message below, we can not determine which repo is the underlined log message belonged to.

![image](https://user-images.githubusercontent.com/35621726/54579093-f2973600-4a3c-11e9-92f4-48c3aca2c05e.png)

It is better to add the repo detail to all the log messages.

**Comment by eugenepeh** [comment]
Good catch 👍

**Comment by myteo** [comment]
> It is better to add the repo detail to all the log messages.

Only one repository will be analyzed at one time, so I think adding a log message at the beginning of each repository's analysis should be sufficient?
