### ISSUE TITLE
Until date doesn't seem to be honored

### ISSUE THREAD

**Issue by okkhoy** [reposense/RepoSense#610]
Please refer to the screenshot for details.

![image](https://user-images.githubusercontent.com/1023494/54579174-37bb6800-4a3d-11e9-8759-ae5608baeb47.png)

PS: or is it the case that if `until` is specified it picks up either the given date or the current date, which ever is earlier?

**Comment by eugenepeh** [comment]
Yes, when a future until date is given, RepoSense can only analyze up till current date. This means that the report can also only be shown up to the report's generation date.

**Comment by eugenepeh** [comment]
#518

**Comment by damithc** [comment]
When an end date is given, perhaps it is better to follow the given end date rather than use _today_ as the end date? Reason: that way, the report's horizontal scale can remain the same every time the report is generated.

**Comment by eugenepeh** [comment]
>When an end date is given, perhaps it is better to follow the given end date rather than use today as the end date? Reason: that way, the report's horizontal scale can remain the same every time the report is generated.

Make sense, will take note to include that into the fix for #518

**Comment by eugenepeh** [comment]
Resolved in #539
