### ISSUE TITLE
Show dashboard at repo level

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#614]
Suppose one wants to compare activities between repos (i.e., not between authors). How difficult is to add that functionality to the current implementation?

**Comment by eugenepeh** [comment]
I suppose this shouldn't be too difficult as all the information already exist in the output files.
We can simply implement a `merge group` checkbox and consolidate all the contributions done by the authors (or repo if `group by authors`) on a single ramp chart.

**Comment by damithc** [comment]
Superseded by #662
