### ISSUE TITLE
Shift the log file to output folder

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#621]
In the event of a bug investigation, it would be more useful if the log file is tagged along with the generated report. Let's have the log file generated together in the designed output folder.

**Comment by fzdy1914** [comment]
Working on this.

**Comment by fzdy1914** [comment]
> Let's have the log file generated together in the designed output folder.

Can I clarify which this `designed output folder` mean? Do you mean the default output directory?

If the user specifies the output directory using the command line, do we need to change the log directory to the user-defined output directory? This may be a little harder to implement.

**Comment by eugenepeh** [comment]
>Can I clarify which this designed output folder mean? Do you mean the default output directory?

Yes. It will be best if its bind together with the report.

>If the user specifies the output directory using the command line, do we need to change the log directory to the user-defined output directory? This may be a little harder to implement.

Yes. Can try to figure out how to dynamically switch the log directory first.
