### ISSUE TITLE
Checkstyle: wrong position of curly brace not triggering error

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#624]
In the #623 PR, I have accidentally adopt the [Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style), which deviates from our coding standard, yet not triggering any checkstyle error

https://github.com/reposense/RepoSense/blob/0f6d4f305890442739f045c1c8eb5997c30bfaf2/src/main/java/reposense/parser/CsvParser.java#L55-L56

**Comment by emer7** [comment]
I will look into it
