### ISSUE TITLE
Update the link in the description of Repo Sense

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#630]
As title.
The generated report in the link is not up to date. Not updated with v1.8 or master.

![image](https://user-images.githubusercontent.com/35621726/54999981-725c6c00-500c-11e9-9e1e-811542605e55.png)

**Comment by eugenepeh** [comment]
>The generated report in the link is not up to date. Not updated with v1.8 or master.

It is the https://github.com/reposense/dashboard-demo not following the v1.8 product, can someone please help to update it?

**Comment by fzdy1914** [comment]
I will update them after v1.9 is released.

**Comment by fzdy1914** [comment]
@eugenepeh I have sent a PR to https://github.com/reposense/dashboard-demo.
