### ISSUE TITLE
Allow sinceDate and untilDate to be configured in config files

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#634]

**Comment by damithc** [comment]
It's a bit awkward to specify key-value pairs in a csv file though. Might have to add another json file for this purpose.

**Comment by anubh-v** [comment]
This would allow users to easily compare git activity for repositories that were active over different time periods.

i.e. Repository A was actively developed 1 year ago, while Repository B has only been under development for the past month.

With regards to specifying the `sinceDate` / `untilDate` in the `repo-config.csv` file, I think we could simply add a "Data range" column to `repo-config.csv`, as shown below?

Repository's Location | Branch | File formats | Ignore Glob List | Ignore standalone config | Ignore Commits List | Date range
-- | -- | -- | -- | -- | -- | --
https://github.com/foo/bar.git | master | override:java;css | test/** | yes |  | 10/10/2018;10/12/2018


@damithc , I'm not clear what you meant by the "difficulty of specifying key-value pairs in a csv". 

Does the above proposal for the `repo-config.csv` seem suitable?

**Comment by damithc** [comment]
If the value can differ across different repos, a csv file is the way to go.
But I'm not sure we can handle different periods for different repos. The current ReposSense ramp chart assumes a single timeline.

**Comment by anubh-v** [comment]
Thanks for the response @damithc 
Yes, I overlooked that `sinceDate` and `untilDate` are *report-level* parameters, and not *repository/branch* level.

Perhaps these parameters can be configured in the ReportConfiguration that is being considered in PR #627.

**Comment by FH-30** [comment]
Hi, can I try working on this issue?

**Comment by damithc** [comment]
> Hi, can I try working on this issue?

Go ahead @FH-30

**Comment by dcshzj** [comment]
Sorry @FH-30 @damithc I am currently working on this in #1501. This issue is currently assigned to myself.

**Comment by dcshzj** [comment]
@FH-30 I have closed my PR as it is not progressing. Feel free to work on it if you wish.

**Comment by FH-30** [comment]
Thanks for notifying @dcshzj , I would like to work on this issue!

**Comment by dcshzj** [comment]
@FH-30 Please do so. You may refer to the original PR I have created if you wish to.

**Comment by yhtMinceraft1010X** [comment]
I propose closing this issue since it has been encapsulated in #1360
