### ISSUE TITLE
Contribution bar length changes on breakdown option selected

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#637]
Seems like a bug introduced in #625, it only occurs after that PR

* https://deploy-preview-625--reposense.netlify.com/#search=eugene&sort=displayName&since=2017-10-09&until=2019-03-25&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false
* https://deploy-preview-596--reposense.netlify.com/#search=eugene&sort=displayName&since=2017-10-09&until=2019-03-25&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=true

![image](https://user-images.githubusercontent.com/19277206/55668172-743def00-5898-11e9-8f97-ade16dedc725.png)
![image](https://user-images.githubusercontent.com/19277206/55668170-6c7e4a80-5898-11e9-915f-ecff2415e72e.png)

**Comment by damithc** [comment]
@myteo can take a look?

**Comment by myteo** [comment]
Narrowed it down to this commit specifically: https://github.com/reposense/RepoSense/pull/625/commits/250a333ebf74f22b4964a86ac241b28ce443fb84 which is just changing the config file. I'll dig deeper, just putting it here in case anyone has an idea.
