### ISSUE TITLE
CS3281 dashboard: wrong start date shown

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#640]
https://nus-cs3281.github.io/2019-dashboard
![image](https://user-images.githubusercontent.com/1673303/56010893-ffdfd180-5d17-11e9-8cf5-71c4fb1424a1.png)

Actual start date is different https://github.com/nus-cs3281/2019-dashboard/blob/master/run.sh

**Comment by fzdy1914** [comment]
May be related to #603
