### ISSUE TITLE
GitBranch fails with empty repos

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#643]
I set this up a few days ago https://github.com/cs3217-ay1819s2-instructors/dashboard

Started failing today (on Travis)

>04:03:19 - Log folder has been successfully created
04:03:19 - Cloning in parallel from https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git...
04:03:19 - Waiting for cloning of https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git to complete...
04:03:23 - Cloning of https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git completed!
04:03:23 - Cloning in parallel from https://github.com/cs3217-1819/final-project-cs3217-name.git...
04:03:23 - Analyzing https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git (master)...
04:03:24 - https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git (master) does not contain a standalone config file.
04:03:24 - https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git (master) has no authors specified, using all authors by default.
04:03:24 - Extracting commits info for https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git (master)...
04:03:24 - Analyzing commits info for https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git (master)...
04:03:24 - Extracting relevant file info from https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git (master)...
04:03:31 - Analysis of https://github.com/cs3217-1819/final-project-cs3217-gooreatrestaurant.git (master) completed!
04:03:31 - Waiting for cloning of https://github.com/cs3217-1819/final-project-cs3217-name.git to complete...
04:03:31 - Cloning of https://github.com/cs3217-1819/final-project-cs3217-name.git completed!
04:03:31 - Cloning in parallel from https://github.com/cs3217-1819/final-project-dash.git...
04:03:31 - Analyzing https://github.com/cs3217-1819/final-project-cs3217-name.git (master)...
04:03:31 - https://github.com/cs3217-1819/final-project-cs3217-name.git (master) does not contain a standalone config file.
04:03:31 - https://github.com/cs3217-1819/final-project-cs3217-name.git (master) has no authors specified, using all authors by default.
04:03:31 - Extracting commits info for https://github.com/cs3217-1819/final-project-cs3217-name.git (master)...
04:03:32 - Analyzing commits info for https://github.com/cs3217-1819/final-project-cs3217-name.git (master)...
04:03:32 - Extracting relevant file info from https://github.com/cs3217-1819/final-project-cs3217-name.git (master)...
04:03:33 - Analysis of https://github.com/cs3217-1819/final-project-cs3217-name.git (master) completed!
04:03:33 - Waiting for cloning of https://github.com/cs3217-1819/final-project-dash.git to complete...
04:03:33 - Cloning of https://github.com/cs3217-1819/final-project-dash.git completed!
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at reposense.git.GitBranch.getCurrentBranch(GitBranch.java:23)
	at reposense.report.RepoCloner.getClonedRepoLocation(RepoCloner.java:69)
	at reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:110)
	at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:71)
	at reposense.RepoSense.main(RepoSense.java:59)

**Comment by fzdy1914** [comment]
https://github.com/cs3217-1819/final-project-dash.git is an empty repo. So, calling `git branch' will just return an empty string. We use the `trim` method of this string and get the second element. Since the string itself is an empty string, there is no second element in the trimmed array. This is the reason for the problem.

**Comment by damithc** [comment]
How come it is failing now but not before? There are few other empty repos in that list, as per the previous successful run https://cs3217-ay1819s2-instructors.github.io/dashboard

**Comment by fzdy1914** [comment]
This error occurs after #560 is merged. Basically, it tries to get the current branch of the repo without verifying if it has any branch.

**Comment by damithc** [comment]
@myteo can take a look?
