### ISSUE TITLE
Author name formatting is not aligned when breakdown formats are shown

### ISSUE THREAD

**Issue by chelseyong** [reposense/RepoSense#646]
![image](https://user-images.githubusercontent.com/30564248/56277333-57be7400-612e-11e9-8198-b5743190c2d8.png)

**Comment by damithc** [comment]
@apoorva17 can investigate?

**Comment by apoorva17** [comment]
> @apoorva17 can investigate?

This seems to be related to what I brought up [here](https://github.com/reposense/RepoSense/pull/547#issuecomment-480479563)

**Comment by eugenepeh** [comment]
Seems to be solved in #638, marking it as resolved for now.
