### ISSUE TITLE
Unresponsive Code Panel

### ISSUE THREAD

**Issue by apoorva17** [reposense/RepoSense#649]
When using the RepoSense jar (from latest master), the Code Panel becomes unresponsive for some authors. Here's an example for the report for RepoSense (ignoring the standalone config): 

![image](https://user-images.githubusercontent.com/19278550/56371990-ba983400-6230-11e9-9b46-a78deaa9d234.png)

**Comment by fzdy1914** [comment]
This should due to the scale of the lines. There are around 66k lines to load.
