### ISSUE TITLE
Exception messages in console output

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#651]
>Guys, I'm getting this error with the latest version of RepoSense (i.e., the recent RC release). No such problem with the previous version.

![image](https://user-images.githubusercontent.com/19277206/57180711-f16f7a80-6ebd-11e9-9133-ccf7fda8049e.png)

**Comment by eugenepeh** [comment]
@myteo can you look into this issue?

**Comment by fzdy1914** [comment]
I am investigating.

**Comment by fzdy1914** [comment]
Should be similar with this issue: https://github.com/apache/felix/pull/114

**Comment by fzdy1914** [comment]
The issue can be fixed by generating the jar file using JDK 8. When we do a release next time, we should remember to generating the jar file using JDK8 instead of JDK11.

**Comment by fzdy1914** [comment]
I will replace the jar file in the release using the correct one.
