### ISSUE TITLE
Migrate to JDK 11

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#653]
We use JDK 8 as our target language.

Oracle has already started requiring an Oracle account to download JDK 8. Meanwhile, the addressbook4 has migrated to JDK 11 already.

It makes no sense to use JDK 8 anymore, let's migrate our project to JDK 11.

**Comment by fzdy1914** [comment]
@damithc @eugenepeh 
Please kindly provide your opinion.

**Comment by damithc** [comment]
No objections from me. 👍

**Comment by eugenepeh** [comment]
The rationale from me is to be as backward compatible as possible (while remain usable with latest jdk), to widen our target audience beyond the AB users. So if there is no strong rationale to make the jump, we should keep the target version as it is.

For the Oracle issue, current proposition is to make the switch to openjdk instead.

**Comment by fzdy1914** [comment]
> The rationale from me is to be as backward compatible as possible (while remain usable with latest jdk), to widen our target audience beyond the AB users. So if there is no strong rationale to make the jump, we should keep the requirement as it is.
> 

OK, I agree with this. However, we should remember to make the release using JDK 8.

**Comment by damithc** [comment]
Yes it is good to keep backward compatibility unless there are some significant advantages of moving to later JDKs.
