### ISSUE TITLE
Make toolbars fixed top after scrolling

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#654]
![Capture](https://user-images.githubusercontent.com/2003406/57597065-4d9e6280-7580-11e9-8064-27cfaf9e6738.JPG)

It may be challenging to show all elements in the toolbar. So we can take [1] as an example and do a partition, keeping the useful elements the that fixed top partition.

[1] https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sticky_header

**Comment by jylee-git** [comment]
I'm attempting this enhancement, though may take a while for me as I'm still learning all the necessary tech stacks and the languages.

**Comment by damithc** [comment]
Let's hold back on this until we have finalized a new design for the tools bar. The downside of a sticky toolbar is that it takes screen space permanently; might not be a good thing for cases where the user has a lot of data to look at.

**Comment by jylee-git** [comment]
> Let's hold back on this until we have finalized a new design for the tools bar. The downside of a sticky toolbar is that it takes screen space permanently; might not be a good thing for cases where the user has a lot of data to look at.

Ok noted.

**Comment by jylee-git** [comment]
![image](https://user-images.githubusercontent.com/35756209/59012839-1f543000-886b-11e9-97e9-f709b85355bb.png)

This is the result of a sticky toolbar.Seems like the sticky toolbar will chomp out a huge portion of the space for code view. 

Not a good idea to implement the sticky toolbar on the code view unless if we implement it in such a way to allow the user to selectively show/hide the toolbars.

**Comment by damithc** [comment]
> Not a good idea to implement the sticky toolbar on the code view unless if we implement it in such a way to allow the user to selectively show/hide the toolbars.

Agreed. The current toolbars are good enough for the moment. Optimizing further is not an urgent requirement and could introduced unnecessary complications or bugs. Let's put this on hold for now.

**Comment by yong24s** [comment]
Sorry, I should have mentioned that this PR should depends on https://github.com/reposense/RepoSense/issues/509.

**Comment by damithc** [comment]
Closing for now. Will reopen later, if needed.
