### ISSUE TITLE
ChartView: File format breakdown takes up significant space

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#657]
<img width="822" alt="Screen Shot 2019-05-15 at 10 44 42 PM" src="https://user-images.githubusercontent.com/32864116/57785229-e3deae00-7763-11e9-8232-be169a00bdb2.png">

When charts are sorted by author, each author will have the same file format breakdown, which takes up significant space.

Suggestion: Only display the file format breakdown below the toolbar.

**Comment by damithc** [comment]
'Same author' doesn't necessarily mean 'same file breakdown' right? I thought file breakdown can vary based on the repo?

**Comment by jamessspanggg** [comment]
I've ran the program a couple of times with different repositories and the file breakdowns of all authors are the same when the charts are grouped by author.

Another observation:
The first image shows when it is grouped by repo/branch. As you can see, there are only 3 file breakdowns.
<img width="239" alt="Screen Shot 2019-05-15 at 11 58 57 PM" src="https://user-images.githubusercontent.com/32864116/57790790-0bd30f00-776e-11e9-9fba-93460242f0a5.png">

The second image shows when it is grouped by author. The number of file breakdowns are different even though it's the same author and repository.
<img width="826" alt="Screen Shot 2019-05-15 at 11 59 46 PM" src="https://user-images.githubusercontent.com/32864116/57791082-9d428100-776e-11e9-9140-12214f422eb4.png">

**Comment by damithc** [comment]
> I've ran the program a couple of times with different repositories and the file breakdowns of all authors are the same when the charts are grouped by author.

Sounds like a bug.

**Comment by jamessspanggg** [comment]
I think it is due to the highlighted code:
<img width="812" alt="Screen Shot 2019-05-16 at 11 14 24 AM" src="https://user-images.githubusercontent.com/32864116/57823979-17edb980-77cc-11e9-9ba5-d7083af972c9.png">

When the charts are not grouped by repo/branch, it will output all file breakdowns accumulated from all repositories. Hence all authors have the same file breakdown.
