### ISSUE TITLE
I/O errors when running unit tests using Gradlew in IntelliJ for Windows (and the workaround)

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#659]
A number of test cases failed (with all of them being I/O related exceptions) when running gradlew test using IntelliJ for Windows 10. I do not know the exact cause of this issue; it could be permission related issue or that IntelliJ's working directory isn't at RepoSense root folder.

However, one workaround for this is: -

1. Launch a terminal (Powershell, CMD, ...)
2. Change directory to the root folder of the RepoSense project
3. Type command `.\gradlew.bat test systemtest` and press `ENTER`

I think it would be good if we add this into the developer guide.

**Comment by fzdy1914** [comment]
![image](https://user-images.githubusercontent.com/35621726/57854032-cd932980-7819-11e9-8cdc-5db5932a35a6.png)
I got this error when running `gradlew run`, may be related to this.

**Comment by chan-j-d** [comment]
@dcshzj possibly related to #1134? I think it is safe to close this as well.

**Comment by dcshzj** [comment]
Yup, thanks @chan-j-d!
