### ISSUE TITLE
Ramp slices not within date range are still shown

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#660]
<img width="875" alt="Screen Shot 2019-05-16 at 4 20 34 PM" src="https://user-images.githubusercontent.com/32864116/57838410-4339ce00-77f7-11e9-9bc4-84b35fd5a288.png">

After adjusting the dates, some ramp slices that are no longer within the date range are still shown.

**Comment by fzdy1914** [comment]
Can I know how to reproduce the error?

**Comment by fzdy1914** [comment]
OK, Able to reproduce that. The granularity is set to be week. Good Catch.

**Comment by jamessspanggg** [comment]
Hi, I just fixed this UI bug, will make a PR soon.
