### ISSUE TITLE
Tweak chart title format

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#661]
current: `org_repo_branch`
![image](https://user-images.githubusercontent.com/1673303/57850158-d5e66700-780f-11e9-8c3b-84bf959afc12.png)

suggested: `org/repo[branch]`

reason: the org/repo/branch names might have underscores themselves.

**Comment by damithc** [comment]
Related #228

**Comment by fzdy1914** [comment]
Feel free to take over the issue and the pr.
