### ISSUE TITLE
Show total contribution of a group

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#663]
It may be useful to show the total contribution of a group.

![image](https://user-images.githubusercontent.com/1673303/57853128-8d32ac00-7817-11e9-91a9-00df0717825e.png)

**Comment by jamessspanggg** [comment]
When you mean total contribution, is it the total commits or the total number of lines added?

**Comment by jamessspanggg** [comment]
I have tried to get the total contribution of the group, and currently it will be shown if the mouse hovers to the group name as follows:
<img width="830" alt="Screen Shot 2019-05-22 at 12 10 09 PM" src="https://user-images.githubusercontent.com/32864116/58146940-d60cb980-7c8a-11e9-8bd6-47bbf0b59063.png">

How would you like to display the total contribution of a group?

**Comment by damithc** [comment]
> When you mean total contribution, is it the total commits or the total number of lines added? or both?

total LoC contribution

**Comment by jamessspanggg** [comment]
> > When you mean total contribution, is it the total commits or the total number of lines added? or both?
> 
> total LoC contribution

Is this alright?
<img width="824" alt="Screen Shot 2019-05-22 at 4 55 56 PM" src="https://user-images.githubusercontent.com/32864116/58161346-aec9e280-7cb2-11e9-8805-1657efe0160d.png">

**Comment by damithc** [comment]
Looks good. Perhaps omit ~~Total contribution of group:~~ to reduce clutter? We can put that info as a tool tip to show up when you hover over the number.

**Comment by jamessspanggg** [comment]
> Looks good. Perhaps omit ~Total contribution of group:~ to reduce clutter? We can put that info as a tool tip to show up when you hover over the number.

ok noted will PR after.
