### ISSUE TITLE
Expand width for `breakdown by file format`

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#664]
The width of `breakdown by file format` is restricted so it will be displayed in two lines even there is enough room for it to display in one line.

Let's expand the width for it.

![image](https://user-images.githubusercontent.com/35621726/57855988-970bdd80-781e-11e9-8e16-4dab4972c2dd.png)

**Comment by damithc** [comment]
In addition, the text size doesn't seem to match the rest of the setting.
