### ISSUE TITLE
Encoding of search field in URL is not complete

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#667]
We have encoded the search field in URL. 

However, when we open such a URL directly, it displays nothing in the search field, which is quite confusing.

Sample: [https://nus-cs3281.github.io/2019-dashboard/#search=jacob&sort=searchPath&sortWithin=name&since=2018-12-01&until=2019-05-14&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false](https://nus-cs3281.github.io/2019-dashboard/#search=jacob&sort=searchPath&sortWithin=name&since=2018-12-01&until=2019-05-14&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false)

We can see that `search=jacob` is encoded in the link. But when we open it, the search field is empty.

![image](https://user-images.githubusercontent.com/35621726/57866567-21117180-7832-11e9-80fb-ec2806e5ffa7.png)

**Comment by jylee-git** [comment]
Looking at this issue now
