### ISSUE TITLE
Open the GitHub page with commit details when a ramp is clicked

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#673]
Current: when a ramp is clicked, RepoSense opens the GitHub page with a list of commits
![image](https://user-images.githubusercontent.com/1673303/57906729-8ce4f000-78ad-11e9-93c4-38d00997d491.png)

Suggested: when a ramp represents only one commit (for example, when the granularity of the view is `Commit`), it makes sense to open the github page showing the details of the page, thus saving one click.

![image](https://user-images.githubusercontent.com/1673303/57906738-98d0b200-78ad-11e9-989f-095294d648a3.png)

**Comment by jylee-git** [comment]
Can this be closed? Since clicking on the ramp directs the user to the commit directly when the granularity is set to `commit`
