### ISSUE TITLE
RepoSense only allows us to filter UNTIL date 20/4/2019

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#677]
This has to be fixed ASAP. It's 17 May 2019 today (as of creation of this issue) but we are only allowed to filter repos up to the date 20/4/2019.

![image](https://user-images.githubusercontent.com/35756209/57910756-9de72e80-78b8-11e9-94ee-64ff45a66740.png)

UPDATE: This issue happens when trying to clone and analyze the RepoSense repo. What happened was that for the RepoSense repo, the file at `_reposense/config.json` was read. Due to this, only the authors listed in that file were read, and that the commits of the other authors' whose name isn't reflected in `_reposense/config.json` were ignored, no matter when the last committed date happens to be.

So in the case of RepoSense repo, since the last commit by the author whose name is in the `config.json` file is included, is @yong24s (on the 20th April), the `until` date is set to 20th April.

**Comment by damithc** [comment]
related to #343
This is because the chart only shows up to the last commit instead of the last date specified. Yes, needs to be fixed.

**Comment by jylee-git** [comment]
This issue happens when trying to clone and analyze the RepoSense repo. What happened was that for the RepoSense repo, the file at _reposense/config.json was read. Due to this, only the authors listed in that file were read, and that the commits of the other authors' whose name isn't reflected in _reposense/config.json were ignored, no matter when the last committed date happens to be.

So in the case of RepoSense repo, since the last commit by the author whose name is in the config.json file is included, is @yong24s (on the 20th April), the until date is set to 20th April.

My bad for the confusion, but we figured that these can be discussed and/or done: -

- (Suggestion): Change the `until` date to be the last date specified by the user, rather than the last committed date as suggested by @damithc ,
- (Possible bug found in code): `getRepoConfigurations(ConfigCliArguments cliArguments)` method in line 84 does not take into account whether the user wants the standalone config files to be ignored (see line 112). Will check through this further and raise a separate issue once we can confirm.
https://github.com/reposense/RepoSense/blob/adb48f4e903be700b33b953457ca5b69df4908e8/src/main/java/reposense/RepoSense.java#L84-L115

**Comment by jamessspanggg** [comment]
@jylee-git this issue has been resolved right?

**Comment by jylee-git** [comment]
Yes this has already been solved

**Comment by jylee-git** [comment]
Closing issue as this has already been dealt with via #690
