### ISSUE TITLE
Use vue.js instead of vue.min.js to allow using Vue developer tool

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#678]
Vue has provided a plugin for chrome and firefox to help debug website using Vue.

Our dashboard cannot use this developer tool because it uses the compressed version for `vue.js`, which is `vue.min.js`.

Let's use vue.js instead of vue.min.js to allow using Vue developer tool. 

Sample tool usage:
![image](https://user-images.githubusercontent.com/35621726/57928421-44e0c000-78e3-11e9-95d7-efe372794953.png)

**Comment by fzdy1914** [comment]
@eugenepeh @ongspxm 
Can I know your opinions on this issue?

**Comment by fzdy1914** [comment]
The tool is available [here](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)

**Comment by eugenepeh** [comment]
That's very useful 👍 however the drawback would be the difference in the size of the scripts.
Is it significantly larger?

**Comment by fzdy1914** [comment]
> Is it significantly larger?

303KB vs 85.4 KB.

So, It is a little bit larger compared with the compressed one.
If it is a file size that cannot be accepted. We may state this possibility in the DG so developers can change to `vue.js` locally to debug.

**Comment by eugenepeh** [comment]
I think its an acceptable trade off, given that it is saved into cache for future sessions.
Can go ahead with it.
