### ISSUE TITLE
No error message for invalid file format 

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#682]
When analysing with an invalid file format specified (say `-f a`), there are no error messages and the following result is shown:
1. When breakdown by file formats checkbox is checked
<img width="819" alt="Screen Shot 2019-05-21 at 11 28 27 AM" src="https://user-images.githubusercontent.com/32864116/58066419-dc803000-7bbb-11e9-95a1-9b77b39e947c.png">

2. When breakdown by file formats checkbox is not checked, the contribution bar takes up entire line even though the total lines contributed is 0.
<img width="835" alt="Screen Shot 2019-05-21 at 11 28 47 AM" src="https://user-images.githubusercontent.com/32864116/58066422-de49f380-7bbb-11e9-97d9-8e65396f8c19.png">

Suggestion: 
1. should have an extra check to display error message for invalid file formats
2. ignore the invalid file formats and only analyze the valid ones

**Comment by eugenepeh** [comment]
This is more of a front end check problem rather than the back end. There is no such thing as invalid file formats as long as it follows the OS naming convention, hence even `a` is considered a valid file format.
