### ISSUE TITLE
Limiting range of commits captured by the program to one month

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#688]
As discussed with @damithc , when parsing in the CLI arguments: -

- If the user did not specify both "since date" and "until date", then commits ranging one month from today's date till now, will be captured by the program.
- If the user specified the "since date" but not the "until date", then commits from "since date" all the way till now will be captured by the program (which is currently the case)
- If user specified the "until date" but not the "since date", then only the commits that were made one month from today's date will be captured by the program.
- If the user specified both the "since date" and the "until date", then commits ranging from "since date" up to "until date" will be captured by the program (as usual).

This is to ensure consistent performance, especially when the user wants to capture large repos.

**Comment by fzdy1914** [comment]
As doing this, we may need to update the reposense's default `repo-config.csv` and `author-config.csv` or `gradle frontendtest` to pass frontend test. We may also need to update the build command of netlify.
