### ISSUE TITLE
CodeView: long authored code segments

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#692]
For authors with a LoC contribution with long authored code segments, it may take quite an effort to scroll through all the authored code segments as they are opened by default.
<img width="795" alt="Screen Shot 2019-05-22 at 3 21 45 PM" src="https://user-images.githubusercontent.com/32864116/58155778-301b7800-7ca7-11e9-9eb3-a3c562a5c939.png">

Suggestion: for authored code segments that are longer (eg: longer than 20 lines), we can have an icon that toggles to open and close these segments.

**Comment by damithc** [comment]
Scrolling a long page is easier than clicking many buttons to expand code segments :-)
