### ISSUE TITLE
Generate collated files

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#7]
It would be useful for the tool to spit out the collated code as one file per person (similar to the collate tool) so that this tool completely replaces collate.

**Comment by damithc** [comment]
Update: there is a partial solution using python https://github.com/reposense/convert-markdown
An integrated solution is preferable, but not a high priority.

**Comment by fzdy1914** [comment]
@damithc Is this issue still relevant?

**Comment by damithc** [comment]
I think we don't need it anymore. Closing.
