### ISSUE TITLE
Code view: Binary files visible 

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#711]
Expected: binary files should be hidden from code view (even though authors have modified/added these files in).

Current: binary files visible in code view and displays the gibberish codes.

![image](https://user-images.githubusercontent.com/35756209/58400428-8c0e4400-808d-11e9-8a6e-a9a9f321b75e.png)

**Comment by damithc** [comment]
Even if `zip` is not specified as one of the file formats?

**Comment by jylee-git** [comment]
Only when I explicitly specify the format `zip` to be captured (`java -jar ... -f zip ...`). This is a follow up from @eugenepeh 's comments reproduced below

> Our binary file check within the code supposed to ensure that the binary files wouldn't appear in the code view. This seems like a bug.
> 
> _Originally posted by @eugenepeh in https://github.com/reposense/RepoSense/issues/531#issuecomment-495536940_

**Comment by jylee-git** [comment]
Should we use the last comment in [here](https://stackoverflow.com/questions/6559127/how-check-if-a-file-is-plain-text) to detect binary files and exclude them from the report?

![image](https://user-images.githubusercontent.com/35756209/58778620-e10a0700-8605-11e9-81c6-6ebfb2b0e21b.png)

**Comment by eugenepeh** [comment]
try not to use shell, we are trying to get rid of shell dependency.

ASCII itself might not be sufficient, there can be unicode etc as well. 
Within the Git itself, there should be functionalities that differentiate binary files, try look into that.
