### ISSUE TITLE
ChartView: inconsistency in position of chart title

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#712]
When `breakdown by file format` is checked, the position of the title is inconsistent as shown in the diagram.

Suggestion: add css property of `clear:left` to the chart title. 

<img width="1166" alt="Screen Shot 2019-05-28 at 10 40 46 AM" src="https://user-images.githubusercontent.com/32864116/58447619-908f3700-8137-11e9-8ec8-a7c052d7ab96.png">

**Comment by fzdy1914** [comment]
There is a similar issue before, you may have a look of it. #646

**Comment by jamessspanggg** [comment]
> There is a similar issue before, you may have a look of it. #646

The issue stated that this was resolved but however I still get this misalignment.

**Comment by fzdy1914** [comment]
I mean if you try to fix this issue, you may reference #646 and see why the previous fix does not work.
