### ISSUE TITLE
ChartView: missing ramp slices for certain commits

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#714]
I observed that there are missing ramp slices in the chart, in this case it would be the commit with date 2018-05-17.

<img width="798" alt="Screen Shot 2019-05-28 at 12 58 30 PM" src="https://user-images.githubusercontent.com/32864116/58452121-ca1c6e00-8148-11e9-9a7c-5835b23792eb.png">
<img width="453" alt="Screen Shot 2019-05-28 at 1 03 30 PM" src="https://user-images.githubusercontent.com/32864116/58452201-21224300-8149-11e9-9f88-d628203cfa71.png">

**Comment by fzdy1914** [comment]
This commit has been ignored.

**Comment by fzdy1914** [comment]
See [here](https://github.com/reposense/RepoSense/blob/master/_reposense/config.json#L4-L9)

**Comment by jamessspanggg** [comment]
Ok noted thanks for informing.
