### ISSUE TITLE
List of file format contribution icons does not match the contribution bar

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#718]
When `breakdown by file format` is checked, the list of file format contribution icons contains extra file formats as compared to the file formats in the contribution bars. This takes up extra space of the report.

<img width="823" alt="Screen Shot 2019-05-30 at 12 08 46 PM" src="https://user-images.githubusercontent.com/32864116/58607921-fdd7cf00-82d3-11e9-97c2-febe843aace2.png">

**Comment by damithc** [comment]
It is intended; to makes it obvious that the student could/should have, but did not, contribute any html code, for example.
