### ISSUE TITLE
Separate direct and indirect methods in javascripts

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#719]
Methods that are use by the html are mixed with the indirect dependent methods. We should separate them for better code quality.

**Comment by Tejas2805** [comment]
@eugenepeh How would you prefer to separate them out ?

**Comment by eugenepeh** [comment]
My bad, should've included more context.
What I meant was to increase the level of abstractions and to extract out all the static calculations etc to separate js files. 

For e.g. [v_summary.js](https://github.com/reposense/RepoSense/blob/master/frontend/src/static/js/v_summary.js)
It has too many static functions lying around such as `dateRounding`, and many of the calculations can be refactor into static methods etc which can be stored in a separate js file.

**Comment by ang-zeyu** [comment]
Would it better to move such functions used only in one component into the methods of the components instead?
For global functions used in multiple places, we could then extract them to utility files.
