### ISSUE TITLE
Unable to activate zoom-in feature for macOS device

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#720]
I have tried using `control-click`, `command-click`, and other combinations but am still unable to activate the zoom-in feature.

**Comment by fzdy1914** [comment]
Correct, `control-click` will be recognized as right click and does not work here. It is a bug to fix.

**Comment by jamessspanggg** [comment]
Yep. How about for macOS devices, we allow `command-click` for the zoom-in feature? We can add that in to the User Guide.

**Comment by yong24s** [comment]
In the early implementation of #573, we did use `shift + click`. It was later changed as it conflicts with the browser `shift + click` behavior. You can try `shift + clicking` on very packed ramps.

> How about for macOS devices, we allow `command-click` for the zoom-in feature whereas for other devices we allow `control-click`. We can add that in to the User Guide.

Sounds good.
