### ISSUE TITLE
Compatibility issue with Microsoft Edge

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#721]
There seems to be compatibility issue when viewing the report using Microsoft Edge.

Before PR #573 , summary view works fine, but the code panel can't load any author's code (and just a blank code panel).
![image](https://user-images.githubusercontent.com/35756209/58682188-2f1ed080-83a2-11e9-9fed-118361f55bd7.png)

After PR #573 , summary view doesn't load any of the commits data.
![image](https://user-images.githubusercontent.com/35756209/58682244-5b3a5180-83a2-11e9-8864-38ac09a653bd.png)

**Comment by damithc** [comment]
I'm facing the same issue.
