### ISSUE TITLE
Unable to modify sinceDate and untilDate for Safari browser

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#723]
When using Safari browser to launch the report, I am unable to modify the two dates as the controls does not appear when I hover my cursor over the dates.
<img width="703" alt="Screen Shot 2019-06-03 at 11 45 24 AM" src="https://user-images.githubusercontent.com/32864116/58774736-89639f80-85f5-11e9-8c94-d542794f6e21.png">

**Comment by jylee-git** [comment]
https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari

This could be the reason for this issue
