### ISSUE TITLE
UG: update Commit Panel section

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#727]
- should update to 4 main parts and include `Commit Panel` as one of the main parts
- should add an image of report with the `Commit Panel` to show different components of `Commit Panel` to the user

<img width="902" alt="Screen Shot 2019-06-04 at 12 09 25 PM" src="https://user-images.githubusercontent.com/32864116/58850639-fe9ca680-86c1-11e9-951a-3b1823c79b3f.png">

**Comment by damithc** [comment]
What's the _Commit Panel_?
More like there are only two parts (_Chart Panel_ and the _Code Panel_) -- each has a toolbar at the top, but no need to consider them as main parts?

**Comment by jamessspanggg** [comment]
> What's the _Commit Panel_?
> More like there are only two parts (_Chart Panel_ and the _Code Panel_) -- each has a toolbar at the top, but no need to consider them as main parts?

_Commit Panel_ is the latest panel added for the zoom-in feature. It replaces the _Code Panel_ when zoom-in feature is activated.
<img width="1669" alt="Screen Shot 2019-06-04 at 12 38 53 PM" src="https://user-images.githubusercontent.com/32864116/58851567-db73f600-86c5-11e9-829d-cd29a4cc3e67.png">

**Comment by damithc** [comment]
> _Commit Panel_ is the latest panel added for the zoom-in feature. It replaces the _Code Panel_ when zoom-in feature is activated.

Got it. Let's not consider it a main component (from the user POV) as it only appears under certain rare situations.

**Comment by jamessspanggg** [comment]
> > _Commit Panel_ is the latest panel added for the zoom-in feature. It replaces the _Code Panel_ when zoom-in feature is activated.
> 
> Got it. Let's not consider it a main component (from the user POV) as it only appears under certain rare situations.

Ok noted. In that case, because currently the User Guide starts off by introducing the components as follows:

<img width="837" alt="Screen Shot 2019-06-04 at 2 04 37 PM" src="https://user-images.githubusercontent.com/32864116/58855768-70c9b700-86d3-11e9-8c26-755db5fb14b6.png">

Should we also mention the sub-component _Commit Panel_ in the introduction as it is explained together with the main components? Also, should we attach a screenshot of the _Commit Panel_ below the explanation to show users on how it looks like?
<img width="884" alt="Screen Shot 2019-06-04 at 2 01 56 PM" src="https://user-images.githubusercontent.com/32864116/58855842-a7073680-86d3-11e9-8420-164b9d2036b5.png">

**Comment by damithc** [comment]
> Should we also mention the sub-component _Commit Panel_ in the introduction as it is explained together with the main components?

Instead, we can remove the `Tool Bar` from the initial introduction as it is a sub-component.

> Also, should we attach a screenshot of the _Commit Panel_ below the explanation to show users on how it looks like?

Yes, there should be a screenshot.
