### ISSUE TITLE
Report: rename `sort ...` controls to `arrange ...`

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#731]
I think `arrange` would be a more adequate word than `sort` for the frontend controls, what do you think @damithc ?

**Comment by damithc** [comment]
`sort` is more universally known/understood?

**Comment by eugenepeh** [comment]
> sort is more universally known/understood?

Agree. The reason I mention this is because one of my non English native friend brought this up in a conversation. 

Apparently from the definition given in the Google result, 
![image](https://user-images.githubusercontent.com/19277206/59038169-25ff9900-88a5-11e9-8c70-b69220da32a8.png)
![image](https://user-images.githubusercontent.com/19277206/59038183-30219780-88a5-11e9-8060-29a98fdfbf51.png)

it has word it such that `Arrange` appears to be more adequate than `Sort` for ordering of things, even though Microsoft has been using `Sort` in their file system and Mac uses them interchangeably.

Hence, I brought up this discussion to debate on whether if it would lead to better response from the foreign users if we follow the Google's dictionary definition.

**Comment by damithc** [comment]
It looks like for some reason the world (at least the Computing world) chose the wrong word :-p
But I think we have to stick with the common usage.
