### ISSUE TITLE
Unexpected date reset for months with less than 31 days

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#734]
To replicate: modify date for months with less than 31 days (February, April, June, September and November) to dates that are non-existent (eg: Feb 31st, April 31st etc.).

![weird-date-bug](https://user-images.githubusercontent.com/32864116/59161948-a6c7ca80-8b1b-11e9-9595-bc0314f1c132.gif)

**Comment by eugenepeh** [comment]
interesting but i think this is the implementation of browser calendar elements, hence we have little control over that

**Comment by HCY123902** [comment]
The current behavior is that when the date is changed to a non existing date, it will be automatically set to the earliest since date or lastest until date. This seems to be the default behavior of the browser calender, which looks acceptable to me from a user perspective
