### ISSUE TITLE
Issues when Display name contains commas in author-config.csv

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#738]
Commas in name causes issue in Displaying the name in report.

In excel, when user keys in names with commas (e.g.: `Tang Tjun Chii, Zachary`): -
![image](https://user-images.githubusercontent.com/35756209/59180901-a6214980-8b98-11e9-9670-b58bf091626b.png)

When viewed as a raw file, `"` gets added in automatically when user did not do so: -
![image](https://user-images.githubusercontent.com/35756209/59180955-c3561800-8b98-11e9-83d8-9d848c0fefc4.png)

When running RepoSense using the above `author-config.csv` and displaying it in the report: -
![image](https://user-images.githubusercontent.com/35756209/59181177-4f683f80-8b99-11e9-91e4-2dcb931ccf83.png)

Found this issue when dealing with #185

**Comment by yong24s** [comment]
Need to change the way of we tokenize.

Right now, we are naively splitting by `,`.
https://github.com/reposense/RepoSense/blob/f96222a79167a55bb30fc9ced940b8660ef72425/src/main/java/reposense/parser/CsvParser.java#L61

**Comment by yong24s** [comment]
Also, using double quotes is fine. It is needed if you want to use `,`.

**Comment by jylee-git** [comment]
> Perhaps, we can use Regex?
> https://regex101.com/r/0MHeYe/1

Yes I think we can try to use regex.

> Need to change the way of we tokenize.
> 
> Right now, we are naively splitting by `,`.
> https://github.com/reposense/RepoSense/blob/f96222a79167a55bb30fc9ced940b8660ef72425/src/main/java/reposense/parser/CsvParser.java#L61
>

Think we may need to cater to different types of delimiters as well, or force the user to download [this example in UG](https://github.com/reposense/RepoSense/blob/release/docs/author-config.csv) and modify the values in there. Most users may do this, but there may be some who might create a new `author-config.csv` from scratch and fill the values in. This results in a different delimiter (for my case it's a `\t` ) instead of a comma.

**Comment by yong24s** [comment]
> Think we may need to cater to different types of delimiters as well

Not sure, since CSV is commonly delimiter by commas.
Let's work changing `String#split` to use regex.
