### ISSUE TITLE
CodeView tab closes when viewing author's code

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#741]
As pointed out by @fzdy1914, there is a bug where clicking on the code icon closes the CodeView tab.

To replicate:
1. Set granularity as `week`
2. Reload the page
3. Click to view author's code

![week-granularity-codeview-error](https://user-images.githubusercontent.com/32864116/59275004-0ba33200-8c8e-11e9-9dd9-601122a1c328.gif)

**Comment by eugenepeh** [comment]
Yes, the expected behavior should be that url with parameters should not load the default tab view
