### ISSUE TITLE
Make tool bar responsive

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#745]
The `search` field is not visible under certain screen widths:
![image](https://user-images.githubusercontent.com/1673303/59409228-5b960c00-8de8-11e9-8d39-e24e9276e303.png)

**Comment by jamessspanggg** [comment]
Would you prefer moving the items to the next line when the screen width cannot accommodate the items?

**Comment by damithc** [comment]
I guess that's the easiest way to make it _responsive_
Usually, that kind of simple responsiveness comes free with UI frameworks such as Bootstrap, Vue, etc. as long as we use the framework correctly.
