### ISSUE TITLE
CodeView: loading screen only shows when first time selecting to view code

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#746]
The loading screen only appears the first time selecting to view the code. 
After that, when users selects another code, they may not know that the code is loading as the loading screen does not appear.

![loading-screen](https://user-images.githubusercontent.com/32864116/59408797-6308e580-8de7-11e9-96bd-6f41aed64230.gif)

**Comment by fzdy1914** [comment]
Wait for #967 to be merged.

**Comment by damithc** [comment]
Seems to be fixed now.
