### ISSUE TITLE
Report: add commit message body in zoom tab

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#750]
The commit title alone may be too abstract to understand the rationale of large implementation.
Also, including commit body helps organizations like us who emphasize on such messages.
It may be good for us to include them in the zoom tab view as well, given that the processing cost is low

![image](https://user-images.githubusercontent.com/19277206/59555304-cdd24080-8fe2-11e9-9619-dcb63d9369f3.png)

**Comment by jylee-git** [comment]
This is the result (assuming that #751 is approved and merged):

![image](https://user-images.githubusercontent.com/35756209/59750304-2fc7ca00-92b1-11e9-9f0e-4d2882ebbc8a.png)

Any feedback to improve the displaying of commit message title and body?

**Comment by eugenepeh** [comment]
looks good to me, can consider adding a expand / collapse button next to the title so that it doesn't flood the list for people who are not concern with messages.

**Comment by jylee-git** [comment]
> looks good to me, can consider adding a expand / collapse button next to the title so that it doesn't flood the list for people who are not concern with messages.

Noted. Added one here:
![image](https://user-images.githubusercontent.com/35756209/59833285-56046d00-9378-11e9-9f1a-318ae6ca8b4e.png)

**Comment by eugenepeh** [comment]
Perhaps add the button here, corresponding to each commit, so that the reviewer can choose to read only those that perks their interest

![image](https://user-images.githubusercontent.com/19277206/59935582-aff05a00-9480-11e9-8b44-a385792262dd.png)

**Comment by damithc** [comment]
> Perhaps add the button here, corresponding to each commit, so that the reviewer can choose to read only those that perks their interest

Yes, that can be useful. Can be done as a separate issue sometime in the future? It's prudent to dogfood the basic version of a feature for a while before adding bells and whistles.

**Comment by eugenepeh** [comment]
>Yes, that can be useful. Can be done as a separate issue sometime in the future? It's prudent to dogfood the basic version of a feature for a while before adding bells and whistles.

I am fine with that too if it cost too much additional work.

@jylee-git you can work on it in a later issue if you'd like or you can try reusing the code from the toggle untouched code too.
