### ISSUE TITLE
URL should not capture end date unless it is specifically set

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#754]
Scenario: I set up a report by specifying a start date but no end date. Furthermore, I set up Travis to auto-generate the report periodically. Then, I share the URL of the report with others.

Problem: The URL captures the end date of that specific report. when others visit that URL in future, they only see ramps up to the original end date although the report has been updated to include more recent commits.

Suggestion: If the end date of the analysis period is unspecified, the URL should not capture a specific end date either.

**Comment by jamessspanggg** [comment]
When users reload the page, users might want to see the same page with same end date as modified before reloading. If the URL does not capture end date, reloading the page will always show the updated end date rather than the modified end date before reloading.

**Comment by damithc** [comment]
Yes, when the date is modified specifically, it should be captured in the URL. Currently, the default date is captured into the URL as if it was specifically specified by the user. In other words, the current mechanism cannot capture the 'end date unspecified' condition. When the end date is unspecified, the current mechanism calculates an end date on its own and treat it as if the user specified it. At that point we lose the knowledge that the end date was not specified by the user to begin with.
