### ISSUE TITLE
UG: Provide a more appropriate example of cli command

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#756]
In the User Guide, there is an example of a cli command:
<img width="930" alt="Screen Shot 2019-06-19 at 10 00 09 PM" src="https://user-images.githubusercontent.com/32864116/59772328-26a12200-92de-11e9-818e-27c329730086.png">

That command will lead to this page where there are no commits in between the since date
and until date:
<img width="613" alt="Screen Shot 2019-06-19 at 10 05 56 PM" src="https://user-images.githubusercontent.com/32864116/59772574-9c0cf280-92de-11e9-9be9-1f14c7697e79.png">

Suggestion: Let's update the since date and until date of that cli command example that can capture commits to provide a more realistic command.

**Comment by damithc** [comment]
While we are at it, may be not use RepoSense as the target repo? It could be confusing to the reader to see RepoSense appear multiple times in the command. We can use se-edu/addressbook-level4 instead.
