### ISSUE TITLE
Increase performance by not cloning a repo twice

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#759]
(Problem applies to users of Windows OS)
### Current
Currently, RepoSense does a `git clone --bare` of each individual repos and check if any of the files/folders contain illegal characters in the repo. Then when no illegal characters are detected, RepoSense performs a proper clone of the repository (again).

This incurs heavy performance penalty, especially if the remo repo is huge in size (e.g.: TEAMMATES) as repos will be cloned twice (note `clone bare` and `clone` clones the repo with the same total size).

### Suggested
Do a clone bare of the repo, check for illegal file names in windows. Once done, do a clone **from the local directory where the bare repo is located** to a new location. Doing so will just copy the files over, and do a chekout to the master branch. See [this](https://stackoverflow.com/questions/6403982/accessing-source-files-from-git-baremaster).
![image](https://user-images.githubusercontent.com/35756209/59909216-bca18d80-9441-11e9-9a96-4c13a05da7b3.png)

**Comment by damithc** [comment]
Sounds promising. Any estimate of how much extra work (i.e., coding) it would take?

**Comment by jylee-git** [comment]
Roughly up to two days to code if only dealing with this issue alone. 

But I would prefer this to be solved together with #761 as I believe the change in code will coincide with #761 as well.

**Comment by damithc** [comment]
Alright, go ahead.
