### ISSUE TITLE
Duplicated repository analysed instead of skipped

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#760]
When customising the analysis using Command Line Parameters, if the input has duplicates such as:
`-r https://github.com/reposense/RepoSense.git https://github.com/reposense/Re...`

The duplicates are not detected and are analysed.
<img width="829" alt="Screen Shot 2019-06-21 at 4 59 33 PM" src="https://user-images.githubusercontent.com/32864116/59911341-418ea600-9446-11e9-8dee-0062bf1a7d09.png">

**Comment by damithc** [comment]
Good catch. May be leave as it is if there is no other cost other than the duplicated work, as the duplicates are the users fault?

**Comment by Tejas2805** [comment]
@damithc In reference to your previous comment, so do we do not work on this issue?

**Comment by damithc** [comment]
Yes, let's leave it be.
