### ISSUE TITLE
Unable to use `--since *` when running jar file

### ISSUE THREAD

**Issue by bluein-green** [reposense/RepoSense#781]
I ran `./gradlew clean build` to build the jar file after #690. Trying to run the jar file from command line resulted in an error:

![image](https://user-images.githubusercontent.com/35626067/60416544-adc09500-9c10-11e9-9932-49e8b17e6ca5.png)

Editing the program arguments in intellij configuration to use the same arguments (`-r https://github.com/reposense/reposense.git --since *`) and running from intellij does result in reposense running successfully though.

**Comment by jylee-git** [comment]
https://stackoverflow.com/questions/2755795/how-do-i-pass-in-the-asterisk-character-in-bash-as-arguments-to-my-c-program

Apparently `*` is a reserved character in shells. My bad on this. We need to use another character when parsing `since date`, such as `^`.
