### ISSUE TITLE
File type icons shown for repos with no contribution in recent month

### ISSUE THREAD

**Issue by bluein-green** [reposense/RepoSense#786]
In our [netlify preview](reposense.netlify.com), when `breakdown by file types` is selected, repos with no commits and 0 total contribution have file types listed.

![netlify_nocommits_breakdownicon2](https://user-images.githubusercontent.com/35626067/60560887-357ae080-9d84-11e9-9063-d5722f6c7e07.png)

**Comment by jamessspanggg** [comment]
Related to #770

**Comment by jamessspanggg** [comment]
Fixed in PR #770, closing this issue now.
