### ISSUE TITLE
Make zoom tab reactive towards all sort flags

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#793]
When our control flags change, the zoom tab does not change, which is misleading. 

There is one ongoing PR(#775) which closes the zoom tab when the flags changes, which can be a temp solution to the problem.

Should we make the zoom tab reactive towards all the changes of control flags? Just like what we have done in #729.

**Comment by jamessspanggg** [comment]
Just discussed with Prof @damithc, he thinks that when changing the controls in the toolbar, we should just remove the zoom-in region overlays while the zoom tab will stay the same.

**Comment by jamessspanggg** [comment]
In my PR #729, I have made the zoom tab reactive towards the `granularity` changes, should I remove this functionality?

**Comment by damithc** [comment]
> In my PR #729, I have made the zoom tab reactive towards the `granularity` changes, should I remove this functionality?

Yes, I think so. It's cleaner that way. Making it reactive _fully_ may not be worth the effort, and hence, best not to make it reactive at all. Zoom is a complicated (to implement) feature. We should not mix it up with other features if it can be helped.

**Comment by fzdy1914** [comment]
OK
