### ISSUE TITLE
Projectify frontend part

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#795]
The way we use to develop frontend now is more like an attached component. They are less organized and formal. 

As the frontend part growing bigger, such organizations will make it harder to develop. Newcomers will also need more time to familiarize them with the code base.

Suggestion: Projectify frontend part to a formal project like `vue-cli 3` or some else.

Warning: This going to be a huge change to our frontend, which will potentially stall the front end development for some time.

Potential drawbacks: 
1. The framework itself may be too heavy for us.
2. It needs some time to test and integrate.

Potential benefits:
1. A hot re-load frontend development.
2. It may be easier to write tests.
3. The organization will be better.

**Comment by fzdy1914** [comment]
@damithc @ongspxm @yamidark @yong24s 
Your inputs are needed.

**Comment by damithc** [comment]
I have no objections. At least we can discuss and come up with a rough solution. A timeline depends on the availability of devs willing to take on the task.

**Comment by eugenepeh** [comment]
>Suggestion: Projectify frontend part to a formal project like vue-cli 3 or some else.

Does that mean your proposition is to separate to front end off and form its own repository?

**Comment by fzdy1914** [comment]
> Does that mean that your proposition is to separate to front end off and form its own repository?

I mean to have a project named frontend nested within our repo directory. It is not necessary to form a separate repo as we have PRs which will modify them together.

What I mean for projectify, is more like re-construct our codes. For now, the structure is less organized. The CSS and js do not stay together with the templates, making it harder to locate and change the code. 

To projectify, we abstract each component to one `.vue` file, which only contains the `.pug`, `.js`, `CSS` code related to this component. For example, if we want to change the style of a component, instead of doing a `control - f` in our around 1k CSS file, we can locate them easier in the `.vue` of this component. 

Meanwhile, we may also need to extract more component from our code(v_segment is a good example).

**Comment by Tejas2805** [comment]
Labelling as epic as quite a few issues need to be solved to solve this issue.

**Comment by gerhean** [comment]
Done in #1412
