### ISSUE TITLE
Show a numeric breakdown of individual file types contributed

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#804]
![image](https://user-images.githubusercontent.com/35756209/60955679-ef012500-a333-11e9-89db-9604fe077335.png)

Current: It is difficult to tell whether an author has contributed into a certain file format if he/she wrote majority of code in `format A` but only a little fraction of code in `format B`.

Suggested: complement this feature by showing a **numeric** breakdown of **each** file formats that the author contributed.

![image](https://user-images.githubusercontent.com/35756209/60956356-3c31c680-a335-11e9-935d-a65b9c67ae15.png)

**Comment by damithc** [comment]
A breakdown is available on the code view though:
![image](https://user-images.githubusercontent.com/1673303/60976256-ec1c2980-a35f-11e9-9ace-b0623f259c38.png)

**Comment by jylee-git** [comment]
Oh yeah forgot about this 😅
