### ISSUE TITLE
Show ramp chart for this period button in code view only works once

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#846]
* select a sub range to display in code view
* press the `Show ramp chart for this period` 
* modify the date range in summary view
* press `Show ramp chart for this period` again -> doesn't work

Here's the url I have when encountering this error
https://deploy-preview-844--reposense.netlify.com/#tabOpen=true&search=&sort=groupTitle&sortWithin=title&since=2017-10-09&until=2019-07-30&timeframe=commit&groupSelect=groupByRepos&breakdown=false&tabType=zoom

**Comment by jamessspanggg** [comment]
It is due to the dotted lines being cleared by `deactivateAllOverlays()` after pressing the `show ramp chart for this period`.
