### ISSUE TITLE
Deprecated npm package.

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#849]
Some of the dependencies in our project are deprecated:
![image](https://user-images.githubusercontent.com/35621726/62262438-4124fa00-b44b-11e9-8da9-0dfa550f148e.png)
We can do a whole check of the dependencies we have.

**Comment by gerhean** [comment]
Don't think this issue is relevant, seeing deprecated packages is annoying so people naturally will make PR to remove them.

Also the deps shown here are no longer in the project.

**Comment by damithc** [comment]
> Also the deps shown here are no longer in the project.

This is enough justification to close this issue.
