### ISSUE TITLE
Fail to analyse repos which contain submodule

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#850]
[Git submodule](https://git-scm.com/docs/git-submodule) is a tool which will be commonly used in large projects. 

When trying to analyze a repo which contains submodules, the following error occurs.

![image](https://user-images.githubusercontent.com/35621726/62263118-a679ea80-b44d-11e9-8f49-9ef94b691f9e.png)

**Comment by damithc** [comment]
In such cases, should we exclude code from sub-modules, as they separate repos altogether?

**Comment by fzdy1914** [comment]
> In such cases, should we exclude code from sub-modules, as they separate repos altogether?

I believe we should just ignore the module instead of producing an error.
