### ISSUE TITLE
Zoom tab url directing to wrong repository when merged group

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#851]
![image](https://user-images.githubusercontent.com/19277206/62304631-f0e08300-b4b0-11e9-85ba-05539fe35ae3.png)

![image](https://user-images.githubusercontent.com/19277206/62304659-02298f80-b4b1-11e9-8539-38d0f8932550.png)

**Comment by jamessspanggg** [comment]
I'm sorry but I can't understand the bug here. Do u mean the link for the ramp slices?

**Comment by jamessspanggg** [comment]
Oh I get it know, the ramp slice url of a merged group always points to the same repository even though there are more than 1 repositories within a merged group.

<img width="1335" alt="Screen Shot 2019-08-01 at 11 59 21 PM" src="https://user-images.githubusercontent.com/32864116/62308974-15d8f400-b4b9-11e9-8bf7-d4baf4e60e6e.png">

**Comment by jamessspanggg** [comment]
I am wondering if we should just disable the url if it is `group by authors` and merge group option is checked.

**Comment by damithc** [comment]
> I am wondering if we should just disable the url if it is `group by authors` and merge group option is checked.

Yes, disable if not applicable.

**Comment by eugenepeh** [comment]
hmm, why don't we bind the repository information to the commit? It would just be an additional pointer reference after all.
