### ISSUE TITLE
Zoom tab displays commits not within filter time

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#852]
Current: 
Instead of zooming in terms of the position of the dotted lines, the current zoom feature gets the nearest since and until dates from the dotted lines, and zooms into commits that are within the duration.

Issue: 
Ramps that are not included in the dotted lines are also included in the zoom tab.

<img width="1657" alt="Screen Shot 2019-08-01 at 11 48 03 PM" src="https://user-images.githubusercontent.com/32864116/62308056-56377280-b4b7-11e9-99b9-c59aab8128a0.png">

**Comment by damithc** [comment]
Ideally, the duration should match the position of the dotted lines. if that is hard to do, we can make it match the nearest ramp _inside_ the box.

BTW, the triangles are supposed to be called _ramps_, not _ramp slices_.

**Comment by fzdy1914** [comment]
I found another bug similar to this is that: if you send two same data range for zoom, the commits displayed in second time are not correct.

**Comment by fzdy1914** [comment]
Meanwhile, I don't think your investigation for the bug is correct as the commit displayed is out of range.

![image](https://user-images.githubusercontent.com/35621726/70912685-71aeae80-204f-11ea-9aca-c832b56cd18b.png)

**Comment by fzdy1914** [comment]
Supporting gif
![a](https://user-images.githubusercontent.com/35621726/70916177-32379080-2056-11ea-871a-97efd2ef0c72.gif)
