### ISSUE TITLE
Improve logging message when repo (branch) isn't found in repo-config.csv

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#859]
Given this config setup (note that `testrepo-Beta (master)` doesn't exist in repo-config.csv but is included in author-config.csv)
![image](https://user-images.githubusercontent.com/35756209/63067624-6aad4d80-bf42-11e9-9858-54cb0047ff81.png)

The log message `[WARNING] Repository https://github.com/reposense/testrepo-Beta.git is not found in repo-config.csv.` doesn't include which branch of testrepo-Beta isn't found in the repo-config.csv
![image](https://user-images.githubusercontent.com/35756209/63067689-b829ba80-bf42-11e9-9471-796551c4fae3.png)

**Comment by 0blivious** [comment]
Hi @jylee-git can I work on this?

**Comment by jylee-git** [comment]
Sure! Go ahead. Just assign yourself as the assignee so ppl know that this is taken and there won't be any clashes

**Comment by 0blivious** [comment]
Thanks, will start working on it. I don't think I have the access to assign people though. @jylee-git  Can help me assign pls?

**Comment by jamessspanggg** [comment]
@0blivious done.
