### ISSUE TITLE
Generalize findMatching method in GroupConfigCsvParser and AuthorConfigCsvParser

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#864]
As discussed in https://github.com/reposense/RepoSense/pull/787#discussion_r309248962, in `GroupConfigCsvParser#findMatchingGroupConfig` and `AuthorConfigCsvParser#findMatchingAuthorConfig` are quite similar and can be generalized.

**Comment by dcshzj** [comment]
I think this can be closed. Reducing code duplication is important, but the number of lines are small and is not a priority now.

**Comment by damithc** [comment]
> I think this can be closed. Reducing code duplication is important, but the number of lines are small and is not a priority now.

@dcshzj thanks for looking into this. Can post the two code segments here?

**Comment by dcshzj** [comment]
This is for GroupConfigCsvParser:
https://github.com/reposense/RepoSense/blob/9609c591f7e3a4c8d3a1f8acf2f71f7aec15b043/src/main/java/reposense/parser/GroupConfigCsvParser.java#L73-L92

This is for AuthorConfigCsvParser:
https://github.com/reposense/RepoSense/blob/9609c591f7e3a4c8d3a1f8acf2f71f7aec15b043/src/main/java/reposense/parser/AuthorConfigCsvParser.java#L96-L116

The main difference is in line 108 of AuthorConfigCsvParser, as there is an additional check of the branch.

**Comment by damithc** [comment]
Yup. I think the gain is too small in this case. Closing.
