### ISSUE TITLE
AuthorConfig: further improve the branch field

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#865]
In the author config, branch is an optional field that will automatically uses the default branch in the repo field.

However, this can be improved such that if the branch field is not filled, we can bind that AuthorConfig to all the RepoConfig that has the same repo's location irregardless of branch.

**Comment by 0blivious** [comment]
Hi can I work on this? Doing for my CP3108 project.

**Comment by eugenepeh** [comment]
>Hi can I work on this? Doing for my CP3108 project.

Sure, go ahead

**Comment by 0blivious** [comment]
I have a problem regarding the design of repo-config.csv and author-config.csv.

Currently, the UG states that, for author-config.csv, if the Branch column is left empty, the default value will be the the default branch of the repo.

However, when I try use csv file as below, the author nbriannl is not recognized though the default branch of the repo is actually master, and is included in repo-config.csv. There is a warning message `[WARNING] Repository https://github.com/reposense/testrepo-Beta.git is not found in repo-config.csv`
<p float="left">
<img src="https://user-images.githubusercontent.com/39231750/63752403-c3d29500-c8e3-11e9-80c6-c368d5b10099.png" width="200" height="200">
<img src="https://user-images.githubusercontent.com/39231750/63752407-c634ef00-c8e3-11e9-886e-86c64ff8ce0f.png" width="200" height="200">
<img src="https://user-images.githubusercontent.com/39231750/63752987-cb466e00-c8e4-11e9-96dc-39cf4eb00e4f.png" width="200" height="200">
</p>

When I changed the repo-config.csv as below, the author April0616 and CindyTsai1 are ignored.
<p float="left">
<img src="https://user-images.githubusercontent.com/39231750/63753753-46f4ea80-c8e6-11e9-933f-bad0ecc8ca9d.png" width="300" height="200">
<img src="https://user-images.githubusercontent.com/39231750/63753832-6db32100-c8e6-11e9-96f1-a3cc35fbe598.png" width="300" height="200">
</p>

I am not very sure if this is a bug or it is designed to be like that? 


.

**Comment by 0blivious** [comment]
Also UG it is stated that `If author-config.csv is not given and the repo has not provide author details in a standalone config file, all the authors of the repositories within the date range specified (if any) will be analyzed`.

So now if we have a author using default branch, it will be treated as no author details given. Just as the image above, all author for the branch `add-config-json` will be analysed.

If we want to bind AuthorConfig to all the RepoConfig that has the same repo's location irregardless of branch when the branch field is not filled, do we consider this as author detail provided? For eg if we have author-config and repo-config as images above, do we still analyse all author for branch `add-config-json`, or we should only analyse `nbriannl` for the branch `add-config-json`.

**Comment by eugenepeh** [comment]
For our configuration, newer lines are supposed to overwrite the former lines.

For some authors that weren't recognized is likely due to the remote/standalone config on the beta repo.
