### ISSUE TITLE
Footer: link to main site

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#868]
Current: footer links to specific release
![image](https://user-images.githubusercontent.com/1673303/63479799-2a117f00-c4c2-11e9-91de-9ec7c079c1fa.png)

Suggested: keep the version number but link to the main site, as this is simply a way to market the product.

**Comment by fzdy1914** [comment]
Is it better to have `RepoSense` link to main site but have `version number` link to the specified site?

**Comment by damithc** [comment]
> Is it better to have `RepoSense` link to main site but have `version number` link to the specified site?

That works too.

**Comment by Tejas2805** [comment]
@fzdy1914 Hi I wanted to work on this issue for my  CP3106 Project. But I was confused as to what did you mean by the main site?
