### ISSUE TITLE
repo-config.csv: give a way to omit authors

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#869]
Current: repo-config.csv allows omitting specific commits
Suggested: also allow omitting specific authors

Reason: In [this use case](https://nus-cs2103-ay1920s1.github.io/ip-dashboard), a member from the duke dev team appears in every fork. It's nice if we can omit him everywhere

**Comment by yong24s** [comment]
Additionally, we should also provide this option in `_reposense/config.json`.
