### ISSUE TITLE
Capture code view in URL

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#870]
For example, [this URL](https://nus-cs2103-ay1920s1.github.io/ip-dashboard/#tabOpen=true&search=alxkohh&sort=groupTitle&sortWithin=title&since=2019-08-16&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabType=authorship&tabAuthor=alxkohh&tabRepo=alxkohh%2Fduke%5Bmaster%5D) was copied when the code view was open but when the URL is used in a fresh Browser, it does not open the code view at the start.

**Comment by jamessspanggg** [comment]
Same issue as #858

**Comment by damithc** [comment]
I see. closing in favor or the earlier issue.
