### ISSUE TITLE
Improve on "Merge group" features

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#873]
We can improve on merge group features.

These can be considered and/or applied: -

* [Doable] Enable `view commits` option for both grouping by `Repo/branch` and `Author`. This is doable since we can already zoom in to the ramp slices of merged author/repo (zoom tab). **[done]**
* [To be discussed; not trivial] Enable code view for merged repo. However, my guess is that this is not trivial and not sure if we should implement this option.
* [To be discussed] Enable `octocat` icon to link merged repo to the respective github repository **[done]**

**Comment by Tejas2805** [comment]
Based on what we discussed with Prof in class, removing the label `s.ToDiscuss` and making it a issue to be worked on

**Comment by damithc** [comment]
I think we've done as much as reasonable for this issue. Closing.
