### ISSUE TITLE
Fix contradiction in User Guide

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#88]
In [UserGuide#CsvConfigFile](https://github.com/reposense/RepoSense/blob/master/docs/user_guide.md#csv-config-file) (first paragraph, second line), `white list of authors(if the author is listed in the CSV, his/her contribution will be ignored by the analyzer`.

If its white listed, it should be taken into analyzer rather than ignored.

Let's fix this error in the user guide.

**Comment by yamidark** [comment]
@eugenepeh Resolved in #146
