### ISSUE TITLE
Appveyor CI is failing 

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#886]
![image](https://user-images.githubusercontent.com/19277206/64469095-20914380-d15f-11e9-94b5-769244291dc1.png)

**Comment by fzdy1914** [comment]
Add on:
The travis CI for my personal repo is also failing.
![image](https://user-images.githubusercontent.com/35621726/64471719-8d203880-d187-11e9-939e-06434b42af29.png)
