### ISSUE TITLE
User Guide: Minor inconsistency

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#891]
Hi all,
I wish to raise a (minor) inconsistency in the User Guide.
This is not an urgent issue.

Within the introduction to the **Interpreting the Report** section, a sentence states that the report "consists of three main parts: the Chart Panel, the Code Panel, and the Tool Bar, each of which is explained in the sections below".

However, there seem to be 4 main components in the report - Chart Panel, Code Panel, **Commits Panel** and Tool Bar.

The **Commits Panel** is not mentioned in the introductory sentence - perhaps this sentence should be updated? I can update it, if this is indeed an issue.

I've placed some relevant screenshots below:

![image](https://user-images.githubusercontent.com/35621759/64832391-61300780-d60c-11e9-9b72-f563c397c9cd.png)

![image](https://user-images.githubusercontent.com/35621759/64832491-c2f07180-d60c-11e9-8770-dfbc50f2db33.png)

**Comment by Tejas2805** [comment]
This issue is closed as it was solved by PR #902.
