### ISSUE TITLE
Ramp chart: allow filtering by file type/group

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#892]
Current: code view can be filtered by file type/group but ramp chart cannot be filtered like that

![image](https://user-images.githubusercontent.com/1673303/64917475-33d98a00-d7c3-11e9-97bc-285822158918.png)

Suggested: allow filtering the ramp chart by file type/group

Rationale: for example, to find who wrote most java code, one can filter out other file types and sort by contribution

**Comment by fzdy1914** [comment]
Or we can change the color beside the file type into a radio button with the corresponding color?

I believe the color is  repeated in all group because it is inconvenient to check each time on top to determine the file type for the color .
