### ISSUE TITLE
Improper width computed for contribution bar when breakdown by file type

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#893]
When breakdown by file type, the width of one of the contribution bar is computed incorrectly.

![image](https://user-images.githubusercontent.com/35621726/64932155-aef87a00-d86f-11e9-9466-04036791d3d4.png)
An example is the blue `.md` contribution bar. 

Reproduce: https://nus-cs2103-ay1920s1.github.io/ip-dashboard/#sort=totalCommits%20dsc&groupSelect=groupByAuthors&search=whneo97&sortWithin=title&since=2019-08-16&timeframe=commit&mergegroup=false&breakdown=true&tabOpen=true&tabType=authorship&tabAuthor=whneo97&tabRepo=whneo97%2Fduke%5Bmaster%5D

**Comment by damithc** [comment]
Another problem from [here](https://nus-cs2103-ay1920s1.github.io/tp-dashboard). @myteo is it the same problem?
![image](https://user-images.githubusercontent.com/1673303/65385408-de702080-dd60-11e9-998b-7472ebd273b0.png)

**Comment by myteo** [comment]
@damithc Yup it should be the same problem.

**Comment by damithc** [comment]
> @damithc Yup it should be the same problem.

Thanks. Seems to be fixed now.
