### ISSUE TITLE
Update link on main page to latest release

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#894]
Current: The link takes us to Version 1.9rc of RepoSense. 

![Screen Shot 2019-09-17 at 1 38 44 AM](https://user-images.githubusercontent.com/35946746/64980186-e86ecb00-d8eb-11e9-9ffe-ecaccf06659c.png)

Suggested: Since Version 1.10 has been officially released, the link should take us there.

Rationale: Users might try to find v1.10 features on this link and they will not be able to find it or use it.

**Comment by fzdy1914** [comment]
Just make pull request to the `dashboard-demo` repo.
