### ISSUE TITLE
group-config.csv: provide a way to specify groups for all repos

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#900]
Current: groups need to be specified for each repo, one row per repo per group. For example, specifying 3 groups for 330 repos result in nearly 1000 rows.

Suggestion: allow a way to specify groups for all repos at once

For example, we can allow using `*` as the repo location.

**Comment by 0blivious** [comment]
Hi can I claim this?

**Comment by damithc** [comment]
> Hi can I claim this?

Sure. Propose a solution first and see what other devs think of it?

**Comment by 0blivious** [comment]
Just do what we did for authorConfig.csv? If the repo location column is left empty, than we treat it as default location and map that group to all repos.
