### ISSUE TITLE
User Guide: update analyze multiple repos

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#906]
Analyze multiple repos just has an explanation for  `author-config.csv` and `repo-config.csv` files. Let's update it to include `group-config.csv` and include examples too. 

![Screen Shot 2019-09-29 at 10 01 52 PM](https://user-images.githubusercontent.com/35946746/65835679-d9d8d880-e31b-11e9-9347-424378e51252.png)

**Comment by eugenepeh** [comment]
Prior to working on an issue, perhaps check with other devs as well so that more than 1 people acknowledge that it is a legit issue that we should work on.
