### ISSUE TITLE
Ramp chart: Shows zero lines

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#909]
Despite the ramp chart showing one ramp slice, the number of lines is shown to be zero. The Code Panel displays as empty as well. 

![Screen Shot 2019-10-06 at 4 44 10 AM](https://user-images.githubusercontent.com/35946746/66260699-ad79fc00-e7f4-11e9-81ae-662514877b0c.png)

This is shown in the Netlify deploy of PR #908, so not sure whether bug or PR specific.

**Comment by damithc** [comment]
Not sure if this case is a bug but it is possible for the above scenario to happen. For examples, a person's contribution can get deleted/claimed by another person -- that can result in ramps without a contribution.

**Comment by Tejas2805** [comment]
Closing this issue as the above scenario can possibly exist.
