### ISSUE TITLE
Outdated UI in GitHub pages

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#911]
The link to the GitHub pages below shows an outdated UI:
<img width="1056" alt="Screen Shot 2019-10-06 at 11 56 54 PM" src="https://user-images.githubusercontent.com/32864116/66271833-30eb2a00-e895-11e9-80de-ef289afcdbd0.png">

Let's update the GitHub pages to reflect the UI in the latest release.
<img width="1662" alt="Screen Shot 2019-10-06 at 11 56 37 PM" src="https://user-images.githubusercontent.com/32864116/66271835-321c5700-e895-11e9-8a53-2373d258a5df.png">

**Comment by Tejas2805** [comment]
Repeat of #894. Closing #894.

**Comment by jamessspanggg** [comment]
Fixed by [PR](https://github.com/reposense/dashboard-demo/pull/19#event-3108291425). Closing this.
