### ISSUE TITLE
Better exception handling: Uncaught exception while analysing one repository causes whole report generation to fail

### ISSUE THREAD

**Issue by myteo** [reposense/RepoSense#918]
Bug in #917 leads to an uncaught exception. This causes the whole report generation to fail although only one repository has a problem. Users should still be able to generate the report even though some repositories encountered failures during analysis.

**Comment by Tejas2805** [comment]
I think this scenario is specific to the bug in #917 because I have seen reports getting generated, even if some of the repositories failed. Maybe we should explore this further and try to find in which cases is it exactly happening?

**Comment by myteo** [comment]
Yup some exceptions are being caught, but not all of them. The issue here is that the bug in #917, which occured for one repo, should not have caused all the other repos and the whole report to fail as well. I think the solution here will be to have a catch-all at the end of the try-catch block because there might still be undiscovered exceptions after #917 is fixed.

Thanks for clarifying, I updated the title to make it clearer.
