### ISSUE TITLE
Code View: scrolling bug when using Safari browser

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#921]
Using Safari browser, when scrolling certain code horizontally, instead of the entire segment being scrolled together, (`FindCommandParserTest`) only a single line scrolls (`FindCommandParser`). Shown below:

![ui-bug](https://user-images.githubusercontent.com/32864116/66913748-dea1ca00-f047-11e9-9655-e944f369acf5.gif)

Link to reproduce: [url](https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=CS2103T-T11&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=jascxx&tabRepo=AY1920S1-CS2103T-T11-2%2Fmain%5Bmaster%5D)

**Comment by fzdy1914** [comment]
Seems can not be reproduced now, can you find another reproduction?

**Comment by jamessspanggg** [comment]
> Seems can not be reproduced now, can you find another reproduction?

Yes. [Check it here.](https://deploy-preview-969--reposense.netlify.com/#search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=eugenepeh&tabRepo=reposense%2FRepoSense%5Bmaster%5D). Observe the `CommitInfoAnalyzer` file.

![scroll-bug](https://user-images.githubusercontent.com/32864116/70918125-90b23e00-2059-11ea-8c70-c5c45a72c86c.gif)

**Comment by fzdy1914** [comment]
@jamessspanggg Can you try Chrome? seems can not reproduce on chrome.

**Comment by jamessspanggg** [comment]
@fzdy1914 yep it only occurs in Safari, Chrome works fine.

**Comment by jamessspanggg** [comment]
This issue no longer occurs as code panel is no longer scrollable. Closing this.
