### ISSUE TITLE
RepoLocation might neither be local nor match matcher pattern

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#923]
Current: If the RepoLocation doesn't match the matcher pattern, it's considered to be a local repository.

![Screen Shot 2019-10-17 at 2 55 58 PM](https://user-images.githubusercontent.com/35946746/66984959-59bdbb80-f0ee-11e9-86a2-5f02c5f1fd66.png)

Possibility: A repo might not match the matcher pattern but its also not a local repo. 
Example: `bitbucket/gitlabs/gitea`

Suggestion: Better handling of such scenarios.

**Comment by yong24s** [comment]
If we are supporting other git repositories, then we will have to update external links in the report too.

**Comment by anubh-v** [comment]
Conversely, if we do not want to support other git repo hosting services (at this point in time),
perhaps our repo location verification should be stronger and we should throw an error when GitLab or Bitbucket repo urls are used?

**Comment by anubh-v** [comment]
Prof @damithc , may I check what the expected behaviour should be when a git URL of a repo hosted on other services is used (e.g. GitLab) ?

Currently, RepoSense is able to clone, run analysis and generate the report. However, the links in the report do not work (as expected).

**Comment by anubh-v** [comment]
Here is another example of the loophole in our verification:
If we run RepoSense with the command `./gradlew run -Dargs="--repo https://some-random-text.git"`,
RepoSense will try to clone this repository, instead of detecting it as an invalid location.

Output:
![image](https://user-images.githubusercontent.com/35621759/77725086-8677e680-702f-11ea-8051-37e026e2cadc.png)

**Comment by damithc** [comment]
Our state of support for non-github repos at the moment is 'if it works, then it works; if it doesn't work; then it doesn't work'. Nothing is guaranteed as we have not declared support for non-github repos yet. Adding support for other hosting services is something we need not worry about at the moment. When we have solid support for GitHub to the level that other people also start using RepoSense, we can expand into other hosting services.

**Comment by damithc** [comment]
Putting on hold as no plans to support other platforms anytime soon.
