### ISSUE TITLE
RepoSense: Build failing

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#926]
The `build` is failing after merging PR #908.  

![Screen Shot 2019-10-22 at 7 40 32 AM](https://user-images.githubusercontent.com/35946746/67250777-54ba8c80-f49f-11e9-879e-f50fc2f64275.png)

The PR is clean, have tested it again. Saw the report generated by Travis, it's a one-time error. A new commit to the `master` branch directly or merging a PR should fix it.

**Comment by damithc** [comment]
I've restarted the build for the master branch.

**Comment by Tejas2805** [comment]
Issue is solved. So closing it.
