### ISSUE TITLE
Ramp chart: Duplicate ramps

### ISSUE THREAD

**Issue by myteo** [reposense/RepoSense#927]
This only occurs when no `author-config.csv` is provided and one author made commits using two different GitHub Author names. For example, **Alice Tan** and **alice99**. Authors are retrieved manually and they are treated as 2 separate authors.

If a commit was made using the following author configuration:
Author Name: Alice Tan
Author Email: alice99@users.noreply.github.com

This commit will be retrieved 2 times when retrieving commits made by **Alice Tan** and **alice99**. When assigning the commit ownership, **Alice Tan** will get for credit for both the commits, leading to duplicate ramps.

To see this bug, run the following command:
```
./gradlew run -Dargs="--repos http://github.com/AY1920S1-CS2103T-T12-2/main.git --view --since 25/09/2019 --until 25/09/2019"
```

One of the authors (Ryan Tay) will have duplicate ramps:

![Screenshot 2019-10-23 at 1 09 02 AM](https://user-images.githubusercontent.com/14971883/67311232-c2af9400-f531-11e9-894c-76df99f9fa55.png)

**Comment by myteo** [comment]
Putting this as low priority since most users will want the 2 authors to be consolidated in such a case anyway, by providing author-config.csv.

**Comment by ang-zeyu** [comment]
Hi, I've investigated the issue and the problem seems to be an issue with the backend.

Briefly, its due to the commit extraction process, where the 2nd 300 line commit is extracted twice under 2 the usernames.

I'm interested in fixing this, but was there a reason this issue was tagged as `frontEnd`?
