### ISSUE TITLE
Explore using libgit2 as a replacement to git on cli

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#93]
https://github.com/libgit2/libgit2

Using cli to execute git command introduces overheads that are not doing productive work.

Let's explore other means to replace cli commands.

**Comment by harryggg** [comment]
But calling a C program from Java causes more overheads... And I think this library is using cli to execute Git command too...how else can it do Git

**Comment by eugenepeh** [comment]
>But calling a C program from Java causes more overheads...

C will directly work on the memory addresses passed by Java so I think the overhead should be smaller than CLI though.

**Comment by harryggg** [comment]
Git is in C too, so the difference in 'overhead' depends only on the method of invoking the program (Git or libgit2). I do believe that JNI has a very large overhead, comparing to CLI anyway. 
https://stackoverflow.com/questions/13973035/what-is-the-quantitative-overhead-of-making-a-jni-call?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by damithc** [comment]
At this stage we can use whichever the one that is easier to use. But it is good to know the alternatives and pros and cons in case we need to optimize later.
