### ISSUE TITLE
RepoConfiguration: `commitNum` field appears to be unused

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#936]
The `commitNum` field in the `RepoConfiguration` class, and its getter / setter methods do not seem to be used anywhere.

![image](https://user-images.githubusercontent.com/35621759/68064807-4f8cf580-fd5b-11e9-8fd1-b087f4f5f3fd.png)

![image](https://user-images.githubusercontent.com/35621759/68064795-240a0b00-fd5b-11e9-82f7-c13738f2b062.png)

Should these be removed? I'm not sure if I'm misunderstanding something here.

**Comment by fzdy1914** [comment]
These lines of code are left because of a deprecated feature `analyze latest N commit`. For now, we only need to analyze the repo by date range, so it is safe to remove them.
