### ISSUE TITLE
Test: use generic throw Exception in all tests

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#937]
The `repoConfig_overrideKeyword_success` test case has the `HelpScreenException` specified in its `throws` clause.

However, `HelpScreenException` is not thrown by the code in the body of the test case.
We should remove this exception from the `throws` clause.

![image](https://user-images.githubusercontent.com/35621759/68088448-54a48e80-fe9a-11e9-94d4-16acef7ad6ad.png)

**Comment by damithc** [comment]
Actually, it is OK to use a generic `throws Exception` in test cases, as all exceptions result in failure i.e., there is no handling of exceptions

**Comment by anubh-v** [comment]
I agree that we can just specify a single `Exception` in the `throws` clause of all test cases.

Another issue with the current approach: we have to modify alot of test code if we change the `throws` clause of any method that is used in many test cases.

@fzdy1914, would it be ok to start specifying a generic `throws Exception` in all future test cases?

**Comment by fzdy1914** [comment]
Actually, I got a different idea from prof. Although there is no exception handler, the Exception type itself can give us some information. For example, for the above code, if we got a `ParseException`, we may easily conclude that this Exception may not occur in the test method itself but the `Parser` class it calls. Using the specific exception is a kind of defining `"normal"` exception apart from `"abnormal"` exception.

It is just my own opinion anyway.
@eugenepeh @yong24s Can you kindly provide your idea?

**Comment by yong24s** [comment]
> For example, for the above code, if we got a ParseException, we may easily conclude that this Exception may not occur in the test method itself but the Parser class it calls. Using the specific exception is a kind of defining "normal" exception apart from "abnormal" exception.

But those exceptions on the `throws` clause are needed to be there by the compiler, so it may or may not be thrown, right?
It should be more consistent to read expected exceptions by writing it explicitly like this:
```
@Test(expected = ParseException.class)
assertThrows(ParseException.class, () -> new TestMethod(null));
```
This way we are clear that these exceptions are being tested or expected. Also, referencing `se-edu` practices, they are using a generic `throw Exception`.

I'm supporting the use of a generic `throw Exception`, for simplicity.

**Comment by anubh-v** [comment]
Thanks everyone for the discussion. 
Since we agree on using a generic `throws Exception` clause, I will close this issue.

We can starting using the generic `throws Exception` style for new tests in future PRs.

How should we proceed for the existing tests?
I don't think there is a need to immediately make a PR to switch all tests to this new style.
We could slowly adopt this style when we happen to edit existing tests.
Is this ok?

**Comment by fzdy1914** [comment]
No need to close the issue, I will rename the issue and pin it to the project.

**Comment by dcshzj** [comment]
Most of the exceptions thrown in tests are now using Exception except for the following:

- `git/GitLsTreeTest.java`
- `parser/ArgsParserTest.java`
- `template/GitTestTemplate.java`
- `util/TestUtil.java`

This task is ideal for first timers and involves changing any other type of exceptions thrown into the generic Exception class.

**Comment by FH-30** [comment]
Hi, can I work on this issue?

**Comment by FH-30** [comment]
![Screen Shot 2021-07-14 at 4 35 59 PM](https://user-images.githubusercontent.com/61911161/125590986-07a9ef1e-baa8-4964-8d32-2d9b3c062e03.png)

I also noticed that in GitCloneTest.java the throws Exception clause is redundant, should it be removed?

**Comment by FH-30** [comment]
![Screen Shot 2021-07-14 at 4 52 33 PM](https://user-images.githubusercontent.com/61911161/125593513-25ec991b-cdb5-473b-a52c-dd6b9f1d2eec.png)
I also noticed that if you change the throws IoException clause to throws Exception in TestUtil.java the following catch clause will have to be changed to catch Exception in ConfigSystemTest.java. Is that alright?
![Screen Shot 2021-07-14 at 4 54 02 PM](https://user-images.githubusercontent.com/61911161/125593733-df03e768-2a03-48d6-b861-ff65ba976029.png)

**Comment by FH-30** [comment]
![Screen Shot 2021-07-14 at 4 56 10 PM](https://user-images.githubusercontent.com/61911161/125594042-8118d5da-b0ff-4443-9e44-3c850ed01c00.png)
There is also another unnecessary throws Exception clause in TimeUtilTest.java

**Comment by damithc** [comment]
@FH-30 I think you can go ahead and create a PR for this with the suggested changes so that others can comment on each.
