### ISSUE TITLE
RepoConfiguration: `update` method has inaccurate Javadoc comment

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#938]
![image](https://user-images.githubusercontent.com/35621759/68118834-fc25cd80-ff3b-11e9-8e48-873758b935ad.png)

The Javadoc comment does not mention that `update` will alter the *repository level* information as well (**not just** the *authors'* information).

Perhaps the comment should be:
`Clears existing information related to this repository and its authors, and replaces it with information from the standalone config.`

**Comment by dcshzj** [comment]
I am a new contributor and I hope to work on this task if it is still relevant?
