### ISSUE TITLE
RepoConfigCsvParser: Improve exception handling when repo-config csv has no valid records

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#942]
RepoSense crashes with an unhelpful error message when all the repo configs in `repo-config.csv.` are malformed.

To recreate this error: create a `repo-config.csv` with the following contents:

```
Repository Location,Branch,File formats,Ignore Glob List,Ignore standalone config, Ignore commits
https://github.com/reposense/RepoSense.git,master,,,
https://github.com/reposense/testrepo-Alpha.git,master,,,
https://github.com/reposense/testrepo-Beta.git,master,,,
```

Note that **all 3 repo configs in this CSV are malformed.** They all have only **5 columns**, although the CSV header has **6 columns.**

Now, run  `java -jar RepoSense.jar --config <path to directory containing repo-config.csv>`

RepoSense will crash as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/35621759/68544154-30493480-03fb-11ea-914b-bb491fdc4e0b.png)

Reason for the crash:
The `cloneAndAnalyzeRepos` method in `ReportGenerator` class is given a List of RepoConfigurations and the method assumes there will be at least 1 RepoConfiguration in the List.

Please see line 144 in `ReportGenerator.java`:
![image](https://user-images.githubusercontent.com/35621759/68544231-152af480-03fc-11ea-969c-05ea21322998.png)

To fix this error, let's check that the `repo-config.csv` has at least 1 **valid** RepoConfiguration **during the parsing process**. We can show a helpful error message to the user if all records in `repo-config.csv` are malformed.

**Comment by dezhanglee** [comment]
may i work on this
