### ISSUE TITLE
CodeView: improve visualization on different sort parameters

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#946]
We should place more emphasis on the values of interest using graphical effects.

E.g. if the sort by is on file name, we should highlight the file name in one way or another

![image](https://user-images.githubusercontent.com/19277206/69151333-667e6680-0b15-11ea-92d2-d4ac109628ee.png)

**Comment by jinyingtan** [comment]
Would it be alright if I attempt on this issue?

**Comment by jamessspanggg** [comment]
> Would it be alright if I attempt on this issue?
> 
> The approach I would take is to italicize only the `file name` if the sort is by `file name` and to italicize the whole `path` if it is sorted by `path`. Else the `path` would be normal.
> 
> Let me know if this works :)

@damithc what is your opinion on this approach?

**Comment by damithc** [comment]
How about this?
If by file name,
`Filename [path]` e.g., `Duke.java [src/main/java]`
If by path,
`path/filename` e.g., `src/main/java/Duke.java]`
If by extension (in future)
`[ext] path/file` e.g., `[.java] src/main/java/Duke.java`

The idea is to put the sorted element in front so that it is easier to locate when scrolling.

**Comment by jinyingtan** [comment]
should we put brackets on the element that is sorted or the one that is not?

**Comment by damithc** [comment]
> should we put brackets on the element that is sorted or the one that is not?

I used the bracket to improve readability, not to indicate what is being sorted.

**Comment by jinyingtan** [comment]
I think If we keep the brackets to indicate the sorted section,  it would help to clearly highlight what is being sorted and also improves readability.

**Comment by damithc** [comment]
> I think If we keep the brackets to indicate the sorted section, it would help to clearly highlight what is being sorted and also improves readability.

Yes, we can do that too.
`src/main/java/[Duke.java]`
`[src/main/java/]Duke.java`
`src/main/java/Duke[.java]`

Or use bold?
`src/main/java/`**`Duke.java`**
**`src/main/java/`**`Duke.java`
`src/main/java/Duke`**`.java`**

**Comment by jinyingtan** [comment]
I thought of it as what you mentioned previously, keeping the sorted element in front and bold it. Would this work?

File name: **`[Duke.java]`** `src/main/`
Path **`[src/main/Duke.java]`**
File Type: **`[frontend]`** `src/main/Duke.java`
LOC **`[1 line]`** `src/main/Duke.java`

**Comment by damithc** [comment]
> I thought of it as what you mentioned previously, keeping the sorted element in front and bold it. Would this work?

Let's give it a try and see how it looks.

**Comment by Tejas2805** [comment]
@damithc How do you want this to be implemented based on the discussion we have already had in #1084

**Comment by damithc** [comment]
> @damithc How do you want this to be implemented based on the discussion we have already had in #1084

What are my choices?

**Comment by jbkim1999** [comment]
Hi, I would like to attempt on this issue if this is still relevant.

**Comment by jbkim1999** [comment]
Hi @damithc @chan-j-d 

For `File Type` and `LoC`, since they are in the same icon label under current design,
I suggest when these are set as the sorting parameter, the icon label can be placed in front of others.

Specifically, for `LoC`, I would want to suggest flipping the file type and LoC to clearly depict the sorting parameter.

For `Path` and `File Name`, I want to follow one of the suggestions listed above, that is, wrapping the file name with a square bracket, 

e.g. 
`[src/main/java/]Duke.java`
`src/main/java/[Duke.java]`

The font is already strong enough, so making it bold could make the font look too strong.

What do you think about this approach?

**Comment by damithc** [comment]
@jbkim1999 as this is a visual tweak, it's hard to predict which one is best. Try different options and see how they appear to the user. When you have narrowed it down to a few equally good choices, you can post screenshots here to seek others' opinions too.

**Comment by jbkim1999** [comment]
@damithc I see. In that case, can I make a PR and show the screenshots there? Since it requires a code change I might need to create a branch for the change.

**Comment by jbkim1999** [comment]
Now that I see, I think I would create a separate branch and try out different options, post the screenshots here, and make a PR once that visual changes are approved.

**Comment by jbkim1999** [comment]
@damithc 

Hi Prof,

Here is one implementation I tried. The idea is to put whichever sort parameter being used in front of the title.

There are four sort parameters: `lineOfCode`, `fileName`, `path`, and `fileType`.

I noticed `lineOfCode` and `fileType` are merged together in an icon (`fileTypeLabel`).
When these two are used, then `fileTypeLabel` should be placed in front.
More specifically, when `lineOfCode` is used, then there would be an internal change in the order within the `fileTypeLabel`
### fileType
<img width="751" alt="Screenshot 2022-07-23 at 8 18 56 PM" src="https://user-images.githubusercontent.com/60286063/180604696-39d72b6a-9d1f-4f23-b91b-9c916f28e870.png">

### lineOfCode (note the change of order within fileTypeLabel)
<img width="756" alt="Screenshot 2022-07-23 at 8 18 31 PM" src="https://user-images.githubusercontent.com/60286063/180604699-17a9f960-ab42-4ea1-8bd4-62badf3db249.png">

For `path` and `fileName`, the mentioned parameter will be enclosed in a square bracket, like so:
### path
<img width="754" alt="Screenshot 2022-07-23 at 8 19 43 PM" src="https://user-images.githubusercontent.com/60286063/180604837-36f460cb-618f-49e4-a78a-7384fd04758f.png">

### fileName
<img width="750" alt="Screenshot 2022-07-23 at 8 19 51 PM" src="https://user-images.githubusercontent.com/60286063/180604842-669e2560-bd8d-46b8-9d87-eedeee238133.png">

**Comment by damithc** [comment]
@jbkim1999 yes, that approach might work.
For the `fileName` case, should we put the file name itself in front? e.g., `variables.md [_markbind/site/]`

**Comment by jbkim1999** [comment]
@damithc 

I thought about that one too, but I was a bit worried that it would make the path look broken, looked more complete when filePath and fileName were put together.

**Comment by jbkim1999** [comment]
For `path` and `fileName`, I also tried making the sort parameter bold instead of a square bracket,
but the bold effect was too weak, so I believe square bracket is a better approach.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/60286063/180639373-dc9b1f00-6254-4613-b11b-31a565981bae.png">
