### ISSUE TITLE
Inconsistency color of repo names in authorship and zoom view

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#947]
Both the zoom view and authorship view highlight the repo name in different colours.

Let's make them the same for consistency. 

![Screen Shot 2019-11-20 at 2 08 51 PM](https://user-images.githubusercontent.com/35946746/69213652-adb13980-0b9f-11ea-8840-45c60c6f6cac.png)

![Screen Shot 2019-11-20 at 2 09 02 PM](https://user-images.githubusercontent.com/35946746/69213658-b0139380-0b9f-11ea-9953-4c70e65e3b61.png)

**Comment by Tejas2805** [comment]
Or have we kept it different to show the difference between the two views? In that case, maybe we can give some kind of header to make it easy to differentiate between the two views.

**Comment by damithc** [comment]
> Or have we kept it different to show the difference between the two views?

I don't think so.

>In that case, maybe we can give some kind of header to make it easy to differentiate between the two views.

Yes, we can do that.

**Comment by jamessspanggg** [comment]
Closing this as fixed by #948
