### ISSUE TITLE
Find a netlify alternative

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#950]
Netlify is implementing a limit of 300 build minutes per month; it may not be sufficient for RepoSense as we have been using it as a PR review tool.
Hence, we might need to look out for an alternative.

https://www.netlify.com/pricing/#features

**Comment by damithc** [comment]
Perhaps see if they will give us a pro license for free? https://www.netlify.com/legal/open-source-policy/

**Comment by Tejas2805** [comment]
> Perhaps see if they will give us a pro license for free? https://www.netlify.com/legal/open-source-policy/

I think we are eligible for it. They are going to upgrade their criteria but based on the response given to the Professor's post, I think we should be okay. Posting it here, for everyone's review. 

![Screen Shot 2019-11-28 at 7 38 37 AM](https://user-images.githubusercontent.com/35946746/69766261-2de42a00-11b2-11ea-988a-d8b108fdd8b9.png)

**Comment by Tejas2805** [comment]
Also, while I was looking for alternatives, I found these two which we can think of using (in case):

Surge: Unlimited publishing but doesn't provide the feature of git hooks yet
GitLab: Provides all features but limits to 2000 minutes per month

**Comment by fzdy1914** [comment]
We should step ahead for the application. @Tejas2805 How can we apply for it?

**Comment by Tejas2805** [comment]
As seen in the previous comments, there are 4 requirements to fulfill other than providing the Netlify badge on the main web page. I think we are okay with all, though we might have to work on point 3 - proper code of conduct for participation - as we don't state it explicitly anywhere. 
Once that is done, we can just tell them on the Professor's post on Netlify's page to check our repository, and if all seems okay, we will get the required license.

**Comment by damithc** [comment]
I have asked @eugenepeh to apply for the Netlify license.

**Comment by eugenepeh** [comment]
>I have asked @eugenepeh to apply for the Netlify license.

Working on it, this issue can be KIV for now in case the need for it arise again.

**Comment by eugenepeh** [comment]
Updated our netlify to open source plan

**Comment by eugenepeh** [comment]
I afraid the issue have arised again. We've used up 511/1000 build minutes in less than half a month. There might be a possibility where they will charge us $7 for every additional 500 build minutes.

We probably need to source for an alternative or slim down the build process so that it uses lesser time

![image](https://user-images.githubusercontent.com/19277206/74043224-effe5000-4a03-11ea-9f41-f9ba29c7544a.png)
![image](https://user-images.githubusercontent.com/19277206/74043274-04dae380-4a04-11ea-859e-5d73179a2d69.png)

**Comment by damithc** [comment]
Is it possible to get travis (better yet, GitHub actions) to push the site generated from each PR to gh-pages branch but to a different folder? e.g., `<gh-pages>/previews/123` `<gh-pages>/previews/124` ...

**Comment by Tejas2805** [comment]
https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f 

It looks like using Travis it might be possible. But I will have to try it though.

**Comment by damithc** [comment]
> It looks like using Travis it might be possible. But I will have to try it though.

Give it a try. Even better if we can push to gh-pages rather than another third party service surge.sh but that can be the next step. A further step would be to port the CI task from Travis to GitHub actions.

**Comment by damithc** [comment]
It will be useful to get some inputs from our dev-ops expert @yong24s too

**Comment by fzdy1914** [comment]
> Is it possible to get travis (better yet, GitHub actions) to push the site generated from each PR to gh-pages branch but to a different folder? e.g., `<gh-pages>/previews/123` `<gh-pages>/previews/124` ...

I think it is a good idea.

**Comment by yong24s** [comment]
> https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f

This is a good guide to base our solution on. 

Some of my thoughts:
1. Netlify has a CLI tool that can do what surge does. Since we are on Netlify's open source plan, there is no incentive to use surge.

2. The above guide doesn't use [GitHub Check](https://developer.github.com/v3/checks/) but instead comments for notification, which is noisy.

3. Other than [GitHub Pages usage limits](https://help.github.com/en/github/working-with-github-pages/about-github-pages#usage-limits), there are also limitation such as:
 - Not able to use `/` as the `basePath` i.e. `deploy-preview-1062--reposense.netlify.com` vs `reposense.github.io/1062/`. This may hinder debugging as our projects being deployed to use base `/`.
- It is noisy, we need another repository, which will be frequently updated when CI is triggered. Also maintenance is required to keep to the usage limits. 
- It is cached so changes don't reflect for awhile.

**Comment by damithc** [comment]
> 1. Netlify has a CLI tool that can do what surge does. Since we are on Netlify's open source plan, there is no incentive to use surge.

Does it reduce build minute usage, compared to normal netlify PR previews? What are the limits of using the CLI tool?

**Comment by eugenepeh** [comment]
It seems like we've burst the netlify usage for the month and it is likely that our subscription will be cancelled if we dont make the payment for the excess usage.

![image](https://user-images.githubusercontent.com/19277206/75093709-25d43480-55bf-11ea-9c96-31753ee19c88.png)
![image](https://user-images.githubusercontent.com/19277206/75093723-4d2b0180-55bf-11ea-87d0-d942ddabab1b.png)

**Comment by eugenepeh** [comment]
>Does it reduce build minute usage, compared to normal netlify PR previews? What are the limits of using the CLI tool?

From what was described on [medium](https://medium.com/onfido-tech/travis-surge-github-auto-deploy-every-pr-branch-and-tag-a6c8c790831f), it seems like this surge thing taps on travis to perform the static webpage deployment. They seems to have crafted a [script](https://github.com/onfido/onfido-sdk-ui/blob/master/deploy.sh) to automate their deployment.

We would need a developer to evaluate and see if we can implement it in our environment.

**Comment by fzdy1914** [comment]
@reposense/stage0-reviewers Please have a look at this issue.

**Comment by damithc** [comment]
I think we need to move away from Netlify. Their new free quota is not enough for an active project.

**Comment by Tejas2805** [comment]
We have a PR on GitHub Actions. Maybe we can explore that.

**Comment by jamessspanggg** [comment]
> We would need a developer to evaluate and see if we can implement it in our environment.

Tried to deploy RepoSense using surge. Just have to modify their `deploy.sh` script slightly and modify our `travis.yml` file. It works fine, but the web page generated seems to be significantly slower than netlify's. 

Note: I tried setting the deployment on my forked RepoSense in this [PR](https://github.com/jamessspanggg/RepoSense/pull/1), the generated surge link is: https://1-pr-RepoSense-jamessspanggg.surge.sh

**Comment by damithc** [comment]
> It works fine, but the web page generated seems to be significantly slower than netlify's.

Nice. We can live with 'slow'.


> Another con: the generated link can only be found within the travis build, which cannot be directly accessed in the Github Checks as compared to netlify.

This is a bit of a bummer. Perhaps GitHub actions can do better on this front?

**Comment by jamessspanggg** [comment]
> This is a bit of a bummer. Perhaps GitHub actions can do better on this front?

Just have to add-on that the links generated by surge are of this format: 
For PRs: `<PR-num>-pr-<repo-name><repo-owner>.surge.sh`
For Branches: `<branch-name>-branch-<repo-name>-<repo-owner>.surge.sh`

We can also use the script to automatically comment on the PR with the link tho.

**Comment by jamessspanggg** [comment]
The automatic comment may also be an option, if GitHub actions does not work out.

<img width="796" alt="Screen Shot 2020-02-24 at 12 08 11 PM" src="https://user-images.githubusercontent.com/32864116/75128299-62f31080-56fe-11ea-9267-1b4714f21d00.png">

**Comment by fzdy1914** [comment]
> The automatic comment may also be an option, if GitHub actions does not work out.
> 
> <img alt="Screen Shot 2020-02-24 at 12 08 11 PM" width="796" src="https://user-images.githubusercontent.com/32864116/75128299-62f31080-56fe-11ea-9267-1b4714f21d00.png">

It would be nicer if this comment will always appear only once at the most top of the list. Otherwise, it will be troublesome to find the link or get spammed by the auto comment.

**Comment by jamessspanggg** [comment]
> It would be nicer if this comment will always appear only once at the most top of the list. Otherwise, it will be troublesome to find the link or get spammed by the auto comment.

Ok. Will find a way to only post the comment once. 

For the comment to be at the top of the list, what I can only do is to execute the deployment script earlier on during the travis build. But there still might be a chance where users comment even before the deployment script is finished. If only GitHub PRs have a pin comment functionality...

**Comment by damithc** [comment]
> For the comment to be at the top of the list, what I can only do is to execute the deployment script earlier on during the travis build. But there still might be a chance where users comment even before the deployment script is finished. If only GitHub PRs have a 'pin' comment functionality...

Append to the PR description?

**Comment by fzdy1914** [comment]
> Append to the PR description?

I agrees it is a good idea.  Meanwhile, since the style is fixed, maybe we can insert a template in the default PR description or a GitHub action to do this so we do not need travis.

**Comment by eugenepeh** [comment]
Let's make use of the travis for now, once its up then we can move the deployment to github action instead so that they can be performed in parallel.

The downside is that github action also seems to have its own fixed number of build minutes

**Comment by eugenepeh** [comment]
Netlify has agreed to waive off the charges this time round but the condition is that we'll be liable for future charges. Payment method also has to be input into the system so that we won't be able to avoid the payment next time round.

![image](https://user-images.githubusercontent.com/19277206/76869693-a24af200-68a3-11ea-8028-a2fdffe3f3e5.png)

**Comment by fzdy1914** [comment]
We can watch how surge works for 10 days. If it is OK, then, we can stop Netlify related status in our PR.

**Comment by jamessspanggg** [comment]
> We can watch how surge works for 10 days. If it is OK, then, we can stop Netlify related status in our PR.

sounds good to me

**Comment by jamessspanggg** [comment]
Closing this as surge works fine now
