### ISSUE TITLE
CsvParser: Error logs do not display an exact representation of user input

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#953]
When we warn users about malformed lines in the CSV files, we print the contents of these lines in the log messages, so that users can identify the problematic lines in the file.

However, the error messages do not display an exact representation of the malformed lines' contents.

Suppose, we have the following `repo-config.csv` file.

```
Repository Location,Branch,File formats,Ignore Glob List,Ignore standalone config, Ignore commit list
https://github.com/reposense/testrepo-Alpha.git, ,"md",,"yes"
https://github.com/reposense/testrepo-Beta.git,,,,,
https://github.com/reposense/testrepo-Delta.git,master, , ,yes,
```

The first record is malformed, as it only has 5 values instead of the expected 6 values.
In the first record, two values have been surrounded with quotation marks (`"md"` and `"yes"`).

However, these quotation marks are not seen in the error logs:
![image](https://user-images.githubusercontent.com/35621759/69533965-daa48880-0fb3-11ea-8da9-edfe26db2cfb.png)

We should change our logging code such that the log messages show the contents of the malformed lines exactly as they are provided in the user supplied CSV.

**Comment by anubh-v** [comment]
This issue was identified while discussing PR #935 

Related comment by @eugenepeh:
> iirc, what we are getting back now is a "reconstructed" version of the entry in the csv file, it is not the exact string at that was read from the file. E.g. if a column is surrounded by double quotes, the quotes wont be printed out.

**Comment by fzdy1914** [comment]
The quotation is missing because of the CSV parser we use and the way CSV file expresses its content (double quote is used when `,` is inside the content).

**Comment by damithc** [comment]
I think we can let this one slide. Probably the benefit is too small to justify the effort to fix.
