### ISSUE TITLE
RepoConfiguration: redundant usage of streams when setting isStandaloneConfigIgnored attribute

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#954]
In the `setStandaloneConfigIgnoredToRepoConfigs` method of `RepoConfiguration`, 
we iterate through a list of `RepoConfiguration` objects and modify the `isStandaloneConfigIgnored` attribute in each object.

This is currently done use the `Stream.foreach()` method, but it could be done using the `forEach` that is available to Lists.

https://github.com/reposense/RepoSense/blob/c6ffecd214e73fc8ecf97a742108af5ac6d2ceab/src/main/java/reposense/model/RepoConfiguration.java#L181-L184

Line 181 could be rewritten as:
```
configs.forEach(config -> config.setStandaloneConfigIgnored(isStandaloneConfigIgnored));
```

**Comment by anubh-v** [comment]
This issue may be affected by an ongoing PR #928, hence please do not work on it yet.

**Comment by dcshzj** [comment]
The original PR was merged and this task is ideal for first timers. The code snippet to change is:

https://github.com/reposense/RepoSense/blob/8c052946cee72d757fcdf013c42d31ff27fc28c5/src/main/java/reposense/model/RepoConfiguration.java#L211-L216

Line 214 should be written as:

```java
configs..forEach(config -> config.setStandaloneConfigIgnored(true)); 
```

**Comment by litone01** [comment]
Hi @dcshzj @anubh-v , can I kindly check if I can work on this issue? Thanks!

**Comment by dcshzj** [comment]
@litone01 Sure! You can refer to my earlier comment above on how to start.
