### ISSUE TITLE
Explore using MarkBind for RepoSense documentation

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#956]
It is good if we can use MarkBind for RepoSense documentation (similar to how we use it for [MarkBind's own documentation](https://markbind.org/)).
Complication: we need to use Netlify to preview how a PR would update docs but we are using Netlify   to preview a test dashboard already. 
Question: Is it possible to configure netlify to generate a MarkBind site as well as the dashboard? Perhaps we can put commands for generating both in one script file?

**Comment by damithc** [comment]
@yong24s what do you think?

**Comment by fzdy1914** [comment]
After a rough investigation, I believe it is possible.
1) It is possible to run several build commands together, which means we are able to generate MarkBind site.
2) Netlify supports different configurations for deployment and preview, so we do not need to worry that it may potentially affect the existing features.
3) We can configure the output directory of MarkBind to be a subfolder of the current output directory. So we are able to access the file using the link. 

For convenient issue, we may need some way for the website access: some potential solution:
1) add a link in our reposense preview website which can be triggered using a command.

2) Instead of directly entering the reposense preview when clicking the link, we have a routing index HTML to direct to the two websites.

**Comment by yong24s** [comment]
Yes, we can use MarkBind to enhance our documentation.

Before that, we should look into how much we are using Netlify, as the build time is limited to **300 minutes** a month. I am not sure if it will be enough for the upcoming semester.

**Comment by Tejas2805** [comment]
> Yes, we can use MarkBind to enhance our documentation.
> 
> Before that, we should look into how much we are using Netlify, as the build time is limited to **300 minutes** a month. I am not sure if it will be enough for the upcoming semester.

I think the limit of 300 minutes a month should be solved based on #950

**Comment by Tejas2805** [comment]
Based on a bit of what I researched regarding this, I agree with @fzdy1914 that it is possible. We can run several builds together in a single build command, which will help us in deploying both the dashboard and the MarkBind site together. 

Regarding viewing of PRs, there are two ways which I think can be used to handle this:

1) To create a repository inside reposense which handles the documentation for RepoSense. We can use that repository to handle all documentation related to RepoSense. 

**Pros:** We just need to setup Netlify in that repository and everything will work as intended and wished.
**Cons:** We will need to handle a whole another repository for the documentation only.

2) We run multiple build commands together, and both sites get deployed together. We use a link in our RepoSense preview (maybe the footer which already links to the UG) to go to the MarkBind generated site. 

**Pros:** Developers save a lot of hassle in setting this up
**Cons:** PRs regarding documentation updates might be a bit cumbersome to preview.

Based on @fzdy1914 suggestion

**Comment by damithc** [comment]
> 1. We run multiple build commands together, and both sites get deployed together. We use a link in our RepoSense preview (maybe the footer which already links to the UG) to go to the MarkBind generated site.
> 
> **Pros:** Developers save a lot of hassle in setting this up
> **Cons:** PRs regarding documentation updates might be a bit cumbersome to preview.

I like this option as it ensures code and docs get updated together.

**Comment by jamessspanggg** [comment]
Any updates on this?

Since we are currently using surge, we can run the markbind build command and deploy to surge site separately from our RepoSense dashboard. We can then add the another Github Status that links to the deployed markbind surge site.

@damithc opinion on this?

**Comment by damithc** [comment]
I'm all for moving to MarkBind as I'm keen to have a proper https://reposense.org website. As long as you guys can figure out a worflow that is not harder than the current workflow, and still can do PR previous for changes to docs, I'm fine with it.

**Comment by Tejas2805** [comment]
I don't think it should be an issue. Once James deploys to a new site, we can use the link in the footer to go to it, and review PR through it. Or, if I understood surge correctly, we can review the docs independently. 

I already have a PR for this conversion ready.
