### ISSUE TITLE
CsvParserTest: consider splitting into repo, author and group csvParserTest

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#958]
Currently, `CsvParserTest` has 425 LoC and will increase even further. This is messy in the sense that it's difficult for one to figure out whether group, author and/or repo configs is/are sufficiently covered.

It would be good if we can split them all into various repoConfig, authorConfig and groupConfig CSV Parser test classes for better code management.

**Comment by fzdy1914** [comment]
I think it is a good suggestion, and should be done asap.

**Comment by dezhanglee** [comment]
ok if i try this too? :)
