### ISSUE TITLE
Split CSS file into its relevant part

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#960]
Part of #795.

As it is quite a huge ramp to directly projectify the whole frontend. We can take the process step by step. 

The final goal of #795 is to have all component related code into one file. So it is nice if we can split out the CSS/JS/HTML of one component into its own file first. Then, in the final combination part, we can reduce much effort. 

For now, the JS/HTML code of each component has already rested in its own file, we can explore to split the CSS file into its own part.

**Comment by fzdy1914** [comment]
@eugenepeh @yong24s Your input, please?

**Comment by yong24s** [comment]
Sounds good.

**Comment by eugenepeh** [comment]
>@eugenepeh @yong24s Your input, please?

Yes, sounds great

**Comment by fzdy1914** [comment]
Putting the priority to high to encourage developers to solve this issue.
