### ISSUE TITLE
Explore using Vuex for globle variable management

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#961]
We are getting more and more variables in our frontend, inter-component communication becomes more tedious. Some of our existing implementations can also be revamped using a more elegant way using global variables.

Let's explore the use of Vuex in our project and how it may benefit us.

**Comment by Tejas2805** [comment]
Since we are thinking of exploring this, I was also thinking about revamping the front-end to Vue files. This will result in the JavaScript, HTML, CSS all associated with a particular component (eg: Authorship) to be in a single file and this will lead to better readability and understanding

**Comment by jamessspanggg** [comment]
Yes I would agree to use Vuex as well.

**Comment by fzdy1914** [comment]
> Since we are thinking of exploring this, I was also thinking about revamping the front-end to Vue files. This will result in the JavaScript, HTML, CSS all associated with a particular component (eg: Authorship) to be in a single file and this will lead to better readability and understanding

Yes, you may refer to #795 and #960 for more detail.

**Comment by gerhean** [comment]
I am in favor of this.

**Comment by fzdy1914** [comment]
Closed due to issue #1268
