### ISSUE TITLE
Consider adding link to UG in the report page

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#964]
In `README.md`, the link to the UG always points to the release version of the UG.

For some who run RepoSense using master branch, or any other version aside from the release branch, there may be feature and/or functional discrepancies between master (or any specific commit) and release branch.

It would be good if there's a link from the report page that directly links to the UG corresponding to the RepoSense version that was ran on.

**Comment by Tejas2805** [comment]
We do provide a link to the specific version and home page of RepoSense at the footer.

![Screen Shot 2019-12-14 at 10 22 44 AM](https://user-images.githubusercontent.com/35946746/70842213-c093f280-1e5b-11ea-96c2-ea4e321be0d2.png)

Maybe we can edit this to solve this issue.

**Comment by jylee-git** [comment]
You have a point on the implications of the UI.

@fzdy1914 any opinions on this?

**Comment by fzdy1914** [comment]
We should ask @damithc for his opinion. Both two links are acceptable to me.

**Comment by damithc** [comment]
Perhaps instead of linking to the specific commit, we can link to the UG as at that commit?

**Comment by Tejas2805** [comment]
Should I progress with this in mind?

**Comment by damithc** [comment]
> Should I progress with this in mind?

Sure. Go ahead.
