### ISSUE TITLE
Enforce Vue option order

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#968]
As pointed out by @jamessspanggg , it is better to follow the option order style recommended by Vue in our JS file, which may increase the readability of the code a lot.

See https://vuejs.org/v2/style-guide/index.html#Component-instance-options-order-recommended for more details.

**Comment by vig42** [comment]
We could enforce this using the [ESLint Vue plugin](https://eslint.vuejs.org/rules/). The ['order-in-components' rule](https://eslint.vuejs.org/rules/order-in-components.html) does exactly this; there are also several other rules which could be worthwhile for us to include.

If we do so, we should probably update the DG as well, as it currently does not reference any style guide for Vue.

**Comment by gerhean** [comment]
Just want to add that the [ESLint Vue plugin](https://eslint.vuejs.org/rules/) is already part of the project, and this particular rule can immediately be enforced just by removing this line:

https://github.com/reposense/RepoSense/blob/ed131f6294bf83fac436a6265bc4d53b022739f7/frontend/.eslintrc.json#L12

**Comment by vvidday** [comment]
Hi, can I try to take this issue? Thanks!
