### ISSUE TITLE
Minor release to fix broken links in UG

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#970]
As suggested by @eugenepeh in PR #901 let's do a minor release to update all the broken links updated by PR #913 and PR #902

**Comment by fzdy1914** [comment]
@eugenepeh I can do the release, and is going to label it `v1.10.1` since there are no major changes. Or you prefer `v.1.11rc` ?

**Comment by fzdy1914** [comment]
@eugenepeh Done with the release.

**Comment by eugenepeh** [comment]
thanks @fzdy1914 , sorry for the late reply.

1.10.1 is good since we didnt roll out any new features. Thanks for compiling the new release 👍

**Comment by Tejas2805** [comment]
Can we close this issue now, if done with the release?
