### ISSUE TITLE
Gradle JVM compatibility issue

### ISSUE THREAD

**Issue by HoWeiChin** [reposense/RepoSense#979]
Dear all,

I am trying to set up the preqs needed for the reposense project.

The developer guide mentioned that "Ensure that the selected version of Gradle JVM matches our prerequisite."

Since my JDK version is 11.0.4, I suppose the gradle version should be 5.0+, according to: 
https://www.jetbrains.com/help/idea/gradle-jvm-selection.html.

PS: I am trying to fix build issues as some test cases didnt pass. I am wondering if the aforementioned issue is a contributing factor.

**Comment by fzdy1914** [comment]
Hi, can you attach the result of running `./gradlew -version` command and the error of your test cases?

**Comment by HoWeiChin** [comment]
Hello Wang Chao,
The command returns gradlew 4.9.
Error messages:

![image](https://user-images.githubusercontent.com/28749044/71400855-fb1f3b80-2662-11ea-98ff-534682fcd8da.png)

![image](https://user-images.githubusercontent.com/28749044/71400883-112cfc00-2663-11ea-8562-e6834be2d0cf.png)

![image](https://user-images.githubusercontent.com/28749044/71400897-1f7b1800-2663-11ea-9d38-5bc5b5598da1.png)
