### ISSUE TITLE
Inaccurate Testing of AnnotatorAnalyzerTest

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#981]
As per my conversation with @eugenepeh in #789,  

`AnnotatorAnalyzerTest` is meant to test the functionality of the author tag - `//@@author`. However, the test currently analyses `blameTest.java` within `testrepo-Alpha`, which does not contain any author tags: https://github.com/reposense/testrepo-Alpha/blob/136c6713fc00cfe79a1598e8ce83c6ef3b878660/blameTest.java#L1-L4

Hence, both tests in `AnnotatorAnalyzerTest` are unable to test the functionality of the author tag and yields the same output.

Code in `AnnotatorAnalyzerTest`: 
https://github.com/reposense/RepoSense/blob/9f10e7aff83b620595976c25a828be15e9863ece/src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java#L9-L27

**Comment by anubh-v** [comment]
@jamessspanggg, seems like this test file (`AnnotatorAnalyzerTest.java`) was removed in [PR 789](https://github.com/reposense/RepoSense/pull/789). Should we add it back, and use [annotationTest.java](https://github.com/reposense/testrepo-Alpha/blob/master/annotationTest.java) to test it?

Currently, it seems that `AnnotatorAnalyzer.java` is untested.

**Comment by jamessspanggg** [comment]
@anubh-v yes the test was removed by me in #789. Yes go ahead!
