### ISSUE TITLE
Show GitHub issues filed by authors

### ISSUE THREAD

**Issue by jamessspanggg** [reposense/RepoSense#989]
Currently, RepoSense only shows the commits and code contribution of authors.

Since GitHub issues (finding bugs, advise to refactor code) may also be considered as part of a contribution to git repositories, should we also provide a way that shows the issues filed by each author?

**Comment by jamessspanggg** [comment]
@damithc what do you think?

As you have mentioned that you want to also make RepoSense a way for users to show off their git contribution portfolio, the quality of issues filed by the users may also be useful.

**Comment by damithc** [comment]
This is a good idea and something we want to do some day. But perhaps we should not venture into this area just yet as it would create a dependency on the GitHub API and GitHub API enforces limits (requires authentication too). e.g., downloading issues of 300+ repos is likely to take a long time and likely to hit API limits as well.

**Comment by damithc** [comment]
Putting on hold as we are not going in this direction for now.
