### ISSUE TITLE
Commit view: use a tick box to control commit message details

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#993]
![image](https://user-images.githubusercontent.com/1673303/72484965-1d127500-3841-11ea-8c45-7c8f0116c339.png)

Suggestion: use a tick box for this, to be consistent with the ramp chart?

**Comment by anubh-v** [comment]
Removing myself as it's being tackled in PR 943

**Comment by Tejas2805** [comment]
Closing this issue as solved #943 

![Screen Shot 2020-02-12 at 4 10 25 AM](https://user-images.githubusercontent.com/35946746/74274787-a8522e00-4d4d-11ea-8fa4-61ed24fe9027.png)
