### ISSUE TITLE
User Guide: Fix formatting for repo-config.csv example

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#994]
The markdown formatting for the `repo-config.csv` example is missing a column, which causes the table to render incorrectly.

![image](https://user-images.githubusercontent.com/35621759/72487976-a0849400-384a-11ea-8f29-e6c654dbc93f.png)

**Comment by Tejas2805** [comment]
@anubh-v thanks for the suggestion

**Comment by Tejas2805** [comment]
@anubh-v Didn't get this issue exactly. All seems to be fine locally. I believe the User Guide isn't updated on the repo. Could you check that once? If you think the issue still persists, do elaborate a bit on it for my clearer understanding.

**Comment by Tejas2805** [comment]
Solved in #907
