### ISSUE TITLE
Ramp Chart: ramp appears outside row

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#995]
The left part of the ramp goes out of the blue ~triangle~ rectangle as shown in the image below.
![image](https://user-images.githubusercontent.com/39231750/72495642-3bd53380-3862-11ea-805e-d9b7a3029d2e.png)
Link to reproduce: https://reposense.github.io/dashboard-demo/#search=&sort=searchPath&sortWithin=name&since=2019-02-10&until=2019-04-15&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false

**Comment by damithc** [comment]
In this case, the tail of the offending ramp should be clipped so that nothing appears outside the blue rectangle.

**Comment by jamessspanggg** [comment]
for the example given, the version of reposense was not up-to-date. Are you able to reproduce it in the current version?

**Comment by 0blivious** [comment]
The problem is actually due to the outdated IO page. Will close this issue
