### ISSUE TITLE
Give a way to view code for the entire repository

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#996]
Give a way to view the code of the entire repository at once and not just author wise. 

Use case: to see all the code of a repository as one page
Pros: easier than viewing one file at a time as one has to do via the GitHub UI
Cons: might not scale to big repositories.

Description edited by @damithc

**Comment by Tejas2805** [comment]
Part of #873

**Comment by jamessspanggg** [comment]
@Tejas2805 How's the progress of this? If you haven't started, may I try to attempt this?
